export default function useNavStateSnapshot({
  navStateRef,
  headHidden,
  headPinned,
  sel,
  threadRoot,
  inboxOpen,
  inboxTab,
  dmWithUserId,
  videoFeedOpen,
  questOpen,
  questSel,
  profileBranchMode,
  profileBranchUserId,
  profileBranchUserNick,
  topicFilterId,
  topicSort,
  postSort,
  feedSort,
  starMode,
  q,
  drop,
  sortOpen,
  replyTo,
}) {
  navStateRef.current = {
    headHidden,
    headPinned,
    selId: sel?.id ?? null,
    threadRootId: threadRoot?.id ?? null,
    inboxOpen,
    inboxTab,
    dmWithUserId,
    videoFeedOpen,
    questOpen,
    questSelId: questSel?.id ?? null,
    profileBranchMode: profileBranchMode || null,
    profileBranchUserId: profileBranchUserId || null,
    profileBranchUserNick: profileBranchUserNick || '',
    topicFilterId,
    topicSort,
    postSort,
    feedSort,
    starMode,
    q,
    drop,
    sortOpen,
    replyToId: replyTo?.id ?? null,
  }
}
