import d0 from './platform.js'
import d1 from './homepage.js'
import d2 from './news.js'
import d3 from './exchange.js'
import d4 from './exchange_ai.js'
import d5 from './battlecoin.js'
import d6 from './battle_chat.js'
import d7 from './futures.js'
import d8 from './academy.js'
import d9 from './academy_exam.js'
import d10 from './gameverse.js'
import d11 from './metastudio.js'
import d12 from './metaverse.js'
import d13 from './quantum_zigzag.js'
import d14 from './ql7_blockchain.js'
import d15 from './forum_feed.js'
import d16 from './forum_threads.js'
import d17 from './search.js'
import d18 from './geodetect.js'
import d19 from './media.js'
import d20 from './moderation.js'
import d21 from './metamarket.js'
import d22 from './quantum_family.js'
import d23 from './profile.js'
import d24 from './auth.js'
import d25 from './wallet.js'
import d26 from './telegram.js'
import d27 from './qcoin.js'
import d28 from './payments.js'
import d29 from './vip.js'
import d30 from './ads_packages.js'
import d31 from './ads_campaigns.js'
import d32 from './push.js'
import d33 from './messenger.js'
import d34 from './quests.js'
import d35 from './contact.js'
import d36 from './privacy.js'
import d37 from './security.js'
import d38 from './account_deletion.js'
import d39 from './navigation.js'
import d40 from './roadmap.js'
import d41 from './system_status.js'
import d42 from './localization.js'
import d43 from './accessibility.js'
import d44 from './partnership.js'
import d45 from './investment.js'
export const QL7_SUPPORT_DOMAIN_MODULES=Object.freeze([d0,d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11,d12,d13,d14,d15,d16,d17,d18,d19,d20,d21,d22,d23,d24,d25,d26,d27,d28,d29,d30,d31,d32,d33,d34,d35,d36,d37,d38,d39,d40,d41,d42,d43,d44,d45])
export const QL7_SUPPORT_DOMAIN_MODULE_BY_ID=Object.freeze(Object.fromEntries(QL7_SUPPORT_DOMAIN_MODULES.map((row)=>[row.domainId,row])))
export const QL7_SUPPORT_RELEASE_DOMAIN_ROOTS=Object.freeze(QL7_SUPPORT_DOMAIN_MODULES.map((row)=>row.domainId))
export const QL7_SUPPORT_SYSTEM_ONLY_DOMAINS=Object.freeze(['support_system','learning_governance'])
export const QL7_SUPPORT_CANONICAL_DOMAIN_IDS=Object.freeze([...QL7_SUPPORT_RELEASE_DOMAIN_ROOTS,...QL7_SUPPORT_SYSTEM_ONLY_DOMAINS])
export default QL7_SUPPORT_DOMAIN_MODULES
