const ROWS=Object.freeze({
 en:['Temporary account restriction','Some actions are temporarily unavailable while a verified security decision is active.','Remaining time','Open Support','Privacy','Appeal','Log out'],
 ru:['Временное ограничение аккаунта','Некоторые действия временно недоступны, пока действует подтверждённое решение безопасности.','Осталось','Открыть поддержку','Приватность','Апелляция','Выйти'],
 uk:['Тимчасове обмеження акаунта','Деякі дії тимчасово недоступні, поки діє підтверджене рішення безпеки.','Залишилось','Відкрити підтримку','Приватність','Апеляція','Вийти'],
 es:['Restricción temporal de la cuenta','Algunas acciones no están disponibles temporalmente mientras esté activa una decisión de seguridad verificada.','Tiempo restante','Abrir soporte','Privacidad','Apelar','Cerrar sesión'],
 tr:['Geçici hesap kısıtlaması','Doğrulanmış güvenlik kararı etkin olduğu sürece bazı işlemler geçici olarak kullanılamaz.','Kalan süre','Desteği aç','Gizlilik','İtiraz','Çıkış yap'],
 ar:['تقييد مؤقت للحساب','بعض الإجراءات غير متاحة مؤقتًا أثناء سريان قرار أمني موثّق.','الوقت المتبقي','فتح الدعم','الخصوصية','استئناف','تسجيل الخروج'],
 zh:['临时账户限制','经验证的安全决定生效期间，部分操作暂时不可用。','剩余时间','打开支持','隐私','申诉','退出登录'],
 he:['הגבלת חשבון זמנית','חלק מהפעולות אינן זמינות זמנית בזמן שהחלטת אבטחה מאומתת פעילה.','זמן שנותר','פתיחת תמיכה','פרטיות','ערעור','התנתקות'],
 de:['Vorübergehende Kontoeinschränkung','Einige Aktionen sind vorübergehend nicht verfügbar, solange eine bestätigte Sicherheitsentscheidung aktiv ist.','Verbleibende Zeit','Support öffnen','Datenschutz','Einspruch','Abmelden'],
 fr:['Restriction temporaire du compte','Certaines actions sont temporairement indisponibles pendant une décision de sécurité vérifiée.','Temps restant','Ouvrir le support','Confidentialité','Faire appel','Se déconnecter'],
 it:['Limitazione temporanea dell’account','Alcune azioni non sono temporaneamente disponibili durante una decisione di sicurezza verificata.','Tempo rimanente','Apri assistenza','Privacy','Ricorso','Esci'],
 pt:['Restrição temporária da conta','Algumas ações ficam temporariamente indisponíveis enquanto uma decisão de segurança verificada estiver ativa.','Tempo restante','Abrir suporte','Privacidade','Recorrer','Sair'],
 pl:['Tymczasowe ograniczenie konta','Niektóre działania są tymczasowo niedostępne podczas aktywnej, potwierdzonej decyzji bezpieczeństwa.','Pozostały czas','Otwórz pomoc','Prywatność','Odwołanie','Wyloguj'],
 nl:['Tijdelijke accountbeperking','Sommige acties zijn tijdelijk niet beschikbaar zolang een geverifieerd beveiligingsbesluit actief is.','Resterende tijd','Support openen','Privacy','Bezwaar','Uitloggen'],
 sv:['Tillfällig kontobegränsning','Vissa åtgärder är tillfälligt otillgängliga medan ett verifierat säkerhetsbeslut är aktivt.','Återstående tid','Öppna support','Integritet','Överklaga','Logga ut'],
 no:['Midlertidig kontobegrensning','Noen handlinger er midlertidig utilgjengelige mens en verifisert sikkerhetsbeslutning er aktiv.','Gjenstående tid','Åpne support','Personvern','Klage','Logg ut'],
 da:['Midlertidig kontobegrænsning','Nogle handlinger er midlertidigt utilgængelige, mens en verificeret sikkerhedsbeslutning er aktiv.','Resterende tid','Åbn support','Privatliv','Klage','Log ud'],
 fi:['Tilin väliaikainen rajoitus','Jotkin toiminnot ovat tilapäisesti poissa käytöstä vahvistetun turvallisuuspäätöksen aikana.','Aikaa jäljellä','Avaa tuki','Tietosuoja','Valita','Kirjaudu ulos'],
 cs:['Dočasné omezení účtu','Některé akce jsou dočasně nedostupné, dokud platí ověřené bezpečnostní rozhodnutí.','Zbývající čas','Otevřít podporu','Soukromí','Odvolání','Odhlásit se'],
 sk:['Dočasné obmedzenie účtu','Niektoré akcie sú dočasne nedostupné, kým platí overené bezpečnostné rozhodnutie.','Zostávajúci čas','Otvoriť podporu','Súkromie','Odvolanie','Odhlásiť sa'],
 hu:['Ideiglenes fiókkorlátozás','Egyes műveletek átmenetileg nem érhetők el, amíg egy ellenőrzött biztonsági döntés aktív.','Hátralévő idő','Támogatás megnyitása','Adatvédelem','Fellebbezés','Kijelentkezés'],
 ro:['Restricție temporară a contului','Unele acțiuni sunt temporar indisponibile cât timp este activă o decizie de securitate verificată.','Timp rămas','Deschide suportul','Confidențialitate','Contestație','Deconectare'],
 bg:['Временно ограничение на акаунта','Някои действия временно не са достъпни, докато е активно потвърдено решение за сигурност.','Оставащо време','Отвори поддръжката','Поверителност','Обжалване','Изход'],
 sr:['Privremeno ograničenje naloga','Neke radnje su privremeno nedostupne dok je aktivna potvrđena bezbednosna odluka.','Preostalo vreme','Otvori podršku','Privatnost','Žalba','Odjavi se'],
 hr:['Privremeno ograničenje računa','Neke radnje privremeno nisu dostupne dok je aktivna potvrđena sigurnosna odluka.','Preostalo vrijeme','Otvori podršku','Privatnost','Žalba','Odjava'],
 sl:['Začasna omejitev računa','Nekatera dejanja so začasno nedostopna, dokler je aktivna preverjena varnostna odločitev.','Preostali čas','Odpri podporo','Zasebnost','Pritožba','Odjava'],
 el:['Προσωρινός περιορισμός λογαριασμού','Ορισμένες ενέργειες δεν είναι προσωρινά διαθέσιμες όσο ισχύει επαληθευμένη απόφαση ασφαλείας.','Χρόνος που απομένει','Άνοιγμα υποστήριξης','Απόρρητο','Έφεση','Αποσύνδεση'],
 ka:['ანგარიშის დროებითი შეზღუდვა','ზოგი მოქმედება დროებით მიუწვდომელია, სანამ დადასტურებული უსაფრთხოების გადაწყვეტილება მოქმედებს.','დარჩენილი დრო','მხარდაჭერის გახსნა','კონფიდენციალურობა','გასაჩივრება','გასვლა'],
 az:['Hesabın müvəqqəti məhdudlaşdırılması','Təsdiqlənmiş təhlükəsizlik qərarı aktiv olduğu müddətdə bəzi əməliyyatlar müvəqqəti əlçatmazdır.','Qalan vaxt','Dəstəyi aç','Məxfilik','Apellyasiya','Çıxış'],
 kk:['Аккаунтты уақытша шектеу','Расталған қауіпсіздік шешімі әрекет еткен кезде кейбір әрекеттер уақытша қолжетімсіз.','Қалған уақыт','Қолдауды ашу','Құпиялылық','Шағымдану','Шығу'],
 ja:['アカウントの一時制限','確認済みのセキュリティ判断が有効な間、一部の操作は一時的に利用できません。','残り時間','サポートを開く','プライバシー','異議申し立て','ログアウト'],
 ko:['일시적인 계정 제한','확인된 보안 결정이 활성화된 동안 일부 작업을 일시적으로 사용할 수 없습니다.','남은 시간','지원 열기','개인정보','이의 제기','로그아웃']
})
export function getRestrictionPortalCopy(locale='en'){const k=String(locale||'en').toLowerCase().split('-')[0];const r=ROWS[k]||ROWS.en;return Object.freeze({title:r[0],body:r[1],remaining:r[2],support:r[3],privacy:r[4],appeal:r[5],logout:r[6]})}
export const RESTRICTION_PORTAL_LOCALES=Object.freeze(Object.keys(ROWS))
