import { assertQl7SupportActive } from '../config/featureFlag.js'
import { QL7_SUPPORT_BEHAVIOR_MANIFEST_HASH, QL7_SUPPORT_RUNTIME_EXECUTOR_ID, QL7_SUPPORT_RUNTIME_VERSION } from '../config/behaviorManifest.js'
import { createQl7SupportConversationLedger, mergeQl7SupportLedgerTurn } from '../conversation/ledger.js'
import { normalizeQl7SupportReceipts, receiptFromQl7DiagnosticV13 } from '../data/adapterReceipt.js'
import { buildQl7SupportFactProjection } from '../data/factProjection.js'
import { resolveQl7SupportResponseLocale } from '../language/responseLocalePolicy.js'
import { buildQl7SupportIncidentCandidate } from '../learning/incidentCandidate.js'
import { buildQl7SupportComposerPolicyFromSafety } from '../inputPolicy.js'
import { ql7Locale, ql7StableHash, ql7Str } from '../internal/text.js'
import { buildQl7SupportOperatorCase } from '../operator/buildCase.js'
import { buildQl7SupportSurface } from '../presentation/buildSupportSurface.js'
import { buildQl7SupportResponseContentPlan } from '../response/buildContentPlan.js'
import { critiqueQl7SupportResponse } from '../response/critiqueResponse.js'
import { realizeQl7SupportHumanResponse } from '../response/realizeNatural.js'
import { analyzeQl7SupportTurn } from '../semantics/analyzeTurn.js'
import { normalizeQl7SupportOperatorState } from '../ecosystemCatalog.js'

export const QL7_SUPPORT_RUNTIME_VERSION_V13=QL7_SUPPORT_RUNTIME_VERSION
export const QL7_SUPPORT_RUNTIME_EXECUTOR_ID_V13=QL7_SUPPORT_RUNTIME_EXECUTOR_ID
export const QL7_SUPPORT_BEHAVIOR_MANIFEST_HASH_V13=QL7_SUPPORT_BEHAVIOR_MANIFEST_HASH
function adapterRows(adapters={}){const out=[];for(const [name,value] of Object.entries(adapters||{})){if(value&&typeof value==='object'&&('executed'in value||'result'in value||'data'in value))out.push({...value,adapter:value.adapter||name,source:value.source||name})}return out}
function runtimeEvents(input,analysis,surface,policy,finalMessageId,plan={}){const at=ql7Str(input.now)||new Date().toISOString();const base={correlationId:ql7Str(input.correlationId||input.requestId),requestId:ql7Str(input.requestId),triggeringUserMessageId:ql7Str(input.userTurnId||input.messageId),attemptId:ql7Str(input.attemptId||input.requestId),serverTime:at};const rawStates=['accepted'];if(analysis.requiresAdapter)rawStates.push('checking_evidence');rawStates.push('analyzing','composing','answer_committed');if(policy.allowed)rawStates.push(surface.surfaceKind==='choices'?'waiting_choice':'input_ready');else rawStates.push('cooldown');if(plan.operatorHandoff?.required)rawStates.push('operator_pending');const byState=new Map();for(const rawState of rawStates){const state=normalizeQl7SupportOperatorState(rawState);const previous=byState.get(state)||{};byState.set(state,{...previous,rawStates:[...(previous.rawStates||[]),rawState],...(state==='answer_ready'?{finalMessageId,surfaceHash:surface.integrityBlock.surfaceHash,composerAllowed:policy.allowed===true}:{}),...(state==='needs_clarification'?{composerAllowed:true,expectedInputType:'choice'}:{}),...(state==='attention_required'&&rawState==='operator_pending'?{operatorReason:ql7Str(plan.operatorHandoff?.reason),operatorStatus:ql7Str(plan.operatorHandoff?.status)}:{}),...(state==='attention_required'&&rawState==='cooldown'?{blockedUntil:policy.blockedUntil,remainingMs:policy.remainingMs}: {})})}return Object.freeze(Array.from(byState.entries()).map(([state,event],index)=>Object.freeze({...base,...event,state,sequence:index+1,operatorPublicState:true}))) }
function contactsFromAnalysis(analysis={}){
 const signals=analysis.contactSignals||{}
 if(analysis.contactConsent===true)return Object.freeze({consent:true,email:ql7Str(signals.email),phone:ql7Str(signals.phone),telegram:ql7Str(signals.telegram),preferred:ql7Str(signals.preferred||analysis.contactPreferred),channels:signals.channels||analysis.contactChannels||[]})
 if(analysis.contactRefused===true)return Object.freeze({consent:false,preferred:'dm',channels:['dm'],note:'user_declined_external_contacts'})
 return null
}
export function executeQl7SupportTurnRuntime(input={},adapters={}){
 const mode=ql7Str(input.mode||'test').toLowerCase()||'test';if(mode==='production')assertQl7SupportActive();const localePolicy=resolveQl7SupportResponseLocale(input);const locale=localePolicy.locale;const text=ql7Str(input.originalText||input.text||input.sourceText);const ledger=createQl7SupportConversationLedger(input.priorLedger||input.ledger||input.memory||{});const explicit=Array.isArray(input.adapterReceipts)?input.adapterReceipts:[];const diagnostic=input.diagnosticResult?[receiptFromQl7DiagnosticV13(input.diagnosticResult)]:[];const receipts=normalizeQl7SupportReceipts([...explicit,...diagnostic,...adapterRows(adapters)]);const semantic=analyzeQl7SupportTurn({text,locale,previousContext:ledger,baseAnalysis:input.analysis||{},baseRoute:input.route||{},baseTone:input.tone||{},baseAnalysisTrust:input.baseAnalysisTrust===true,now:input.clock||Date.now});const factProjection=buildQl7SupportFactProjection({topic:semantic.analysis.topic,receipts});const plan=buildQl7SupportResponseContentPlan({analysis:semantic.analysis,route:semantic.route,tone:semantic.tone,locale,receipts,ledger,seed:input.seed||input.requestId||'',factProjection});const realized=realizeQl7SupportHumanResponse(plan,{locale,ledger});const surface=buildQl7SupportSurface({plan,realized,locale,receipts,ledger,requestContext:{requestId:input.requestId,caseId:input.caseId}});const critic=critiqueQl7SupportResponse({text:realized.text,surface,locale,plan,receipts,expectedLocale:locale});const composerPolicy=buildQl7SupportComposerPolicyFromSafety({safety:semantic.safety,caseId:input.caseId,locale,now:input.clock||Date.now});const finalMessageId=`support:${ql7StableHash(`${input.requestId}:${surface.integrityBlock.surfaceHash}:${realized.responseHash}`)}`;const detectedContacts=contactsFromAnalysis(semantic.analysis);const operatorRequired=input.forceOperatorCase===true||plan.operatorHandoff?.required===true||(semantic.analysis.topic==='security'&&semantic.analysis.messageAct==='incident_report'&&semantic.analysis.scamCrimeSignal===true);const operatorCase=operatorRequired?buildQl7SupportOperatorCase({requestId:input.requestId,caseId:input.caseId,actor:input.actor||{},profile:input.profile||{},analysis:semantic.analysis,originalText:text,translatedMeaning:input.translatedMeaning||text,receipts,rating:input.rating||null,geo:input.geo||{},activity:input.activity||{},contacts:input.contacts||detectedContacts,now:ql7Str(input.now)||new Date().toISOString()}):undefined;const operatorStatus=operatorCase?'ready_for_review':'none';const nextState=plan.choices?'waiting_choice':composerPolicy.allowed?(plan.closureState==='closed'?'idle':'input_ready'):'cooldown';const events=runtimeEvents(input,semantic.analysis,surface,composerPolicy,finalMessageId,plan)
 const replyPlan=Object.freeze({text:realized.text,title:realized.title,responseMode:plan.surfaceKind==='compact'?'human_short':'structured',replyBudget:Object.freeze({text:realized.text,graphemes:critic.graphemes,max:400,truncated:false}),responseCode:ql7Str(plan.responseCode)||`v14:${plan.topic}:${plan.messageAct}:${plan.resultKind}`,locale,topic:plan.topic,messageAct:plan.messageAct,semanticFingerprint:realized.responseHash,nextState,domainPlan:input.route?.domainPlan||input.analysis?.domainPlan||null,cardSpec:surface,clarification:plan.choices?realized.text:null,userFacingAsOf:surface.checkedAt,contentPlan:plan,adapterReceipts:receipts,runtimeVersion:QL7_SUPPORT_RUNTIME_VERSION,behaviorManifestHash:QL7_SUPPORT_BEHAVIOR_MANIFEST_HASH,composerPolicy,finalMessageId,operatorStatus})
 const learningIncident=['insult_uncertain','insult_denied','direct_insult'].includes(semantic.safety.category)?buildQl7SupportIncidentCandidate({actorHash:input.actor?.id||input.actor?.wallet||'',caseId:input.caseId||input.requestId,assessment:semantic.safety.insultAssessment,locale,resolution:semantic.safety.insultState?.state,topicRecovery:semantic.safety.insultState?.state==='denied'}):null;const nextLedger=mergeQl7SupportLedgerTurn(ledger,{userText:text,assistantText:realized.text,topic:plan.topic,messageAct:plan.messageAct,userTurnId:input.userTurnId||input.messageId,waitingFor:plan.waitingFor,resolved:plan.closureState==='closed',safety:semantic.safety,emotionalSupport:semantic.analysis.emotionalSupport,humorMode:semantic.analysis.humor,correction:semantic.analysis.correction,rejectedHypothesis:semantic.analysis.rejectedHypothesis,svgAssetId:surface.primarySvg.assetId,propositions:realized.propositions,relationshipStage:plan.relationshipIntent?.stage,contactPrompted:plan.contactRequest?.requested===true,contactProvided:semantic.analysis.contactConsent===true,contactRefused:semantic.analysis.contactRefused===true,operatorHandoff:plan.operatorHandoff?.required===true,insultState:semantic.safety.insultState,now:ql7Str(input.now)||new Date().toISOString()})
 return Object.freeze({version:QL7_SUPPORT_RUNTIME_VERSION,runtimeVersion:QL7_SUPPORT_RUNTIME_VERSION,mode,executorId:QL7_SUPPORT_RUNTIME_EXECUTOR_ID,behaviorManifestHash:QL7_SUPPORT_BEHAVIOR_MANIFEST_HASH,analysis:semantic.analysis,tone:semantic.tone,localePolicy,factProjection,learningIncident,effectiveRoute:semantic.route,safety:semantic.safety,replyPlan,plan,contentPlan:plan,realized,text:realized.text,surface,critic,ledger:nextLedger,receipts,adapterReceipts:receipts,composerPolicy,stateEvents:events,operatorCase,finalMessageId,internalProvenance:Object.freeze({resolvedExecutorPath:'lib/ql7-support/runtime/executeTurn.js',inputHash:ql7StableHash(text),surfaceHash:surface.integrityBlock.surfaceHash,receiptsHash:ql7StableHash(JSON.stringify(receipts)),finalMessageId}),runtimeParity:Object.freeze({sameExecutor:true,localePolicyVersion:localePolicy.version,executorId:QL7_SUPPORT_RUNTIME_EXECUTOR_ID,behaviorManifestHash:QL7_SUPPORT_BEHAVIOR_MANIFEST_HASH})})
}
export const executeQl7SupportTurnRuntimeV13=executeQl7SupportTurnRuntime
