export const QL7_SUPPORT_BREADTH_SEMANTIC_CASES_V11 = Object.freeze([
  // Russian
  ['ru','Расскажи, что сейчас с моим рекламным пакетом.','ads_packages','ads_packages_self_status'],
  ['ru','Пакетик мой ещё живой или уже закончился?','ads_packages','ads_packages_self_status'],
  ['ru','Выведи метрики рекламы: показы, клики и CTR.','ads_campaigns','ads_campaigns_metrics'],
  ['ru','Чё по стате моей рекламной кампании?','ads_campaigns','ads_campaigns_metrics'],
  ['ru','Как взять рекламу и что она мне даст?','ads_packages','ads_packages_purchase'],
  ['ru','Какие преимущества даст рекламный пакет?','ads_packages','ads_packages_benefits'],
  ['ru','Сколько QCoin у меня осталось?','qcoin','qcoin_balance'],
  ['ru','Почему Quantum Wallet не подключает мою сессию?','wallet','wallet_connection_status'],
  ['ru','Проверь статус моего платежа и инвойса.','payments','payments_self_status'],
  ['ru','Мой VIP ещё активен?','vip','vip_self_status'],
  ['ru','Сколько жалоб сейчас на мой пост?','moderation','moderation_report_count'],
  ['ru','Хочу обжаловать удаление поста.','moderation','moderation_appeal'],
  ['ru','Кто на меня пожаловался?','moderation','moderation_reporter_privacy'],
  // Ukrainian
  ['uk','Що зараз із моїм рекламним пакетом?','ads_packages','ads_packages_self_status'],
  ['uk','Покажи статистику кампанії: покази, кліки та CTR.','ads_campaigns','ads_campaigns_metrics'],
  ['uk','Як купити рекламу і що вона мені дасть?','ads_packages','ads_packages_purchase'],
  ['uk','Скільки QCoin у мене на балансі?','qcoin','qcoin_balance'],
  ['uk','Перевір статус мого платежу.','payments','payments_self_status'],
  ['uk','Хочу оскаржити видалення допису.','moderation','moderation_appeal'],
  // English
  ['en','What is going on with my ad package right now?','ads_packages','ads_packages_self_status'],
  ['en','Show my campaign stats, impressions, clicks and CTR.','ads_campaigns','ads_campaigns_metrics'],
  ['en','How do I buy advertising and what value will it give me?','ads_packages','ads_packages_purchase'],
  ['en','What are the benefits of an advertising package?','ads_packages','ads_packages_benefits'],
  ['en','How much QCoin is left in my balance?','qcoin','qcoin_balance'],
  ['en','Check my wallet connection and session.','wallet','wallet_connection_status'],
  ['en','Check the status of my invoice payment.','payments','payments_self_status'],
  ['en','Is my VIP subscription still active?','vip','vip_self_status'],
  ['en','How many reports are on my post?','moderation','moderation_report_count'],
  ['en','I need to appeal the post removal.','moderation','moderation_appeal'],
  ['en','Who reported my post?','moderation','moderation_reporter_privacy'],
  // Spanish
  ['es','¿Qué pasa con mi paquete publicitario, sigue activo?','ads_packages','ads_packages_self_status'],
  ['es','Enséñame las métricas de mi campaña: impresiones, clics y CTR.','ads_campaigns','ads_campaigns_metrics'],
  ['es','¿Cómo compro publicidad y qué beneficios me da?','ads_packages','ads_packages_purchase'],
  ['es','¿Cuánto QCoin queda en mi saldo?','qcoin','qcoin_balance'],
  ['es','Comprueba el estado de mi pago y factura.','payments','payments_self_status'],
  ['es','Quiero apelar la eliminación de mi publicación.','moderation','moderation_appeal'],
  // Turkish
  ['tr','Reklam paketim ne durumda, hâlâ aktif mi?','ads_packages','ads_packages_self_status'],
  ['tr','Kampanyamın metriklerini, gösterimlerini ve tıklamalarını göster.','ads_campaigns','ads_campaigns_metrics'],
  ['tr','Reklamı nasıl satın alırım ve bana ne kazandırır?','ads_packages','ads_packages_purchase'],
  ['tr','QCoin bakiyemde ne kadar kaldı?','qcoin','qcoin_balance'],
  ['tr','Ödememin ve faturamın durumunu kontrol et.','payments','payments_self_status'],
  ['tr','Gönderi silme kararına itiraz etmek istiyorum.','moderation','moderation_appeal'],
  // Arabic
  ['ar','ما حالة حزمتي الإعلانية وهل ما زالت نشطة؟','ads_packages','ads_packages_self_status'],
  ['ar','اعرض إحصائيات حملتي الإعلانية ومرات الظهور والنقرات.','ads_campaigns','ads_campaigns_metrics'],
  ['ar','كيف أشتري الإعلان وما الفوائد التي سيعطيني إياها؟','ads_packages','ads_packages_purchase'],
  ['ar','كم بقي في رصيد QCoin الخاص بي؟','qcoin','qcoin_balance'],
  ['ar','تحقق من حالة دفع فاتورتي.','payments','payments_self_status'],
  ['ar','أريد استئناف قرار حذف المنشور.','moderation','moderation_appeal'],
  // Chinese
  ['zh','查看我的广告套餐状态，还有效吗？','ads_packages','ads_packages_self_status'],
  ['zh','显示我的广告活动指标、展示次数、点击和CTR。','ads_campaigns','ads_campaigns_metrics'],
  ['zh','如何购买广告，它能给我什么好处？','ads_packages','ads_packages_purchase'],
  ['zh','我的QCoin余额还有多少？','qcoin','qcoin_balance'],
  ['zh','检查我的付款和账单状态。','payments','payments_self_status'],
  ['zh','我要申诉帖子被删除的决定。','moderation','moderation_appeal'],
  // Hebrew
  ['he','מה הסטטוס של חבילת הפרסום שלי, היא עדיין פעילה?','ads_packages','ads_packages_self_status'],
  ['he','הצג את מדדי קמפיין הפרסום שלי, חשיפות וקליקים.','ads_campaigns','ads_campaigns_metrics'],
  ['he','איך רוכשים פרסום ומה היתרונות שלו?','ads_packages','ads_packages_purchase'],
  ['he','כמה QCoin נותר ביתרה שלי?','qcoin','qcoin_balance'],
  ['he','בדוק את סטטוס התשלום והחשבונית שלי.','payments','payments_self_status'],
  ['he','אני רוצה לערער על מחיקת הפוסט.','moderation','moderation_appeal'],
  // Cross-intent slang, explicit rejection and privacy controls
  ['ru','Не пакет, дай стату кампании.','ads_campaigns','ads_campaigns_metrics'],
  ['ru','Без аналитики: мой рекламный тариф ещё действует?','ads_packages','ads_packages_self_status'],
  ['ru','Хочу оформить рекламный пакет, сколько пользы и охвата?','ads_packages','ads_packages_purchase'],
  ['ru','Балик QCoin какой сейчас?','qcoin','qcoin_balance'],
  ['ru','Wallet отвалился, сессия подключена или нет?','wallet','wallet_connection_status'],
  ['ru','Мне влепили жалобы, сколько их?','moderation','moderation_report_count'],
  ['uk','Не метрики, перевір чи діє мій пакет реклами.','ads_packages','ads_packages_self_status'],
  ['uk','Дай стату кампанії, покази й кліки.','ads_campaigns','ads_campaigns_metrics'],
  ['en','Skip the package status; give me campaign performance stats.','ads_campaigns','ads_campaigns_metrics'],
  ['en','No analytics: is my advertising plan still active?','ads_packages','ads_packages_self_status'],
  ['en','I want to activate an ad package and understand its reach.','ads_packages','ads_packages_purchase'],
  ['en','Who filed the complaint against me?','moderation','moderation_reporter_privacy'],
  ['es','Sin métricas: ¿mi paquete de publicidad sigue activo?','ads_packages','ads_packages_self_status'],
  ['es','Dame la estadística de campaña, no el paquete.','ads_campaigns','ads_campaigns_metrics'],
  ['es','¿Quién reportó mi publicación?','moderation','moderation_reporter_privacy'],
  ['tr','Metrik değil; reklam paketim hâlâ aktif mi?','ads_packages','ads_packages_self_status'],
  ['tr','Beni kim şikayet etti?','moderation','moderation_reporter_privacy'],
  ['ar','لا أريد المقاييس، هل حزمتي الإعلانية ما زالت نشطة؟','ads_packages','ads_packages_self_status'],
  ['ar','من أبلغ عن منشوري؟','moderation','moderation_reporter_privacy'],
  ['zh','不要广告数据，只看我的套餐是否有效。','ads_packages','ads_packages_self_status'],
  ['zh','谁举报了我的帖子？','moderation','moderation_reporter_privacy'],
  ['he','בלי מדדים: חבילת הפרסום שלי עדיין פעילה?','ads_packages','ads_packages_self_status'],
  ['he','מי דיווח על הפוסט שלי?','moderation','moderation_reporter_privacy'],
])

export const QL7_SUPPORT_BREADTH_EMOTION_CASES_V11 = Object.freeze([
  ['ru','Я в ярости, опять всё сломалось.','angry'],['en','I am furious; this is broken again.','angry'],['es','Estoy furioso, otra vez no funciona.','angry'],['tr','Çok öfkeliyim, yine çalışmıyor.','angry'],['ar','أنا غاضب، لا يعمل مرة أخرى.','angry'],['zh','我很生气，又坏了。','angry'],['he','אני כועס, זה שוב לא עובד.','angry'],['uk','Я розлючений, знову не працює.','angry'],
  ['ru','Ура, это просто супер!','joyful'],['en','Amazing, I am really happy!','joyful'],['es','¡Genial, estoy feliz!','joyful'],['tr','Harika, çok mutluyum!','joyful'],['ar','رائع، أنا سعيد جداً!','joyful'],['zh','太棒了，我很开心！','joyful'],['he','מעולה, אני ממש שמח!','joyful'],['uk','Ура, це просто супер!','joyful'],
  ['ru','Мне тревожно, срочно проверь безопасность.','anxious'],['en','I am worried; urgently check the security.','anxious'],['es','Estoy preocupado, comprueba la seguridad con urgencia.','anxious'],['tr','Endişeliyim, güvenliği acil kontrol et.','anxious'],['ar','أنا قلق، تحقق من الأمان بشكل عاجل.','anxious'],['zh','我很担心，请紧急检查安全。','anxious'],['he','אני מודאג, בדוק את האבטחה בדחיפות.','anxious'],['uk','Мені тривожно, терміново перевір безпеку.','anxious'],
  ['ru','Дай строгую аналитику, метрики и доказательства.','analytical'],['en','Give me a strict analysis with metrics and evidence.','analytical'],['es','Dame análisis, métricas y pruebas.','analytical'],['tr','Bana metrikler ve kanıtlarla analiz ver.','analytical'],['ar','أعطني تحليلاً ومقاييس وأدلة.','analytical'],['zh','给我分析、指标和证据。','analytical'],['he','תן לי ניתוח, מדדים וראיות.','analytical'],['uk','Дай аналітику, метрики й докази.','analytical'],
  ['ru','Пошути немного, но по делу.','humorous'],['en','Make it a little funny, but stay useful.','humorous'],['es','Haz una broma, pero sigue siendo útil.','humorous'],['tr','Biraz şaka yap ama faydalı kal.','humorous'],['ar','امزح قليلاً لكن ابق مفيداً.','humorous'],['zh','开个小玩笑，但要有用。','humorous'],['he','תוסיף בדיחה קטנה אבל תישאר מועיל.','humorous'],['uk','Трохи пожартуй, але по суті.','humorous'],
])

export const QL7_SUPPORT_BREADTH_MUTATIONS_V11 = Object.freeze([
  ['plain', (text) => text],
  ['colloquial-prefix', (text, locale) => ({ru:'Слушай, ',uk:'Слухай, ',en:'Hey, ',es:'Oye, ',tr:'Bak, ',ar:'اسمع، ',zh:'请问，',he:'שמע, '}[locale] || '') + text],
  ['emoji', (text) => `${text} 🤔`],
  ['punctuation', (text) => `${text.replace(/[.!?。！？]+$/u,'')}?!`],
  ['case', (text, locale) => ['en','es','tr'].includes(locale) ? text.toUpperCase() : text],
  ['filler', (text, locale) => `${({ru:'короче, ',uk:'коротше, ',en:'basically, ',es:'pues, ',tr:'yani, ',ar:'يعني، ',zh:'就是说，',he:'בקיצור, '}[locale] || '')}${text}`],
])
