import crypto from 'node:crypto'
export const QL7_SUPPORT_LEARNING_SIGNAL_COLLECTION='ql7_support_learning_signals'
export const QL7_SUPPORT_COMMUNICATION_PROFILE_COLLECTION='ql7_support_communication_profiles'
function s(v){return String(v??'').trim()}
function redact(v=''){return s(v).replace(/\bql7ws_[A-Za-z0-9_-]+\b/g,'[session-redacted]').replace(/\bBearer\s+\S+/gi,'Bearer [redacted]').replace(/\b(api[_-]?key|secret|password|passwd|token)\s*[:=]\s*[^\s,;]+/gi,'$1=[redacted]').replace(/\b(?:0x)?[a-f0-9]{64}\b/gi,'[secret-redacted]').slice(0,1200)}
export async function recordQl7LearningSignal({database,userId='',caseId='',type='',locale='',input='',output='',outcome='',metadata={},retentionDays=90}={}){if(!database?.collection||!s(userId)||!s(type))return{ok:false,skipped:true,reason:'missing_context'};const profile=await database.collection(QL7_SUPPORT_COMMUNICATION_PROFILE_COLLECTION).findOne({_id:s(userId)});if(profile?.optOut===true)return{ok:true,skipped:true,reason:'user_opt_out',productionMutation:false};const atDate=new Date();const at=atDate.toISOString();const keep=Math.max(7,Math.min(365,Number(retentionDays||90)));const doc={_id:`learn:${crypto.createHash('sha256').update(`${userId}:${caseId}:${type}:${at}`).digest('hex').slice(0,30)}`,userId:s(userId),caseId:s(caseId),type:s(type),locale:s(locale),input:redact(input),output:redact(output),outcome:s(outcome),metadata:{clarificationCount:Number(metadata.clarificationCount||0),responseLatencyMs:Number(metadata.responseLatencyMs||0),chosenOption:s(metadata.chosenOption),reaction:s(metadata.reaction)},reviewState:'candidate',productionMutation:false,createdAt:at,expireAt:new Date(atDate.getTime()+keep*86400000)};await database.collection(QL7_SUPPORT_LEARNING_SIGNAL_COLLECTION).insertOne(doc);return{ok:true,id:doc._id,productionMutation:false,retentionDays:keep}}
export async function getQl7CommunicationProfile({database,userId=''}={}){if(!database?.collection||!s(userId))return null;return database.collection(QL7_SUPPORT_COMMUNICATION_PROFILE_COLLECTION).findOne({_id:s(userId)})}
export async function setQl7LearningOptOut({database,userId='',optOut=true}={}){if(!database?.collection||!s(userId))return{ok:false};await database.collection(QL7_SUPPORT_COMMUNICATION_PROFILE_COLLECTION).updateOne({_id:s(userId)},{$set:{optOut:optOut===true,updatedAt:new Date().toISOString()},$setOnInsert:{createdAt:new Date().toISOString(),detailLevel:'balanced',directness:.6,warmth:.7,humorReceptivity:.3,terminologyLevel:'standard',evidenceCount:0}},{upsert:true});return{ok:true,optOut:optOut===true}}
export async function deleteQl7LearningProfile({database,userId=''}={}){if(!database?.collection||!s(userId))return{ok:false};const [a,b]=await Promise.all([database.collection(QL7_SUPPORT_COMMUNICATION_PROFILE_COLLECTION).deleteOne({_id:s(userId)}),database.collection(QL7_SUPPORT_LEARNING_SIGNAL_COLLECTION).deleteMany({userId:s(userId)})]);return{ok:true,profileDeleted:Number(a.deletedCount||0),signalsDeleted:Number(b.deletedCount||0)}}
