export const QL7_SUPPORT_CORE_LOCALES_V7 = Object.freeze(['en', 'ru', 'uk', 'es', 'tr', 'ar', 'zh', 'he'])

export const QL7_SUPPORT_SCENARIO_ACTS_V7 = Object.freeze([
  'overview',
  'how_to',
  'personal_status',
  'incident',
  'comparison',
  'correction',
  'denial',
  'status_followup',
  'ambiguous_alias',
  'clarification_choice',
  'clarification_other',
  'no_data',
  'provider_unavailable',
  'timeout',
  'inconsistency',
  'diagnostic_result',
  'completion',
  'abandonment',
  'reopening',
  'safety',
  'event_notification',
  'admin_review',
  'spam_interrupt',
  'translation_fallback',
])

export const QL7_SUPPORT_MULTI_TURN_SCENARIOS_V7 = Object.freeze([
  'greeting_with_question',
  'vague_vip_status',
  'vip_activation_incident',
  'ads_package_status',
  'ads_campaign_followup',
  'contextual_short_reply',
  'correction_replaces_fact',
  'denial_is_negative_fact',
  'profanity_with_request',
  'ambiguity_choice',
  'ambiguity_other',
  'interrupt_during_audit',
  'repeated_spam',
  'runtime_unlock_after_question',
  'multiple_open_cases',
  'case_status_selection',
  'abandonment',
  'case_reopening',
  'safety_override',
  'deep_translate_success',
  'deep_translate_timeout',
  'diagnostic_no_data',
  'diagnostic_inconsistent',
  'admin_email_escalation',
  'admin_reminder_dedupe',
  'complaint_text',
  'complaint_image',
  'complaint_video',
  'complaint_audio',
])

export function auditQl7SupportScenarioContractsV7({ domains = 43 } = {}) {
  const expected = Number(domains || 0) * QL7_SUPPORT_SCENARIO_ACTS_V7.length * QL7_SUPPORT_CORE_LOCALES_V7.length
  return Object.freeze({
    ok: domains === 43 && QL7_SUPPORT_SCENARIO_ACTS_V7.length === 24 && QL7_SUPPORT_CORE_LOCALES_V7.length === 8,
    domains,
    acts: QL7_SUPPORT_SCENARIO_ACTS_V7.length,
    locales: QL7_SUPPORT_CORE_LOCALES_V7.length,
    canonicalScenarios: expected,
    multiTurnScenarios: QL7_SUPPORT_MULTI_TURN_SCENARIOS_V7.length,
  })
}
