import {isVipNowSideEffectFree} from '../subscriptions.js'
import {buildQl7IdentityGraph, publicQl7IdentityGraphProjection} from './identityGraph.js'
function s(v){return String(v??'').trim()}
export async function runQl7SupportVipDiagnostic({database,userId='',aliases=[],actor=null,caseId=''}={}){
 const graph=await buildQl7IdentityGraph({database,actor:actor||{canonicalAccountId:userId,aliases},extraAliases:aliases})
 const evidence=[];let active=null;let matched='';let untilISO=null;let daysLeft=0;let sawInactive=false
 for(const id of graph.lookupIds){try{const state=await isVipNowSideEffectFree(id);evidence.push({source:'subscriptions_read_only',aliasType:/^0x/i.test(id)?'wallet':(/telegram|^tg:/i.test(id)?'telegram':'account'),aliasMasked:id.length>12?`${id.slice(0,5)}…${id.slice(-5)}`:'***',active:state.active===true,untilISO:state.untilISO||null});if(state.active){active=true;matched=id;untilISO=state.untilISO;daysLeft=Number(state.daysLeft||0);break}if(state.untilISO){sawInactive=true;untilISO=untilISO||state.untilISO}}catch(error){evidence.push({source:'subscriptions_read_only',errorCategory:'unavailable'})}}
 const branch=active===true?'active':(sawInactive?'expired':(evidence.length?'inactive':'unavailable'))
 return{ok:branch!=='unavailable',topic:'vip',caseId:s(caseId),branch,status:branch==='active'?'healthy':(branch==='unavailable'?'unavailable':'no_data'),active:active===true,plan:active?'VIP':null,activatedAt:null,expiresAt:untilISO,remainingMs:untilISO?Math.max(0,Date.parse(untilISO)-Date.now()):0,daysLeft,resolvedIdentity:{matchedAliasType:matched?(/^0x/i.test(matched)?'wallet':(/telegram|^tg:/i.test(matched)?'telegram':'account')):null,matchedAliasMasked:matched?(matched.length>12?`${matched.slice(0,5)}…${matched.slice(-5)}`:'***'):null,graph:publicQl7IdentityGraphProjection(graph)},facts:[{key:'vipStatus',value:branch},{key:'expiresAt',value:untilISO||''},{key:'remainingDays',value:daysLeft}],checks:['canonical_identity_graph','subscriptions_side_effect_free'],anomalies:branch==='unavailable'?[{code:'vip_source_unavailable',severity:'medium'}]:[],evidence,readOnly:true,businessCollectionsRead:['subscriptions','profile_aliases'],businessCollectionsWritten:[],asOf:new Date().toISOString()}
}
