export const QL7_SUPPORT_ECOSYSTEM_LOCALE_LEXICON_VERSION = '5.1.0'

export const QL7_SUPPORT_ECOSYSTEM_ALL_LOCALES = Object.freeze(['en','ru','uk','es','tr','ar','zh','he','de','fr','it','pt','pl','nl','sv','no','da','fi','cs','sk','hu','ro','bg','sr','hr','sl','el','ka','az','kk','ja','ko'])

export const QL7_SUPPORT_ECOSYSTEM_MULTILINGUAL_LOCALES = Object.freeze([
  'de', 'fr', 'it', 'pt', 'pl', 'nl', 'sv', 'no', 'da', 'fi', 'cs', 'sk',
  'hu', 'ro', 'bg', 'sr', 'hr', 'sl', 'el', 'ka', 'az', 'kk', 'ja', 'ko',
])

const freeze = (value) => Object.freeze(value)

// This is a lexical/morphological owner, not a final-answer bank. Product names
// stay immutable while every descriptive label and verb is native to the locale.
const MULTILINGUAL = freeze({
  de: freeze({ news: 'Krypto-Nachrichten', futures: 'Futures-Simulator', academy: 'Akademie', exam: 'Prüfung', metaverse: 'Metaversum', forumFeed: 'Forum-Feed', forumThreads: 'Forum-Themen', search: 'Suche', media: 'Medien', moderation: 'Moderation', profile: 'Profil', auth: 'Anmeldung', payments: 'Zahlungen', adsPackages: 'Werbepakete', adsCampaigns: 'Werbekampagnen', push: 'Push-Benachrichtigungen', quests: 'Aufgaben', contact: 'Kontakt', privacy: 'Datenschutz', security: 'Sicherheit', accountDeletion: 'Konto löschen', navigation: 'Navigation', roadmap: 'Roadmap', systemStatus: 'Systemstatus', localization: 'Lokalisierung', accessibility: 'Barrierefreiheit', support: 'Support', learn: 'Mehr erfahren', openSection: 'Bereich öffnen', details: 'Details ansehen', open: 'öffnen', check: 'prüfen', continueSupport: 'Mit der Hilfe fortfahren', actionOrder: 'suffix' }),
  fr: freeze({ news: 'Actualités crypto', futures: 'Simulateur de contrats à terme', academy: 'Académie', exam: 'Examen', metaverse: 'Métavers', forumFeed: 'Fil du forum', forumThreads: 'Sujets du forum', search: 'Recherche', media: 'Médias', moderation: 'Modération', profile: 'Profil', auth: 'Connexion', payments: 'Paiements', adsPackages: 'Forfaits publicitaires', adsCampaigns: 'Campagnes publicitaires', push: 'Notifications push', quests: 'Quêtes', contact: 'Contact', privacy: 'Confidentialité', security: 'Sécurité', accountDeletion: 'Suppression du compte', navigation: 'Navigation', roadmap: 'Feuille de route', systemStatus: 'État du système', localization: 'Localisation', accessibility: 'Accessibilité', support: 'Assistance', learn: 'En savoir plus', openSection: 'Ouvrir la section', details: 'Voir les détails', open: 'Ouvrir', check: 'Vérifier', continueSupport: 'Continuer avec l’assistance', actionOrder: 'prefix' }),
  it: freeze({ news: 'Notizie crypto', futures: 'Simulatore di futures', academy: 'Accademia', exam: 'Esame', metaverse: 'Metaverso', forumFeed: 'Feed del forum', forumThreads: 'Discussioni del forum', search: 'Ricerca', media: 'Media', moderation: 'Moderazione', profile: 'Profilo', auth: 'Accesso', payments: 'Pagamenti', adsPackages: 'Pacchetti pubblicitari', adsCampaigns: 'Campagne pubblicitarie', push: 'Notifiche push', quests: 'Missioni', contact: 'Contatti', privacy: 'Privacy', security: 'Sicurezza', accountDeletion: 'Eliminazione account', navigation: 'Navigazione', roadmap: 'Roadmap', systemStatus: 'Stato del sistema', localization: 'Localizzazione', accessibility: 'Accessibilità', support: 'Assistenza', learn: 'Scopri di più', openSection: 'Apri la sezione', details: 'Vedi i dettagli', open: 'Apri', check: 'Controlla', continueSupport: 'Continua con l’assistenza', actionOrder: 'prefix' }),
  pt: freeze({ news: 'Notícias de criptomoedas', futures: 'Simulador de futuros', academy: 'Academia', exam: 'Exame', metaverse: 'Metaverso', forumFeed: 'Feed do fórum', forumThreads: 'Tópicos do fórum', search: 'Pesquisa', media: 'Mídia', moderation: 'Moderação', profile: 'Perfil', auth: 'Autorização', payments: 'Pagamentos', adsPackages: 'Pacotes publicitários', adsCampaigns: 'Campanhas publicitárias', push: 'Notificações push', quests: 'Missões', contact: 'Contato', privacy: 'Privacidade', security: 'Segurança', accountDeletion: 'Exclusão da conta', navigation: 'Navegação', roadmap: 'Roteiro', systemStatus: 'Estado do sistema', localization: 'Localização', accessibility: 'Acessibilidade', support: 'Suporte', learn: 'Saiba mais', openSection: 'Abrir a seção', details: 'Ver detalhes', open: 'Abrir', check: 'Verificar', continueSupport: 'Continuar com o suporte', actionOrder: 'prefix' }),
  pl: freeze({ news: 'Wiadomości kryptowalutowe', futures: 'Symulator kontraktów terminowych', academy: 'Akademia', exam: 'Egzamin', metaverse: 'Metawersum', forumFeed: 'Aktualności forum', forumThreads: 'Wątki forum', search: 'Wyszukiwanie', media: 'Multimedia', moderation: 'Moderacja', profile: 'Profil', auth: 'Logowanie', payments: 'Płatności', adsPackages: 'Pakiety reklamowe', adsCampaigns: 'Kampanie reklamowe', push: 'Powiadomienia push', quests: 'Zadania', contact: 'Kontakt', privacy: 'Prywatność', security: 'Bezpieczeństwo', accountDeletion: 'Usunięcie konta', navigation: 'Nawigacja', roadmap: 'Plan rozwoju', systemStatus: 'Stan systemu', localization: 'Lokalizacja', accessibility: 'Dostępność', support: 'Pomoc', learn: 'Dowiedz się więcej', openSection: 'Otwórz sekcję', details: 'Zobacz szczegóły', open: 'Otwórz', check: 'Sprawdź', continueSupport: 'Kontynuuj z pomocą', actionOrder: 'prefix' }),
  nl: freeze({ news: 'Cryptonieuws', futures: 'Futuresimulator', academy: 'Academie', exam: 'Examen', metaverse: 'Metaverse', forumFeed: 'Forumoverzicht', forumThreads: 'Forumonderwerpen', search: 'Zoeken', media: 'Media', moderation: 'Moderatie', profile: 'Profiel', auth: 'Aanmelden', payments: 'Betalingen', adsPackages: 'Advertentiepakketten', adsCampaigns: 'Advertentiecampagnes', push: 'Pushmeldingen', quests: 'Opdrachten', contact: 'Contact', privacy: 'Privacy', security: 'Beveiliging', accountDeletion: 'Account verwijderen', navigation: 'Navigatie', roadmap: 'Routekaart', systemStatus: 'Systeemstatus', localization: 'Lokalisatie', accessibility: 'Toegankelijkheid', support: 'Ondersteuning', learn: 'Meer informatie', openSection: 'Sectie openen', details: 'Details bekijken', open: 'openen', check: 'controleren', continueSupport: 'Doorgaan met ondersteuning', actionOrder: 'suffix' }),
  sv: freeze({ news: 'Kryptonyheter', futures: 'Terminssimulator', academy: 'Akademi', exam: 'Prov', metaverse: 'Metaversum', forumFeed: 'Forumflöde', forumThreads: 'Forumtrådar', search: 'Sökning', media: 'Media', moderation: 'Moderering', profile: 'Profil', auth: 'Inloggning', payments: 'Betalningar', adsPackages: 'Annonspaket', adsCampaigns: 'Annonskampanjer', push: 'Pushnotiser', quests: 'Uppdrag', contact: 'Kontakt', privacy: 'Integritet', security: 'Säkerhet', accountDeletion: 'Radera konto', navigation: 'Navigering', roadmap: 'Färdplan', systemStatus: 'Systemstatus', localization: 'Lokalisering', accessibility: 'Tillgänglighet', support: 'Support', learn: 'Läs mer', openSection: 'Öppna avsnittet', details: 'Visa detaljer', open: 'Öppna', check: 'Kontrollera', continueSupport: 'Fortsätt med hjälp', actionOrder: 'prefix' }),
  no: freeze({ news: 'Kryptonyheter', futures: 'Futuressimulator', academy: 'Akademi', exam: 'Eksamen', metaverse: 'Metavers', forumFeed: 'Forumstrøm', forumThreads: 'Forumtråder', search: 'Søk', media: 'Medier', moderation: 'Moderering', profile: 'Profil', auth: 'Innlogging', payments: 'Betalinger', adsPackages: 'Annonsepakker', adsCampaigns: 'Annonsekampanjer', push: 'Pushvarsler', quests: 'Oppdrag', contact: 'Kontakt', privacy: 'Personvern', security: 'Sikkerhet', accountDeletion: 'Slett konto', navigation: 'Navigasjon', roadmap: 'Veikart', systemStatus: 'Systemstatus', localization: 'Lokalisering', accessibility: 'Tilgjengelighet', support: 'Brukerstøtte', learn: 'Les mer', openSection: 'Åpne delen', details: 'Se detaljer', open: 'Åpne', check: 'Kontroller', continueSupport: 'Fortsett med brukerstøtte', actionOrder: 'prefix' }),
  da: freeze({ news: 'Kryptonyheder', futures: 'Futuresimulator', academy: 'Akademi', exam: 'Eksamen', metaverse: 'Metavers', forumFeed: 'Forumfeed', forumThreads: 'Forumtråde', search: 'Søgning', media: 'Medier', moderation: 'Moderation', profile: 'Profil', auth: 'Login', payments: 'Betalinger', adsPackages: 'Annoncepakker', adsCampaigns: 'Annoncekampagner', push: 'Pushnotifikationer', quests: 'Opgaver', contact: 'Kontakt', privacy: 'Privatliv', security: 'Sikkerhed', accountDeletion: 'Slet konto', navigation: 'Navigation', roadmap: 'Køreplan', systemStatus: 'Systemstatus', localization: 'Lokalisering', accessibility: 'Tilgængelighed', support: 'Support', learn: 'Læs mere', openSection: 'Åbn området', details: 'Se detaljer', open: 'Åbn', check: 'Kontrollér', continueSupport: 'Fortsæt med hjælp', actionOrder: 'prefix' }),
  fi: freeze({ news: 'Kryptouutiset', futures: 'Futuurisimulaattori', academy: 'Akatemia', exam: 'Koe', metaverse: 'Metaversumi', forumFeed: 'Foorumisyöte', forumThreads: 'Foorumin ketjut', search: 'Haku', media: 'Media', moderation: 'Moderointi', profile: 'Profiili', auth: 'Kirjautuminen', payments: 'Maksut', adsPackages: 'Mainospaketit', adsCampaigns: 'Mainoskampanjat', push: 'Push-ilmoitukset', quests: 'Tehtävät', contact: 'Yhteydenotto', privacy: 'Tietosuoja', security: 'Turvallisuus', accountDeletion: 'Tilin poistaminen', navigation: 'Navigointi', roadmap: 'Etenemissuunnitelma', systemStatus: 'Järjestelmän tila', localization: 'Lokalisointi', accessibility: 'Saavutettavuus', support: 'Tuki', learn: 'Lue lisää', openSection: 'Avaa osio', details: 'Näytä tiedot', open: 'Avaa', check: 'Tarkista', continueSupport: 'Jatka tuen kanssa', actionOrder: 'prefix' }),
  cs: freeze({ news: 'Krypto zprávy', futures: 'Simulátor futures', academy: 'Akademie', exam: 'Zkouška', metaverse: 'Metaverzum', forumFeed: 'Přehled fóra', forumThreads: 'Vlákna fóra', search: 'Vyhledávání', media: 'Média', moderation: 'Moderování', profile: 'Profil', auth: 'Přihlášení', payments: 'Platby', adsPackages: 'Reklamní balíčky', adsCampaigns: 'Reklamní kampaně', push: 'Push oznámení', quests: 'Úkoly', contact: 'Kontakt', privacy: 'Soukromí', security: 'Bezpečnost', accountDeletion: 'Odstranění účtu', navigation: 'Navigace', roadmap: 'Plán vývoje', systemStatus: 'Stav systému', localization: 'Lokalizace', accessibility: 'Přístupnost', support: 'Podpora', learn: 'Zjistit více', openSection: 'Otevřít sekci', details: 'Zobrazit podrobnosti', open: 'Otevřít', check: 'Zkontrolovat', continueSupport: 'Pokračovat s podporou', actionOrder: 'prefix' }),
  sk: freeze({ news: 'Krypto správy', futures: 'Simulátor futures', academy: 'Akadémia', exam: 'Skúška', metaverse: 'Metaverzum', forumFeed: 'Prehľad fóra', forumThreads: 'Vlákna fóra', search: 'Vyhľadávanie', media: 'Médiá', moderation: 'Moderovanie', profile: 'Profil', auth: 'Prihlásenie', payments: 'Platby', adsPackages: 'Reklamné balíky', adsCampaigns: 'Reklamné kampane', push: 'Push oznámenia', quests: 'Úlohy', contact: 'Kontakt', privacy: 'Súkromie', security: 'Bezpečnosť', accountDeletion: 'Odstránenie účtu', navigation: 'Navigácia', roadmap: 'Plán vývoja', systemStatus: 'Stav systému', localization: 'Lokalizácia', accessibility: 'Prístupnosť', support: 'Podpora', learn: 'Zistiť viac', openSection: 'Otvoriť sekciu', details: 'Zobraziť podrobnosti', open: 'Otvoriť', check: 'Skontrolovať', continueSupport: 'Pokračovať s podporou', actionOrder: 'prefix' }),
  hu: freeze({ news: 'Kriptohírek', futures: 'Határidős szimulátor', academy: 'Akadémia', exam: 'Vizsga', metaverse: 'Metaverzum', forumFeed: 'Fórumfolyam', forumThreads: 'Fórumtémák', search: 'Keresés', media: 'Média', moderation: 'Moderálás', profile: 'Profil', auth: 'Bejelentkezés', payments: 'Fizetések', adsPackages: 'Hirdetési csomagok', adsCampaigns: 'Hirdetési kampányok', push: 'Push értesítések', quests: 'Küldetések', contact: 'Kapcsolat', privacy: 'Adatvédelem', security: 'Biztonság', accountDeletion: 'Fiók törlése', navigation: 'Navigáció', roadmap: 'Ütemterv', systemStatus: 'Rendszerállapot', localization: 'Lokalizáció', accessibility: 'Akadálymentesség', support: 'Támogatás', learn: 'További információ', openSection: 'Szakasz megnyitása', details: 'Részletek megtekintése', open: 'Megnyitás:', check: 'Ellenőrzés:', continueSupport: 'Folytatás a támogatással', actionOrder: 'prefix' }),
  ro: freeze({ news: 'Știri cripto', futures: 'Simulator futures', academy: 'Academie', exam: 'Examen', metaverse: 'Metavers', forumFeed: 'Fluxul forumului', forumThreads: 'Subiectele forumului', search: 'Căutare', media: 'Media', moderation: 'Moderare', profile: 'Profil', auth: 'Autentificare', payments: 'Plăți', adsPackages: 'Pachete publicitare', adsCampaigns: 'Campanii publicitare', push: 'Notificări push', quests: 'Misiuni', contact: 'Contact', privacy: 'Confidențialitate', security: 'Securitate', accountDeletion: 'Ștergerea contului', navigation: 'Navigare', roadmap: 'Foaie de parcurs', systemStatus: 'Starea sistemului', localization: 'Localizare', accessibility: 'Accesibilitate', support: 'Asistență', learn: 'Află mai multe', openSection: 'Deschide secțiunea', details: 'Vezi detaliile', open: 'Deschide', check: 'Verifică', continueSupport: 'Continuă cu asistența', actionOrder: 'prefix' }),
  bg: freeze({ news: 'Крипто новини', futures: 'Симулатор за фючърси', academy: 'Академия', exam: 'Изпит', metaverse: 'Метавселена', forumFeed: 'Поток на форума', forumThreads: 'Теми във форума', search: 'Търсене', media: 'Медия', moderation: 'Модерация', profile: 'Профил', auth: 'Вход', payments: 'Плащания', adsPackages: 'Рекламни пакети', adsCampaigns: 'Рекламни кампании', push: 'Push известия', quests: 'Задачи', contact: 'Контакт', privacy: 'Поверителност', security: 'Сигурност', accountDeletion: 'Изтриване на акаунт', navigation: 'Навигация', roadmap: 'Пътна карта', systemStatus: 'Състояние на системата', localization: 'Локализация', accessibility: 'Достъпност', support: 'Поддръжка', learn: 'Научете повече', openSection: 'Отворете раздела', details: 'Вижте подробности', open: 'Отворете', check: 'Проверете', continueSupport: 'Продължете с поддръжката', actionOrder: 'prefix' }),
  sr: freeze({ news: 'Kripto vesti', futures: 'Simulator fjučersa', academy: 'Akademija', exam: 'Ispit', metaverse: 'Metaverzum', forumFeed: 'Tok foruma', forumThreads: 'Teme foruma', search: 'Pretraga', media: 'Mediji', moderation: 'Moderacija', profile: 'Profil', auth: 'Prijava', payments: 'Plaćanja', adsPackages: 'Reklamni paketi', adsCampaigns: 'Reklamne kampanje', push: 'Push obaveštenja', quests: 'Zadaci', contact: 'Kontakt', privacy: 'Privatnost', security: 'Bezbednost', accountDeletion: 'Brisanje naloga', navigation: 'Navigacija', roadmap: 'Plan razvoja', systemStatus: 'Stanje sistema', localization: 'Lokalizacija', accessibility: 'Pristupačnost', support: 'Podrška', learn: 'Saznajte više', openSection: 'Otvorite odeljak', details: 'Pogledajte detalje', open: 'Otvorite', check: 'Proverite', continueSupport: 'Nastavite sa podrškom', actionOrder: 'prefix' }),
  hr: freeze({ news: 'Kripto vijesti', futures: 'Simulator futuresa', academy: 'Akademija', exam: 'Ispit', metaverse: 'Metaverzum', forumFeed: 'Tok foruma', forumThreads: 'Teme foruma', search: 'Pretraživanje', media: 'Mediji', moderation: 'Moderiranje', profile: 'Profil', auth: 'Prijava', payments: 'Plaćanja', adsPackages: 'Oglasni paketi', adsCampaigns: 'Oglasne kampanje', push: 'Push obavijesti', quests: 'Zadaci', contact: 'Kontakt', privacy: 'Privatnost', security: 'Sigurnost', accountDeletion: 'Brisanje računa', navigation: 'Navigacija', roadmap: 'Plan razvoja', systemStatus: 'Stanje sustava', localization: 'Lokalizacija', accessibility: 'Pristupačnost', support: 'Podrška', learn: 'Saznajte više', openSection: 'Otvorite odjeljak', details: 'Pogledajte pojedinosti', open: 'Otvorite', check: 'Provjerite', continueSupport: 'Nastavite s podrškom', actionOrder: 'prefix' }),
  sl: freeze({ news: 'Kripto novice', futures: 'Simulator terminskih pogodb', academy: 'Akademija', exam: 'Izpit', metaverse: 'Metaverzum', forumFeed: 'Tok foruma', forumThreads: 'Teme foruma', search: 'Iskanje', media: 'Predstavnost', moderation: 'Moderiranje', profile: 'Profil', auth: 'Prijava', payments: 'Plačila', adsPackages: 'Oglaševalski paketi', adsCampaigns: 'Oglaševalske kampanje', push: 'Potisna obvestila', quests: 'Naloge', contact: 'Stik', privacy: 'Zasebnost', security: 'Varnost', accountDeletion: 'Izbris računa', navigation: 'Krmarjenje', roadmap: 'Načrt razvoja', systemStatus: 'Stanje sistema', localization: 'Lokalizacija', accessibility: 'Dostopnost', support: 'Podpora', learn: 'Več informacij', openSection: 'Odprite razdelek', details: 'Oglejte si podrobnosti', open: 'Odprite', check: 'Preverite', continueSupport: 'Nadaljujte s podporo', actionOrder: 'prefix' }),
  el: freeze({ news: 'Νέα κρυπτονομισμάτων', futures: 'Προσομοιωτής συμβολαίων μελλοντικής εκπλήρωσης', academy: 'Ακαδημία', exam: 'Εξέταση', metaverse: 'Μετασύμπαν', forumFeed: 'Ροή φόρουμ', forumThreads: 'Θέματα φόρουμ', search: 'Αναζήτηση', media: 'Πολυμέσα', moderation: 'Εποπτεία', profile: 'Προφίλ', auth: 'Σύνδεση', payments: 'Πληρωμές', adsPackages: 'Διαφημιστικά πακέτα', adsCampaigns: 'Διαφημιστικές καμπάνιες', push: 'Ειδοποιήσεις push', quests: 'Αποστολές', contact: 'Επικοινωνία', privacy: 'Απόρρητο', security: 'Ασφάλεια', accountDeletion: 'Διαγραφή λογαριασμού', navigation: 'Πλοήγηση', roadmap: 'Οδικός χάρτης', systemStatus: 'Κατάσταση συστήματος', localization: 'Τοπική προσαρμογή', accessibility: 'Προσβασιμότητα', support: 'Υποστήριξη', learn: 'Μάθετε περισσότερα', openSection: 'Ανοίξτε την ενότητα', details: 'Δείτε λεπτομέρειες', open: 'Ανοίξτε', check: 'Ελέγξτε', continueSupport: 'Συνεχίστε με την υποστήριξη', actionOrder: 'prefix' }),
  ka: freeze({ news: 'კრიპტო სიახლეები', futures: 'ფიუჩერსების სიმულატორი', academy: 'აკადემია', exam: 'გამოცდა', metaverse: 'მეტავერსი', forumFeed: 'ფორუმის ნაკადი', forumThreads: 'ფორუმის თემები', search: 'ძიება', media: 'მედია', moderation: 'მოდერაცია', profile: 'პროფილი', auth: 'შესვლა', payments: 'გადახდები', adsPackages: 'სარეკლამო პაკეტები', adsCampaigns: 'სარეკლამო კამპანიები', push: 'Push შეტყობინებები', quests: 'დავალებები', contact: 'კონტაქტი', privacy: 'კონფიდენციალურობა', security: 'უსაფრთხოება', accountDeletion: 'ანგარიშის წაშლა', navigation: 'ნავიგაცია', roadmap: 'საგზაო რუკა', systemStatus: 'სისტემის მდგომარეობა', localization: 'ლოკალიზაცია', accessibility: 'ხელმისაწვდომობა', support: 'მხარდაჭერა', learn: 'გაიგეთ მეტი', openSection: 'გახსენით განყოფილება', details: 'იხილეთ დეტალები', open: 'გახსენით', check: 'შეამოწმეთ', continueSupport: 'გააგრძელეთ მხარდაჭერასთან', actionOrder: 'prefix' }),
  az: freeze({ news: 'Kripto xəbərləri', futures: 'Fyuçers simulyatoru', academy: 'Akademiya', exam: 'İmtahan', metaverse: 'Metakainat', forumFeed: 'Forum axını', forumThreads: 'Forum mövzuları', search: 'Axtarış', media: 'Media', moderation: 'Moderasiya', profile: 'Profil', auth: 'Giriş', payments: 'Ödənişlər', adsPackages: 'Reklam paketləri', adsCampaigns: 'Reklam kampaniyaları', push: 'Push bildirişləri', quests: 'Tapşırıqlar', contact: 'Əlaqə', privacy: 'Məxfilik', security: 'Təhlükəsizlik', accountDeletion: 'Hesabın silinməsi', navigation: 'Naviqasiya', roadmap: 'Yol xəritəsi', systemStatus: 'Sistem vəziyyəti', localization: 'Lokallaşdırma', accessibility: 'Əlçatanlıq', support: 'Dəstək', learn: 'Ətraflı öyrənin', openSection: 'Bölməni açın', details: 'Təfərrüatlara baxın', open: 'Açın', check: 'Yoxlayın', continueSupport: 'Dəstəklə davam edin', actionOrder: 'prefix' }),
  kk: freeze({ news: 'Крипто жаңалықтары', futures: 'Фьючерстер симуляторы', academy: 'Академия', exam: 'Емтихан', metaverse: 'Метаверс', forumFeed: 'Форум таспасы', forumThreads: 'Форум тақырыптары', search: 'Іздеу', media: 'Медиа', moderation: 'Модерация', profile: 'Профиль', auth: 'Кіру', payments: 'Төлемдер', adsPackages: 'Жарнама пакеттері', adsCampaigns: 'Жарнама науқандары', push: 'Push хабарландырулары', quests: 'Тапсырмалар', contact: 'Байланыс', privacy: 'Құпиялылық', security: 'Қауіпсіздік', accountDeletion: 'Аккаунтты жою', navigation: 'Навигация', roadmap: 'Жол картасы', systemStatus: 'Жүйе күйі', localization: 'Локализация', accessibility: 'Қолжетімділік', support: 'Қолдау', learn: 'Толығырақ білу', openSection: 'Бөлімді ашу', details: 'Мәліметтерді көру', open: 'Ашу:', check: 'Тексеру:', continueSupport: 'Қолдаумен жалғастыру', actionOrder: 'prefix' }),
  ja: freeze({ news: '暗号資産ニュース', futures: '先物シミュレーター', academy: 'アカデミー', exam: '試験', metaverse: 'メタバース', forumFeed: 'フォーラムフィード', forumThreads: 'フォーラムトピック', search: '検索', media: 'メディア', moderation: 'モデレーション', profile: 'プロフィール', auth: 'ログイン', payments: '支払い', adsPackages: '広告パッケージ', adsCampaigns: '広告キャンペーン', push: 'プッシュ通知', quests: 'クエスト', contact: 'お問い合わせ', privacy: 'プライバシー', security: 'セキュリティ', accountDeletion: 'アカウント削除', navigation: 'ナビゲーション', roadmap: 'ロードマップ', systemStatus: 'システム状態', localization: 'ローカライズ', accessibility: 'アクセシビリティ', support: 'サポート', learn: '詳しく見る', openSection: 'セクションを開く', details: '詳細を確認', open: 'を開く', check: 'を確認', continueSupport: 'サポートを続ける', actionOrder: 'suffix' }),
  ko: freeze({ news: '암호화폐 뉴스', futures: '선물 시뮬레이터', academy: '아카데미', exam: '시험', metaverse: '메타버스', forumFeed: '포럼 피드', forumThreads: '포럼 주제', search: '검색', media: '미디어', moderation: '관리', profile: '프로필', auth: '로그인', payments: '결제', adsPackages: '광고 패키지', adsCampaigns: '광고 캠페인', push: '푸시 알림', quests: '퀘스트', contact: '문의', privacy: '개인정보 보호', security: '보안', accountDeletion: '계정 삭제', navigation: '탐색', roadmap: '로드맵', systemStatus: '시스템 상태', localization: '현지화', accessibility: '접근성', support: '지원', learn: '자세히 알아보기', openSection: '섹션 열기', details: '세부 정보 보기', open: '열기', check: '확인', continueSupport: '지원 계속하기', actionOrder: 'suffix' }),
})



// Special non-product domain labels are lexical primitives, never final-answer sentences.
// They are explicit to prevent silent English/generic-Support fallback in provider locales.
const SPECIAL_MULTILINGUAL_TOPIC_LABELS = freeze({
  de: freeze({ partnership:'Partnerschaft', investment:'Investitionsvorschlag', learning_governance:'Sichere Lernsteuerung' }),
  fr: freeze({ partnership:'Partenariat', investment:'Proposition d’investissement', learning_governance:'Gouvernance sûre de l’apprentissage' }),
  it: freeze({ partnership:'Collaborazione', investment:'Proposta di investimento', learning_governance:'Governance sicura dell’apprendimento' }),
  pt: freeze({ partnership:'Parceria', investment:'Proposta de investimento', learning_governance:'Governança segura da aprendizagem' }),
  pl: freeze({ partnership:'Partnerstwo', investment:'Propozycja inwestycyjna', learning_governance:'Bezpieczne zarządzanie uczeniem' }),
  nl: freeze({ partnership:'Partnerschap', investment:'Investeringsvoorstel', learning_governance:'Veilig leerbeheer' }),
  sv: freeze({ partnership:'Partnerskap', investment:'Investeringsförslag', learning_governance:'Säker styrning av lärande' }),
  no: freeze({ partnership:'Partnerskap', investment:'Investeringsforslag', learning_governance:'Sikker styring av læring' }),
  da: freeze({ partnership:'Partnerskab', investment:'Investeringsforslag', learning_governance:'Sikker styring af læring' }),
  fi: freeze({ partnership:'Kumppanuus', investment:'Sijoitusehdotus', learning_governance:'Turvallinen oppimisen hallinta' }),
  cs: freeze({ partnership:'Partnerství', investment:'Investiční návrh', learning_governance:'Bezpečná správa učení' }),
  sk: freeze({ partnership:'Partnerstvo', investment:'Investičný návrh', learning_governance:'Bezpečná správa učenia' }),
  hu: freeze({ partnership:'Partnerség', investment:'Befektetési javaslat', learning_governance:'Biztonságos tanulásirányítás' }),
  ro: freeze({ partnership:'Parteneriat', investment:'Propunere de investiție', learning_governance:'Guvernanță sigură a învățării' }),
  bg: freeze({ partnership:'Партньорство', investment:'Инвестиционно предложение', learning_governance:'Безопасно управление на обучението' }),
  sr: freeze({ partnership:'Partnerstvo', investment:'Investicioni predlog', learning_governance:'Bezbedno upravljanje učenjem' }),
  hr: freeze({ partnership:'Partnerstvo', investment:'Investicijski prijedlog', learning_governance:'Sigurno upravljanje učenjem' }),
  sl: freeze({ partnership:'Partnerstvo', investment:'Naložbeni predlog', learning_governance:'Varno upravljanje učenjem' }),
  el: freeze({ partnership:'Συνεργασία', investment:'Επενδυτική πρόταση', learning_governance:'Ασφαλής διακυβέρνηση μάθησης' }),
  ka: freeze({ partnership:'პარტნიორობა', investment:'საინვესტიციო შეთავაზება', learning_governance:'სწავლის უსაფრთხო მართვა' }),
  az: freeze({ partnership:'Tərəfdaşlıq', investment:'İnvestisiya təklifi', learning_governance:'Təhlükəsiz öyrənmə idarəetməsi' }),
  kk: freeze({ partnership:'Серіктестік', investment:'Инвестициялық ұсыныс', learning_governance:'Қауіпсіз оқытуды басқару' }),
  ja: freeze({ partnership:'パートナーシップ', investment:'投資提案', learning_governance:'安全な学習ガバナンス' }),
  ko: freeze({ partnership:'파트너십', investment:'투자 제안', learning_governance:'안전한 학습 거버넌스' }),
})

const BRANDED = freeze({
  platform: 'Quantum L7 AI', homepage: 'CryptoRadar', exchange: 'Quantum Exchange', exchange_ai: 'Exchange AI',
  battlecoin: 'BattleCoin', battle_chat: 'Battle Chat', gameverse: 'Gameverse', metastudio: 'MetaStudio',
  quantum_zigzag: 'Quantum Zigzag', ql7_blockchain: 'L7 Blockchain', geodetect: 'GeoDetect',
  metamarket: 'MetaMarket', quantum_family: 'Quantum Family', wallet: 'Quantum Wallet', telegram: 'Telegram Mini App',
  qcoin: 'QCoin', vip: 'VIP Plus', messenger: 'Quantum Messenger',
})

function buildLabels(pack, locale) {
  return freeze({
    ...BRANDED,
    news: pack.news, futures: pack.futures, academy: pack.academy, academy_exam: `${pack.academy}: ${pack.exam}`,
    metaverse: pack.metaverse, forum_feed: pack.forumFeed, forum_threads: pack.forumThreads,
    search: pack.search, media: pack.media, moderation: pack.moderation, profile: pack.profile, auth: pack.auth,
    payments: pack.payments, ads_packages: pack.adsPackages, ads_campaigns: pack.adsCampaigns, push: pack.push,
    quests: pack.quests, contact: pack.contact, privacy: pack.privacy, security: pack.security,
    account_deletion: pack.accountDeletion, navigation: pack.navigation, roadmap: pack.roadmap,
    system_status: pack.systemStatus, localization: pack.localization, accessibility: pack.accessibility,
    support_system: pack.support, ...(SPECIAL_MULTILINGUAL_TOPIC_LABELS[locale] || {}),
  })
}

const LABELS = freeze(Object.fromEntries(Object.entries(MULTILINGUAL).map(([locale, pack]) => [locale, buildLabels(pack, locale)])))

function action(pack, object, verb = pack.open) {
  return pack.actionOrder === 'suffix' ? `${object}${verb.startsWith('を') ? '' : ' '}${verb}`.trim() : `${verb} ${object}`.trim()
}

export function getQl7SupportMultilingualTopicLabel(topic = '', locale = '') {
  return LABELS[locale]?.[topic] || ''
}

export function getQl7SupportMultilingualActionLabels(locale = '') {
  const pack = MULTILINGUAL[locale]
  const labels = LABELS[locale]
  if (!pack || !labels) return null
  return freeze({
    default: freeze([pack.learn, pack.openSection, pack.details]),
    wallet: action(pack, labels.wallet), qcoin: action(pack, labels.qcoin, pack.check), vip: action(pack, labels.vip),
    metamarket: action(pack, labels.metamarket), ads: action(pack, labels.ads_campaigns), exchange: action(pack, labels.exchange),
    exchangeAi: action(pack, labels.exchange_ai), gameverse: action(pack, labels.gameverse), academy: action(pack, labels.academy),
    forum: action(pack, labels.forum_feed), messenger: action(pack, labels.messenger), auth: action(pack, labels.auth),
    privacy: action(pack, labels.privacy), support: pack.continueSupport,
  })
}

export function auditQl7SupportEcosystemLocaleLexicon(topics = []) {
  const requiredTopics = [...new Set(topics)]
  const requiredActions = ['default', 'wallet', 'qcoin', 'vip', 'metamarket', 'ads', 'exchange', 'exchangeAi', 'gameverse', 'academy', 'forum', 'messenger', 'auth', 'privacy', 'support']
  const rows = QL7_SUPPORT_ECOSYSTEM_MULTILINGUAL_LOCALES.map((locale) => {
    const labels = LABELS[locale] || {}
    const actions = getQl7SupportMultilingualActionLabels(locale)
    const missingTopics = requiredTopics.filter((topic) => !String(labels[topic] || '').trim())
    const missingActions = requiredActions.filter((key) => !actions || (Array.isArray(actions[key]) ? !actions[key].length : !String(actions[key] || '').trim()))
    const specialDomainCollision = ['partnership','investment','learning_governance'].filter((topic) => !String(labels[topic] || '').trim() || String(labels[topic]).trim() === String(labels.support_system || '').trim())
    return freeze({ locale, missingTopics: freeze(missingTopics), missingActions: freeze(missingActions), specialDomainCollision: freeze(specialDomainCollision), ok: !missingTopics.length && !missingActions.length && !specialDomainCollision.length })
  })
  return freeze({ version: QL7_SUPPORT_ECOSYSTEM_LOCALE_LEXICON_VERSION, localeCount: rows.length, topicCount: requiredTopics.length, rows: freeze(rows), ok: rows.length === QL7_SUPPORT_ECOSYSTEM_MULTILINGUAL_LOCALES.length && rows.every((item) => item.ok) })
}
