import {ql7StableHash} from '../internal/text.js'
import {QL7_SUPPORT_ALL_LOCALES} from '../config/behaviorManifest.js'
import {QL7_SUPPORT_REVIEWED_SEEDS_BY_LOCALE, auditQl7SupportReviewedSeedRegistry} from './reviewedSeedRegistry.js'
import {readQl7MaterialJson} from './materialDataLoader.js'
import {QL7_SUPPORT_MUTATION_FAMILIES} from './mutationLattice.js'
export const QL7_SUPPORT_LANGUAGE_VARIANT_BANK_VERSION='5.4.0'
export const QL7_SUPPORT_LANGUAGE_VARIANT_REQUIRED_MATERIAL_FAMILIES=Object.freeze(['code_switch','intentional_obfuscation'])
export const QL7_SUPPORT_LANGUAGE_MUTATION_FAMILIES=QL7_SUPPORT_MUTATION_FAMILIES
export const QL7_SUPPORT_LANGUAGE_VARIANT_PROFILES=Object.freeze(Object.fromEntries(QL7_SUPPORT_ALL_LOCALES.map(locale=>{const doc=readQl7MaterialJson(`lib/ql7-support/language/dialectProfiles/${locale}.json`),profiles=Object.freeze((doc.profiles||[]).map(Object.freeze));return [locale,Object.freeze({locale,dialectFamilies:Object.freeze(profiles.map(x=>x.dialectId)),dialectProfiles:profiles,mutationFamilies:QL7_SUPPORT_LANGUAGE_MUTATION_FAMILIES,reviewedSemanticSeedCount:QL7_SUPPORT_REVIEWED_SEEDS_BY_LOCALE[locale]?.length||0,openDialectFallback:true,nativeCompletenessClaimed:false,nativeHumanReviewRequired:true,profileHash:ql7StableHash(JSON.stringify({locale,profiles,mutations:QL7_SUPPORT_LANGUAGE_MUTATION_FAMILIES}))})]})))
export function auditQl7SupportLanguageVariantBank(){const failures=[],locales=Object.keys(QL7_SUPPORT_LANGUAGE_VARIANT_PROFILES),seedAudit=auditQl7SupportReviewedSeedRegistry();let materialProfiles=0;for(const l of locales){const r=QL7_SUPPORT_LANGUAGE_VARIANT_PROFILES[l];if(r.dialectProfiles.length<4)failures.push(`dialect_floor:${l}`);for(const p of r.dialectProfiles){materialProfiles++;const n=(p.lexicalPatterns?.length||0)+(p.morphologyNotes?.length||0)+(p.phoneticVoiceLikePatterns?.length||0)+(p.slangAliases?.length||0)+(p.safeNegativeExamples?.length||0);if(n<20)failures.push(`dialect_material:${p.dialectId}:${n}`)}if(r.reviewedSemanticSeedCount<1500)failures.push(`seed_floor:${l}`)}if(locales.length!==32)failures.push(`locale_count:${locales.length}`);if(materialProfiles<256)failures.push(`material_profiles:${materialProfiles}`);if(QL7_SUPPORT_LANGUAGE_MUTATION_FAMILIES.length<24)failures.push(`mutation_floor:${QL7_SUPPORT_LANGUAGE_MUTATION_FAMILIES.length}`);if(!seedAudit.ok)failures.push('seed_registry');return Object.freeze({schema:'ql7.support.language-variant-bank-audit',schemaVersion:QL7_SUPPORT_LANGUAGE_VARIANT_BANK_VERSION,ok:!failures.length,localeCount:locales.length,dialectFamilyCount:materialProfiles,materialDialectProfileCount:materialProfiles,mutationFamilyCount:QL7_SUPPORT_LANGUAGE_MUTATION_FAMILIES.length,reviewedSeedsPerLocale:1500,totalReviewedSeeds:seedAudit.totalSeeds,openDialectFallback:true,nativeCompletenessClaimed:false,nativeHumanReviewRequired:true,failures:Object.freeze(failures)})}
