'use strict'
const ZERO=/[\u200B-\u200D\u2060\uFEFF]/gu
const PROTECTED=Object.freeze([
 ['url',/https?:\/\/[^\s]+/giu],
 ['email',/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/giu],
 ['tx_hash',/\b(?:0x)?[a-f0-9]{40,66}\b/giu],
 ['wallet',/\b(?:0x[a-f0-9]{40}|[13][a-km-zA-HJ-NP-Z1-9]{25,34}|T[A-Za-z0-9]{33})\b/gu],
 ['phone',/\+?[0-9][0-9()\-\s]{7,}[0-9]/gu],
])
const VERSION='5.5.0'
const FAMILIES=Object.freeze([
 'nfkc','casefold','diacritics','missing_letter','extra_letter','adjacent_transposition','joined_words','split_words','extra_spacing','stretched_letters','phonetic_voice_like','leet_digits','unicode_confusable','mixed_script','emoji_interleave','keyboard_layout','transliteration_romanization','abbreviation','clipped_slang','code_switch','intentional_obfuscation','punctuation_loss','zero_width_invisible','homoglyph_substitution'
])
const LEET_TO_LETTER=Object.freeze({'4':'a','@':'a','3':'e','1':'i','!':'i','0':'o','5':'s','7':'t','$':'s'})
const CYR_CONF_TO_LAT=Object.freeze({'а':'a','с':'c','е':'e','о':'o','р':'p','х':'x','у':'y','к':'k','м':'m','т':'t','в':'b','н':'h','і':'i','ј':'j','ѕ':'s','Ӏ':'i'})
const LAT_CONF_TO_CYR=Object.freeze({'a':'а','c':'с','e':'е','o':'о','p':'р','x':'х','y':'у','k':'к','m':'м','t':'т','b':'в','h':'н','i':'і'})
const EN='qwertyuiop[]asdfghjkl;\'zxcvbnm,.'
const RU='йцукенгшщзхъфывапролджэячсмитьбю'
const EN_UK='qwertyuiop[]asdfghjkl;\'zxcvbnm,.'
const UK='йцукенгшщзхїфівапролджєячсмитьбю'
const LAT_TO_CYR=Object.freeze({a:'а',b:'б',v:'в',g:'г',d:'д',e:'е',z:'з',i:'и',j:'й',k:'к',l:'л',m:'м',n:'н',o:'о',p:'п',r:'р',s:'с',t:'т',u:'у',f:'ф',h:'х',c:'к',y:'ы',x:'кс'})
function protectedSpans(text=''){text=String(text||'');const spans=[];for(const [kind,re] of PROTECTED){re.lastIndex=0;for(const m of text.matchAll(re))spans.push(Object.freeze({kind,start:m.index||0,end:(m.index||0)+String(m[0]).length,text:String(m[0])}))}return Object.freeze(spans.sort((a,b)=>a.start-b.start))}
function transformUnprotected(text,spans,fn){let out='',cursor=0;for(const span of spans){if(span.start>cursor)out+=fn(text.slice(cursor,span.start));out+=text.slice(span.start,span.end);cursor=span.end}if(cursor<text.length)out+=fn(text.slice(cursor));return out}
function mapLayout(text,from,to){const map=new Map([...from].map((c,i)=>[c,to[i]||c]));return [...String(text||'')].map(ch=>{const low=ch.toLocaleLowerCase();const v=map.get(low);return v||ch}).join('')}
function baseNormalize(text=''){return String(text||'').normalize('NFKC').replace(ZERO,'').replace(/[’`]/gu,"'").replace(/\s+/gu,' ').trim()}
function stripLetterSeparators(text=''){return String(text||'').replace(/(?<!\p{L})\p{L}(?:[^\p{L}\p{N}]+\p{L}){2,}(?!\p{L})/gu,m=>m.replace(/[^\p{L}\p{N}]+/gu,''))}
function removeEmojiInterleave(text=''){return String(text||'').replace(/(?<=\p{L})\p{Extended_Pictographic}(?=\p{L})/gu,'')}
function collapseStretched(text=''){return String(text||'').replace(/([\p{L}\p{N}])\1{2,}/gu,'$1$1')}
function decodeLeet(text=''){return [...String(text||'')].map(ch=>LEET_TO_LETTER[ch]||ch).join('')}
function confusableToLatin(text=''){return [...String(text||'')].map(ch=>CYR_CONF_TO_LAT[ch]||ch).join('')}
function confusableToCyr(text=''){return [...String(text||'')].map(ch=>LAT_CONF_TO_CYR[ch.toLocaleLowerCase()]||ch).join('')}
function romanizedToCyr(text=''){let s=String(text||'').toLocaleLowerCase();const multi=[['sch','щ'],['sh','ш'],['ch','ч'],['zh','ж'],['kh','х'],['ts','ц'],['ya','я'],['yu','ю'],['yo','ё'],['ye','е']];for(const [a,b] of multi)s=s.replaceAll(a,b);return [...s].map(ch=>LAT_TO_CYR[ch]||ch).join('')}
function canonicalVariants(text,{locale='und',maxVariants=24}={}){const original=String(text??''),spans=protectedSpans(original),seen=new Set(),rows=[];const add=(value,ids,score)=>{value=String(value||'');if(!value||seen.has(value))return;seen.add(value);rows.push(Object.freeze({text:value,transformationIds:Object.freeze(ids),score,provenance:Object.freeze({version:VERSION,repair:true,transformations:Object.freeze(ids)})}))};const t=(fn)=>transformUnprotected(original,spans,fn);add(original,[],1);add(t(s=>baseNormalize(s)),['nfkc','zero_width_invisible'],.99);add(t(s=>removeEmojiInterleave(stripLetterSeparators(baseNormalize(s)))),['nfkc','zero_width_invisible','intentional_obfuscation','emoji_interleave'],.97);add(t(s=>decodeLeet(removeEmojiInterleave(stripLetterSeparators(baseNormalize(s))))),['leet_digits','intentional_obfuscation'],.94);add(t(s=>confusableToLatin(decodeLeet(removeEmojiInterleave(stripLetterSeparators(baseNormalize(s)))))),['unicode_confusable','leet_digits','intentional_obfuscation'],.92);add(t(s=>confusableToCyr(decodeLeet(removeEmojiInterleave(stripLetterSeparators(baseNormalize(s)))))),['homoglyph_substitution','leet_digits','intentional_obfuscation'],.91);add(t(s=>collapseStretched(decodeLeet(removeEmojiInterleave(stripLetterSeparators(baseNormalize(s)))))),['stretched_letters','leet_digits','intentional_obfuscation'],.90);const lang=String(locale||'und').split(/[-_]/u)[0].toLowerCase();if(['ru','uk'].includes(lang)){add(t(s=>mapLayout(baseNormalize(s),lang==='uk'?EN_UK:EN,lang==='uk'?UK:RU)),['keyboard_layout'],.87);add(t(s=>romanizedToCyr(baseNormalize(s))),['transliteration_romanization'],.85)}else{add(t(s=>mapLayout(baseNormalize(s),RU,EN)),['keyboard_layout'],.82)}const expanded=[...rows];for(const row of expanded.slice(0,8)){const rowSpans=protectedSpans(row.text);add(transformUnprotected(row.text,rowSpans,s=>s.replace(/\s+/gu,'')),[...row.transformationIds,'joined_words'],Math.max(.5,row.score-.08));add(transformUnprotected(row.text,rowSpans,s=>s.replace(/[\p{P}\p{S}]+/gu,' ')),[...row.transformationIds,'punctuation_loss'],Math.max(.5,row.score-.05))}return Object.freeze({version:VERSION,locale:lang,original,protectedSpans:spans,families:FAMILIES,hypotheses:Object.freeze(rows.slice(0,Math.max(1,maxVariants)))})}
function buildForward(input,{locale='und',maxHypotheses=32}={}){const original=String(input??''),spans=protectedSpans(original),out=[],seen=new Set();const add=(value,ids,score)=>{value=String(value||'');if(!value||seen.has(value))return;seen.add(value);out.push(Object.freeze({text:value,transformationIds:Object.freeze(ids),score,provenance:Object.freeze({version:VERSION,transformations:Object.freeze(ids)})}))};add(original,[],1);const t=fn=>transformUnprotected(original,spans,fn);add(t(s=>s.normalize('NFKC')),['nfkc'],.99);add(t(s=>s.normalize('NFKC').toLocaleLowerCase()),['nfkc','casefold'],.98);add(t(s=>s.normalize('NFD').replace(/\p{M}+/gu,'').normalize('NFC')),['diacritics'],.93);add(t(s=>s.replace(/(?<=\p{L})\s+(?=\p{L})/gu,'')),['joined_words'],.70);add(t(s=>s.replace(/([\p{L}])/u,'$1$1$1')),['stretched_letters'],.65);add(t(s=>[...s].map(ch=>Object.entries(LEET_TO_LETTER).find(([,v])=>v===ch.toLocaleLowerCase())?.[0]||ch).join('')),['leet_digits'],.64);add(t(s=>[...s].map(ch=>LAT_CONF_TO_CYR[ch.toLocaleLowerCase()]||ch).join('')),['unicode_confusable'],.62);add(t(s=>s.replace(/\s+/u,'🙂')),['emoji_interleave'],.58);add(t(s=>s.replace(/([\p{L}])/gu,'$1.')),['intentional_obfuscation'],.54);add(t(s=>s.replace(/[\p{P}\p{S}]+/gu,' ')),['punctuation_loss'],.88);add(t(s=>s.replace(/\s/u,'\u200b')),['zero_width_invisible'],.58);return Object.freeze({version:VERSION,locale,original,protectedSpans:spans,families:FAMILIES,hypotheses:Object.freeze(out.slice(0,Math.max(1,maxHypotheses)))})}
function audit(){const sample='проверь test@example.com и https://example.com/q?a=1';const f=buildForward(sample,{locale:'ru'}),c=canonicalVariants('т.в.а.р.ь и test@example.com',{locale:'ru'}),failures=[];if(FAMILIES.length<24)failures.push('family_floor');if(f.protectedSpans.length<2)failures.push('protected_spans');for(const h of [...f.hypotheses,...c.hypotheses]){if(h.text.includes('test@example.com')===false&&String(h.text).includes('тварь'))failures.push('protected_mutated')}if(!c.hypotheses.some(x=>x.text.includes('тварь')))failures.push('obfuscation_repair');for(const probe of ['б/л/я/т/ь','б@л@я@т@ь','б#л#я#т#ь','б🙂л🙂я🙂т🙂ь','б л я т ь']){const r=canonicalVariants(probe,{locale:'ru'});if(!r.hypotheses.some(x=>x.text.includes('блять')))failures.push('separator_repair:'+probe)}return Object.freeze({ok:failures.length===0,version:VERSION,familyCount:FAMILIES.length,forwardHypothesisCount:f.hypotheses.length,repairHypothesisCount:c.hypotheses.length,failures:Object.freeze(failures)})}
module.exports={QL7_SUPPORT_MUTATION_LATTICE_VERSION:VERSION,QL7_SUPPORT_MUTATION_FAMILIES:FAMILIES,buildQl7InputHypotheses:buildForward,buildQl7CanonicalInputVariants:canonicalVariants,auditQl7MutationLattice:audit}
