import { ql7Locale, ql7Str } from '../internal/text.js'

export const QL7_SUPPORT_NATIVE_COPY_VERSION = '14.2.0'

const COPY = Object.freeze({
  en: {
    knowledgeIntro: (label) => `${label} is a QUANTUM L7 AI ecosystem section.`,
    knowledgeUse: (label) => `It helps you use ${label}, understand its current capabilities and respect its safety or account boundaries.`,
    knowledgeAccount: 'Account-specific status is shown only from verified read-only data.',
    qcoinBalance: (value) => `Verified balance: ${value} QCoin.`, vipActive: 'VIP status is active.', vipInactive: 'VIP status is inactive; this is a verified normal state.',
    adsEmpty: (name) => `Package ${name} is verified. There are no active campaigns right now.`, adsActive: (name,count) => `Package ${name} is verified; active campaigns: ${count}.`, campaigns: (count) => `Verified campaigns: ${count}. Metrics are shown in the table.`, payment: (status) => `Payment status: ${status}.`,
    titles:{safety:'Your safety comes first',paused:'Conversation paused',boundary:'Conversation boundary',support:'QL7 Support',humor:'A little humor',emotional:'I am here',identity:'Who I am',investment:'Investment proposal',partnership:'Partnership',choice:'What should I check?',qcoin:'QCoin review',unavailable:'Source temporarily unavailable',verified:'Verified data',how:'How it works'},
    composer:{ready:'Ready',analysis:'Preparing the answer',spam:'Temporary pause',safety:'Security pause',boundary:'Please keep the conversation respectful'},
    surface:{field:'Field',value:'Value',other:'Other',placeholder:'Describe what you need me to check.',checked:'Checked',confirmed:'Verified data',details:'Details',blocked30:'30 minutes',blocked:'Temporary pause',unavailable:'Not verified'},
    badges:{verified:'Verified',empty:'Checked · no active records',warning:'Warning',blocked:'Access paused',operator:'Operator review',unavailable:'Source unavailable'},
    table:{balance:'Balance',available:'Available',pending:'Pending',status:'Status',tier:'Tier',expiry:'Expiry',benefits:'Benefits',package:'Package',slots:'Slots used',activeCampaigns:'Active campaigns',campaign:'Campaign name',views:'Views',clicks:'Clicks',ctr:'CTR',spend:'Spend',regions:'Regions',updated:'Updated',amount:'Amount',currency:'Currency',nickname:'Nickname',locale:'Language',created:'Created',lastActivity:'Last activity',posts:'Posts',topics:'Topics',likes:'Likes',followers:'Followers',following:'Following',rating:'Ecosystem rating',confidence:'Confidence',positiveFactors:'Positive factors',negativeFactors:'Risk factors',missingSignals:'Missing signals',ownedItems:'Owned items',events:'Events',linked:'Linked',telegramId:'Telegram ID',adsPackage:'Advertising package',payment:'Payment',profile:'Profile and activity',forum:'Forum activity',yes:'Yes',no:'No'}
  },
  ru: {
    knowledgeIntro:(label)=>`${label} — раздел экосистемы QUANTUM L7 AI.`,knowledgeUse:(label)=>`Он помогает безопасно пользоваться разделом «${label}», понимать его текущие возможности и ограничения.`,knowledgeAccount:'Персональный статус показывается только по подтверждённым read-only данным аккаунта.',
    qcoinBalance:(v)=>`Подтверждённый баланс: ${v} QCoin.`,vipActive:'VIP-статус активен.',vipInactive:'VIP-статус не активен; это подтверждённое нормальное состояние.',adsEmpty:(n)=>`Пакет ${n} подтверждён. Активных рекламных кампаний сейчас нет.`,adsActive:(n,c)=>`Пакет ${n} подтверждён; активных кампаний: ${c}.`,campaigns:(c)=>`Подтверждено рекламных кампаний: ${c}. Метрики показаны в таблице.`,payment:(s)=>`Статус платежа: ${s}.`,
    titles:{safety:'Ваша безопасность важнее всего',paused:'Диалог приостановлен',boundary:'Граница общения',support:'QL7 Support',humor:'Немного юмора',emotional:'Я рядом',identity:'Кто я',investment:'Инвестиционное предложение',partnership:'Партнёрство',choice:'Что именно проверить?',qcoin:'Проверка QCoin',unavailable:'Источник временно недоступен',verified:'Проверенные данные',how:'Как это работает'},
    composer:{ready:'Можно продолжать',analysis:'Готовлю ответ',spam:'Временная пауза',safety:'Пауза безопасности',boundary:'Продолжим без оскорблений'},surface:{field:'Параметр',value:'Значение',other:'Другое',placeholder:'Опишите, что именно нужно проверить.',checked:'Проверено',confirmed:'Подтверждённые данные',details:'Детали',blocked30:'30 минут',blocked:'Временная пауза',unavailable:'Без подтверждения'},badges:{verified:'Подтверждено',empty:'Проверено · активных записей нет',warning:'Предупреждение',blocked:'Доступ приостановлен',operator:'Проверка оператором',unavailable:'Источник недоступен'},
    table:{balance:'Баланс',available:'Доступно',pending:'В обработке',status:'Статус',tier:'Уровень',expiry:'Действует до',benefits:'Преимущества',package:'Пакет',slots:'Использовано слотов',activeCampaigns:'Активные кампании',campaign:'Название кампании',views:'Просмотры',clicks:'Клики',ctr:'CTR',spend:'Расход',regions:'Регионы',updated:'Обновлено',amount:'Сумма',currency:'Валюта',nickname:'Никнейм',locale:'Язык',created:'Создан',lastActivity:'Последняя активность',posts:'Посты',topics:'Темы',likes:'Лайки',followers:'Подписчики',following:'Подписки',rating:'Рейтинг экосистемы',confidence:'Достоверность',positiveFactors:'Положительные факторы',negativeFactors:'Факторы риска',missingSignals:'Недостающие сигналы',ownedItems:'Предметы',events:'События',linked:'Связан',telegramId:'Telegram ID',adsPackage:'Рекламный пакет',payment:'Платёж',profile:'Профиль и активность',forum:'Активность форума',yes:'Да',no:'Нет'}
  },
  uk: {
    knowledgeIntro:(label)=>`${label} — розділ екосистеми QUANTUM L7 AI.`,knowledgeUse:(label)=>`Він допомагає безпечно користуватися розділом «${label}», розуміти його поточні можливості та обмеження.`,knowledgeAccount:'Персональний статус показується лише за підтвердженими read-only даними акаунта.',qcoinBalance:(v)=>`Підтверджений баланс: ${v} QCoin.`,vipActive:'VIP-статус активний.',vipInactive:'VIP-статус неактивний; це підтверджений нормальний стан.',adsEmpty:(n)=>`Пакет ${n} підтверджено. Активних рекламних кампаній зараз немає.`,adsActive:(n,c)=>`Пакет ${n} підтверджено; активних кампаній: ${c}.`,campaigns:(c)=>`Підтверджено рекламних кампаній: ${c}. Метрики наведено в таблиці.`,payment:(s)=>`Статус платежу: ${s}.`,titles:{safety:'Ваша безпека найважливіша',paused:'Діалог призупинено',boundary:'Межа спілкування',support:'QL7 Support',humor:'Трохи гумору',emotional:'Я поруч',identity:'Хто я',investment:'Інвестиційна пропозиція',partnership:'Партнерство',choice:'Що саме перевірити?',qcoin:'Перевірка QCoin',unavailable:'Джерело тимчасово недоступне',verified:'Перевірені дані',how:'Як це працює'},composer:{ready:'Можна продовжувати',analysis:'Готую відповідь',spam:'Тимчасова пауза',safety:'Пауза безпеки',boundary:'Продовжімо без образ'},surface:{field:'Параметр',value:'Значення',other:'Інше',placeholder:'Опишіть, що саме потрібно перевірити.',checked:'Перевірено',confirmed:'Підтверджені дані',details:'Деталі',blocked30:'30 хвилин',blocked:'Тимчасова пауза',unavailable:'Без підтвердження'},badges:{verified:'Підтверджено',empty:'Перевірено · активних записів немає',warning:'Попередження',blocked:'Доступ призупинено',operator:'Перевірка оператором',unavailable:'Джерело недоступне'},table:{balance:'Баланс',available:'Доступно',pending:'В обробці',status:'Статус',tier:'Рівень',expiry:'Діє до',benefits:'Переваги',package:'Пакет',slots:'Використано слотів',activeCampaigns:'Активні кампанії',campaign:'Назва кампанії',views:'Перегляди',clicks:'Кліки',ctr:'CTR',spend:'Витрати',regions:'Регіони',updated:'Оновлено',amount:'Сума',currency:'Валюта',nickname:'Нікнейм',locale:'Мова',created:'Створено',lastActivity:'Остання активність',posts:'Пости',topics:'Теми',likes:'Вподобання',followers:'Підписники',following:'Підписки',rating:'Рейтинг екосистеми',confidence:'Достовірність',positiveFactors:'Позитивні чинники',negativeFactors:'Чинники ризику',missingSignals:'Відсутні сигнали',ownedItems:'Предмети',events:'Події',linked:'Пов’язано',telegramId:'Telegram ID',adsPackage:'Рекламний пакет',payment:'Платіж',profile:'Профіль і активність',forum:'Активність форуму',yes:'Так',no:'Ні'}
  },
  es: {
    knowledgeIntro:(label)=>`${label} es una sección del ecosistema QUANTUM L7 AI.`,knowledgeUse:(label)=>`Ayuda a usar ${label} de forma segura y a comprender sus funciones y límites actuales.`,knowledgeAccount:'El estado personal solo se muestra con datos verificados y de solo lectura de la cuenta.',qcoinBalance:(v)=>`Saldo verificado: ${v} QCoin.`,vipActive:'El estado VIP está activo.',vipInactive:'El estado VIP está inactivo; es un estado normal verificado.',adsEmpty:(n)=>`El paquete ${n} está verificado. Ahora no hay campañas activas.`,adsActive:(n,c)=>`El paquete ${n} está verificado; campañas activas: ${c}.`,campaigns:(c)=>`Campañas verificadas: ${c}. Las métricas aparecen en la tabla.`,payment:(s)=>`Estado del pago: ${s}.`,titles:{safety:'Tu seguridad es lo primero',paused:'Conversación pausada',boundary:'Límite de la conversación',support:'QL7 Support',humor:'Un poco de humor',emotional:'Estoy aquí',identity:'Quién soy',investment:'Propuesta de inversión',partnership:'Colaboración',choice:'¿Qué debo comprobar?',qcoin:'Revisión de QCoin',unavailable:'Fuente temporalmente no disponible',verified:'Datos verificados',how:'Cómo funciona'},composer:{ready:'Puedes continuar',analysis:'Preparando la respuesta',spam:'Pausa temporal',safety:'Pausa de seguridad',boundary:'Continuemos sin insultos'},surface:{field:'Campo',value:'Valor',other:'Otro',placeholder:'Describe qué necesitas comprobar.',checked:'Comprobado',confirmed:'Datos verificados',details:'Detalles',blocked30:'30 minutos',blocked:'Pausa temporal',unavailable:'Sin verificar'},badges:{verified:'Verificado',empty:'Comprobado · sin registros activos',warning:'Advertencia',blocked:'Acceso pausado',operator:'Revisión por operador',unavailable:'Fuente no disponible'},table:{balance:'Saldo',available:'Disponible',pending:'Pendiente',status:'Estado',tier:'Nivel',expiry:'Vence',benefits:'Beneficios',package:'Paquete',slots:'Espacios usados',activeCampaigns:'Campañas activas',campaign:'Nombre de campaña',views:'Vistas',clicks:'Clics',ctr:'CTR',spend:'Gasto',regions:'Regiones',updated:'Actualizado',amount:'Importe',currency:'Moneda',nickname:'Apodo',locale:'Idioma',created:'Creado',lastActivity:'Última actividad',posts:'Publicaciones',topics:'Temas',likes:'Me gusta',followers:'Seguidores',following:'Siguiendo',rating:'Puntuación del ecosistema',confidence:'Confianza',positiveFactors:'Factores positivos',negativeFactors:'Factores de riesgo',missingSignals:'Señales ausentes',ownedItems:'Objetos propios',events:'Eventos',linked:'Vinculado',telegramId:'ID de Telegram',adsPackage:'Paquete publicitario',payment:'Pago',profile:'Perfil y actividad',forum:'Actividad del foro',yes:'Sí',no:'No'}
  },
  tr: {
    knowledgeIntro:(label)=>`${label}, QUANTUM L7 AI ekosisteminin bir bölümüdür.`,knowledgeUse:(label)=>`${label} özelliğini güvenli kullanmanıza, güncel yeteneklerini ve sınırlarını anlamanıza yardımcı olur.`,knowledgeAccount:'Kişisel durum yalnızca doğrulanmış salt okunur hesap verileriyle gösterilir.',qcoinBalance:(v)=>`Doğrulanmış bakiye: ${v} QCoin.`,vipActive:'VIP durumu aktif.',vipInactive:'VIP durumu etkin değil; bu doğrulanmış normal bir durumdur.',adsEmpty:(n)=>`${n} paketi doğrulandı. Şu anda aktif kampanya yok.`,adsActive:(n,c)=>`${n} paketi doğrulandı; aktif kampanya: ${c}.`,campaigns:(c)=>`Doğrulanmış kampanya sayısı: ${c}. Metrikler tabloda gösterilir.`,payment:(s)=>`Ödeme durumu: ${s}.`,titles:{safety:'Güvenliğiniz her şeyden önemli',paused:'Konuşma duraklatıldı',boundary:'Konuşma sınırı',support:'QL7 Support',humor:'Biraz mizah',emotional:'Buradayım',identity:'Ben kimim',investment:'Yatırım teklifi',partnership:'İş ortaklığı',choice:'Neyi kontrol etmeliyim?',qcoin:'QCoin incelemesi',unavailable:'Kaynak geçici olarak kullanılamıyor',verified:'Doğrulanmış veriler',how:'Nasıl çalışır'},composer:{ready:'Devam edebilirsiniz',analysis:'Yanıt hazırlanıyor',spam:'Geçici duraklama',safety:'Güvenlik duraklaması',boundary:'Hakaret etmeden devam edelim'},surface:{field:'Alan',value:'Değer',other:'Diğer',placeholder:'Neyi kontrol etmem gerektiğini açıklayın.',checked:'Kontrol edildi',confirmed:'Doğrulanmış veriler',details:'Ayrıntılar',blocked30:'30 dakika',blocked:'Geçici duraklama',unavailable:'Doğrulanmadı'},badges:{verified:'Doğrulandı',empty:'Kontrol edildi · aktif kayıt yok',warning:'Uyarı',blocked:'Erişim duraklatıldı',operator:'Operatör incelemesi',unavailable:'Kaynak kullanılamıyor'},table:{balance:'Bakiye',available:'Kullanılabilir',pending:'Beklemede',status:'Durum',tier:'Seviye',expiry:'Bitiş',benefits:'Avantajlar',package:'Paket',slots:'Kullanılan yuvalar',activeCampaigns:'Aktif kampanyalar',campaign:'Kampanya adı',views:'Görüntüleme',clicks:'Tıklama',ctr:'CTR',spend:'Harcama',regions:'Bölgeler',updated:'Güncellendi',amount:'Tutar',currency:'Para birimi',nickname:'Takma ad',locale:'Dil',created:'Oluşturuldu',lastActivity:'Son etkinlik',posts:'Gönderiler',topics:'Konular',likes:'Beğeniler',followers:'Takipçiler',following:'Takip edilenler',rating:'Ekosistem puanı',confidence:'Güven düzeyi',positiveFactors:'Olumlu etkenler',negativeFactors:'Risk etkenleri',missingSignals:'Eksik sinyaller',ownedItems:'Sahip olunan öğeler',events:'Olaylar',linked:'Bağlı',telegramId:'Telegram kimliği',adsPackage:'Reklam paketi',payment:'Ödeme',profile:'Profil ve etkinlik',forum:'Forum etkinliği',yes:'Evet',no:'Hayır'}
  },
  ar: {
    knowledgeIntro:(label)=>`${label} قسم من منظومة QUANTUM L7 AI.`,knowledgeUse:(label)=>`يساعدك على استخدام ${label} بأمان وفهم إمكاناته وحدوده الحالية.`,knowledgeAccount:'لا تُعرض حالة الحساب الشخصية إلا من بيانات موثوقة للقراءة فقط.',qcoinBalance:(v)=>`الرصيد المؤكد: ${v} QCoin.`,vipActive:'حالة VIP نشطة.',vipInactive:'حالة VIP غير نشطة، وهي حالة طبيعية تم التحقق منها.',adsEmpty:(n)=>`تم التحقق من باقة ${n}. لا توجد حملات نشطة حالياً.`,adsActive:(n,c)=>`تم التحقق من باقة ${n}؛ الحملات النشطة: ${c}.`,campaigns:(c)=>`عدد الحملات المؤكدة: ${c}. تظهر المقاييس في الجدول.`,payment:(s)=>`حالة الدفع: ${s}.`,titles:{safety:'سلامتك هي الأهم',paused:'تم إيقاف المحادثة مؤقتاً',boundary:'حدود المحادثة',support:'QL7 Support',humor:'قليل من المرح',emotional:'أنا هنا',identity:'من أنا',investment:'عرض استثماري',partnership:'شراكة',choice:'ما الذي تريد التحقق منه؟',qcoin:'مراجعة QCoin',unavailable:'المصدر غير متاح مؤقتاً',verified:'بيانات مؤكدة',how:'كيف يعمل'},composer:{ready:'يمكنك المتابعة',analysis:'جارٍ إعداد الإجابة',spam:'إيقاف مؤقت',safety:'إيقاف أمني',boundary:'لنكمل من دون إساءة'},surface:{field:'الحقل',value:'القيمة',other:'أخرى',placeholder:'اشرح ما الذي تريد التحقق منه.',checked:'تم الفحص',confirmed:'بيانات مؤكدة',details:'التفاصيل',blocked30:'30 دقيقة',blocked:'إيقاف مؤقت',unavailable:'غير مؤكد'},badges:{verified:'تم التحقق',empty:'تم الفحص · لا توجد سجلات نشطة',warning:'تحذير',blocked:'تم إيقاف الوصول',operator:'مراجعة موظف',unavailable:'المصدر غير متاح'},table:{balance:'الرصيد',available:'المتاح',pending:'قيد المعالجة',status:'الحالة',tier:'المستوى',expiry:'تاريخ الانتهاء',benefits:'المزايا',package:'الباقة',slots:'الخانات المستخدمة',activeCampaigns:'الحملات النشطة',campaign:'اسم الحملة',views:'المشاهدات',clicks:'النقرات',ctr:'CTR',spend:'الإنفاق',regions:'المناطق',updated:'آخر تحديث',amount:'المبلغ',currency:'العملة',nickname:'الاسم المستعار',locale:'اللغة',created:'تاريخ الإنشاء',lastActivity:'آخر نشاط',posts:'المنشورات',topics:'المواضيع',likes:'الإعجابات',followers:'المتابعون',following:'يتابع',rating:'تقييم المنظومة',confidence:'درجة الثقة',positiveFactors:'العوامل الإيجابية',negativeFactors:'عوامل الخطر',missingSignals:'الإشارات المفقودة',ownedItems:'العناصر المملوكة',events:'الأحداث',linked:'مرتبط',telegramId:'معرّف Telegram',adsPackage:'باقة الإعلانات',payment:'الدفع',profile:'الملف والنشاط',forum:'نشاط المنتدى',yes:'نعم',no:'لا'}
  },
  zh: {
    knowledgeIntro:(label)=>`${label} 是 QUANTUM L7 AI 生态系统的一部分。`,knowledgeUse:(label)=>`它帮助你安全使用${label}，了解当前功能与限制。`,knowledgeAccount:'个人账户状态只会依据已验证的只读数据展示。',qcoinBalance:(v)=>`已验证余额：${v} QCoin。`,vipActive:'VIP 状态为有效。',vipInactive:'VIP 状态为未激活；这是已验证的正常状态。',adsEmpty:(n)=>`已验证${n}套餐。目前没有活动中的广告。`,adsActive:(n,c)=>`已验证${n}套餐；活动广告：${c}。`,campaigns:(c)=>`已验证广告活动：${c}。指标显示在表格中。`,payment:(s)=>`支付状态：${s}。`,titles:{safety:'你的安全最重要',paused:'对话已暂停',boundary:'对话边界',support:'QL7 Support',humor:'轻松一下',emotional:'我在这里',identity:'关于我',investment:'投资提案',partnership:'合作提案',choice:'需要检查哪一项？',qcoin:'QCoin 检查',unavailable:'来源暂时不可用',verified:'已验证数据',how:'使用说明'},composer:{ready:'可以继续',analysis:'正在准备回答',spam:'暂时暂停',safety:'安全暂停',boundary:'请不要继续辱骂'},surface:{field:'项目',value:'数值',other:'其他',placeholder:'请说明需要检查的内容。',checked:'已检查',confirmed:'已验证数据',details:'详情',blocked30:'30 分钟',blocked:'暂时暂停',unavailable:'未验证'},badges:{verified:'已验证',empty:'已检查 · 没有活动记录',warning:'警告',blocked:'访问已暂停',operator:'人工复核',unavailable:'来源不可用'},table:{balance:'余额',available:'可用',pending:'处理中',status:'状态',tier:'等级',expiry:'到期时间',benefits:'权益',package:'套餐',slots:'已用名额',activeCampaigns:'活动广告',campaign:'广告名称',views:'浏览',clicks:'点击',ctr:'CTR',spend:'支出',regions:'地区',updated:'更新时间',amount:'金额',currency:'币种',nickname:'昵称',locale:'语言',created:'创建时间',lastActivity:'最近活动',posts:'帖子',topics:'主题',likes:'点赞',followers:'粉丝',following:'关注',rating:'生态评分',confidence:'可信度',positiveFactors:'正向因素',negativeFactors:'风险因素',missingSignals:'缺少的信号',ownedItems:'拥有的物品',events:'事件',linked:'已关联',telegramId:'Telegram ID',adsPackage:'广告套餐',payment:'支付',profile:'资料与活动',forum:'论坛活动',yes:'是',no:'否'}
  },
  he: {
    knowledgeIntro:(label)=>`${label} הוא חלק ממערכת QUANTUM L7 AI.`,knowledgeUse:(label)=>`הוא עוזר להשתמש ב-${label} בבטחה ולהבין את היכולות והמגבלות הנוכחיות.`,knowledgeAccount:'מצב אישי מוצג רק מנתוני חשבון מאומתים לקריאה בלבד.',qcoinBalance:(v)=>`יתרה מאומתת: ${v} QCoin.`,vipActive:'מצב VIP פעיל.',vipInactive:'מצב VIP אינו פעיל; זהו מצב תקין ומאומת.',adsEmpty:(n)=>`החבילה ${n} אומתה. אין כרגע קמפיינים פעילים.`,adsActive:(n,c)=>`החבילה ${n} אומתה; קמפיינים פעילים: ${c}.`,campaigns:(c)=>`קמפיינים מאומתים: ${c}. המדדים מוצגים בטבלה.`,payment:(s)=>`מצב התשלום: ${s}.`,titles:{safety:'הבטיחות שלך קודמת לכל',paused:'השיחה הושהתה',boundary:'גבול השיחה',support:'QL7 Support',humor:'קצת הומור',emotional:'אני כאן',identity:'מי אני',investment:'הצעת השקעה',partnership:'שותפות',choice:'מה לבדוק?',qcoin:'בדיקת QCoin',unavailable:'המקור אינו זמין זמנית',verified:'נתונים מאומתים',how:'איך זה עובד'},composer:{ready:'אפשר להמשיך',analysis:'מכין תשובה',spam:'השהיה זמנית',safety:'השהיית אבטחה',boundary:'נמשיך בלי עלבונות'},surface:{field:'שדה',value:'ערך',other:'אחר',placeholder:'תאר מה צריך לבדוק.',checked:'נבדק',confirmed:'נתונים מאומתים',details:'פרטים',blocked30:'30 דקות',blocked:'השהיה זמנית',unavailable:'לא מאומת'},badges:{verified:'מאומת',empty:'נבדק · אין רשומות פעילות',warning:'אזהרה',blocked:'הגישה הושהתה',operator:'בדיקת נציג',unavailable:'המקור אינו זמין'},table:{balance:'יתרה',available:'זמין',pending:'בהמתנה',status:'מצב',tier:'רמה',expiry:'תוקף עד',benefits:'הטבות',package:'חבילה',slots:'מקומות בשימוש',activeCampaigns:'קמפיינים פעילים',campaign:'שם הקמפיין',views:'צפיות',clicks:'קליקים',ctr:'CTR',spend:'הוצאה',regions:'אזורים',updated:'עודכן',amount:'סכום',currency:'מטבע',nickname:'כינוי',locale:'שפה',created:'נוצר',lastActivity:'פעילות אחרונה',posts:'פוסטים',topics:'נושאים',likes:'לייקים',followers:'עוקבים',following:'נעקב',rating:'דירוג המערכת',confidence:'רמת ביטחון',positiveFactors:'גורמים חיוביים',negativeFactors:'גורמי סיכון',missingSignals:'אותות חסרים',ownedItems:'פריטים בבעלות',events:'אירועים',linked:'מקושר',telegramId:'מזהה Telegram',adsPackage:'חבילת פרסום',payment:'תשלום',profile:'פרופיל ופעילות',forum:'פעילות בפורום',yes:'כן',no:'לא'}
  }
})

export function getQl7NativeCopy(locale='en') { return COPY[ql7Locale(locale)] || COPY.en }
export function getQl7NativeText(locale='en', section='', key='', fallback='') {
  const value = getQl7NativeCopy(locale)?.[section]?.[key]
  return ql7Str(value || fallback)
}
