import {normalizeQl7SupportLanguage,redactQl7SupportTranslationInput} from '../languageOrchestrator.js'
import {isQl7SupportLocaleSupported} from './locales.js'
import {translateQl7SupportTextNative} from '../nativeTranslationService.js'

export const QL7_SUPPORT_NATIVE_STRUCTURED_LOCALIZATION_VERSION='17.0.0'
const TRANSLATABLE_KEYS=new Set(['title','summary','label','description','placeholder','detail','reasonLabel','value','text','message','ariaLabel','caption','tooltip','emptyState','displayName','statusLabel','unitLabel','expectedActionLabel','reviewStatusLabel'])
const NEVER_TRANSLATE_KEYS=new Set(['id','_id','caseId','eventId','correlationId','messageId','userId','accountId','code','key','domain','intent','purpose','visualTheme','tone','severity','icon','iconKey','format','unit','visibility','schema','signature','algorithm','signedAt','signedToken','choiceSetId','choiceContractVersion','issuedAt','expiresAt','nonce','tokenHash','url','src','href','permalink','routeId','actionType','eventName','caseAction','kind','type','status','branch','locale','direction','dir','policyId','runtimeStage','expectedInputType','source','matchedAliasType','matchedAliasMasked','topic','subIntent','operation','postId','authorIdMasked','wallet','walletAddress','currency','amount','count','confidence','asOf'])
const BRAND_PATTERN=/\b(?:QUANTUM L7 AI|QCoin|VIP|AI Box|AI Quota|BattleCoin|MetaMarket|Gameverse|MetaStudio|CryptoRadar|Quantum Wallet|NFT|BTC|ETH|USDT)\b/gu
function s(v){return String(v??'').trim()}
function clone(v){try{return JSON.parse(JSON.stringify(v??null))}catch{return null}}
function technical(v){const x=s(v);return !x||/^[-+]?\d+(?:[.,]\d+)?%?$/u.test(x)||/^https?:\/\//iu.test(x)||/^\/[A-Za-z0-9/_?=&.#-]*$/u.test(x)||/^ql7[._:-]/iu.test(x)||/^[a-f0-9]{24,}$/iu.test(x)||/^0x[a-f0-9]{16,}$/iu.test(x)}
function protect(v){const values=[];const text=String(v??'').replace(BRAND_PATTERN,m=>{const token=`__QL7_NATIVE_${values.length}__`;values.push(m);return token});return{text,values}}
function restore(v,values=[]){let text=String(v??'');values.forEach((x,i)=>{text=text.replaceAll(`__QL7_NATIVE_${i}__`,x)});return text}
function naturalField(key,item,parentKey=''){return TRANSLATABLE_KEYS.has(key)||(parentKey==='labels'&&typeof item==='string')||(key==='name'&&['sections','badges','metrics'].includes(parentKey))}
async function translateString(value,{source,target,translate,purpose}){const input=redactQl7SupportTranslationInput(value);if(!input||technical(input)||source===target)return input;const p=protect(input);const out=await translate({text:p.text,sourceLang:source,targetLang:target,purpose});if(out?.translationSucceeded!==true||!s(out?.text)||s(out.text)===p.text){const e=new Error('support_native_translation_unavailable');e.code='support_native_translation_unavailable';e.status=503;throw e}return restore(out.text,p.values)}
async function walk(value,ctx,path='',parentKey=''){if(ctx.budget.count>=ctx.budget.max)return clone(value);if(Array.isArray(value)){const out=[];for(let i=0;i<value.length;i++)out.push(await walk(value[i],ctx,`${path}[${i}]`,parentKey));return out}if(!value||typeof value!=='object')return value;const out={};for(const [key,item] of Object.entries(value)){const technicalKey=NEVER_TRANSLATE_KEYS.has(key)&&!(key==='status'&&item&&typeof item==='object');if(technicalKey||key==='integrity'||(key==='detail'&&parentKey==='actions')){out[key]=clone(item);continue}if(typeof item==='string'&&naturalField(key,item,parentKey)&&!technical(item)){ctx.budget.count+=1;out[key]=await translateString(item,{source:ctx.source,target:ctx.target,translate:ctx.translate,purpose:`ql7_support_native_${path||'root'}_${key}`});continue}out[key]=await walk(item,ctx,path?`${path}.${key}`:key,key)}return out}
export async function localizeQl7SupportStructuredNative({value,targetLanguage='',sourceLanguage='',translate=translateQl7SupportTextNative,maxStrings=192}={}){
 const target=normalizeQl7SupportLanguage(targetLanguage,''),source=normalizeQl7SupportLanguage(sourceLanguage||value?.locale||'en','en')
 if(!target||!isQl7SupportLocaleSupported(target)){const e=new Error('support_native_translation_target_locale_unsupported');e.code='support_native_translation_target_locale_unsupported';e.status=400;throw e}
 if(!value||source===target)return Object.freeze({value:clone(value),locale:target,status:'same_language',translatedStrings:0,nativeOnly:true})
 if(typeof translate!=='function'){const e=new Error('support_native_translation_engine_unavailable');e.code='support_native_translation_engine_unavailable';e.status=503;throw e}
 const budget={count:0,max:Math.max(1,Math.min(512,Number(maxStrings)||192))};const localized=await walk(value,{target,source,translate,budget})
 return Object.freeze({value:localized,locale:target,status:budget.count?'native_translated':'no_translatable_fields',translatedStrings:budget.count,budgetExhausted:budget.count>=budget.max,nativeOnly:true})
}
export async function localizeQl7SupportInputPolicyNative({policy,targetLanguage='',sourceLanguage='',translate=translateQl7SupportTextNative}={}){const result=await localizeQl7SupportStructuredNative({value:policy,targetLanguage,sourceLanguage:sourceLanguage||policy?.locale||'en',translate,maxStrings:12});return Object.freeze({...((result.value&&typeof result.value==='object')?result.value:policy),locale:normalizeQl7SupportLanguage(targetLanguage,'en'),translationStatus:result.status,nativeOnly:true})}
