export const QL7_SUPPORT_NATIVE_SAFETY_LEXICON_VERSION = '15.0.0'

function row(insults, targets, denials, product, quotes) { return Object.freeze({ insults:Object.freeze(insults), targets:Object.freeze(targets), denials:Object.freeze(denials), product:Object.freeze(product), quotes:Object.freeze(quotes) }) }

export const QL7_SUPPORT_NATIVE_SAFETY_LEXICON = Object.freeze({
 en: row(['idiot','moron','stupid','dumb','jerk','asshole','fuck you','piece of shit','useless bot','trash bot'], ['you','your','support','bot','operator','assistant'], ['no','not you','i was not insulting','you misunderstood','i meant the app','that was a quote','not directed at you'], ['app','service','site','system','feature','product'], ['quote','said','they said','lyrics','movie','someone called']),
 ru: row(['идиот','дебил','тупой','тупая','тупые','мудак','урод','кретин','долбоеб','долбаеб','безмозглый','бесполезный бот','пошел ты','иди нахуй'], ['ты','вы','тебя','вам','саппорт','поддержка','бот','оператор','ассистент'], ['нет','не тебя','я не ругался','я не ругалась','ты неправильно понял','вы неправильно поняли','я про приложение','это была цитата','не в твой адрес'], ['приложение','сервис','сайт','система','функция','продукт'], ['цитата','сказал','сказала','они сказали','песня','фильм','кто-то назвал']),
 uk: row(['ідіот','дебіл','тупий','тупа','мудак','виродок','кретин','довбоеб','безмозкий','марний бот','пішов ти'], ['ти','ви','тебе','вам','підтримка','бот','оператор','асистент'], ['ні','не тебе','я не лаявся','я не лаялась','ти неправильно зрозумів','я про застосунок','це була цитата','не на твою адресу'], ['застосунок','сервіс','сайт','система','функція','продукт'], ['цитата','сказав','сказала','вони сказали','пісня','фільм']),
 es: row(['idiota','imbécil','estúpido','estúpida','tonto','tonta','inútil','gilipollas','vete a la mierda','bot basura'], ['tú','usted','ustedes','soporte','bot','operador','asistente'], ['no','no era para ti','no te insulté','me entendiste mal','hablaba de la app','era una cita','no iba dirigido a ti'], ['aplicación','servicio','sitio','sistema','función','producto'], ['cita','dijo','dijeron','letra','película']),
 tr: row(['aptal','salak','gerizekalı','ahmak','akılsız','beceriksiz','işe yaramaz bot','siktir git'], ['sen','siz','destek','bot','operatör','asistan'], ['hayır','sana demedim','hakaret etmedim','yanlış anladın','uygulamadan bahsediyordum','alıntıydı'], ['uygulama','hizmet','site','sistem','özellik','ürün'], ['alıntı','dedi','dediler','şarkı','film']),
 ar: row(['غبي','أحمق','أبله','تافه','عديم الفائدة','بوت فاشل','اذهب للجحيم'], ['أنت','انتم','الدعم','بوت','المشغل','المساعد'], ['لا','لم أقصدك','لم أشتمك','فهمتني خطأ','كنت أتكلم عن التطبيق','كان اقتباسا'], ['التطبيق','الخدمة','الموقع','النظام','الميزة','المنتج'], ['اقتباس','قال','قالت','قالوا','أغنية','فيلم']),
 zh: row(['白痴','蠢货','笨蛋','傻子','废物','没用的机器人','垃圾机器人','滚开'], ['你','您','客服','支持','机器人','操作员','助手'], ['不是','不是骂你','我没有骂你','你误会了','我说的是应用','那是引用'], ['应用','服务','网站','系统','功能','产品'], ['引用','他说','她说','他们说','歌词','电影']),
 he: row(['אידיוט','מטומטם','טיפש','דביל','חסר תועלת','בוט גרוע','לך לעזאזל'], ['אתה','אתם','תמיכה','בוט','מפעיל','עוזר'], ['לא','לא התכוונתי אליך','לא קיללתי אותך','הבנת לא נכון','דיברתי על האפליקציה','זה היה ציטוט'], ['אפליקציה','שירות','אתר','מערכת','תכונה','מוצר'], ['ציטוט','אמר','אמרה','אמרו','שיר','סרט']),
})
