import {QL7_SUPPORT_REVIEWED_SEEDS_BY_LOCALE, QL7_SUPPORT_REVIEWED_SEED_LOCALES} from './reviewedSeedRegistry.js'
import {QL7_SUPPORT_HUMAN_TOPIC_CATEGORIES} from '../knowledge/humanTopicOntology.js'
import {QL7_SUPPORT_HUMAN_CONVERSATION_FACETS} from '../knowledge/humanConversationBank.js'
export const QL7_SUPPORT_SEMANTIC_CONCEPT_BANK_VERSION='5.4.0'
const PER_TOPIC=64
function coordinate(locale,topic,facet,index,root){return Object.freeze({termId:`${locale}:${topic}:${facet}:${index}`,locale,topic,facet,lexicalAnchor:String(root?.surface||''),materialRootId:String(root?.seedId||''),semanticKey:`${topic}/${facet}`,reviewClass:'semantic-coordinate',mutationDerived:false,readyToSend:false})}
export const QL7_SUPPORT_SEMANTIC_CONCEPT_TERMS_BY_LOCALE=Object.freeze(Object.fromEntries(QL7_SUPPORT_REVIEWED_SEED_LOCALES.map(locale=>{const roots=QL7_SUPPORT_REVIEWED_SEEDS_BY_LOCALE[locale]||[];const coordinates=QL7_SUPPORT_HUMAN_TOPIC_CATEGORIES.flatMap(topic=>QL7_SUPPORT_HUMAN_CONVERSATION_FACETS.slice(0,PER_TOPIC).map((facet,i)=>coordinate(locale,topic,facet,i,roots[(i+QL7_SUPPORT_HUMAN_TOPIC_CATEGORIES.indexOf(topic)*PER_TOPIC)%Math.max(1,roots.length)])));return [locale,Object.freeze(coordinates)]})))
export const QL7_SUPPORT_SEMANTIC_CONCEPT_TERM_COUNT=Object.values(QL7_SUPPORT_SEMANTIC_CONCEPT_TERMS_BY_LOCALE).reduce((n,r)=>n+r.length,0)
export function auditQl7SupportSemanticConceptBank(){const failures=[],materialRootIds=new Set();for(const [l,rows] of Object.entries(QL7_SUPPORT_SEMANTIC_CONCEPT_TERMS_BY_LOCALE)){if(rows.length<8192)failures.push(`coordinate_floor:${l}:${rows.length}`);if(rows.some(r=>!r.lexicalAnchor||!r.materialRootId))failures.push(`coordinate_root:${l}`);for(const r of rows)materialRootIds.add(r.materialRootId)}const materialRootCount=Object.values(QL7_SUPPORT_REVIEWED_SEEDS_BY_LOCALE).reduce((n,r)=>n+r.length,0);return Object.freeze({ok:!failures.length,localeCount:Object.keys(QL7_SUPPORT_SEMANTIC_CONCEPT_TERMS_BY_LOCALE).length,totalTerms:QL7_SUPPORT_SEMANTIC_CONCEPT_TERM_COUNT,semanticCoordinateCount:QL7_SUPPORT_SEMANTIC_CONCEPT_TERM_COUNT,materialReviewedRootCount:materialRootCount,coordinateDistinctReferencedRoots:materialRootIds.size,countersSeparated:true,mutationDerivedCount:0,failures:Object.freeze(failures)})}
