import {getQl7SupportLocaleProfile} from '../language/locales/manifest.js'
import {ql7Arr, ql7StableHash, ql7Str} from '../internal/text.js'
export const QL7_SUPPORT_GENERAL_FACT_REALIZER_VERSION='5.2.0'
const REL=Object.freeze({
 en:{instance_of:['is a kind of','belongs to'],focuses_on:['focuses on','covers'],uses:['uses','can use'],associated_with:['is associated with','often involves'],affected_by:['is influenced by','depends partly on'],can_help:['can be eased by','can be approached through'],distinct_from:['is distinct from','should be distinguished from'],safety_boundary:['has the safety boundary','is limited to']},
 ru:{instance_of:['относится к','представляет собой'],focuses_on:['охватывает','сосредоточено на'],uses:['использует','может использовать'],associated_with:['связано с','обычно включает'],affected_by:['зависит в том числе от','на него влияют'],can_help:['можно смягчить через','проще проживать через'],distinct_from:['нужно отличать от','не следует смешивать с'],safety_boundary:['имеет безопасную границу','ограничено рамкой']},
 uk:{instance_of:['належить до','є різновидом'],focuses_on:['охоплює','зосереджується на'],uses:['використовує','може використовувати'],associated_with:['пов’язане з','зазвичай включає'],affected_by:['залежить зокрема від','на нього впливають'],can_help:['можна пом’якшити через','легше проживати через'],distinct_from:['слід відрізняти від','не слід змішувати з'],safety_boundary:['має безпечну межу','обмежене рамкою']},
 es:{instance_of:['pertenece a','es un tipo de'],focuses_on:['abarca','se centra en'],uses:['utiliza','puede utilizar'],associated_with:['se relaciona con','suele incluir'],affected_by:['está influido por','depende en parte de'],can_help:['puede aliviarse mediante','puede abordarse con'],distinct_from:['debe distinguirse de','no debe confundirse con'],safety_boundary:['tiene como límite seguro','se limita a']},
 tr:{instance_of:['şu sınıfa girer','bir türüdür'],focuses_on:['şuna odaklanır','şunu kapsar'],uses:['kullanır','kullanabilir'],associated_with:['şununla ilişkilidir','genellikle şunu içerir'],affected_by:['şunlardan etkilenir','kısmen şunlara bağlıdır'],can_help:['şunlarla hafifletilebilir','şunlarla ele alınabilir'],distinct_from:['şundan ayrılmalıdır','şununla karıştırılmamalıdır'],safety_boundary:['güvenli sınırı şudur','şununla sınırlıdır']},
 ar:{instance_of:['ينتمي إلى','يُعد نوعاً من'],focuses_on:['يركز على','يشمل'],uses:['يستخدم','يمكن أن يستخدم'],associated_with:['يرتبط بـ','يتضمن عادةً'],affected_by:['يتأثر بـ','يعتمد جزئياً على'],can_help:['يمكن تخفيفه عبر','يمكن التعامل معه من خلال'],distinct_from:['يجب تمييزه عن','لا ينبغي خلطه مع'],safety_boundary:['له حد آمن هو','يقتصر على']},
 zh:{instance_of:['属于','是一类'],focuses_on:['主要涉及','涵盖'],uses:['使用','可以使用'],associated_with:['与…相关','通常涉及'],affected_by:['会受到以下因素影响：','部分取决于'],can_help:['可以通过以下方式缓解：','可以这样应对：'],distinct_from:['应与…区分','不应与…混淆'],safety_boundary:['安全边界是','仅限于']},
 he:{instance_of:['שייך ל','הוא סוג של'],focuses_on:['מתמקד ב','כולל'],uses:['משתמש ב','יכול להשתמש ב'],associated_with:['קשור ל','כולל לעיתים קרובות'],affected_by:['מושפע מ','תלוי בין היתר ב'],can_help:['אפשר להקל עליו באמצעות','אפשר להתמודד איתו דרך'],distinct_from:['יש להבדיל בינו לבין','אין לבלבל בינו לבין'],safety_boundary:['גבול הבטיחות שלו הוא','מוגבל ל']},
})
const CONCEPT=Object.freeze({
 blockchain:{en:'Blockchain',ru:'Блокчейн',uk:'Блокчейн',es:'Blockchain',tr:'Blok zinciri',ar:'سلسلة الكتل',zh:'区块链',he:'בלוקצ׳יין'},
 bitcoin:{en:'Bitcoin',ru:'Bitcoin',uk:'Bitcoin',es:'Bitcoin',tr:'Bitcoin',ar:'بيتكوين',zh:'比特币',he:'ביטקוין'},
 change_psychology:{en:'Fear of change',ru:'Страх перемен',uk:'Страх змін',es:'El miedo al cambio',tr:'Değişim korkusu',ar:'الخوف من التغيير',zh:'对改变的恐惧',he:'פחד משינוי'},
 distributed_ledger_system:{en:'a distributed ledger: many participants can verify the same ordered record',ru:'распределённый реестр, где участники сверяют одну и ту же последовательность записей',uk:'розподілений реєстр, де учасники звіряють ту саму послідовність записів',es:'un registro distribuido donde los participantes verifican la misma secuencia de registros',tr:'katılımcıların aynı kayıt sırasını doğruladığı dağıtık bir defter',ar:'سجل موزع يتحقق فيه المشاركون من تسلسل السجلات نفسه',zh:'由多方共同核验同一记录顺序的分布式账本',he:'יומן מבוזר שבו משתתפים מאמתים את אותו רצף רשומות'},
 cryptographic_linking_and_consensus:{en:'cryptographic links between records and an agreed validation rule',ru:'криптографические связи между записями и согласованное правило их проверки',uk:'криптографічні зв’язки між записами та узгоджене правило їх перевірки',es:'enlaces criptográficos entre registros y una regla acordada de validación',tr:'kayıtlar arasındaki kriptografik bağları ve ortak bir doğrulama kuralını',ar:'روابط تشفيرية بين السجلات وقاعدة تحقق متفقاً عليها',zh:'记录之间的密码学连接与共同认可的验证规则',he:'קישורים קריפטוגרפיים בין רשומות וכלל אימות מוסכם'},
 verifiable_shared_history:{en:'a shared history whose changes can be checked',ru:'общая история, изменения в которой можно проверить',uk:'спільна історія, зміни в якій можна перевірити',es:'un historial compartido cuyos cambios pueden comprobarse',tr:'değişiklikleri doğrulanabilen ortak bir geçmişi',ar:'سجل مشترك يمكن التحقق من تغييراته',zh:'变更可被核验的共享历史',he:'היסטוריה משותפת שניתן לבדוק את השינויים בה'},
 decentralized_digital_asset:{en:'a decentralized digital asset',ru:'децентрализованный цифровой актив',uk:'децентралізований цифровий актив',es:'un activo digital descentralizado',tr:'merkeziyetsiz bir dijital varlık',ar:'أصل رقمي لامركزي',zh:'去中心化数字资产',he:'נכס דיגיטלי מבוזר'},
 public_blockchain:{en:'a public blockchain for recording and validating transfers',ru:'публичный блокчейн для записи и проверки переводов',uk:'публічний блокчейн для запису й перевірки переказів',es:'una blockchain pública para registrar y validar transferencias',tr:'transferleri kaydeden ve doğrulayan açık bir blok zinciri',ar:'سلسلة كتل عامة لتسجيل التحويلات والتحقق منها',zh:'用于记录和验证转账的公有链',he:'בלוקצ׳יין ציבורי לרישום ואימות העברות'},
 adoption_liquidity_regulation_and_risk:{en:'adoption, market liquidity, regulation, technology and overall risk appetite',ru:'принятие технологии, ликвидность рынка, регулирование, развитие сети и общий аппетит к риску',uk:'прийняття технології, ліквідність ринку, регулювання, розвиток мережі та загальна схильність до ризику',es:'la adopción, la liquidez del mercado, la regulación, la tecnología y el apetito general por el riesgo',tr:'benimsenme, piyasa likiditesi, düzenlemeler, teknoloji ve genel risk iştahı',ar:'التبني وسيولة السوق والتنظيم والتقنية والشهية العامة للمخاطر',zh:'采用程度、市场流动性、监管、技术发展与整体风险偏好',he:'אימוץ, נזילות שוק, רגולציה, טכנולוגיה ותיאבון כללי לסיכון'},
 educational_context_not_price_prediction:{en:'education rather than a price forecast or promise of profit',ru:'обучающая информация, а не прогноз цены или обещание прибыли',uk:'навчальна інформація, а не прогноз ціни чи обіцянка прибутку',es:'información educativa, no una previsión de precio ni una promesa de beneficio',tr:'fiyat tahmini veya kâr vaadi değil, eğitim amaçlı bilgi',ar:'معلومات تعليمية لا توقعاً للسعر ولا وعداً بالربح',zh:'教育信息，而非价格预测或收益承诺',he:'מידע לימודי ולא תחזית מחיר או הבטחת רווח'},
 uncertainty_and_loss_of_control:{en:'uncertainty and a perceived loss of control',ru:'неопределённость и ощущение потери контроля',uk:'невизначеність і відчуття втрати контролю',es:'la incertidumbre y la sensación de perder el control',tr:'belirsizlik ve kontrol kaybı hissi',ar:'عدم اليقين والشعور بفقدان السيطرة',zh:'不确定性与失去掌控的感觉',he:'אי ודאות ותחושה של אובדן שליטה'},
 habit_and_predictability:{en:'habit, predictability and the mind’s preference for familiar patterns',ru:'привычка, предсказуемость и стремление психики держаться знакомых схем',uk:'звичка, передбачуваність і прагнення психіки триматися знайомих схем',es:'el hábito, la previsibilidad y la preferencia mental por patrones conocidos',tr:'alışkanlık, öngörülebilirlik ve zihnin tanıdık örüntülere yönelmesi',ar:'العادة وقابلية التوقع وميل الذهن إلى الأنماط المألوفة',zh:'习惯、可预测性以及大脑对熟悉模式的偏好',he:'הרגל, יכולת לצפות מראש והעדפת המוח לדפוסים מוכרים'},
 gradual_steps_and_clear_options:{en:'small reversible steps and clear choices',ru:'небольшие обратимые шаги и понятные варианты выбора',uk:'невеликі зворотні кроки та зрозумілі варіанти вибору',es:'pasos pequeños y reversibles y opciones claras',tr:'küçük, geri alınabilir adımlar ve açık seçenekler',ar:'خطوات صغيرة قابلة للتراجع وخيارات واضحة',zh:'可逆的小步骤与清晰的选择',he:'צעדים קטנים והפיכים ואפשרויות ברורות'},
})
function humanConcept(v='',locale='en',{allowLiteral=false}={}){const id=ql7Str(v);const row=CONCEPT[id];if(row)return ql7Str(row?.[locale]||(locale==='en'?row?.en:'')).replace(/[._-]+/gu,' ').replace(/\s+/gu,' ').trim();if(locale==='en'||allowLiteral)return id.replace(/[._-]+/gu,' ').replace(/\s+/gu,' ').trim();return''}
function pick(rows=[],seed=''){const a=ql7Arr(rows);return a.length?a[Number.parseInt(ql7StableHash(seed).slice(0,8),16)%a.length]:''}
function terminal(locale='en'){return locale==='zh'?'。':'.'}
function relationSentence({locale='en',relation='',subject='',object='',seed=''}={}){
 if(locale==='ru'){
  const templates={instance_of:`${subject} — ${object}`,uses:`В основе темы «${subject}» — ${object}`,focuses_on:`${subject}: главная идея — ${object}`,associated_with:`${subject}: обычно с этим связаны ${object}`,affected_by:`${subject}: ключевые факторы — ${object}`,can_help:`${subject}: обычно помогают ${object}`,distinct_from:`${subject} важно не смешивать со следующим: ${object}`,safety_boundary:`Граница ответа по теме «${subject}»: ${object}`}
  return `${templates[relation]||`${subject}: ${object}`}${terminal(locale)}`
 }
 if(locale==='uk'){
  const templates={instance_of:`${subject} — ${object}`,uses:`В основі теми «${subject}» — ${object}`,focuses_on:`${subject}: головна ідея — ${object}`,associated_with:`${subject}: зазвичай із цим пов’язані ${object}`,affected_by:`${subject}: ключові чинники — ${object}`,can_help:`${subject}: зазвичай допомагають ${object}`,distinct_from:`${subject} важливо не змішувати з таким: ${object}`,safety_boundary:`Межа відповіді за темою «${subject}»: ${object}`}
  return `${templates[relation]||`${subject}: ${object}`}${terminal(locale)}`
 }
 if(locale==='en'){
  const templates={instance_of:`${subject} is ${object}`,uses:`${subject} relies on ${object}`,focuses_on:`${subject} focuses on ${object}`,associated_with:`${subject} is commonly associated with ${object}`,affected_by:`${subject} is influenced by ${object}`,can_help:`${subject} can be approached through ${object}`,distinct_from:`${subject} should be distinguished from ${object}`,safety_boundary:`The boundary for ${subject} is ${object}`}
  return `${templates[relation]||`${subject}: ${object}`}${terminal(locale)}`
 }
 const phrase=pick(REL[locale]?.[relation]||[],seed)
 return phrase?`${subject} ${phrase} ${object}${terminal(locale)}`:''
}
export function realizeQl7SupportGeneralFacts({locale='en',topicLabel='',semanticFacts=[],seed=''}={}){const profile=getQl7SupportLocaleProfile(locale);const lex=REL[profile.locale];if(!lex)return Object.freeze({text:'',fragments:Object.freeze([]),sourceReceipts:Object.freeze([]),unsupportedLocale:true})
 const facts=ql7Arr(semanticFacts).slice(0,4);const fragments=[];const sourceReceipts=[];for(const [i,f] of facts.entries()){if(!ql7Arr(lex[f.relation]).length)continue;const subject=humanConcept(topicLabel||f.subjectId,profile.locale,{allowLiteral:Boolean(topicLabel)});const object=humanConcept(f.objectValue||f.objectConceptId,profile.locale);if(!subject||!object)continue;const text=relationSentence({locale:profile.locale,relation:f.relation,subject,object,seed:`${seed}:${f.factId}:${i}`}).replace(/\s+/gu,' ');fragments.push(Object.freeze({factId:ql7Str(f.factId),text,sourceReceiptId:ql7Str(f.sourceReceipt?.receiptId)}));if(f.sourceReceipt)sourceReceipts.push(f.sourceReceipt)}
 return Object.freeze({text:fragments.map(x=>x.text).join(' '),fragments:Object.freeze(fragments),sourceReceipts:Object.freeze(sourceReceipts),unsupportedLocale:false,readyToSendBank:false})}
