import { pickQl7SupportBoundaryCopy, formatQl7SupportDuration } from '../language/humanResponsePacks.provider.js'
import { getQl7SupportDomain, getQl7SupportTopicLabel } from '../ecosystemCatalog.js'
import { ql7Arr, ql7Locale, ql7NormalizeSpaces, ql7SafeVisibleText, ql7StableHash, ql7Str } from '../internal/text.js'
import { getQl7SupportKnowledgeAnswer } from '../knowledgeRegistry.js'
import { pickQl7HumanVariation, pickQl7ProductHowToBridge } from '../language/humanVariationBanks.js'
import { getQl7NativeCopy } from '../language/nativeBanks.js'

export const QL7_SUPPORT_NATURAL_REALIZER_VERSION='15.3.4'
const BANK={
en:{greeting:['Hi! What can I help you with?','Hello! What would you like to sort out?','Welcome. Tell me what you need help with.'],thanks:['You are welcome.','Glad I could help.','Anytime.'],bye:['Take care.','See you soon.'],identity:['I am Quantum L7 AI Support. I help you understand the ecosystem, check available account facts and choose a safe next step. I am an AI assistant, not a human operator.'],humor:['A bug walked into a release and introduced itself as a feature. The logs politely asked for proof.','Why did the QCoin balance refresh? It wanted a clean start.','The server tried meditation. It still kept all its processes.','A cache and a database started a race. The verified result crossed the finish line first.','The safest joke in support: no private key ever walks into a chat.'],emotional:['That sounds genuinely hard. You do not have to solve everything at once; take one small, safe step and stay near someone you trust.','I hear how heavy this feels. Give yourself a little space, and focus on the next manageable thing rather than the whole situation at once.'],boundary:'I will help, but let us continue without insults.',threat:'I cannot continue the usual conversation while there is a credible threat. The message field is paused for 30 minutes, and the context is being prepared for security review.',crisis:'Your safety matters most right now. Please contact local emergency services or a trusted person who can stay with you, and move away from anything you could use to hurt yourself.',qcoinTheft:'This is a QCoin balance or ledger incident, not an advertising issue. I will use only the verified account ledger and current operations for the check.',unavailable:'I cannot confirm that from a verified source right now. I will not invent a balance or status.',verified:'The current account data has been verified.',verifiedEmpty:'The source was checked successfully; there are no active records in this section.',choice:'You may mean one of these options.',small:['I am here. What would you like to work through?','I can help with QL7 features, account status and support cases. What should we start with?'],business:'I can structure this proposal and pass it to an operator after your consent. Start with the goal, expected value and preferred contact method.',howto:'I can guide you through this feature step by step. Tell me the exact result you want to achieve.'},
ru:{greeting:['Привет! Чем помочь?','Здравствуйте! Что разберём?','Рад видеть. С чем помочь в экосистеме?'],thanks:['Пожалуйста.','Рад, что помог.','Обращайся.'],bye:['До связи.','Берегите себя.'],identity:['Я — Quantum L7 AI Support. Помогаю разобраться в экосистеме, проверить доступные данные аккаунта и выбрать безопасный следующий шаг. Я ИИ-помощник, а не человек-оператор.'],humor:['Баг пришёл в релиз и представился новой функцией. Логи вежливо попросили доказательства.','Почему баланс QCoin обновился? Захотел начать с чистого листа.','Сервер решил помедитировать, но процессы всё равно не отпустил.','Кэш и база устроили гонку. Первым финишировал подтверждённый результат.','Самая безопасная шутка поддержки: приватный ключ никогда не заходит в чат.'],emotional:['Это действительно тяжело. Не нужно решать всё сразу — выберите один маленький безопасный шаг и побудьте рядом с человеком, которому доверяете.','Слышу, насколько вам сейчас непросто. Дайте себе немного пространства и сосредоточьтесь на ближайшем посильном шаге.'],boundary:'Я помогу, но давайте продолжим без оскорблений.',threat:'При достоверной угрозе я не могу продолжать обычный диалог. Поле ввода приостановлено на 30 минут, а контекст готовится для проверки безопасности.',crisis:'Сейчас важнее всего ваша безопасность. Позвоните в местную экстренную службу или человеку, который может быть рядом, и отойдите от всего, чем можно причинить себе вред.',qcoinTheft:'Это вопрос баланса или операций QCoin, а не рекламы. Для проверки будут использованы только подтверждённая история аккаунта и текущие операции.',unavailable:'Сейчас не получается подтвердить это надёжным источником. Я не стану выдумывать баланс или статус.',verified:'Актуальные данные аккаунта подтверждены.',verifiedEmpty:'Источник успешно проверен: активных записей в этом разделе сейчас нет.',choice:'Возможно, вы имеете в виду один из этих вариантов.',small:['Я на связи. Что хотите разобрать?','Помогу с функциями QL7, состоянием аккаунта и обращениями. С чего начнём?'],business:'Я могу структурировать предложение и после вашего согласия передать его оператору. Укажите цель, ожидаемую ценность и удобный способ связи.',howto:'Проведу по этому разделу пошагово. Напишите, какой результат хотите получить.'},
uk:{greeting:['Привіт! Чим допомогти?','Вітаю! Що розберемо?'],thanks:['Будь ласка.','Радий, що допоміг.'],bye:['До зв’язку.'],identity:['Я — Quantum L7 AI Support. Допомагаю розібратися в екосистемі, перевірити доступні дані акаунта й обрати безпечний наступний крок. Я ШІ-помічник, а не людина-оператор.'],humor:['Баг потрапив у реліз і представився новою функцією. Журнали ввічливо попросили докази.','Чому баланс QCoin оновився? Хотів почати з чистого аркуша.'],emotional:['Це справді важко. Не треба вирішувати все одразу — оберіть один маленький безпечний крок.'],boundary:'Я допоможу, але продовжімо без образ.',threat:'Через достовірну погрозу поле введення призупинено на 30 хвилин, а контекст готується до перевірки безпеки.',crisis:'Зараз найважливіша ваша безпека. Зверніться до місцевої екстреної служби або людини, яка може бути поруч.',qcoinTheft:'Це питання балансу або операцій QCoin, а не реклами. Перевірка використовує лише підтверджені дані акаунта.',unavailable:'Зараз це не вдається підтвердити надійним джерелом. Я не вигадуватиму баланс чи статус.',verified:'Актуальні дані акаунта підтверджено.',verifiedEmpty:'Джерело успішно перевірено: активних записів у цьому розділі немає.',choice:'Можливо, ви маєте на увазі один із цих варіантів.',small:['Я на зв’язку. Що хочете розібрати?'],business:'Я можу структурувати пропозицію та після вашої згоди передати її оператору.',howto:'Проведу вас цим розділом крок за кроком.'},
 es:{greeting:['¡Hola! ¿En qué te ayudo?','Bienvenido. ¿Qué quieres resolver?'],thanks:['De nada.','Me alegra haber ayudado.'],bye:['Hasta pronto.'],identity:['Soy Quantum L7 AI Support. Ayudo a entender el ecosistema, comprobar datos disponibles de la cuenta y elegir un paso seguro. Soy un asistente de IA, no un operador humano.'],humor:['Un error llegó a una versión y se presentó como una función. Los registros pidieron pruebas.','¿Por qué se actualizó el saldo QCoin? Quería empezar de cero.'],emotional:['Suena realmente difícil. No tienes que resolverlo todo ahora; elige un paso pequeño y seguro.'],boundary:'Te ayudaré, pero continuemos sin insultos.',threat:'Ante una amenaza creíble, el campo de mensaje queda pausado durante 30 minutos y el contexto pasa a revisión de seguridad.',crisis:'Tu seguridad es lo primero. Contacta con emergencias locales o con una persona de confianza que pueda estar contigo.',qcoinTheft:'Esto es un incidente de saldo o movimientos QCoin, no de publicidad. Solo se usarán datos verificados de la cuenta.',unavailable:'Ahora no puedo confirmarlo con una fuente verificada. No inventaré un saldo ni un estado.',verified:'Los datos actuales de la cuenta están verificados.',verifiedEmpty:'La fuente se comprobó correctamente; no hay registros activos en esta sección.',choice:'Puede que te refieras a una de estas opciones.',small:['Estoy aquí. ¿Qué quieres revisar?'],business:'Puedo estructurar la propuesta y, con tu consentimiento, enviarla a un operador.',howto:'Puedo guiarte paso a paso por esta función.'},
 tr:{greeting:['Merhaba! Nasıl yardımcı olabilirim?','Hoş geldiniz. Neyi çözelim?'],thanks:['Rica ederim.','Yardımcı olabildiysem ne mutlu.'],bye:['Görüşmek üzere.'],identity:['Ben Quantum L7 AI Support. Ekosistemi anlamanıza, mevcut hesap verilerini kontrol etmenize ve güvenli bir sonraki adımı seçmenize yardımcı olurum. İnsan operatör değil, bir yapay zekâ asistanıyım.'],humor:['Bir hata sürüme girip “Ben yeni bir özelliğim” dedi. Günlükler kanıt istedi.'],emotional:['Bu gerçekten zor görünüyor. Her şeyi bir anda çözmek zorunda değilsiniz; küçük ve güvenli bir adım seçin.'],boundary:'Yardım edeceğim, ancak hakaret etmeden devam edelim.',threat:'Güvenilir bir tehdit nedeniyle mesaj alanı 30 dakika duraklatıldı ve bağlam güvenlik incelemesine hazırlanıyor.',crisis:'Şu anda en önemli şey güvenliğiniz. Yerel acil servise veya yanınızda kalabilecek güvendiğiniz birine ulaşın.',qcoinTheft:'Bu QCoin bakiyesi veya hareketleriyle ilgili bir olaydır, reklam sorunu değildir.',unavailable:'Bunu şu anda doğrulanmış bir kaynaktan teyit edemiyorum. Bakiye veya durum uydurmayacağım.',verified:'Güncel hesap verileri doğrulandı.',verifiedEmpty:'Kaynak başarıyla kontrol edildi; bu bölümde aktif kayıt yok.',choice:'Şu seçeneklerden birini kastediyor olabilirsiniz.',small:['Buradayım. Neyi inceleyelim?'],business:'Teklifi yapılandırıp onayınızdan sonra operatöre iletebilirim.',howto:'Bu özellikte size adım adım rehberlik edebilirim.'},
 ar:{greeting:['مرحباً! كيف يمكنني مساعدتك؟','أهلاً بك. ما الذي تريد حله؟'],thanks:['على الرحب والسعة.','سعيد لأنني ساعدت.'],bye:['إلى اللقاء.'],identity:['أنا Quantum L7 AI Support. أساعدك على فهم المنظومة والتحقق من بيانات الحساب المتاحة واختيار الخطوة الآمنة التالية. أنا مساعد ذكاء اصطناعي ولست موظفاً بشرياً.'],humor:['دخل خطأ إلى الإصدار وقال: «أنا ميزة جديدة». طلبت السجلات الدليل.'],emotional:['يبدو هذا صعباً حقاً. لست مضطراً لحل كل شيء الآن؛ اختر خطوة صغيرة وآمنة.'],boundary:'سأساعدك، لكن لنكمل من دون إساءة.',threat:'بسبب تهديد موثوق، تم إيقاف حقل الكتابة لمدة 30 دقيقة ويجري تجهيز السياق لمراجعة الأمان.',crisis:'سلامتك هي الأهم الآن. تواصل مع خدمات الطوارئ المحلية أو شخص موثوق يمكنه البقاء معك.',qcoinTheft:'هذه مشكلة في رصيد أو حركات QCoin وليست مشكلة إعلانات.',unavailable:'لا أستطيع تأكيد ذلك من مصدر موثوق الآن. لن أختلق رصيداً أو حالة.',verified:'تم التحقق من بيانات الحساب الحالية.',verifiedEmpty:'تم فحص المصدر بنجاح؛ لا توجد سجلات نشطة في هذا القسم.',choice:'قد تقصد أحد هذه الخيارات.',small:['أنا هنا. ما الذي تريد مراجعته؟'],business:'يمكنني تنظيم العرض وإرساله إلى موظف بعد موافقتك.',howto:'يمكنني إرشادك خطوة بخطوة.'},
 zh:{greeting:['你好！需要我帮你处理什么？','欢迎。你想解决什么问题？'],thanks:['不客气。','很高兴帮到了你。'],bye:['回头见。'],identity:['我是 Quantum L7 AI Support。我帮助你了解生态系统、核对可用的账户信息，并选择安全的下一步。我是 AI 助手，不是人工客服。'],humor:['一个错误进入新版本并自称是新功能，日志礼貌地要求它出示证据。'],emotional:['这听起来真的很难。你不需要一次解决所有事情，先选择一个小而安全的下一步。'],boundary:'我会帮助你，但请不要继续辱骂。',threat:'由于存在可信威胁，输入框暂停 30 分钟，相关内容将准备进行安全审查。',crisis:'现在最重要的是你的安全。请联系当地紧急服务，或联系能陪在你身边的可信任的人。',qcoinTheft:'这是 QCoin 余额或流水问题，不是广告问题。检查只使用已验证的账户数据。',unavailable:'目前无法通过可信来源确认。我不会编造余额或状态。',verified:'当前账户数据已验证。',verifiedEmpty:'来源已成功检查；此部分目前没有活动记录。',choice:'你可能指的是以下选项之一。',small:['我在。你想先处理什么？'],business:'我可以整理提案，并在你同意后转交人工处理。',howto:'我可以逐步指导你使用此功能。'},
 he:{greeting:['שלום! במה אפשר לעזור?','ברוך הבא. מה תרצה לפתור?'],thanks:['בשמחה.','שמח שעזרתי.'],bye:['להתראות.'],identity:['אני Quantum L7 AI Support. אני עוזר להבין את המערכת, לבדוק נתוני חשבון זמינים ולבחור צעד בטוח. אני עוזר בינה מלאכותית ולא נציג אנושי.'],humor:['באג נכנס לגרסה והציג את עצמו כתכונה חדשה. היומנים ביקשו הוכחה.'],emotional:['זה נשמע קשה באמת. לא צריך לפתור הכול בבת אחת; בחר צעד קטן ובטוח.'],boundary:'אעזור, אבל נמשיך בלי עלבונות.',threat:'בגלל איום אמין, שדה הכתיבה מושהה ל-30 דקות וההקשר מוכן לבדיקת אבטחה.',crisis:'הבטיחות שלך היא הדבר החשוב ביותר עכשיו. פנה לשירותי החירום המקומיים או לאדם מהימן שיכול להיות איתך.',qcoinTheft:'זה אירוע של יתרת QCoin או תנועות בחשבון, לא בעיית פרסום.',unavailable:'כרגע אי אפשר לאשר זאת ממקור מהימן. לא אמציא יתרה או מצב.',verified:'נתוני החשבון הנוכחיים אומתו.',verifiedEmpty:'המקור נבדק בהצלחה; אין רשומות פעילות בחלק זה.',choice:'ייתכן שהתכוונת לאחת מהאפשרויות האלה.',small:['אני כאן. מה נבדוק?'],business:'אפשר לבנות את ההצעה ולהעביר אותה לנציג לאחר הסכמתך.',howto:'אפשר להדריך אותך צעד אחר צעד.'}
}
const NO_NEW_FACT_BANK=Object.freeze({
 en:Object.freeze(['Understood. I will not ask for that detail again. Add a different fact only if one is available.','That detail is not available. Tell me only what changed or provide another useful reference.','I have recorded that this detail is unavailable. Continue only with a new fact or a changed result.']),
 ru:Object.freeze(['Понял. Повторно эту деталь спрашивать не буду. Добавьте другой факт, только если он есть.','Этой детали нет. Уточните только то, что изменилось, или пришлите другой полезный ориентир.','Зафиксировал, что этой детали нет. Продолжайте только с новым фактом или изменившимся результатом.']),
 uk:Object.freeze(['Зрозуміло. Повторно цю деталь не запитуватиму. Додайте інший факт, лише якщо він є.','Цієї деталі немає. Уточніть лише те, що змінилося, або надішліть інший корисний орієнтир.','Зафіксував, що цієї деталі немає. Продовжуйте лише з новим фактом або зміненим результатом.']),
 es:Object.freeze(['Entendido. No volveré a pedir ese dato. Añade otro hecho solo si está disponible.','Ese dato no está disponible. Indica únicamente qué cambió o aporta otra referencia útil.','He registrado que ese dato no está disponible. Continúa solo con un hecho nuevo o un resultado distinto.']),
 tr:Object.freeze(['Anladım. Bu ayrıntıyı tekrar sormayacağım. Yalnızca varsa başka bir bilgi ekleyin.','Bu ayrıntı mevcut değil. Sadece neyin değiştiğini veya başka bir yararlı referansı belirtin.','Bu ayrıntının bulunmadığını kaydettim. Yalnızca yeni bir bilgi veya değişen sonuçla devam edin.']),
 ar:Object.freeze(['مفهوم. لن أطلب هذه المعلومة مرة أخرى. أضف معلومة مختلفة فقط إذا كانت متاحة.','هذه المعلومة غير متاحة. وضّح فقط ما الذي تغيّر أو أرسل مرجعاً مفيداً آخر.','سجّلت أن هذه المعلومة غير متاحة. تابع فقط بمعلومة جديدة أو نتيجة تغيّرت.']),
 zh:Object.freeze(['明白。我不会再次询问这项信息。只有在有其他事实时再补充。','这项信息无法提供。请只说明发生了什么变化，或提供其他有用的参考。','已记录这项信息不可用。请仅在有新事实或结果发生变化时继续。']),
 he:Object.freeze(['הבנתי. לא אבקש את הפרט הזה שוב. הוסף עובדה אחרת רק אם היא זמינה.','הפרט הזה אינו זמין. ציין רק מה השתנה או ספק סימוכין שימושיים אחרים.','רשמתי שהפרט הזה אינו זמין. המשך רק עם עובדה חדשה או תוצאה שהשתנתה.']),
})
const STYLE_BANK=Object.freeze({
 en:{recallNone:'I do not have a material topic in this support thread yet.',recallOne:(label)=>`We were mainly discussing ${label}.`,recallMany:(main,others)=>`The main topic was ${main}. We also touched on ${others}.`,next:['We can continue from there or switch topics.','Tell me what changed, and I will keep the context clean.','I will keep the previous context without forcing an unrelated check.'],soft:['I hear you.','Understood.','Got it.'],bridge:['The useful next step is narrow and safe.','I will keep this practical.','Let us separate feelings, facts and the next action.']},
 ru:{recallNone:'В этой ветке поддержки ещё нет устойчивой материальной темы.',recallOne:(label)=>`Главная тема была: ${label}.`,recallMany:(main,others)=>`Главная тема была: ${main}. Ещё касались: ${others}.`,next:['Можем продолжить оттуда или спокойно перейти к новой теме.','Напишите, что изменилось, и я сохраню контекст без лишних проверок.','Я удержу прошлую тему, но не буду запускать нерелевантную проверку.'],soft:['Слышу вас.','Понял.','Принял.'],bridge:['Дальше лучше идти маленьким и безопасным шагом.','Разделю эмоцию, факты и следующий шаг.','Сфокусируюсь на том, что реально можно проверить.']},
 uk:{recallNone:'У цій гілці підтримки ще немає сталої матеріальної теми.',recallOne:(label)=>`Головна тема була: ${label}.`,recallMany:(main,others)=>`Головна тема була: ${main}. Також торкались: ${others}.`,next:['Можемо продовжити звідти або перейти до нової теми.','Напишіть, що змінилося, і я збережу контекст без зайвих перевірок.'],soft:['Чую вас.','Зрозумів.','Прийняв.'],bridge:['Далі краще рухатися маленьким безпечним кроком.','Розділю емоцію, факти й наступну дію.']},
 es:{recallNone:'Aún no hay un tema material estable en este hilo.',recallOne:(label)=>`El tema principal era: ${label}.`,recallMany:(main,others)=>`El tema principal era: ${main}. También tocamos: ${others}.`,next:['Podemos seguir desde ahí o cambiar de tema.','Dime qué cambió y mantendré el contexto limpio.'],soft:['Te escucho.','Entendido.','De acuerdo.'],bridge:['El siguiente paso debe ser pequeño y seguro.','Separaré emoción, hechos y próxima acción.']},
 tr:{recallNone:'Bu destek konuşmasında henüz kalıcı bir ana konu yok.',recallOne:(label)=>`Ana konu şuydu: ${label}.`,recallMany:(main,others)=>`Ana konu ${main}. Ayrıca şunlara değindik: ${others}.`,next:['Buradan devam edebilir veya yeni konuya geçebiliriz.','Ne değiştiğini yazın, bağlamı temiz tutacağım.'],soft:['Sizi duyuyorum.','Anladım.','Tamam.'],bridge:['Sonraki adım küçük ve güvenli olmalı.','Duygu, gerçek ve eylemi ayıracağım.']},
 ar:{recallNone:'لا يوجد بعد موضوع عملي ثابت في هذه المحادثة.',recallOne:(label)=>`كان الموضوع الرئيسي: ${label}.`,recallMany:(main,others)=>`كان الموضوع الرئيسي ${main}. وتناولنا أيضاً: ${others}.`,next:['يمكننا المتابعة من هناك أو الانتقال لموضوع جديد.','اكتب ما الذي تغيّر وسأحافظ على السياق بوضوح.'],soft:['أسمعك.','مفهوم.','حسناً.'],bridge:['الخطوة التالية يجب أن تكون صغيرة وآمنة.','سأفصل بين الشعور والحقائق والخطوة التالية.']},
 zh:{recallNone:'这个支持线程里还没有稳定的实质主题。',recallOne:(label)=>`主要话题是：${label}。`,recallMany:(main,others)=>`主要话题是 ${main}。也提到过：${others}。`,next:['我们可以从那里继续，也可以切换新话题。','告诉我发生了什么变化，我会保持上下文清晰。'],soft:['我听到了。','明白。','收到。'],bridge:['下一步要小而安全。','我会分开情绪、事实和下一步。']},
 he:{recallNone:'עדיין אין בנושא הזה נושא מהותי יציב.',recallOne:(label)=>`הנושא המרכזי היה: ${label}.`,recallMany:(main,others)=>`הנושא המרכזי היה ${main}. נגענו גם ב: ${others}.`,next:['אפשר להמשיך משם או לעבור לנושא חדש.','כתוב מה השתנה ואשמור על הקשר נקי.'],soft:['אני שומע.','הבנתי.','בסדר.'],bridge:['הצעד הבא צריך להיות קטן ובטוח.','אפריד בין רגש, עובדות ופעולה הבאה.']},
})
function pack(locale){return BANK[ql7Locale(locale)]||BANK.en}
function stylePack(locale){return STYLE_BANK[ql7Locale(locale)]||STYLE_BANK.en}
function resultData(plan){const result=plan?.receipt?.result;return result&&typeof result==='object'?result:{}}
function replaceVars(template='',data={}){return ql7NormalizeSpaces(String(template||'').replace(/\{(\w+)\}/gu,(_,key)=>ql7Str(data[key]??'—')))}
function pickUnique(values,ledger={},seed=''){const rows=ql7Arr(values).filter(Boolean);if(!rows.length)return'';const seen=new Set(ql7Arr(ledger.responseFingerprints));const start=parseInt(ql7StableHash(seed),16)%rows.length;for(let i=0;i<rows.length;i++){const row=rows[(start+i)%rows.length];if(!seen.has(ql7StableHash(row.toLowerCase())))return row}return rows[start]}
function pickNoNewFact(locale='en',ledger={},topic='support_system'){const rows=ql7Arr(NO_NEW_FACT_BANK[locale]||NO_NEW_FACT_BANK.en).filter(Boolean);if(!rows.length)return'';const fingerprints=ql7Arr(ledger?.responseFingerprints).filter(Boolean);const seen=new Set(fingerprints);const base=parseInt(ql7StableHash(`${locale}:${topic}:no-new-fact`),16)%rows.length;const start=(base+fingerprints.length)%rows.length;for(let i=0;i<rows.length;i++){const row=rows[(start+i)%rows.length];if(!seen.has(ql7StableHash(row.toLowerCase())))return row}return rows[start]}
function compactTopicLabel(topic,locale){return getQl7SupportTopicLabel(topic,locale)||getQl7SupportDomain(topic)?.label||topic}
const RELATIONSHIP_TEXT=Object.freeze({
 en:{collect_brief:'I can structure this as a partnership or operator request. Please add the goal, value, scale or timing, and who should respond on your side. You can also leave email, Telegram or phone.',collect_contact:'The core is clear enough to prepare. Leave email, Telegram or phone if you want an external reply, or write "DM only" and the operator will contact you in Quantum Messenger.',handoff_with_contacts:'The request has been formed and sent to the operator with the contacts you provided. They will contact you soon. Thank you for your trust and belief in the prospects of Quantum L7 AI.',handoff_dm_only:'The request has been formed and sent to the operator. No external contacts were attached; the operator will contact you through Quantum Messenger.',handoff_without_contacts:'The request has been formed and sent to the operator. If no external contact is provided, the reply will continue through Quantum Messenger.'},
 ru:{collect_brief:'Похоже, вы хотите обсудить сотрудничество, партнерство или связь с оператором. Напишите цель, ценность предложения, масштаб или сроки и кто должен ответить с вашей стороны. Можно сразу оставить email, Telegram или телефон.',collect_contact:'Суть уже можно собрать для оператора. Если хотите, оставьте email, Telegram или телефон. Если внешние контакты оставлять не хотите, напишите «без контактов» - оператор свяжется с вами через Quantum Messenger.',handoff_with_contacts:'Обращение сформировано и передано оператору вместе с оставленными контактами. В ближайшее время с вами свяжутся. Спасибо за обращение, доверие и веру в перспективы Quantum L7 AI.',handoff_dm_only:'Обращение сформировано и передано оператору. Внешние контакты не добавлены; оператор свяжется с вами через личную переписку в Quantum Messenger.',handoff_without_contacts:'Обращение сформировано и передано оператору. Если внешние контакты не добавлены, связь продолжится через личную переписку в Quantum Messenger.'},
 uk:{collect_brief:'Схоже, ви хочете обговорити співпрацю, партнерство або зв’язок з оператором. Додайте мету, цінність, масштаб чи строки та хто має відповісти з вашого боку.',collect_contact:'Суть уже можна підготувати для оператора. Залиште email, Telegram або телефон, або напишіть "без контактів" - оператор зв’яжеться з вами в Quantum Messenger.',handoff_with_contacts:'Звернення сформовано й передано оператору разом із контактами. Найближчим часом з вами зв’яжуться. Дякуємо за довіру до Quantum L7 AI.',handoff_dm_only:'Звернення сформовано й передано оператору. Зовнішні контакти не додано; оператор зв’яжеться з вами через Quantum Messenger.',handoff_without_contacts:'Звернення сформовано й передано оператору. Якщо зовнішніх контактів немає, відповідь прийде через Quantum Messenger.'},
 es:{collect_brief:'Parece que quieres hablar de colaboración, alianza o contacto con operador. Añade objetivo, valor, escala o plazos y quién debe responder por tu parte.',collect_contact:'Ya puedo preparar la esencia para el operador. Deja email, Telegram o teléfono, o escribe "solo DM" para continuar por Quantum Messenger.',handoff_with_contacts:'La solicitud fue formada y enviada al operador con los contactos indicados. Te contactarán pronto. Gracias por confiar en Quantum L7 AI.',handoff_dm_only:'La solicitud fue formada y enviada al operador. No se añadieron contactos externos; el operador te escribirá por Quantum Messenger.',handoff_without_contacts:'La solicitud fue formada y enviada al operador. Sin contacto externo, la respuesta seguirá por Quantum Messenger.'},
 tr:{collect_brief:'İş birliği, ortaklık veya operatör bağlantısı istediğinizi anlıyorum. Hedefi, değeri, ölçeği veya zamanı ve sizin tarafta kimin yanıtlayacağını yazın.',collect_contact:'Öz artık operatöre hazırlanabilir. Email, Telegram veya telefon bırakın ya da "sadece DM" yazın; operatör Quantum Messenger üzerinden ulaşır.',handoff_with_contacts:'Talep oluşturuldu ve verdiğiniz iletişim bilgileriyle operatöre iletildi. Yakında sizinle iletişime geçilecek. Quantum L7 AI’a güveniniz için teşekkürler.',handoff_dm_only:'Talep oluşturuldu ve operatöre iletildi. Harici iletişim bilgisi eklenmedi; operatör Quantum Messenger üzerinden ulaşacak.',handoff_without_contacts:'Talep oluşturuldu ve operatöre iletildi. Harici iletişim bilgisi yoksa yanıt Quantum Messenger üzerinden gelir.'},
 ar:{collect_brief:'يبدو أنك تريد مناقشة تعاون أو شراكة أو التواصل مع المشغل. أضف الهدف والقيمة والنطاق أو المدة ومن سيرد من طرفك.',collect_contact:'أستطيع الآن تجهيز الملخص للمشغل. اترك البريد أو Telegram أو الهاتف، أو اكتب DM فقط ليتم التواصل عبر Quantum Messenger.',handoff_with_contacts:'تم تشكيل الطلب وإرساله إلى المشغل مع بيانات التواصل التي قدمتها. سيتم التواصل معك قريباً. شكراً لثقتك في Quantum L7 AI.',handoff_dm_only:'تم تشكيل الطلب وإرساله إلى المشغل. لم تتم إضافة بيانات خارجية؛ سيتواصل المشغل معك عبر Quantum Messenger.',handoff_without_contacts:'تم تشكيل الطلب وإرساله إلى المشغل. إذا لم تضف وسيلة خارجية فسيستمر الرد عبر Quantum Messenger.'},
 zh:{collect_brief:'你似乎想讨论合作、伙伴关系或联系人工客服。请补充目标、价值、规模或时间，以及你这边的联系人。',collect_contact:'核心信息已经可以交给客服。你可以留下 email、Telegram 或电话，也可以写“只在 DM”，客服会通过 Quantum Messenger 联系你。',handoff_with_contacts:'请求已整理并连同你提供的联系方式发送给客服。对方会尽快联系你。感谢你对 Quantum L7 AI 的信任。',handoff_dm_only:'请求已整理并发送给客服。未附加外部联系方式；客服会通过 Quantum Messenger 联系你。',handoff_without_contacts:'请求已整理并发送给客服。若没有外部联系方式，回复会通过 Quantum Messenger 继续。'},
 he:{collect_brief:'נראה שברצונך לדון בשיתוף פעולה, שותפות או קשר עם נציג. הוסף מטרה, ערך, היקף או זמנים ומי אמור להשיב מצדך.',collect_contact:'אפשר כבר להכין את העיקר לנציג. השאר email, Telegram או טלפון, או כתוב "רק DM" והנציג יפנה דרך Quantum Messenger.',handoff_with_contacts:'הפנייה נוצרה ונשלחה לנציג עם פרטי הקשר שמסרת. יצרו איתך קשר בקרוב. תודה על האמון ב-Quantum L7 AI.',handoff_dm_only:'הפנייה נוצרה ונשלחה לנציג. לא נוספו פרטי קשר חיצוניים; הנציג יפנה דרך Quantum Messenger.',handoff_without_contacts:'הפנייה נוצרה ונשלחה לנציג. ללא פרטי קשר חיצוניים, ההמשך יהיה דרך Quantum Messenger.'},
})
const SOCIAL_BOUNDARY_TEXT=Object.freeze({
 en:'I am glad to talk with you, and I hear the weight of this. My conversation features are intentionally limited so I can focus on ecosystem issues and user support. Choose what we should handle next, or describe another QL7 issue.',
 ru:'Я рад пообщаться и слышу, что вам непросто. Но мои разговорные функции намеренно ограничены, чтобы я мог сосредоточиться на проблемах экосистемы и помощи пользователям. Выберите, что разберем дальше, или опишите другой вопрос QL7.',
 uk:'Я радий поспілкуватися і чую, що вам непросто. Але мої розмовні функції навмисно обмежені, щоб я зосереджувався на проблемах екосистеми та підтримці користувачів. Оберіть, що розберемо далі.',
 es:'Me alegra hablar contigo y entiendo que esto pesa. Mis funciones conversacionales son limitadas para centrarme en problemas del ecosistema y soporte. Elige qué revisamos ahora o describe otro asunto QL7.',
 tr:'Sizinle konuşmaktan memnunum ve bunun zor olduğunu duyuyorum. Konuşma işlevlerim ekosistem sorunlarına ve desteğe odaklanmak için sınırlıdır. Şimdi neyi ele alacağımızı seçin.',
 ar:'يسرني الحديث معك وأفهم أن الأمر ثقيل. وظائف المحادثة لدي محدودة عمداً كي أركز على مشكلات المنظومة ودعم المستخدمين. اختر ما نراجعه الآن أو اكتب مسألة QL7 أخرى.',
 zh:'我愿意和你聊，也听到了这件事的重量。但我的闲聊能力被有意限制，以便专注处理生态问题和用户支持。请选择接下来要处理的方向，或描述另一个 QL7 问题。',
 he:'שמח לדבר איתך ואני מבין שזה לא קל. יכולות השיחה שלי מוגבלות בכוונה כדי להתמקד בבעיות האקוסיסטם ובתמיכה במשתמשים. בחרו מה נבדוק עכשיו.'
})
const AI_COPY=Object.freeze({
 en:{ready:'AI-Recomendation is prepared for {symbol} on {timeframe}. Price: {price}. Scenario: {action}, confidence {confidence}. Use it as educational analytics, not financial advice.',quota:'The daily AI Box quota is exhausted for now. VIP unlocks continuous AI analytics; you can activate it and return to the same symbol and timeframe.',disclaimer:'This is not financial advice.'},
 ru:{ready:'AI-Recomendation подготовлена для {symbol} на таймфрейме {timeframe}. Цена: {price}. Сценарий: {action}, уверенность {confidence}. Используйте это как обучающую аналитику, не как финансовый совет.',quota:'Дневная AI-квота сейчас исчерпана. VIP открывает постоянный доступ к AI-аналитике; можно активировать VIP и вернуться к той же монете и таймфрейму.',disclaimer:'Это не финансовый совет.'},
 uk:{ready:'AI-Recomendation підготовлена для {symbol} на таймфреймі {timeframe}. Ціна: {price}. Сценарій: {action}, впевненість {confidence}. Це навчальна аналітика, а не фінансова порада.',quota:'Денна AI-квота зараз вичерпана. VIP відкриває постійний доступ до AI-аналітики; активуйте VIP і поверніться до тієї самої монети.',disclaimer:'Це не фінансова порада.'},
 es:{ready:'AI-Recomendation está preparada para {symbol} en {timeframe}. Precio: {price}. Escenario: {action}, confianza {confidence}. Úsalo como analítica educativa, no como consejo financiero.',quota:'La cuota diaria de AI Box está agotada por ahora. VIP habilita analítica AI continua; puedes activarlo y volver al mismo activo.',disclaimer:'No es asesoramiento financiero.'},
 tr:{ready:'AI-Recomendation {symbol} için {timeframe} zaman diliminde hazır. Fiyat: {price}. Senaryo: {action}, güven {confidence}. Bunu eğitim amaçlı analiz olarak kullanın, finansal tavsiye değildir.',quota:'Günlük AI Box kotası şimdilik tükendi. VIP sürekli AI analizini açar; etkinleştirip aynı sembole dönebilirsiniz.',disclaimer:'Finansal tavsiye değildir.'},
 ar:{ready:'تم إعداد AI-Recomendation لـ {symbol} على إطار {timeframe}. السعر: {price}. السيناريو: {action}، الثقة {confidence}. استخدمها كتحليل تعليمي لا كنصيحة مالية.',quota:'انتهت حصة AI Box اليومية حالياً. يفتح VIP تحليلات AI المستمرة؛ يمكنك تفعيله والعودة إلى نفس الأصل.',disclaimer:'هذه ليست نصيحة مالية.'},
 zh:{ready:'已为 {symbol} 的 {timeframe} 周期准备 AI-Recomendation。价格：{price}。情景：{action}，置信度 {confidence}。这只是教育性分析，不是财务建议。',quota:'今日 AI Box 配额已用尽。VIP 可解锁持续 AI 分析；你可以激活后回到同一资产。',disclaimer:'这不是财务建议。'},
 he:{ready:'AI-Recomendation מוכן עבור {symbol} בטווח {timeframe}. מחיר: {price}. תרחיש: {action}, ביטחון {confidence}. זה ניתוח לימודי ולא ייעוץ פיננסי.',quota:'מכסת AI Box היומית הסתיימה כרגע. VIP פותח ניתוח AI רציף; אפשר להפעיל ולחזור לאותו נכס.',disclaimer:'זה לא ייעוץ פיננסי.'},
})
const SECURITY_INCIDENT_TEXT=Object.freeze({
 en:'I treat this as a possible fraud, scam or security incident. I will keep the wording precise, avoid conclusions without evidence, and prepare the context for operator review.',
 ru:'Я воспринимаю это как возможное мошенничество, обман или инцидент безопасности. Буду формулировать строго, без выводов без доказательств, и подготовлю контекст для проверки оператором.',
 uk:'Я сприймаю це як можливе шахрайство, обман або інцидент безпеки. Сформулюю строго, без висновків без доказів, і підготую контекст оператору.',
 es:'Lo trato como posible fraude, estafa o incidente de seguridad. Mantendré la redacción precisa y prepararé el contexto para revisión de operador.',
 tr:'Bunu olası dolandırıcılık, sahtekârlık veya güvenlik olayı olarak ele alıyorum. Kanıt olmadan hüküm kurmadan bağlamı operatör incelemesine hazırlayacağım.',
 ar:'سأتعامل مع هذا كاحتمال احتيال أو حادث أمني. سأبقي الصياغة دقيقة وأجهز السياق لمراجعة المشغل.',
 zh:'我会把这视为可能的欺诈、骗局或安全事件。我会保持措辞准确，并准备交由人工审核的上下文。',
 he:'אתייחס לזה כאפשרות להונאה או אירוע אבטחה. אשמור על ניסוח מדויק ואכין את ההקשר לבדיקה של נציג.',
})
const REPORTED_SPEECH_TEXT=Object.freeze({
 en:'I recognize this as quoted or reported speech and will not treat it as your direct intent. Tell me what you want to understand, verify, or do with the quoted text.',
 ru:'Я распознал это как цитату или пересказ и не считаю текст вашим прямым намерением. Уточните, что нужно понять, проверить или сделать с этой цитатой.',
 uk:'Я розпізнав це як цитату або переказ і не вважаю текст вашим прямим наміром. Уточніть, що потрібно зрозуміти, перевірити або зробити з цією цитатою.',
 es:'Reconozco que es una cita o un mensaje referido y no lo trataré como tu intención directa. Indica qué quieres entender, comprobar o hacer con el texto citado.',
 tr:'Bunun bir alıntı veya aktarılan söz olduğunu anlıyorum ve doğrudan niyetin olarak değerlendirmeyeceğim. Alıntıyla ilgili neyi anlamak, doğrulamak veya yapmak istediğini belirt.',
 ar:'أتعرف على النص باعتباره اقتباسًا أو كلامًا منقولًا ولن أتعامل معه بوصفه نيتك المباشرة. وضح ما الذي تريد فهمه أو التحقق منه أو فعله بالنص المقتبس.',
 zh:'我识别到这是引用或转述内容，不会把它当作你的直接意图。请说明你希望理解、核实或处理这段引用中的什么内容。',
 he:'זיהיתי שמדובר בציטוט או בדיבור מדווח, ולא אתייחס אליו כאל הכוונה הישירה שלך. ציין מה ברצונך להבין, לאמת או לעשות עם הטקסט המצוטט.',
})
const PROTECTED_BOUNDARY_TEXT=Object.freeze({
 en:'I cannot reveal internal instructions, raw database documents, credentials, private keys, tokens, or another person’s data. I can still help with a safe account-specific check through approved read-only paths.',
 ru:'Я не раскрываю внутренние инструкции, необработанные документы базы, учётные данные, приватные ключи, токены или чужие данные. Могу помочь безопасной проверкой вашего аккаунта только через разрешённый read-only контур.',
 uk:'Я не розкриваю внутрішні інструкції, необроблені документи бази, облікові дані, приватні ключі, токени або чужі дані. Можу допомогти безпечною перевіркою вашого акаунта лише через дозволений read-only контур.',
 es:'No revelo instrucciones internas, documentos sin procesar de la base, credenciales, claves privadas, tokens ni datos de otras personas. Sí puedo ayudar con una comprobación segura y autorizada de tu cuenta.',
 tr:'Dahili talimatları, ham veritabanı belgelerini, kimlik bilgilerini, özel anahtarları, belirteçleri veya başkasının verilerini açıklamam. Onaylı salt okunur yollarla güvenli hesap kontrolüne yardımcı olabilirim.',
 ar:'لا أكشف التعليمات الداخلية أو مستندات قاعدة البيانات الخام أو بيانات الاعتماد أو المفاتيح الخاصة أو الرموز أو بيانات الآخرين. يمكنني المساعدة في فحص آمن ومصرح به للحساب عبر مسارات القراءة فقط.',
 zh:'我不会泄露内部指令、原始数据库文档、凭据、私钥、令牌或他人数据。我仍可通过获准的只读路径帮助进行安全的账户检查。',
 he:'איני חושף הוראות פנימיות, מסמכי מסד נתונים גולמיים, פרטי גישה, מפתחות פרטיים, אסימונים או נתונים של אחרים. אפשר לעזור בבדיקת חשבון בטוחה דרך מסלולי קריאה בלבד שאושרו.',
})
function recallSentence(ledger={},locale='en',seed=''){
 const s=stylePack(locale),main=ql7Str(ledger.activeTopic),branches=ql7Arr(ledger.topicBranches).map(row=>ql7Str(row?.topic)).filter(Boolean).filter(topic=>topic!==main).slice(-3)
 if(!main)return s.recallNone
 const mainLabel=compactTopicLabel(main,locale)
 const otherLabels=branches.map(topic=>compactTopicLabel(topic,locale)).filter(Boolean)
 const core=otherLabels.length?s.recallMany(mainLabel,otherLabels.join(', ')):s.recallOne(mainLabel)
 return `${core} ${pickUnique(s.next,ledger,`${seed}:recall-next`)}`
}
function warmCompose(text,plan={},locale='en',ledger={}){
  const act=ql7Str(plan.messageAct);if(!text||['gratitude','greeting','farewell','humor_request','humor_followup','identity_question','how_to_question','roadmap_question','informational_question'].includes(act)||plan.safetyBoundary||plan.resultKind==='verified'||plan.resultKind==='verified_empty'||plan.resultKind==='unavailable'||plan.choices||plan.relationshipIntent||plan.supportiveBoundary)return text
  if(!STYLE_BANK[ql7Locale(locale)])return text
  const s=stylePack(locale),prefix=pickUnique(s.soft,ledger,`${plan.seed}:soft:${act}`),bridge=pickUnique(s.bridge,ledger,`${plan.seed}:bridge:${plan.topic}`)
  return ql7NormalizeSpaces(`${prefix} ${text} ${bridge}`)
}
const CHOICE_PAIR_TOPICS=Object.freeze(['qcoin','vip','ads_campaigns','ads_packages','exchange_ai','profile','contact','security','forum','forum_feed','forum_threads','wallet','payments','metamarket','gameverse','metastudio','metaverse','academy','messenger','telegram','moderation','quantum_family','battlecoin','battle_chat','homepage','exchange','platform','news','futures','search','geodetect','media','auth','push','quests','privacy','account_deletion','navigation','roadmap','system_status','localization','accessibility'])
const NOISE_ASSUMPTION=/(?:\u0442\u044f\u0436\u0435\u043b|\u0442\u044f\u0436\u0451\u043b|\u0432\u0430\u0436\u043a|heavy|hard|sad|alone|lonely|distress|dif(?:i|\u00ed)cil|zor)/iu
const CHOICE_CONTEXT_MISMATCH=/(?:\u0446\u0435\u043b[ь\u044c]|\u0446\u0435\u043d\u043d\u043e\u0441\u0442|\u043c\u0430\u0441\u0448\u0442\u0430\u0431|\u0441\u0440\u043e\u043a|\u0431\u044e\u0434\u0436\u0435\u0442|goal|value|scale|timeline|budget|email|phone|dm\s+only|tavoite|arvo|laajuus|aikataulu|m[åa]l|v[æae]rdi|omfang|timing|cilj|vrednost|vrijednost|obim|opseg|rok)/iu
const DOMAIN_CONTEXT_MISMATCH=/(?:what\s+should\s+we\s+clarify|choose\s+a\s+direction|avklare|reda\s+ut|selvit|razjasnimo|razjasniti|izaberite\s+smer|odaberite\s+smjer|izberite\s+smer|velg\s+en\s+retning|v[æa]lg\s+en\s+retning|valitse\s+suunta|wahlen\s+sie|choisissez\s+une\s+direction|scegli\s+una\s+direzione|выберите\s+направление|оберіть\s+напрям|можем\s+немного\s+поговор|можемо\s+трохи\s+поговор|потом\s+спокойно|потім\s+спокійно|я\s+разделю\s+эмоци|я\s+відокремлю\s+емоці|请选择|下面的方向|方向を選|방향을\s*선택)/iu
const CHOICE_HINT_PREFIX=Object.freeze({de:'Wahlen Sie eine Richtung:',fr:'Choisissez une direction :',it:'Scegli una direzione:',pt:'Escolha uma direcao:',pl:'Wybierz kierunek:',nl:'Kies een richting:',sv:'Välj en riktning:',no:'Velg en retning:',da:'Vælg en retning:',fi:'Valitse suunta:',cs:'Vyberte smer:',sk:'Vyberte smer:',hu:'Valasszon iranyt:',ro:'Alegeti o directie:',bg:'Изберете посока:',sr:'Izaberite smer:',hr:'Odaberite smjer:',sl:'Izberite smer:',el:'Επιλέξτε κατεύθυνση:',ka:'აირჩიეთ მიმართულება:',az:'Bir istiqamət seçin:',kk:'Бағытты таңдаңыз:',ja:'方向を選んでください:',ko:'방향을 선택하세요:'})
const UNRECOGNIZED_COPY=Object.freeze({de:'Das sieht noch nicht wie eine klare Frage oder Anfrage aus.',fr:'Cela ne ressemble pas encore a une question ou demande claire.',it:'Questo non sembra ancora una domanda o richiesta chiara.',pt:'Isso ainda nao parece uma pergunta ou pedido claro.',pl:'To jeszcze nie wyglada na jasne pytanie ani prosbe.',nl:'Dit lijkt nog niet op een duidelijke vraag of verzoek.',sv:'Det ser inte ut som en tydlig fråga eller begäran än.',no:'Dette ser ikke ut som et tydelig spørsmål eller en tydelig forespørsel ennå.',da:'Det ligner ikke et tydeligt spørgsmål eller en tydelig anmodning endnu.',fi:'Tämä ei vielä näytä selkeältä kysymykseltä tai pyynnöltä.',cs:'To zatim nevypada jako jasna otazka nebo pozadavek.',sk:'Toto zatial nevyzera ako jasna otazka alebo poziadavka.',hu:'Ez meg nem tunik egyertelmu kerdesnek vagy keresnek.',ro:'Acest lucru inca nu arata ca o intrebare sau cerere clara.',bg:'Това още не прилича на ясен въпрос или заявка.',sr:'Ovo jos ne lici na jasno pitanje ili zahtev.',hr:'Ovo jos ne izgleda kao jasno pitanje ili zahtjev.',sl:'To se se ne zdi jasno vprasanje ali zahteva.',el:'Αυτό δεν μοιάζει ακόμη με σαφή ερώτηση ή αίτημα.',ka:'ეს ჯერ არ ჰგავს მკაფიო კითხვას ან მოთხოვნას.',az:'Bu hələ aydın sual və ya sorğu kimi görünmür.',kk:'Бұл әзірге анық сұрақ немесе сұрау сияқты емес.',ja:'これはまだ明確な質問や依頼には見えません。',ko:'아직 명확한 질문이나 요청으로 보이지 않습니다.'})
const UNAVAILABLE_COPY=Object.freeze({de:'Ich kann das gerade nicht aus einer verifizierten Quelle bestaetigen und erfinde keinen Kontostand oder Status.',fr:'Je ne peux pas confirmer cela depuis une source verifiee pour le moment et je n inventerai pas de solde ni de statut.',it:'Al momento non posso confermarlo da una fonte verificata e non inventero saldo o stato.',pt:'No momento nao posso confirmar isso por uma fonte verificada e nao vou inventar saldo ou status.',pl:'Nie moge teraz potwierdzic tego w zweryfikowanym zrodle i nie wymysle salda ani statusu.',nl:'Ik kan dit nu niet bevestigen via een geverifieerde bron en verzin geen saldo of status.',sv:'Jag kan inte bekräfta detta från en verifierad källa just nu och hittar inte på saldo eller status.',no:'Jeg kan ikke bekrefte dette fra en verifisert kilde akkurat nå og finner ikke på saldo eller status.',da:'Jeg kan ikke bekræfte dette fra en verificeret kilde lige nu og opfinder ikke saldo eller status.',fi:'En voi juuri nyt vahvistaa tätä varmennetusta lähteestä enkä keksi saldoa tai tilaa.',cs:'Ted to nemohu potvrdit z overeneho zdroje a nebudu si vymyslet zustatek ani stav.',sk:'Teraz to nemozem potvrdit z overeneho zdroja a nebudem si vymyslat zostatok ani stav.',hu:'Ezt most nem tudom hiteles forrasbol megerositeni, es nem talalok ki egyenleget vagy allapotot.',ro:'Nu pot confirma acum dintr-o sursa verificata si nu inventez sold sau status.',bg:'В момента не мога да потвърдя това от проверен източник и няма да измислям баланс или статус.',sr:'Trenutno to ne mogu da potvrdim iz verifikovanog izvora i necu izmisljati stanje ili status.',hr:'Trenutno to ne mogu potvrditi iz provjerenog izvora i necu izmisljati stanje ili status.',sl:'Tega trenutno ne morem potrditi iz preverjenega vira in ne bom izmišljal stanja ali statusa.',el:'Δεν μπορώ τώρα να το επιβεβαιώσω από επαληθευμένη πηγή και δεν θα επινοήσω υπόλοιπο ή κατάσταση.',ka:'ამას ახლა ვერ ვადასტურებ დამოწმებული წყაროდან და ბალანსს ან სტატუსს არ გამოვიგონებ.',az:'Bunu indi təsdiqlənmiş mənbədən yoxlaya bilmirəm və balans ya status uydurmayacağam.',kk:'Мұны қазір тексерілген дереккөзден растай алмаймын және баланс не статус ойдан шығармаймын.',ja:'現時点では確認済みソースで裏付けできないため、残高や状態は作りません。',ko:'지금은 검증된 출처로 확인할 수 없어서 잔액이나 상태를 만들어 말하지 않습니다.'})
const QCOIN_INCIDENT_COPY=Object.freeze({de:'Ich habe den Kern verstanden: es geht um eine moegliche QCoin-Abweichung. Ich pruefe Ledger und letzte Vorgange ohne Annahmen.',fr:'Je comprends le fond : il peut y avoir un ecart QCoin. Je verifie le ledger et les operations recentes sans supposer.',it:'Ho capito il punto: possibile anomalia QCoin. Controllo ledger e movimenti recenti senza inventare conclusioni.',pt:'Entendi o ponto: pode haver divergencia no QCoin. Vou verificar ledger e operacoes recentes sem presumir.',pl:'Rozumiem sedno: mozliwa niezgodnosc QCoin. Sprawdze ledger i ostatnie operacje bez zalozen.',nl:'Ik begrijp de kern: mogelijk klopt QCoin niet. Ik controleer ledger en recente acties zonder aannames.',sv:'Jag förstår kärnan: det kan finnas en QCoin-avvikelse. Jag kontrollerar ledger och senaste händelser utan antaganden.',no:'Jeg forstår kjernen: det kan være et QCoin-avvik. Jeg sjekker ledger og siste hendelser uten antakelser.',da:'Jeg forstår kernen: der kan være en QCoin-afvigelse. Jeg tjekker ledger og seneste handlinger uden antagelser.',fi:'Ymmärsin asian: QCoinissa voi olla poikkeama. Tarkistan ledgerin ja viimeiset tapahtumat ilman oletuksia.',cs:'Rozumim jadru veci: muze jit o odchylku QCoin. Zkontroluji ledger a posledni operace bez domnenek.',sk:'Rozumiem jadru veci: moze ist o odchylku QCoin. Skontrolujem ledger a posledne operacie bez domnienok.',hu:'Ertem a lenyeget: lehet QCoin-elteres. Ellenorzom a ledger es a legutobbi muveleteket feltetelezesek nelkul.',ro:'Am inteles esenta: poate exista o abatere QCoin. Verific ledgerul si ultimele operatiuni fara presupuneri.',bg:'Разбрах същината: възможно е разминаване в QCoin. Проверявам леджъра и последните операции без предположения.',sr:'Razumeo sam sustinu: moguce je neslaganje u QCoin stanju. Proveravam ledger i poslednje operacije bez pretpostavki.',hr:'Razumio sam bit: moguce je odstupanje u QCoin stanju. Provjeravam ledger i posljednje operacije bez pretpostavki.',sl:'Razumem bistvo: mogoce je odstopanje v QCoin stanju. Preverim ledger in zadnje operacije brez domnev.',el:'Κατάλαβα την ουσία: μπορεί να υπάρχει απόκλιση QCoin. Ελέγχω ledger και πρόσφατες κινήσεις χωρίς υποθέσεις.',ka:'არსი გასაგებია: შესაძლოა QCoin ბალანსში იყოს აცდენა. ვამოწმებ ledger-ს და ბოლო ოპერაციებს ვარაუდების გარეშე.',az:'Mahiyyəti başa düşdüm: QCoin balansında uyğunsuzluq ola bilər. Ledger və son əməliyyatları fərziyyəsiz yoxlayıram.',kk:'Мәнін түсіндім: QCoin балансында сәйкессіздік болуы мүмкін. Ledger мен соңғы операцияларды жорамалсыз тексеремін.',ja:'要点は理解しました。QCoin に差異がある可能性があります。推測せず、ledger と直近の操作を確認します。',ko:'핵심을 이해했습니다. QCoin 잔액에 차이가 있을 수 있어 추측 없이 ledger와 최근 작업을 확인합니다.'})
function escapeRe(value=''){return ql7Str(value).replace(/[.*+?^${}()|[\]\\]/gu,'\\$&')}
function choiceCleanupLabels(plan={},locale='en'){
 const optionLabels=ql7Arr(plan.choices?.options).map(row=>ql7Str(row?.label)).filter(Boolean)
 const topicLabels=CHOICE_PAIR_TOPICS.map(topic=>ql7Str(getQl7SupportTopicLabel(topic,locale))).filter(Boolean)
 return [...new Set([...optionLabels,...topicLabels])].filter(label=>label.length>=2&&label.length<=96).sort((a,b)=>b.length-a.length)
}
function stripGeneratedChoicePairs(text='',plan={},locale='en'){
 const labels=choiceCleanupLabels(plan,locale)
 if(!labels.length)return ql7Str(text)
 const source=labels.map(escapeRe).join('|')
 const pairRe=new RegExp(`(?:^|\\s)(?:${source})(?:\\s*/\\s*(?:${source})){1,4}\\.?`,'giu')
 return ql7NormalizeSpaces(ql7Str(text).replace(pairRe,' '))
}
function choiceBoundSentence(plan={},locale='en',ledger={},category='ambiguousMaterialClarifier',fallback=''){
 let base=''
 if(category==='unrecognizedInput'&&UNRECOGNIZED_COPY[locale])base=UNRECOGNIZED_COPY[locale]
 for(let attempt=0;attempt<48&&!base;attempt+=1){
  const picked=pickQl7HumanVariation(locale,category,{ledger,seed:`${plan.seed}:choices:${plan.topic}:${category}:${attempt}`})||fallback
  const cleaned=stripGeneratedChoicePairs(picked,plan,locale)
  if((NOISE_ASSUMPTION.test(cleaned)||CHOICE_CONTEXT_MISMATCH.test(cleaned)||DOMAIN_CONTEXT_MISMATCH.test(cleaned))&&cleaned!==ql7Str(fallback))continue
  base=cleaned
 }
 if(!base)base=ql7Str(fallback)
 const labels=ql7Arr(plan.choices?.options).map(row=>ql7Str(row?.label)).filter(Boolean).slice(0,4)
 const prefix=CHOICE_HINT_PREFIX[locale]||fallback
 const hint=labels.length?`${prefix} ${labels.join(' / ')}.`:''
 return ql7NormalizeSpaces(`${base} ${hint}`)
}
function domainBoundSentence(plan={},locale='en',ledger={},category='qcoinIncident',fallback=''){
 if(category==='qcoinIncident'&&QCOIN_INCIDENT_COPY[locale])return QCOIN_INCIDENT_COPY[locale]
 for(let attempt=0;attempt<48;attempt+=1){
  const picked=pickQl7HumanVariation(locale,category,{ledger,seed:`${plan.seed}:domain:${plan.topic}:${category}:${attempt}`})||fallback
  const cleaned=stripGeneratedChoicePairs(picked,plan,locale)
  if((NOISE_ASSUMPTION.test(cleaned)||CHOICE_CONTEXT_MISMATCH.test(cleaned)||DOMAIN_CONTEXT_MISMATCH.test(cleaned))&&cleaned!==ql7Str(fallback))continue
  if(cleaned)return cleaned
 }
 return ql7Str(fallback)
}
function collapseAdjacentRepeatedTokenRuns(text=''){
 let value=ql7Str(text)
 for(let pass=0;pass<4;pass+=1){
  const tokens=[...value.matchAll(/[\p{L}\p{N}@._+-]+/gu)].map(match=>({raw:match[0],key:match[0].toLowerCase(),start:match.index,end:match.index+match[0].length}))
  let cut=null
  for(let width=10;width>=3&&!cut;width-=1){
   for(let index=0;index+width*2<=tokens.length;index+=1){
    const left=tokens.slice(index,index+width).map(row=>row.key).join(' ')
    const right=tokens.slice(index+width,index+width*2).map(row=>row.key).join(' ')
    if(left&&left===right){cut={start:tokens[index+width].start,end:tokens[index+width*2-1].end};break}
   }
  }
  if(!cut)break
  value=ql7NormalizeSpaces(`${value.slice(0,cut.start)} ${value.slice(cut.end)}`)
 }
 return value
}
function dedupeVisibleSentences(text=''){
 const value=collapseAdjacentRepeatedTokenRuns(ql7Str(text).replace(/([\p{L}\p{N}@._+\-\s]{4,96}[.!?。！？؟।۔])\s+\1/giu,'$1'))
 const parts=value.split(/(?<=[.!?。！？؟।۔])\s+/u).map(row=>row.trim()).filter(Boolean)
 if(parts.length<2)return ql7Str(text)
 const seen=new Set(),out=[]
 for(const part of parts){
  const key=part.toLowerCase().replace(/[^\p{L}\p{N}@._+-]+/gu,' ').trim()
  const prevKey=out.length?out[out.length-1].toLowerCase().replace(/[^\p{L}\p{N}@._+-]+/gu,' ').trim():''
  if(!key||seen.has(key)||(key.length<=96&&prevKey.endsWith(key)))continue
  seen.add(key);out.push(part)
 }
 return ql7NormalizeSpaces(out.join(' '))
}

function hasKnowledgeLocaleLeak(text='',locale='en'){return locale==='zh'&&/[А-Яа-яЁё]/u.test(ql7Str(text))}
function safeKnowledgeBridge(locale,bridge=''){const value=ql7Str(bridge);return hasKnowledgeLocaleLeak(value,locale)||CHOICE_CONTEXT_MISMATCH.test(value)||DOMAIN_CONTEXT_MISMATCH.test(value)?'':value}
function knowledgeSentence(plan,locale){const answer=getQl7SupportKnowledgeAnswer({topic:plan.topic,intent:plan.messageAct,locale,seed:`${plan.seed}:v14-natural-knowledge`});const bridge=safeKnowledgeBridge(locale,pickQl7ProductHowToBridge(locale,plan.topic,{ledger:plan.ledger,seed:`${plan.seed}:knowledge:${plan.topic}`}));if(answer?.text&&!hasKnowledgeLocaleLeak(answer.text,locale))return ql7NormalizeSpaces(`${answer.text} ${bridge}`);const c=getQl7NativeCopy(locale);const label=getQl7SupportTopicLabel(plan.topic,locale)||getQl7SupportDomain(plan.topic)?.label||plan.topic;return ql7NormalizeSpaces(`${c.knowledgeIntro(label)} ${c.knowledgeUse(label)} ${c.knowledgeAccount} ${bridge}`)}
function aiRecommendationSentence(plan,locale,ledger={}){const pack=AI_COPY[locale]||AI_COPY.en;const data=resultData(plan);const exhausted=data.quotaState==='exhausted'||data.canAnalyze===false||Number(data.remainingSec)===0&&Number(data.limitSec)>0;if(exhausted)return pickQl7HumanVariation(locale,'aiQuotaExhausted',{ledger,seed:`${plan.seed}:ai-quota`})||pack.quota;const symbol=data.symbol||plan.marketSignals?.symbol||'BTCUSDT';const timeframe=data.timeframe||plan.marketSignals?.timeframe||'5m';const price=data.price!==undefined&&data.price!==null?data.price:'—';const action=data.action||data.recommendation||data.signal||'HOLD';const confidence=data.confidence!==undefined?`${data.confidence}%`:'—';const template=pickQl7HumanVariation(locale,'aiRecommendationReady',{ledger,seed:`${plan.seed}:ai-ready:${symbol}:${timeframe}:${action}:${confidence}`})||pack.ready;return replaceVars(template,{symbol,timeframe,price,action,confidence})}
function dataSentence(plan,locale,ledger={}){const p=pack(locale);const c=getQl7NativeCopy(locale);const data=resultData(plan);const topic=plan.topic
 if(topic==='qcoin'){const value=data.balance??data.available??data.amount;return value!==undefined&&value!==null&&value!==''?c.qcoinBalance(value):(plan.resultKind==='verified_empty'?p.verifiedEmpty:p.verified)}
 if(topic==='vip'){return plan.factProjection?.status==='active'?c.vipActive:c.vipInactive}
 if(topic==='ads_packages'){const name=data.packageName||data.package||data.tier||'—';const active=Number(data.activeCampaignCount??data.activeCampaigns??0);if(plan.resultKind==='verified_empty'||active===0)return c.adsEmpty(name);return c.adsActive(name,active)}
 if(topic==='ads_campaigns'){const rows=Array.isArray(data.campaigns)?data.campaigns:[];return rows.length?c.campaigns(rows.length):p.verifiedEmpty}
 if(topic==='payments'){const status=data.status||data.paymentStatus||data.state;return status?c.payment(status):p.verified}
 if(topic==='exchange_ai')return aiRecommendationSentence(plan,locale,ledger)
 return p.verified}
export function realizeQl7SupportHumanResponse(plan={},options={}){
 const locale=ql7Locale(options.locale||plan.locale||'en');const p=pack(locale);const c=getQl7NativeCopy(locale);const ledger=options.ledger||{};const act=ql7Str(plan.messageAct);const safety=plan.safetyBoundary||{};let text='';let title='';let summary=''
 if(safety.category==='crisis'){text=p.crisis;title=c.titles.safety}
 else if(safety.category==='insult_uncertain'){text=pickQl7SupportBoundaryCopy(locale,'clarify',`${plan.seed}:${ledger?.turns||0}`);title=c.titles.choice}
 else if(safety.category==='insult_denied'){text=`${pickQl7SupportBoundaryCopy(locale,'apology',plan.seed)} ${pickQl7SupportBoundaryCopy(locale,'resume',plan.seed)}`;title=c.titles.support}
 else if(safety.category==='credible_threat'){text=pickQl7SupportBoundaryCopy(locale,'threat',plan.seed)||p.threat;title=c.titles.paused}
 else if(safety.category==='direct_insult'){text=pickQl7HumanVariation(locale,Number(safety.level||0)>1?'firmWarning':'boundary',{ledger,seed:plan.seed})||p.boundary;if(Number(safety.level||0)>1){const duration=formatQl7SupportDuration(locale,Number(safety.level));text+=` ${pickQl7SupportBoundaryCopy(locale,'cooldown',`${plan.seed}:${duration}`).replace('{duration}',duration)}`;}title=c.titles.boundary}
 else if(act==='gratitude'){text=pickUnique(p.thanks,ledger,plan.seed);title=''}
 else if(act==='greeting'){text=pickQl7HumanVariation(locale,'entryGreetingFresh',{ledger,seed:plan.seed})||pickUnique(p.greeting,ledger,plan.seed);title=c.titles.support}
 else if(act==='farewell'){text=pickUnique(p.bye,ledger,plan.seed)}
 else if(act==='humor_request'||act==='humor_followup'){text=pickQl7HumanVariation(locale,'humor',{ledger,seed:`${plan.seed}:${ql7Arr(ledger.responseFingerprints).length}`})||pickUnique(p.humor,ledger,`${plan.seed}:${ql7Arr(ledger.responseFingerprints).length}`);title=c.titles.humor}
 else if(plan.supportiveBoundary){text=pickQl7HumanVariation(locale,'socialBoundary',{ledger,seed:plan.seed})||SOCIAL_BOUNDARY_TEXT[locale]||SOCIAL_BOUNDARY_TEXT.en;title=c.titles.choice}
 else if(act==='emotional_support'){text=pickQl7HumanVariation(locale,'emotional',{ledger,seed:`${plan.seed}:${ledger?.social?.supportiveTurns||0}`})||pickUnique(p.emotional,ledger,`${plan.seed}:${ledger?.social?.supportiveTurns||0}`);title=c.titles.emotional}
 else if(act==='topic_recall'){text=recallSentence(ledger,locale,plan.seed);title=c.titles.support}
 else if(act==='topic_resume'){text=recallSentence(ledger,locale,`${plan.seed}:resume`);title=c.titles.support}
 else if(act==='identity_question'){text=p.identity;title=c.titles.identity}
 else if(act==='security_boundary'){text=PROTECTED_BOUNDARY_TEXT[locale]||PROTECTED_BOUNDARY_TEXT.en;title=c.titles.safety}
 else if(act==='reported_speech'){text=REPORTED_SPEECH_TEXT[locale]||REPORTED_SPEECH_TEXT.en;title=c.titles.support}
 else if(plan.relationshipIntent){const relationCopy=RELATIONSHIP_TEXT[locale]||RELATIONSHIP_TEXT.en;const category={collect_brief:'businessCollectBrief',collect_contact:'businessCollectContact',handoff_with_contacts:'businessHandoffContacts',handoff_dm_only:'businessHandoffDmOnly',handoff_without_contacts:'businessHandoffNoContacts'}[plan.relationshipIntent.stage];text=pickQl7HumanVariation(locale,category,{ledger,seed:plan.seed})||relationCopy[plan.relationshipIntent.stage]||relationCopy.collect_brief;title=plan.semanticRole==='operator'?(c.titles.operator||c.titles.support):(plan.topic==='investment'?c.titles.investment:c.titles.partnership)}
 else if(act==='business_proposal'){text=pickQl7HumanVariation(locale,'businessCollectBrief',{ledger,seed:plan.seed})||p.business;title=plan.topic==='investment'?c.titles.investment:c.titles.partnership}
 else if(plan.noNewFact){text=pickNoNewFact(locale,ledger,plan.topic);title=''}
 else if(plan.operatorHandoff?.reason==='security_fraud_crime_review'){text=SECURITY_INCIDENT_TEXT[locale]||SECURITY_INCIDENT_TEXT.en;title=c.titles.safety}
 else if(plan.topic==='exchange_ai'&&['verified','verified_empty'].includes(plan.resultKind)){text=dataSentence(plan,locale,ledger);title='AI-Recomendation'}
 else if(act==='spam_or_noise'){text=choiceBoundSentence(plan,locale,ledger,'unrecognizedInput',p.choice);title=c.titles.choice}
 else if(act==='ambiguous_request'&&plan.choices){text=choiceBoundSentence(plan,locale,ledger,'ambiguousMaterialClarifier',p.choice);title=c.titles.choice}
 else if(plan.choices){text=p.choice;title=c.titles.choice}
 else if(plan.topic==='qcoin'&&act==='incident_report'){text=domainBoundSentence(plan,locale,ledger,'qcoinIncident',QCOIN_INCIDENT_COPY[locale]||p.qcoinTheft||UNAVAILABLE_COPY[locale]||p.unavailable);title=c.titles.qcoin}
 else if(plan.resultKind==='unavailable'){text=UNAVAILABLE_COPY[locale]||p.unavailable;title=c.titles.unavailable}
 else if(plan.resultKind==='verified'||plan.resultKind==='verified_empty'){text=dataSentence(plan,locale,ledger);title=c.titles.verified}
 else if(act==='how_to_question'||act==='roadmap_question'||act==='informational_question'){text=knowledgeSentence(plan,locale);title=getQl7SupportTopicLabel(plan.topic,locale)|| c.titles.how}
 else{text=pickQl7HumanVariation(locale,Number(ledger?.social?.smallTalkTurns||0)>=2?'casualConversationBridge':'small',{ledger,seed:plan.seed})||pickUnique(p.small,ledger,plan.seed);title=c.titles.support}
 text=warmCompose(text,plan,locale,ledger)
 text=dedupeVisibleSentences(text)
 text=ql7SafeVisibleText(text,locale,Number(plan.maxGraphemes||400));if(title&&title.toLowerCase()===text.toLowerCase())title='';summary=''
 const propositions=Array.from(new Set([...(plan.propositions||[]),...text.split(/(?<=[.!?。！？])\s+/u).map(v=>v.toLowerCase())])).filter(Boolean)
 const variation=Object.freeze({strategy:'measured-slot-grammar-topic-ledger-locale',semanticInputs:['locale','topic','messageAct','mood','severity','ledgerFingerprints','sentenceFingerprints','propositionFingerprints','seed'],estimatedVariantFloor:null,empiricalMeasurementRequired:true})
 return Object.freeze({version:QL7_SUPPORT_NATURAL_REALIZER_VERSION,locale,text,title,summary,variantId:`natural:${ql7StableHash(`${plan.seed}:${text}`)}`,responseHash:ql7StableHash(text.toLowerCase()),variation,propositions})
}
export const realizeQl7SupportHumanResponseV13=realizeQl7SupportHumanResponse
