import {ql7Arr, ql7StableHash, ql7Str} from '../internal/text.js'
export const QL7_SUPPORT_SURFACE_REDUNDANCY_RECEIPT_VERSION = '5.2.5'
export const QL7_SUPPORT_SURFACE_REDUNDANCY_OWNER_ID = 'ql7-support.surface-redundancy'
const STOP = new Set(['a','an','the','of','to','and','or','is','are','в','на','и','или','это','для','по','с','из','у','та','це','і','або','de','la','el','y','o','un','una'])
const DOMAIN_ENTITY_ALIASES = Object.freeze({
  qcoin:['qcoin','q coin','кьюкоин','кью коин'], vip:['vip','вип','віp'], metamarket:['metamarket','meta market'],
  telegram:['telegram','телеграм'], battlecoin:['battlecoin','battle coin'], wallet:['wallet','кошелек','кошелёк','гаманець'],
  exchange_ai:['exchange ai','биржа','біржа'], ads_packages:['ads','реклама'], ads_campaigns:['ads','реклама'],
})
export function normalizeQl7SupportSurfaceSemanticText(value=''){return ql7Str(value).normalize('NFKC').toLocaleLowerCase().replace(/[\p{P}\p{S}]+/gu,' ').replace(/\s+/gu,' ').trim()}
function tokens(value=''){return normalizeQl7SupportSurfaceSemanticText(value).split(/\s+/u).filter((x)=>x.length>1&&!STOP.has(x))}
function item(path,kind,text,semanticId='',meta={}){const value=ql7Str(text);if(!value)return null;return Object.freeze({path,kind,textHash:ql7StableHash(value),normalized:normalizeQl7SupportSurfaceSemanticText(value),tokens:Object.freeze(tokens(value)),semanticId:ql7Str(semanticId),...meta})}
function tableList(surface={}){const rows=ql7Arr(surface.tables);if(rows.length)return rows;return surface.table?[surface.table]:[]}
export function collectQl7SupportVisibleSurfaceUnits({surface={},text='',title=''}={}){
 const rows=[];const push=(v)=>{if(v)rows.push(v)};const body=ql7Str(text);push(item('body','body',body,'body'));const resolvedTitle=ql7Str(title||surface.title);push(item('title','title',resolvedTitle,'title'))
 const summary=ql7Str(surface.summary);if(summary&&normalizeQl7SupportSurfaceSemanticText(summary)!==normalizeQl7SupportSurfaceSemanticText(body))push(item('summary','summary',summary,'summary'))
 push(item('status.label','status',surface.status?.label,'status'))
 ql7Arr(surface.badges).forEach((b,i)=>{push(item(`badges[${i}].label`,'badge',b?.label,b?.id||`badge:${i}`));push(item(`badges[${i}].detail`,'badge-detail',b?.detail,b?.id||`badge:${i}`))})
 tableList(surface).forEach((t,ti)=>{push(item(`tables[${ti}].title`,'table-title',t?.title,t?.schema||t?.id||`table:${ti}`));ql7Arr(t?.rows).forEach((r,ri)=>{push(item(`tables[${ti}].rows[${ri}].label`,'table-label',r?.label,r?.key||`row:${ri}`,{tableId:t?.id||'',rowKey:r?.key||''}));push(item(`tables[${ti}].rows[${ri}].value`,'table-value',String(r?.value??''),r?.key||`row:${ri}`,{tableId:t?.id||'',rowKey:r?.key||'',unit:r?.unit||'',format:r?.format||''}))})})
 ql7Arr(surface.actions).forEach((a,i)=>push(item(`actions[${i}].label`,'action',a?.label,a?.routeId||a?.id||`action:${i}`)))
 ql7Arr(surface.options).forEach((a,i)=>push(item(`options[${i}].label`,'option',a?.label,a?.id||`option:${i}`)))
 return Object.freeze(rows)
}
function substantiveKind(kind=''){return ['body','summary','badge-detail'].includes(kind)}
function entityRegionClass(kind=''){if(['body','summary','badge-detail'].includes(kind))return'prose';if(kind==='table-value')return'data';return'structural'}
function canonicalEntityLabels(domainId='',extra=[]){return Object.freeze([...new Set([...(DOMAIN_ENTITY_ALIASES[ql7Str(domainId)]||[]),...ql7Arr(extra).map(ql7Str)].map(normalizeQl7SupportSurfaceSemanticText).filter(Boolean))])}
function countPhrase(normalized='',phrase=''){if(!phrase)return 0;let count=0,pos=0;while((pos=normalized.indexOf(phrase,pos))>=0){count+=1;pos+=Math.max(1,phrase.length)}return count}
export function buildQl7SupportSurfaceRedundancyReceipt(input={}){
 const units=collectQl7SupportVisibleSurfaceUnits(input),groups=new Map();for(const row of units){if(row.normalized.length<2)continue;const list=groups.get(row.normalized)||[];list.push(row);groups.set(row.normalized,list)}
 const duplicatePropositionGroups=[];for(const [normalized,locations] of groups){const substantive=locations.filter((r)=>substantiveKind(r.kind));if(substantive.length>1)duplicatePropositionGroups.push(Object.freeze({normalizedHash:ql7StableHash(normalized),locations:Object.freeze(substantive.map(r=>r.path)),semanticIds:Object.freeze([...new Set(substantive.map(r=>r.semanticId).filter(Boolean))])}))}
 const semanticIdGroups=new Map();for(const row of units.filter((r)=>substantiveKind(r.kind)&&r.semanticId&&!['body','title','summary'].includes(r.semanticId))){const list=semanticIdGroups.get(row.semanticId)||[];list.push(row);semanticIdGroups.set(row.semanticId,list)}
 const duplicateSemanticIdGroups=Object.freeze([...semanticIdGroups.entries()].filter(([,rows])=>rows.length>1).map(([semanticId,rows])=>Object.freeze({semanticId,locations:Object.freeze(rows.map(r=>r.path))})))
 const tableRows=[];for(const t of tableList(input.surface)){const tableIdentity=normalizeQl7SupportSurfaceSemanticText(t?.title)||ql7Str(t?.schema||t?.id);for(const r of ql7Arr(t?.rows))tableRows.push({tableId:t?.id||'',tableIdentity,key:ql7Str(r?.key),label:normalizeQl7SupportSurfaceSemanticText(r?.label),value:normalizeQl7SupportSurfaceSemanticText(String(r?.value??'')),format:ql7Str(r?.format),unit:ql7Str(r?.unit)})}
 const seenRows=new Map(),duplicateRows=[];for(const row of tableRows){const k=JSON.stringify([row.tableIdentity,row.key,row.label,row.value,row.format,row.unit]);if(seenRows.has(k))duplicateRows.push(Object.freeze({first:seenRows.get(k),duplicate:row}));else seenRows.set(k,row)}
 const valueGroups=new Map();for(const row of tableRows){if(!row.value)continue;const k=JSON.stringify([row.value,row.format,row.unit]);const list=valueGroups.get(k)||[];list.push(row);valueGroups.set(k,list)}
 const duplicateTableValues=Object.freeze([...valueGroups.entries()].filter(([,rows])=>rows.length>1).map(([valueKey,rows])=>Object.freeze({valueKeyHash:ql7StableHash(valueKey),rows:Object.freeze(rows)})))
 const statusLabels=units.filter(r=>r.kind==='status'||r.kind==='badge').map(r=>r.normalized).filter(Boolean);const duplicateStatuses=[...new Set(statusLabels.filter((x,i,a)=>a.indexOf(x)!==i))]
 const bodyNorm=normalizeQl7SupportSurfaceSemanticText(input.text),tableValueRepeats=[];for(const row of units.filter(r=>r.kind==='table-value'&&r.normalized.length>=2)){if(bodyNorm&&bodyNorm.includes(row.normalized))tableValueRepeats.push(Object.freeze({path:row.path,valueHash:ql7StableHash(row.normalized),semanticId:row.semanticId}))}
 const entityLabels=canonicalEntityLabels(input.domainId||input.surface?.topic,input.entityLabels);const entityMentionGroups=[];for(const label of entityLabels){const locations=[];for(const row of units){const count=countPhrase(row.normalized,label);if(count)locations.push({path:row.path,kind:row.kind,regionClass:entityRegionClass(row.kind),count})}const total=locations.reduce((sum,row)=>sum+row.count,0),proseMentionCount=locations.filter(row=>row.regionClass==='prose').reduce((sum,row)=>sum+row.count,0),structuralMentionCount=locations.filter(row=>row.regionClass==='structural').reduce((sum,row)=>sum+row.count,0),dataMentionCount=locations.filter(row=>row.regionClass==='data').reduce((sum,row)=>sum+row.count,0),proseRegions=[...new Set(locations.filter(row=>row.regionClass==='prose').map(row=>row.path.split(/[.[]/u)[0]))];if(total>1)entityMentionGroups.push(Object.freeze({labelHash:ql7StableHash(label),total,proseMentionCount,structuralMentionCount,dataMentionCount,proseRegionCount:proseRegions.length,locations:Object.freeze(locations)}))}
 const body={schema:'ql7.support.surface-redundancy-receipt',schemaVersion:QL7_SUPPORT_SURFACE_REDUNDANCY_RECEIPT_VERSION,ownerId:QL7_SUPPORT_SURFACE_REDUNDANCY_OWNER_ID,locale:ql7Str(input.locale||input.surface?.locale||'en'),domainId:ql7Str(input.domainId||input.surface?.topic),microtopicId:ql7Str(input.microtopicId),intentId:ql7Str(input.intentId),surfaceHash:ql7Str(input.surface?.integrityBlock?.surfaceHash)||ql7StableHash(JSON.stringify(input.surface||{})),unitCount:units.length,duplicatePropositionGroups:Object.freeze(duplicatePropositionGroups),duplicateSemanticIdGroups,duplicateRows:Object.freeze(duplicateRows),duplicateTableValues,duplicateStatuses:Object.freeze(duplicateStatuses),tableValueRepeats:Object.freeze(tableValueRepeats),entityMentionGroups:Object.freeze(entityMentionGroups),necessaryRepeatReasons:Object.freeze(ql7Arr(input.necessaryRepeatReasons).map(ql7Str).filter(Boolean)),unitsHash:ql7StableHash(JSON.stringify(units.map(({normalized,tokens:tokenList,...r})=>({...r,normalizedHash:ql7StableHash(normalized),tokenHash:ql7StableHash(tokenList.join('|'))}))))}
 const receiptHash=ql7StableHash(JSON.stringify(body));return Object.freeze({...body,receiptId:`surface-redundancy:${receiptHash}`,receiptHash})
}
