import fs from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
export const QL7_SUPPORT_PUBLIC_FIGURE_MATERIAL_PROFILES_VERSION='5.4.2-canonical'
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../../..'),DIR=path.join(ROOT,'lib/ql7-support/knowledge/public-figures/substantiveFacts')
const profiles=fs.readdirSync(DIR).filter(x=>/^shard-\d+\.json$/.test(x)).sort().flatMap(x=>JSON.parse(fs.readFileSync(path.join(DIR,x),'utf8')).profiles||[])
export const QL7_SUPPORT_PUBLIC_FIGURE_MATERIAL_PROFILES=Object.freeze(profiles.map(Object.freeze))
const MAP=new Map(profiles.map(x=>[x.personId,x])),META=new Set(['canonical_name','public_identity','notability_domain','source_lookup_key','catalog_rank'])
export function getQl7PublicFigureMaterialProfile(personId=''){return MAP.get(String(personId))||null}
export function auditQl7PublicFigureMaterialProfiles(){const failures=[];let substantive4=0,explicitInsufficient=0,selfCatalogOnly=0,privateFacts=0,sourceBoundFacts=0;for(const p of profiles){const facts=(p.substantiveStableFacts||[]).filter(x=>!META.has(x.factType)&&x.value&&x.sourceRefs?.length);if(facts.length>=4)substantive4++;else if(p.substantiveSourceStatus==='insufficient_public_stable_facts'||p.sourceLookupRequired===true)explicitInsufficient++;else failures.push(`unaccounted:${p.personId}`);for(const x of facts){sourceBoundFacts++;if((x.sourceRefs||[]).every(r=>String(r).startsWith('catalog:')))selfCatalogOnly++;if(x.publicOnly!==true)privateFacts++}}if(profiles.length<1900)failures.push(`profile_floor:${profiles.length}`);if(selfCatalogOnly)failures.push(`self_catalog_only:${selfCatalogOnly}`);if(privateFacts)failures.push(`private_fact:${privateFacts}`);const substantiveRichCoveragePct=profiles.length?Number(((substantive4/profiles.length)*100).toFixed(6)):0,profileAccountingPct=profiles.length?Number((((substantive4+explicitInsufficient)/profiles.length)*100).toFixed(6)):0;if(profileAccountingPct!==100)failures.push(`accounting:${profileAccountingPct}`);return Object.freeze({ok:!failures.length,profileCount:profiles.length,substantiveFourCount:substantive4,explicitInsufficientCount:explicitInsufficient,substantiveRichCoveragePct,profileAccountingPct,selfCatalogOnlySubstantiveFacts:selfCatalogOnly,sourceBoundFactCount:sourceBoundFacts,metadataExcluded:true,privateFacts,denominatorDefinition:'installed identities',numeratorDefinition:'profiles with >=4 approved-source substantive public stable facts',insufficientDefinition:'explicit source lookup required; not counted rich',failures:Object.freeze(failures)})}
