export const QL7_SUPPORT_PUBLIC_FIGURE_PRIVACY_CLASS='public_figure_public_fact_only'
import {loadQl7PublicFigureRichProfiles} from './manifest.js'
import {assertQl7PublicFigureFactPublic} from './privacyBoundary.js'
import {QL7_SUPPORT_PUBLIC_FIGURE_CURRENT_FACT_TYPES} from './factSchema.js'
import {auditQl7PublicFigureFreshReceipt} from './currentFactFreshnessPolicy.js'
import {getQl7PublicFigureMaterialProfile} from './materialProfiles.js'
import {getQl7PublicEntity} from './entitySnapshot.js'
const PROFILES=new Map(loadQl7PublicFigureRichProfiles().map(r=>[r.personId,r]))
const QL7_SUPPORT_PUBLIC_FIGURE_CATALOG_METADATA_FACT_TYPES=Object.freeze(new Set(['canonical_name','public_identity','notability_domain','source_lookup_key','catalog_rank']))
function canonicalNameFact(profile){const value=String(profile?.canonicalName||'').trim();if(!value)return null;return Object.freeze({factType:'canonical_name',value,publicOnly:true,currentSensitive:false,displayEligible:true,sourceRefs:Object.freeze([`catalog:${profile.personId}:canonical-name`])})}
export async function resolveQl7PublicFigureFact({personId='',factType='',sourceAdapters={},locale='en',now=Date.now()}={}){assertQl7PublicFigureFactPublic(factType);const entity=getQl7PublicEntity(personId);const profile=PROFILES.get(String(personId||''));if(!entity||!profile)return Object.freeze({state:'unknown_person',answerAllowed:false});const materialProfile=getQl7PublicFigureMaterialProfile(personId),current=QL7_SUPPORT_PUBLIC_FIGURE_CURRENT_FACT_TYPES.has(factType);const materialFact=(materialProfile?.substantiveStableFacts||[]).find(f=>f.factType===factType&&f.displayEligible!==false&&Array.isArray(f.sourceRefs)&&f.sourceRefs.length&&!f.sourceRefs.every(r=>String(r).startsWith('catalog:')));if(materialFact&&!current)return Object.freeze({state:'confirmed_stable_public_fact',answerAllowed:true,fact:materialFact,personId,locale,sourceMode:'substantive-public-profile',substantive:true,metadataOnly:false});const staticFact=(profile.stableFacts||[]).find(f=>f.factType===factType&&f.displayEligible!==false)||(factType==='canonical_name'?canonicalNameFact(profile):null);if(staticFact&&!current){const metadataOnly=QL7_SUPPORT_PUBLIC_FIGURE_CATALOG_METADATA_FACT_TYPES.has(String(staticFact.factType||''));return Object.freeze({state:'confirmed_stable_public_fact',answerAllowed:true,fact:staticFact,personId,locale,sourceMode:metadataOnly?'catalog-identity-metadata':'bundled-public-profile',substantive:!metadataOnly,metadataOnly,substantiveSourceStatus:materialProfile?.substantiveSourceStatus||'',sourceLookupRequired:Boolean(materialProfile?.sourceLookupRequired)})}const adapter=sourceAdapters?.publicFigureFacts||sourceAdapters?.knowledge||sourceAdapters?.openHumanKnowledge;if(typeof adapter!=='function')return Object.freeze({state:current?'unavailable_current':'unavailable_public_source',answerAllowed:false,personId,factType,locale,sourceLookupRequired:Boolean(materialProfile?.sourceLookupRequired),substantiveSourceStatus:materialProfile?.substantiveSourceStatus||''});const receipt=await adapter({personId,factType,locale,sourceLookupKeys:materialProfile?.sourceLookupKeys?.length?materialProfile.sourceLookupKeys:profile.sourceLookupKeys,currentSensitive:current});if(current){const fresh=auditQl7PublicFigureFreshReceipt({factType,receipt,now});if(!fresh.ok)return Object.freeze({state:'stale_or_unverified_current_source',answerAllowed:false,personId,factType,locale,freshness:fresh})}if(!(receipt?.verified===true||receipt?.status==='verified'))return Object.freeze({state:'unverified_public_source',answerAllowed:false,personId,factType,locale});return Object.freeze({state:current?'confirmed_current_public_fact':'confirmed_public_fact',answerAllowed:true,personId,factType,locale,value:receipt.value,sourceReceiptId:receipt.receiptId||'',sourceRef:receipt.sourceRef||'',verifiedAt:receipt.verifiedAt||receipt.checkedAt||''})}
