import fs from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {ql7StableHash} from '../internal/text.js'
import {resolveQl7GeneralHumanSourceRoute} from './generalHumanSourceRouteRegistry.js'
export const QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_CORE_VERSION='5.4.2-canonical'
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),DIR=path.join(ROOT,'lib/ql7-support/knowledge/general-human')
const docs=fs.readdirSync(DIR).filter(x=>/^shard-\d+\.json$/.test(x)).sort().map(x=>JSON.parse(fs.readFileSync(path.join(DIR,x),'utf8')))
export const QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES=Object.freeze(docs.flatMap(d=>d.nodes||[]).map(row=>Object.freeze({...row,readyToSend:false,finalText:false,semanticPlanOnly:true})))
export const QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODE_COUNT=QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES.length
export const QL7_SUPPORT_GENERAL_HUMAN_TOPIC_FAMILIES=Object.freeze([...new Set(QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES.map(x=>x.topicFamilyId))])
export const QL7_SUPPORT_GENERAL_HUMAN_CONCEPT_FACETS=Object.freeze([...new Set(QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES.map(x=>x.facetId))])
const INDEX=new Map(QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES.map(n=>[n.conceptId,n]))
export function getQl7GeneralHumanConcept(topicFamilyId='',facetId='overview'){return INDEX.get(`human-concept:${topicFamilyId}:${facetId}`)||null}
export function auditQl7GeneralHumanKnowledgeCore(){const failures=[],ids=new Set();let material=0,sourceRouteBound=0,verifiedWorldFactClaims=0;for(const row of QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES){if(ids.has(row.conceptId))failures.push(`duplicate:${row.conceptId}`);ids.add(row.conceptId);const routes=(row.sourceRefs||[]).map(resolveQl7GeneralHumanSourceRoute).filter(Boolean);const substantive=row.definitions?.some(Boolean)&&row.relations?.length&&row.examples?.length&&routes.length>0&&String(row.sourcePolicy||'').length>0;if(substantive){material++;sourceRouteBound++}else failures.push(`substantive:${row.conceptId}`);for(const f of row.stableFactRecords||[]){if(f.userVisibleAsVerifiedWorldFact===true){verifiedWorldFactClaims++;if(!Array.isArray(f.sourceRefs)||!f.sourceRefs.length||f.sourceRefs.every(x=>String(x).startsWith('ontology:')))failures.push(`world_fact_without_approved_source:${row.conceptId}:${f.factId}`)}}if(row.readyToSend||row.finalText)failures.push(`invalid_owner_state:${row.conceptId}`)}if(material<12000)failures.push(`material_node_floor:${material}/12000`);return Object.freeze({ok:!failures.length,version:QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_CORE_VERSION,topicFamilyCount:QL7_SUPPORT_GENERAL_HUMAN_TOPIC_FAMILIES.length,facetCount:QL7_SUPPORT_GENERAL_HUMAN_CONCEPT_FACETS.length,nodeCount:ids.size,materialNodeCount:material,sourceRouteBoundCount:sourceRouteBound,verifiedWorldFactClaims,openSubjectRouteRequired:true,worldFactsRequireApprovedSourceReceipt:true,materialHash:ql7StableHash(JSON.stringify(QL7_SUPPORT_GENERAL_HUMAN_KNOWLEDGE_NODES.map(x=>x.contentHash))),failures:Object.freeze(failures)})}

export function getQl7GeneralHumanRetrievalDescriptor(topicFamilyId='',facetId='overview'){const c=getQl7GeneralHumanConcept(topicFamilyId,facetId);if(!c)return null;return Object.freeze({conceptId:c.conceptId,topicFamilyId:c.topicFamilyId,facetId:c.facetId,sourceRefs:Object.freeze([...(c.sourceRefs||[])]),substantiveDefinitionCount:(c.definitions||[]).filter(Boolean).length,stableFactCount:(c.stableFactRecords||[]).filter(x=>x?.userVisibleAsVerifiedWorldFact===true).length,relationCount:(c.relations||[]).length,exampleCount:(c.examples||[]).length,semanticScopeOnly:(c.stableFactRecords||[]).every(x=>x?.userVisibleAsVerifiedWorldFact!==true),embeddingKey:`human:${c.conceptId}`})}
