import fs from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import {ql7StableHash, ql7Str} from '../internal/text.js'
export const QL7_SUPPORT_HUMAN_CONVERSATION_BANK_VERSION='5.4.0'
export const QL7_SUPPORT_HUMAN_CONVERSATION_MINIMUM_CELLS=8192
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),DIR=path.join(ROOT,'lib/ql7-support/knowledge/human-conversation')
const docs=fs.readdirSync(DIR).filter(x=>/^shard-\d+\.json$/.test(x)).sort().map(x=>JSON.parse(fs.readFileSync(path.join(DIR,x),'utf8')))
export const QL7_SUPPORT_HUMAN_CONVERSATION_CELLS=Object.freeze(docs.flatMap(d=>d.cells||[]).map(row=>Object.freeze({...row,semanticPlanOnly:true,readyToSend:false,finalText:false})))
export const QL7_SUPPORT_HUMAN_CONVERSATION_CELL_COUNT=QL7_SUPPORT_HUMAN_CONVERSATION_CELLS.length
export const QL7_SUPPORT_HUMAN_CONVERSATION_FACETS=Object.freeze([...new Set(QL7_SUPPORT_HUMAN_CONVERSATION_CELLS.map(x=>x.facet))])
export const QL7_SUPPORT_HUMAN_CONVERSATION_BANK_HASH=ql7StableHash(JSON.stringify(QL7_SUPPORT_HUMAN_CONVERSATION_CELLS.map(r=>r.contentHash||r.cellHash)))
const INDEX=new Map(QL7_SUPPORT_HUMAN_CONVERSATION_CELLS.map(x=>[x.cellId,x]))
const RULES=Object.freeze([['current_context',/(?:today|now|current|latest|сегодня|сейчас|сьогодні|зараз|hoy|ahora|güncel|bugün|اليوم|الآن|今天|现在|היום|עכשיו)/iu],['comparison',/(?:compare|versus| vs |difference|сравн|порівн|compar|karşılaştır|قارن|比较|השוו)/iu],['history',/(?:history|origin|истори|істор|historia|tarih|تاريخ|历史|היסטוריה)/iu],['how_it_works',/(?:how .*work|как .*работ|як .*прац|cómo funciona|nasıl çalış|كيف يعمل|怎么工作|איך .*עובד)/iu],['humor',/(?:joke|funny|humor|шут|анекдот|жарт|chiste|şaka|نكت|笑话|בדיחה)/iu]])
function fallbackCell(category,facet){return Object.freeze({schema:'ql7.support.human-conversation-cell',schemaVersion:QL7_SUPPORT_HUMAN_CONVERSATION_BANK_VERSION,cellId:`human:${category}:${facet}`,category,facet,stableConceptIds:Object.freeze([`human-concept:${category}:${facet}`]),relatedTopicIds:Object.freeze(['open_subject']),disambiguationFeatures:Object.freeze(['topic','facet','current-turn-evidence']),dialogueMoves:Object.freeze([`Answer ${category}/${facet} directly.`,`Clarify only if material ambiguity remains.`,`Switch when current-turn evidence changes.`]),responseDepths:Object.freeze(['brief','normal','deep']),semanticPlanOnly:true,readyToSend:false,finalText:false,sourcePolicy:'approved-open-subject-source',contentHash:ql7StableHash(`${category}:${facet}:fallback`)})}
export function resolveQl7SupportHumanConversationCell({category='',text='',messageAct=''}={}){let facet='overview';for(const [id,re] of RULES)if(re.test(ql7Str(text))){facet=id;break}if(['humor_request','humor_followup'].includes(messageAct))facet='humor';if(messageAct==='how_to_question')facet='how_it_works';const key=`human:${ql7Str(category)||'open_subject'}:${facet}`;return INDEX.get(key)||fallbackCell(ql7Str(category)||'open_subject',facet)}
export function auditQl7SupportHumanConversationBank(){const failures=[],ids=new Set(),sigs=new Map();let material=0;for(const row of QL7_SUPPORT_HUMAN_CONVERSATION_CELLS){if(ids.has(row.cellId))failures.push(`duplicate:${row.cellId}`);ids.add(row.cellId);const substantive=row.dialogueMoves?.length>=3&&row.relatedTopicIds?.length>=1&&row.disambiguationFeatures?.length>=2;if(substantive)material++;else failures.push(`material:${row.cellId}`);const sig=(row.dialogueMoves||[]).join('|');sigs.set(sig,(sigs.get(sig)||0)+1);if(row.readyToSend!==false||row.finalText!==false)failures.push(`ready_text:${row.cellId}`)}const maxReuse=Math.max(0,...sigs.values());if(material<8192)failures.push(`cell_floor:${material}/8192`);if(maxReuse>256)failures.push(`reuse:${maxReuse}`);const categoryCount=new Set(QL7_SUPPORT_HUMAN_CONVERSATION_CELLS.map(x=>x.category||x.topicFamilyId)).size,facetCount=new Set(QL7_SUPPORT_HUMAN_CONVERSATION_CELLS.map(x=>x.facet||x.facetId)).size;return Object.freeze({ok:!failures.length,version:QL7_SUPPORT_HUMAN_CONVERSATION_BANK_VERSION,cellCount:QL7_SUPPORT_HUMAN_CONVERSATION_CELL_COUNT,materialCellCount:material,categoryCount,facetCount,uniqueDialogueSignatures:sigs.size,maxDialogueSignatureReuse:maxReuse,minimumCells:QL7_SUPPORT_HUMAN_CONVERSATION_MINIMUM_CELLS,openSubject:true,failures:Object.freeze(failures)})}
