import {ql7StableHash, ql7Str} from '../internal/text.js'
export const QL7_SUPPORT_HUMOR_MECHANISM_VERSION='5.2.4'
export const QL7_SUPPORT_HUMOR_CAPACITY_FLOOR_PER_LOCALE=10000
const MECHANISMS=Object.freeze(['benign_incongruity','misdirection','analogy','absurd_escalation','understatement','overstatement','observational','situational','callback','riddle','contrast','role_reversal','literalization','expectation_flip','safe_wordplay'])
const SETUPS=Object.freeze(['everyday-task','technology','sports','travel','office','study','weather','pets','food','transport','cinema','music','nature','business','science','space','games','home','park','camera','car','motorcycle','airplane','book'])
const PIVOTS=Object.freeze(['unexpected-rule','tiny-detail','role-swap','literal-twist','scale-shift','timing-shift','misread-goal','overcareful-check','double-check','friendly-contrast','false-start','quiet-reversal','harmless-overprecision','category-mix','callback-point','surprising-priority'])
const CLOSURES=Object.freeze(['short-reveal','contrast-reveal','question-reveal','callback-reveal','understatement-reveal','absurd-reveal','observational-reveal','role-reversal-reveal'])
export function buildQl7SupportHumorMechanismPlan({locale='en',topic='general',index=0,seed=''}={}){const i=Math.max(0,Number(index)||0),m=MECHANISMS[i%MECHANISMS.length],s=SETUPS[Math.floor(i/MECHANISMS.length)%SETUPS.length],p=PIVOTS[Math.floor(i/(MECHANISMS.length*SETUPS.length))%PIVOTS.length],c=CLOSURES[Math.floor(i/(MECHANISMS.length*SETUPS.length*PIVOTS.length))%CLOSURES.length];const body={schema:'ql7.support.humor-mechanism-plan',schemaVersion:QL7_SUPPORT_HUMOR_MECHANISM_VERSION,locale:ql7Str(locale),topic:ql7Str(topic),mechanismId:m,setupConceptId:s,pivotConceptId:p,closureConceptId:c,index:i,seedHash:ql7StableHash(seed),readyToSend:false,finalText:false};return Object.freeze({...body,planHash:ql7StableHash(JSON.stringify(body))})}
export function auditQl7SupportHumorMechanismCapacity(){const theoretical=MECHANISMS.length*SETUPS.length*PIVOTS.length*CLOSURES.length;return Object.freeze({ok:theoretical>=QL7_SUPPORT_HUMOR_CAPACITY_FLOOR_PER_LOCALE,theoreticalSemanticPlanCapacity:theoretical,requiredRealizedCapacityPerLocale:QL7_SUPPORT_HUMOR_CAPACITY_FLOOR_PER_LOCALE,proofRequirement:'actual_post_gate_realizations_required',mechanismCount:MECHANISMS.length,setupCount:SETUPS.length,pivotCount:PIVOTS.length,closureCount:CLOSURES.length})}
