import {ql7StableHash,ql7Str} from '../internal/text.js'
import {getQl7SupportLocaleProfile,QL7_SUPPORT_PROFILE_LOCALES} from '../language/locales/manifest.js'
export const QL7_SUPPORT_HUMOR_LEXICON_BANK_VERSION='17.0.0-native32'
const IDS=Object.freeze({mechanism:['benign_incongruity','misdirection','analogy','absurd_escalation','understatement','overstatement','observational','situational','callback','riddle','contrast','role_reversal','literalization','expectation_flip','safe_wordplay'],setup:['everyday-task','technology','sports','travel','office','study','weather','pets','food','transport','cinema','music','nature','business','science','space','games','home','park','camera','car','motorcycle','airplane','book'],pivot:['unexpected-rule','tiny-detail','role-swap','literal-twist','scale-shift','timing-shift','misread-goal','overcareful-check','double-check','friendly-contrast','false-start','quiet-reversal','harmless-overprecision','category-mix','callback-point','surprising-priority'],closure:['short-reveal','contrast-reveal','question-reveal','callback-reveal','understatement-reveal','absurd-reveal','observational-reveal','role-reversal-reveal']})
const BANK=Object.freeze({mechanism:'explanationStrategyBank',setup:'lexicalAliasBank',pivot:'discourseRelationBank',closure:'gratitudeBank'})
function atom(locale,kind,id){const profile=getQl7SupportLocaleProfile(locale),rows=profile.banks?.[BANK[kind]]||[],ids=IDS[kind]||[],idx=Math.max(0,ids.indexOf(id)),row=rows[idx%Math.max(1,rows.length)],value=ql7Str(row?.lexicalChoices?.[0]);if(!value){const e=new Error(`ql7_humor_native_atom_missing:${locale}:${kind}:${id}`);e.code='ql7_humor_native_atom_missing';throw e}return value}
export function getQl7SupportHumorLexeme(locale='en',kind='',id=''){return atom(ql7Str(locale)||'en',kind,id)}
export function buildQl7SupportHumorLexicalPlan({locale='en',mechanismId='',setupConceptId='',pivotConceptId='',closureConceptId=''}={}){const language=ql7Str(locale)||'en';if(!QL7_SUPPORT_PROFILE_LOCALES.includes(language)){const e=new Error(`ql7_humor_locale_unsupported:${language}`);e.code='ql7_humor_locale_unsupported';throw e}const body={schema:'ql7.support.humor-lexical-plan',schemaVersion:QL7_SUPPORT_HUMOR_LEXICON_BANK_VERSION,locale:language,sourceLocale:language,mechanism:atom(language,'mechanism',mechanismId),setup:atom(language,'setup',setupConceptId),pivot:atom(language,'pivot',pivotConceptId),closure:atom(language,'closure',closureConceptId),externalLocalizationRequired:false,readyToSend:false,finalText:false};return Object.freeze({...body,planHash:ql7StableHash(JSON.stringify(body))})}
export function auditQl7SupportHumorLexiconBank(){const failures=[];for(const locale of QL7_SUPPORT_PROFILE_LOCALES)for(const [kind,ids] of Object.entries(IDS))for(const id of ids){try{if(!atom(locale,kind,id))failures.push(`blank:${locale}:${kind}:${id}`)}catch(e){failures.push(String(e?.message||e))}}return Object.freeze({schema:'ql7.support.humor-lexicon-bank-audit',schemaVersion:QL7_SUPPORT_HUMOR_LEXICON_BANK_VERSION,ok:!failures.length,nativeLocaleCount:QL7_SUPPORT_PROFILE_LOCALES.length,mechanismCount:IDS.mechanism.length,setupCount:IDS.setup.length,pivotCount:IDS.pivot.length,closureCount:IDS.closure.length,compositionalCapacity:IDS.mechanism.length*IDS.setup.length*IDS.pivot.length*IDS.closure.length,externalLocalizationRequiredFor:0,failures:Object.freeze(failures)})}
