import {ql7StableHash, ql7Str} from '../internal/text.js'
import {getQl7SupportPublicFigureFactPolicy} from './publicFigureFactOntology.js'
export const QL7_SUPPORT_PUBLIC_FIGURE_SOURCE_RESOLVER_VERSION='5.2.4'
export const QL7_SUPPORT_PUBLIC_FIGURE_SOURCE_RESOLVER_OWNER_ID='ql7-support.public-figure-source-resolver'
const VERIFIED_STATES=new Set(['verified','confirmed','available']);const CONFLICT_STATES=new Set(['contradictory','conflict','source_conflict']);const DEFAULT_MAX_AGE_MS=24*60*60*1000
const iso=(value,fallback)=>{const d=new Date(value||fallback);return Number.isFinite(d.getTime())?d.toISOString():new Date(fallback).toISOString()};const time=(value)=>{const n=new Date(value||0).getTime();return Number.isFinite(n)?n:0};const str=(value)=>ql7Str(value).trim()
function evaluateSourceReceipt(sourceReceipt={},nowMs=Date.now(),maxAgeMs=DEFAULT_MAX_AGE_MS){const state=str(sourceReceipt?.status||sourceReceipt?.state).toLowerCase(),sourceRef=str(sourceReceipt?.sourceRef||sourceReceipt?.sourceId),receiptId=str(sourceReceipt?.receiptId||sourceReceipt?.id),verifiedAt=time(sourceReceipt?.verifiedAt||sourceReceipt?.checkedAt),explicitExpiry=time(sourceReceipt?.validUntil||sourceReceipt?.expiresAt),ageMs=verifiedAt?Math.max(0,nowMs-verifiedAt):Number.POSITIVE_INFINITY,expired=explicitExpiry?explicitExpiry<nowMs:ageMs>maxAgeMs,conflict=CONFLICT_STATES.has(state)||sourceReceipt?.contradictory===true,verified=VERIFIED_STATES.has(state)&&Boolean(sourceRef)&&Boolean(receiptId)&&!expired&&!conflict;return Object.freeze({state,sourceRef,receiptId,verifiedAt,ageMs:Number.isFinite(ageMs)?ageMs:null,expired,conflict,verified})}
export function resolveQl7SupportPublicFigureSourceRequirement({figure=null,questionKind='stable_identity',sourceReceipt=null,now=new Date().toISOString(),maxAgeMs=DEFAULT_MAX_AGE_MS}={}){
 const nowIso=iso(now,new Date().toISOString()),nowMs=time(nowIso),kind=str(questionKind).toLowerCase()||'stable_identity',policy=getQl7SupportPublicFigureFactPolicy(kind),sourceRequired=policy.sourceRequired===true,currentSensitive=policy.currentSensitive===true||figure?.currentRoleRequiresFreshSource===true&&kind.startsWith('current_'),source=evaluateSourceReceipt(sourceReceipt||{},nowMs,Math.max(60_000,Number(maxAgeMs)||DEFAULT_MAX_AGE_MS))
 let state=sourceRequired?'unavailable_public_source':'stable_identity_only',answerClaimAllowed=!sourceRequired,requiresClarification=false
 if(sourceRequired){if(source.conflict){state='source_conflict';answerClaimAllowed=false;requiresClarification=true}else if(source.verified){state=currentSensitive?'verified_current':'verified_public_fact';answerClaimAllowed=true}else if(source.expired&&source.sourceRef){state=currentSensitive?'stale_current_source':'stale_public_source';answerClaimAllowed=false}else{state=currentSensitive?'unavailable_current':'unavailable_public_source';answerClaimAllowed=false}}
 const body={schema:'ql7.support.public-figure-source-resolution',schemaVersion:QL7_SUPPORT_PUBLIC_FIGURE_SOURCE_RESOLVER_VERSION,ownerId:QL7_SUPPORT_PUBLIC_FIGURE_SOURCE_RESOLVER_OWNER_ID,personId:str(figure?.personId),canonicalName:str(figure?.canonicalName),questionKind:kind,sourceRequired,currentSensitive,state,
  answerClaimAllowed,answerCurrentClaimAllowed:answerClaimAllowed&&!currentSensitive||answerClaimAllowed&&currentSensitive,answerDetailedClaimAllowed:answerClaimAllowed,requiresClarification,stableIdentityClaimAllowed:Boolean(figure?.personId||figure?.canonicalName),sourceReceiptId:source.receiptId,sourceState:source.state,sourceVerified:source.verified,sourceExpired:source.expired,sourceConflict:source.conflict,checkedAt:source.verifiedAt?new Date(source.verifiedAt).toISOString():nowIso,freshness:Object.freeze({maxAgeMs:Math.max(60_000,Number(maxAgeMs)||DEFAULT_MAX_AGE_MS),ageMs:source.ageMs,explicitExpiry:Boolean(time(sourceReceipt?.validUntil||sourceReceipt?.expiresAt))}),unknownClaimMustRemainUnknown:sourceRequired&&!answerClaimAllowed,unknownCurrentFactMustRemainUnknown:currentSensitive&&!answerClaimAllowed,publicOnly:true,privateDataForbidden:true,sourceHash:ql7StableHash(JSON.stringify({sourceRef:source.sourceRef,state:source.state,receiptId:source.receiptId,verifiedAt:source.verifiedAt,expired:source.expired,conflict:source.conflict}))}
 const receiptHash=ql7StableHash(JSON.stringify(body));return Object.freeze({...body,receiptId:`public-figure-source:${receiptHash}`,receiptHash})
}
export function auditQl7SupportPublicFigureSourceResolver(){const figure={personId:'p1',canonicalName:'Example',currentSensitive:true,currentRoleRequiresFreshSource:true},now='2026-08-18T12:00:00.000Z',freshReceipt={receiptId:'r1',sourceRef:'approved:public',status:'verified',verifiedAt:'2026-08-18T11:30:00.000Z'};const fresh=resolveQl7SupportPublicFigureSourceRequirement({figure,questionKind:'current_role',now,sourceReceipt:freshReceipt}),stableDetailed=resolveQl7SupportPublicFigureSourceRequirement({figure,questionKind:'known_for',now,sourceReceipt:freshReceipt}),missing=resolveQl7SupportPublicFigureSourceRequirement({figure,questionKind:'current_role',now}),identity=resolveQl7SupportPublicFigureSourceRequirement({figure,questionKind:'stable_identity',now});const failures=[];if(!fresh.answerCurrentClaimAllowed)failures.push('fresh_current');if(!stableDetailed.answerDetailedClaimAllowed)failures.push('detailed_source');if(missing.answerCurrentClaimAllowed||missing.unknownCurrentFactMustRemainUnknown!==true)failures.push('missing_current');if(!identity.stableIdentityClaimAllowed||identity.sourceRequired)failures.push('identity');return Object.freeze({ok:failures.length===0,fresh,stableDetailed,missing,identity,failures:Object.freeze(failures)})}
