import {buildQl7SupportScenario} from './scenarioCatalog.js'
import {buildQl7SupportBranchScenario} from './branchScenarioCatalog.js'
import {getQl7SupportTopicLabel} from '../ecosystemCatalog.js'
const OP_BRANCH=Object.freeze({greeting:'dialogue.greeting',invite:'dialogue.small-talk',thanks:'dialogue.gratitude',farewell:'dialogue.farewell',wellbeing:'dialogue.wellbeing',noise:'clarification.noise-recovery',clarify:'clarification.domain-ambiguity',abstain:'clarification.domain-ambiguity',emotion:'dialogue.emotional-support',socialBoundary:'dialogue.social-boundary',identity:'dialogue.identity',reportedSpeech:'dialogue.reported-speech',targetClarify:'safety.insult-clarification',denialRepair:'safety.denial-repair',boundary:'safety.direct-insult-boundary',crisis:'safety.crisis',threat:'safety.credible-threat',business:'relationship.collect-brief',contact:'relationship.collect-contact',handoff:'relationship.handoff-without-contact',noNewFact:'dialogue.no-new-fact',incident:'incident.qcoin-discrepancy',unavailable:'fact.unavailable',verified:'fact.verified',empty:'fact.verified-empty',planned:'knowledge.planned-status',knowledge:'knowledge.answer',howTo:'knowledge.answer',smallTalk:'dialogue.small-talk',aiQuota:'fact.ai-quota-exhausted',aiDisclaimer:'fact.ai-recommendation',humor:'dialogue.humor',topicRecall:'dialogue.topic-recall'})
const EVENT_TOPIC=(id)=>id.startsWith('vip')?'vip':id.startsWith('ads')?'ads_campaigns':id.startsWith('qcoin')?'qcoin':id.startsWith('metamarket')?'metamarket':id.includes('payment')?'payments':'moderation'
export function buildCapabilityScenario(capability={},index=0,{locale='en',seed='capability'}={}){const id=String(capability.capabilityId||'')
 if(id.startsWith('knowledge.domain.')){const domain=id.slice('knowledge.domain.'.length),label=getQl7SupportTopicLabel(domain,locale)||domain;const base=buildQl7SupportScenario(index,{profile:'knowledge-32',locale,seed:`${seed}:${id}`});return Object.freeze({...base,id:`cap:${id}:${locale}:${index}`,input:`${label}: explain purpose, current status, limits and how to use it`,analysis:{topic:domain,messageAct:'how_to_question'},baseAnalysisTrust:true,expected:{...(base.expected||{}),topic:domain,noAdapter:true},labCapabilityId:id})}
 if(id.startsWith('locale.')){const target=id.split('.')[1]||locale;const base=buildQl7SupportScenario(index,{profile:'provider-language-quality',locale:target,seed:`${seed}:${id}`});return Object.freeze({...base,id:`cap:${id}:${target}:${index}`,labCapabilityId:id})}
 if(id.startsWith('realization.operation.')){const op=id.slice('realization.operation.'.length),branch=OP_BRANCH[op]||'dialogue.small-talk';const row=buildQl7SupportBranchScenario(branch,index,{locale,seed:`${seed}:${id}`});return Object.freeze({...row,id:`cap:${id}:${locale}:${index}`,expectedOperationId:op,labCapabilityId:id})}
 if(id.startsWith('event.')){const eventType=id.slice('event.'.length),topic=EVENT_TOPIC(eventType);const base=buildQl7SupportScenario(index,{profile:'events',locale,seed:`${seed}:${id}`});return Object.freeze({...base,id:`cap:${id}:${locale}:${index}`,eventType,analysis:{topic,messageAct:'event_notification'},expected:{...(base.expected||{}),topic},labCapabilityId:id})}
 if(id==='presentation.tables'||id==='read.adapter-receipts')return Object.freeze({...buildQl7SupportBranchScenario('fact.verified',index,{locale,seed}),labCapabilityId:id})
 if(id==='presentation.badges'||id==='presentation.title'||id==='presentation.actions-cta')return Object.freeze({...buildQl7SupportBranchScenario('knowledge.answer',index,{locale,seed}),labCapabilityId:id})
 if(id.startsWith('memory.'))return Object.freeze({...buildQl7SupportBranchScenario('dialogue.topic-recall',index,{locale,seed}),labCapabilityId:id})
 if(id.startsWith('contact.'))return Object.freeze({...buildQl7SupportBranchScenario(id.includes('consent')?'relationship.collect-contact':'relationship.handoff-with-contact',index,{locale,seed}),labCapabilityId:id})
 if(id.startsWith('operator.')&&!id.includes('smtp-truth'))return Object.freeze({...buildQl7SupportBranchScenario('relationship.handoff-without-contact',index,{locale,seed}),labCapabilityId:id})
 if(id.startsWith('safety.'))return Object.freeze({...buildQl7SupportBranchScenario(id.includes('crisis')?'safety.crisis':id.includes('quote')?'safety.insult-clarification':'safety.credible-threat',index,{locale,seed}),labCapabilityId:id})
 if(id.startsWith('delivery.'))return Object.freeze({...buildQl7SupportBranchScenario('fact.verified',index,{locale,seed}),labCapabilityId:id})
 const profile=capability.scenarioFamily==='locale-purity'?'languages':capability.scenarioFamily==='events'?'events':capability.scenarioFamily?.includes('human')?'conversation':'mixed';return Object.freeze({...buildQl7SupportScenario(index,{profile,locale,seed:`${seed}:${id}`}),id:`cap:${id}:${locale}:${index}`,labCapabilityId:id})}
