import crypto from 'node:crypto'
import {executeQl7SupportProductionTurn, finalizeQl7SupportProductionDelivery} from '../runtime/productionTurn.js'
import {commitQl7SupportFinalDelivery} from '../runtime/deliveryCommitCoordinator.js'
import {validateQl7SupportFinalDeliveryReceipt} from '../contracts/finalDeliveryReceipt.js'
import {evaluateQl7SupportContractOracle, evaluateQl7SupportDeterministicSemanticConsistency} from './DeterministicContractOracle.js'
import {localizeQl7SupportFinalDelivery} from '../language/finalDeliveryLocalization.js'
const SIMULATION_DELIVERY_KEY='ql7-support-non-production-delivery-key.1'
const SIMULATION_DELIVERY_KEY_ID='delivery-key:non-production.1'
function h(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')}
function baseReceipt(topic,result,resultKind='verified'){const executed=resultKind!=='unavailable';return{ id:`fixture:${topic}:${h(result).slice(0,16)}`,adapter:topic,executed,sourceType:'synthetic_fixture',source:`fixture:${topic}`,actorScope:'self',resultKind,result:executed?result:null,error:executed?undefined:'fixture_unavailable',durationMs:1,writeCount:0,evidenceHash:h(result),checkedAt:executed?'2026-07-31T00:00:00.000Z':undefined}}
function receipt(topic,state='verified',eventType=''){
 if(state==='unavailable')return baseReceipt(topic,null,'unavailable');if(state==='inconsistent')return baseReceipt(topic,{expected:'active',observed:'mismatch'},'inconsistent')
 if(topic==='qcoin')return baseReceipt(topic,{balance:eventType==='qcoin_credit_failed'?1250:1350,available:eventType==='qcoin_credit_failed'?1200:1300,pending:eventType==='qcoin_credit_failed'?50:50,eventType,status:eventType==='qcoin_credit_failed'?'credit_failed':'verified',amount:eventType.startsWith('qcoin_credit')?100:undefined,ledger:[{type:'credit',amount:100,status:eventType==='qcoin_credit_failed'?'failed':'completed',createdAt:'2026-07-30T10:00:00Z'},{type:'debit',amount:25,status:'completed',createdAt:'2026-07-30T12:00:00Z'}]},state==='verified_empty'?'verified_empty':'verified')
 if(topic==='vip'){const days=Number((eventType.match(/vip_expiry_(\d)d/u)||[])[1]||0);return baseReceipt(topic,{active:eventType!=='vip_expired'&&state!=='verified_empty',status:eventType==='vip_expired'?'expired':days?'expires_soon':'inactive',tier:eventType==='vip_expired'?'VIP':'VIP',daysLeft:days,expiresAt:days?`2026-08-0${days}T00:00:00.000Z`:null,eventType,benefits:eventType==='vip_expired'?[]:['AI Box 24/7','priority support']},state==='verified_empty'?'verified_empty':'verified')}
 if(topic==='ads_packages')return baseReceipt(topic,{packageName:'ELITE',status:eventType==='ads_expired'?'expired':eventType.startsWith('ads_expiry_')?'expires_soon':'active',daysLeft:Number((eventType.match(/ads_expiry_(\d)d/u)||[])[1]||0),usedSlots:5,slotLimit:5,activeCampaignCount:0,eventType},state==='verified_empty'?'verified_empty':'verified')
 if(topic==='ads_campaigns')return baseReceipt(topic,{packageName:'ELITE',status:eventType==='ads_expired'?'expired':eventType.startsWith('ads_expiry_')?'expires_soon':'active',daysLeft:Number((eventType.match(/ads_expiry_(\d)d/u)||[])[1]||0),campaigns:[{name:'Samsung S26 Ultra',status:'completed',views:10000,clicks:250,ctr:.025,spend:42,regions:['Paris','Odesa'],updatedAt:'2026-07-31T00:00:00Z'}],eventType},state==='verified_empty'?'verified_empty':'verified')
 if(topic==='payments')return baseReceipt(topic,{status:'completed',amount:25,currency:'USDT'},state)
 if(topic==='exchange_ai')return baseReceipt(topic,state==='quota_exhausted'?{symbol:'BTCUSDT',timeframe:'5m',quotaState:'exhausted',canAnalyze:false,usedSec:1800,remainingSec:0,limitSec:1800,upgradeRoute:'/subscribe',sourceRoute:'/api/aiquota/usage',disclaimer:'Educational analytics only. This is not financial advice.'}:{symbol:'BTCUSDT',timeframe:'5m',price:64250.12,action:'HOLD / WAIT_CONFIRMATION',confidence:72,entry:64120,sl:63380,tp1:64980,tp2:65840,quotaState:'vip',canAnalyze:true,remainingSec:86400,limitSec:86400,sourceRoute:'/api/aiquota/usage + /exchange#ql7-exchange-ai-box',marketRoute:'/api/crypto/market',reasons:['trend compression','volume confirmation pending','risk kept below invalidation'],disclaimer:'Educational analytics only. This is not financial advice.'},'verified')
 if(topic==='profile'||topic==='rating')return baseReceipt(topic,{nickname:'Simulation User',locale:'ru',createdAt:'2025-01-01T00:00:00Z',lastActivityAt:'2026-07-31T00:00:00Z',activity:{posts:12,topics:4,likes:86,followers:10,following:7},rating:{value:74,confidence:83,band:'strong'}},state)
 if(topic==='forum'||topic==='forum_feed'||topic==='forum_threads')return baseReceipt(topic,{posts:12,topics:4,likes:86,followers:10,following:7},state)
 if(topic==='metamarket')return baseReceipt(topic,{ownedItems:3,events:9,recentEvents:[{type:'purchase',item:'QL7 item'}]},state)
 if(topic==='telegram')return baseReceipt(topic,{linked:true,links:[{telegramId:'7000000001',accountId:'0x1111…111111',status:'active'}]},state)
 return baseReceipt(topic,{status:'verified',value:1},state)
}
export async function executeQl7SupportScenario(scenario={},context={}){
 const receipts=[];if(scenario.expected?.noAdapter!==true&&scenario.fixtureTopic)receipts.push(receipt(scenario.fixtureTopic,scenario.fixtureState||'verified',scenario.eventType||''));if(scenario.expected?.noAdapter!==true)for(const item of scenario.fixtureReceipts||[])receipts.push(receipt(item.topic,item.state||'verified',item.eventType||scenario.eventType||''));const contextMemoryGraph=context?.memoryGraph&&Object.keys(context.memoryGraph).length?context.memoryGraph:null;const baseAnalysis=scenario.eventType?{messageAct:'event_notification',topic:scenario.eventType.startsWith('vip')?'vip':scenario.eventType.startsWith('ads_expiry')||scenario.eventType==='ads_expired'?'ads_packages':scenario.eventType.startsWith('ads')?'ads_campaigns':scenario.eventType.startsWith('qcoin')?'qcoin':scenario.eventType.startsWith('metamarket')?'metamarket':'moderation'}:(scenario.analysis||{});if(scenario.eventType&&!receipts.length)receipts.push(receipt(baseAnalysis.topic,'verified',scenario.eventType))
 const syntheticAccountId=String(scenario.userId||`simulation:${scenario.id}`)
 const scenarioActor=scenario.actor&&typeof scenario.actor==='object'&&String(scenario.actor.canonicalAccountId||scenario.actor.accountId||scenario.actor.userId||'').trim()?scenario.actor:{valid:true,authMode:'laboratory_verified_actor',canonicalAccountId:syntheticAccountId,aliases:[syntheticAccountId],accountIdMasked:'0x1111…111111',locale:scenario.locale,actorReceiptId:`actor-receipt:simulation:${h(syntheticAccountId).slice(0,32)}`}
 const turn={mode:'simulation',requestId:scenario.id,conversationId:scenario.conversationId||scenario.id,userTurnId:`user:${scenario.id}`,caseId:`case:${scenario.userId||'simulation'}`,selectedLocale:scenario.locale||'en',originalText:scenario.input,priorMemoryGraph:contextMemoryGraph||scenario.priorMemoryGraph||{},adapterReceipts:receipts,analysis:baseAnalysis,baseAnalysisTrust:Boolean(scenario.eventType||scenario.analysis),route:scenario.route||{},actor:scenarioActor,verifiedActorId:String(scenarioActor.canonicalAccountId||scenarioActor.accountId||scenarioActor.userId),actorReceiptId:String(scenarioActor.actorReceiptId||''),profile:scenario.profile||{},contacts:scenario.contacts||null,forceOperatorCase:scenario.forceOperatorCase===true,now:scenario.now||'2026-07-31T00:00:00.000Z',seed:scenario.seed||scenario.id,browserTimeZone:scenario.browserTimeZone,priorNoveltyLedger:context?.noveltyLedger||scenario.priorNoveltyLedger||null,openCases:scenario.openCases||[],runtimeCapability:scenario.runtimeCapability||null,entryEvent:scenario.entryEvent||null,eventEnvelope:scenario.eventEnvelope||undefined,contextualFollowup:scenario.contextualFollowup===true,productionQuestionCode:scenario.productionQuestionCode||'',clientMutationId:scenario.clientMutationId||`simulation:${scenario.id}`,routeId:scenario.routeId||'lab.simulation.turn',sourceRouteId:scenario.sourceRouteId||scenario.routeId||'lab.simulation.turn',sourceSurfaceId:scenario.sourceSurfaceId||'laboratory.production-parity',neuralProvider:context.neuralProvider||scenario.neuralProvider||null,neuralProviderOptions:context.neuralProviderOptions||scenario.neuralProviderOptions||{},requestBoundary:scenario.requestBoundary||{originDecisionReceiptId:`origin-receipt:simulation:${h(scenario.id).slice(0,24)}`,rateLimitBucketId:`rate-bucket:simulation:${h(scenario.id).slice(0,24)}`,idempotencyKeyHash:h(scenario.clientMutationId||`simulation:${scenario.id}`)},localizeFinalDelivery:(payload)=>localizeQl7SupportFinalDelivery({...payload,translate:context.translateProvider||scenario.translateProvider})}
 const productionTurn=await executeQl7SupportProductionTurn(turn)
 const result=productionTurn.runtime
 const deliveryOverrides=scenario.productionDeliveryOverrides||{}
 const preparedDelivery=Object.keys(deliveryOverrides).length
  ?finalizeQl7SupportProductionDelivery({productionTurn,...deliveryOverrides})
  :productionTurn.delivery
 const productionDelivery=await commitQl7SupportFinalDelivery({
 candidate:preparedDelivery,
  runtime:result,
  signingKey:context.deliverySigningKey||SIMULATION_DELIVERY_KEY,
  keyId:context.deliveryKeyId||SIMULATION_DELIVERY_KEY_ID,
  transport:context.deliveryTransport||(async(candidate)=>({
   messageId:`simulation:${h({scenarioId:scenario.id,candidateHash:candidate.candidateHash}).slice(0,24)}`,
   providerReceiptId:'simulation-transport.1',
   transportEvidence:{scenarioId:scenario.id,candidateHash:candidate.candidateHash},
  })),
 })
 const userVisibleSurface=productionDelivery.surface
 const userVisibleText=productionDelivery.text
 const userVisibleActions=userVisibleSurface.actions||userVisibleSurface.options||[]
 const observedResult=Object.freeze({...result,text:userVisibleText,surface:userVisibleSurface,composerPolicy:productionDelivery.composerPolicy,stateEvents:productionDelivery.stateEvents,finalMessageId:productionDelivery.finalMessageId})
 const baseOracle=evaluateQl7SupportContractOracle({scenario,result:observedResult,productionDelivery})
 const canonical=evaluateQl7SupportDeterministicSemanticConsistency(observedResult)
 const deliveryFailures=[]
 const receiptCheck=validateQl7SupportFinalDeliveryReceipt(productionDelivery.receipt,{signingKey:context.deliverySigningKey||SIMULATION_DELIVERY_KEY,requireCommitted:true})
 if(!productionDelivery.textHash||!productionDelivery.surfaceHash)deliveryFailures.push(Object.freeze({code:'production_delivery_hash_missing',severity:'critical'}))
 if(productionDelivery.text!==userVisibleText)deliveryFailures.push(Object.freeze({code:'production_delivery_text_mismatch',severity:'critical'}))
 if(!receiptCheck.ok)for(const code of receiptCheck.failures)deliveryFailures.push(Object.freeze({code:`delivery_receipt:${code}`,severity:'critical'}))
 const deliveryParity=Object.freeze({ok:deliveryFailures.length===0,failures:Object.freeze(deliveryFailures),textHash:productionDelivery.textHash,surfaceHash:productionDelivery.surfaceHash,actionIds:productionDelivery.actionIds,receiptHash:productionDelivery.receipt.receiptHash,commitState:productionDelivery.receipt.commitState})
 const oracle=Object.freeze({...baseOracle,ok:baseOracle.ok&&canonical.ok&&deliveryParity.ok,failures:Object.freeze([...(baseOracle.failures||[]),...(canonical.failures||[]),...deliveryFailures]),canonical,productionDeliveryParity:deliveryParity})
 return Object.freeze({scenario,turn:productionTurn.runtimeInput,result:observedResult,productionTurn,productionDelivery,oracle,evidence:{input:scenario.input,normalization:result.analysis.normalization,memoryBefore:turn.priorMemoryGraph||null,memoryAfter:result.memoryGraph,analysis:result.analysis,neuralUnderstandingReceipt:result.analysis.neuralUnderstandingReceipt||null,route:result.effectiveRoute,contentPlan:result.contentPlan,receipts:result.adapterReceipts,text:userVisibleText,surface:userVisibleSurface,svgAssetId:userVisibleSurface.primarySvg?.assetId,badges:userVisibleSurface.badges||[],tableSchemas:(userVisibleSurface.tables||[]).map(t=>t.schema),tables:userVisibleSurface.tables||[],actions:userVisibleActions,composerPolicy:productionDelivery.composerPolicy,stateEvents:productionDelivery.stateEvents,operatorCase:result.operatorCase,critic:result.critic,qualityGate:productionDelivery.qualityGate,scopeReceipt:result.scopeReceipt,semanticPlan:result.semanticPlan,memoryBefore:result.memoryBefore,memoryAfter:result.memoryGraph,productionDelivery,deliveryReceipt:productionDelivery.receipt,productionRuntimeInput:productionTurn.runtimeInput,oracle,finalMessageId:productionDelivery.finalMessageId}})
}
export { receipt as buildQl7SupportSimulationReceipt }
