import fs from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'
import crypto from 'node:crypto'
export const QL7_SUPPORT_MATERIALITY_ORACLE_VERSION='5.4.2-canonical-independent'
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..')
const norm=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().replace(/[\u200B-\u200D\uFEFF]/gu,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim()
const sha=v=>crypto.createHash('sha256').update(typeof v==='string'||Buffer.isBuffer(v)?v:JSON.stringify(v)).digest('hex')
function dirDocs(dir,re=/\.json$/u){const base=path.join(ROOT,dir);return fs.readdirSync(base).filter(x=>re.test(x)).sort().map(name=>({name,path:path.join(base,name),doc:JSON.parse(fs.readFileSync(path.join(base,name),'utf8'))}))}
function universeEvidence(files,rows){return {inputFileCount:files.length,inputRowCount:rows.length,universeHash:sha(files.map(f=>`${f.name}\0${sha(fs.readFileSync(f.path))}`).join('\n'))}}
function independentLanguage(){const failures=[],locales={},files=dirDocs('lib/ql7-support/language/reviewedMaterial'),all=[];for(const f of files){const d=f.doc,rows=d.rows||[];all.push(...rows);const unique=new Set(rows.map(r=>norm(r.surface)).filter(Boolean)),prov=rows.filter(r=>r.mutationDerived===false&&r.provenance?.sourceRef&&r.provenance?.kind).length;locales[d.locale]={rows:rows.length,normalizedDistinct:unique.size,provenanceComplete:prov};if(rows.length<1500||unique.size<1500)failures.push(`language:${d.locale}:${rows.length}/${unique.size}`);if(prov!==rows.length)failures.push(`language_provenance:${d.locale}:${prov}/${rows.length}`)}return {ok:!failures.length,localeCount:Object.keys(locales).length,locales,...universeEvidence(files,all),measuredNumerator:Object.values(locales).filter(x=>x.normalizedDistinct>=1500&&x.provenanceComplete===x.rows).length,measuredDenominator:Object.keys(locales).length,failures}}
function independentCrisis(){const failures=[],locales={},files=dirDocs('lib/ql7-support/safety/crisisReviewed'),all=[];for(const f of files){const d=f.doc,rows=d.rows||[];all.push(...rows);const unique=new Set(rows.map(r=>norm(r.surface)).filter(Boolean)),prov=rows.filter(r=>r.mutationDerived===false&&r.provenance?.sourceRef).length;locales[d.locale]={rows:rows.length,normalizedDistinct:unique.size,provenanceComplete:prov};if(rows.length<64||unique.size<64)failures.push(`crisis:${d.locale}:${rows.length}/${unique.size}`);if(prov!==rows.length)failures.push(`crisis_provenance:${d.locale}`)}return {ok:!failures.length,localeCount:Object.keys(locales).length,totalDistinct:Object.values(locales).reduce((n,x)=>n+x.normalizedDistinct,0),locales,...universeEvidence(files,all),measuredNumerator:Object.values(locales).filter(x=>x.normalizedDistinct>=64&&x.provenanceComplete===x.rows).length,measuredDenominator:Object.keys(locales).length,failures}}
function independentGeneral(){const files=dirDocs('lib/ql7-support/knowledge/general-human',/^shard-\d+\.json$/u),nodes=files.flatMap(d=>d.doc.nodes||[]),failures=[];let material=0,sourceRouteBound=0;for(const n of nodes){const substantive=Array.isArray(n.definitions)&&n.definitions.some(Boolean)&&Array.isArray(n.relations)&&n.relations.length&&Array.isArray(n.examples)&&n.examples.length&&Array.isArray(n.sourceRefs)&&n.sourceRefs.length&&String(n.sourcePolicy||'').length;if(substantive)material++;else if(failures.length<100)failures.push(`node:${n.conceptId}`);if((n.sourceRefs||[]).some(r=>String(r).startsWith('source-route:open-human:canonical:')))sourceRouteBound++}if(material<12000)failures.push(`general_floor:${material}`);if(sourceRouteBound<12000)failures.push(`general_source_route_floor:${sourceRouteBound}`);return {ok:!failures.length,nodeCount:nodes.length,materialNodeCount:material,sourceRouteBoundCount:sourceRouteBound,...universeEvidence(files,nodes),measuredNumerator:material,measuredDenominator:nodes.length,failures:failures.slice(0,100)}}
function independentCells(){const files=dirDocs('lib/ql7-support/knowledge/human-conversation'),cells=files.flatMap(d=>d.doc.cells||[]),failures=[],sigs=new Map();let material=0;for(const c of cells){const substantive=c.dialogueMoves?.length>=3&&c.relatedTopicIds?.length>=1&&c.disambiguationFeatures?.length>=2&&c.likelyFollowups?.length>=1;if(substantive)material++;else if(failures.length<100)failures.push(`cell:${c.cellId}`);const sig=norm((c.dialogueMoves||[]).join('|'));sigs.set(sig,(sigs.get(sig)||0)+1)}const maxReuse=Math.max(0,...sigs.values());if(material<8192)failures.push(`cell_floor:${material}`);if(maxReuse>256)failures.push(`cell_reuse:${maxReuse}`);return {ok:!failures.length,cellCount:cells.length,materialCellCount:material,uniqueDialogueSignatures:sigs.size,maxDialogueSignatureReuse:maxReuse,...universeEvidence(files,cells),measuredNumerator:material,measuredDenominator:cells.length,failures:failures.slice(0,100)}}
function independentDialect(){const files=dirDocs('lib/ql7-support/language/dialectProfiles'),all=[],failures=[];let count=0,minMaterial=1e9;for(const f of files){const d=f.doc,ps=d.profiles||[];all.push(...ps);count+=ps.length;if(ps.length<4)failures.push(`profiles:${d.locale}`);for(const p of ps){const material=(p.materialExamples?.length||0)+(p.lexicalPatterns?.length||0)+(p.morphologyNotes?.length||0)+(p.phoneticVoiceLikePatterns?.length||0)+(p.slangAliases?.length||0)+(p.safeNegativeExamples?.length||0);minMaterial=Math.min(minMaterial,material);if(material<20)failures.push(`dialect_material:${p.dialectId}:${material}`)}}if(count<256)failures.push(`dialect_floor:${count}`);return {ok:!failures.length,profileCount:count,minMaterial:minMaterial===1e9?0:minMaterial,...universeEvidence(files,all),measuredNumerator:all.filter(p=>((p.materialExamples?.length||0)+(p.lexicalPatterns?.length||0)+(p.morphologyNotes?.length||0)+(p.phoneticVoiceLikePatterns?.length||0)+(p.slangAliases?.length||0)+(p.safeNegativeExamples?.length||0))>=20).length,measuredDenominator:all.length,failures}}
function independentComposer(){const files=dirDocs('lib/composer-safety/reviewedMaterial'),all=[],locales={},failures=[];for(const f of files){const d=f.doc,rows=d.rows||[];all.push(...rows);const unique=new Set(rows.map(r=>norm(r.surface)).filter(Boolean));locales[d.locale]={rows:rows.length,normalizedDistinct:unique.size};if(unique.size<384)failures.push(`composer:${d.locale}:${unique.size}`)}return {ok:!failures.length,localeCount:Object.keys(locales).length,locales,...universeEvidence(files,all),measuredNumerator:Object.values(locales).filter(x=>x.normalizedDistinct>=384).length,measuredDenominator:Object.keys(locales).length,failures}}
function independentFigures(){const files=dirDocs('lib/ql7-support/knowledge/public-figures/substantiveFacts',/^shard-\d+\.json$/u),profiles=files.flatMap(d=>d.doc.profiles||[]),failures=[],metadata=new Set(['canonical_name','public_identity','notability_domain','source_lookup_key','catalog_rank']);let substantive4=0,explicitInsufficient=0,selfCatalogOnly=0,privateFacts=0,sourceBoundFacts=0;for(const p of profiles){const facts=(p.substantiveStableFacts||[]).filter(f=>!metadata.has(f.factType)&&f.value&&f.sourceRefs?.length);if(facts.length>=4)substantive4++;else if(p.substantiveSourceStatus==='insufficient_public_stable_facts'||p.sourceLookupRequired===true)explicitInsufficient++;else if(failures.length<100)failures.push(`figure_unaccounted:${p.personId}`);for(const f of facts){sourceBoundFacts++;if((f.sourceRefs||[]).every(x=>String(x).startsWith('catalog:')))selfCatalogOnly++;if(f.publicOnly!==true)privateFacts++}}if(profiles.length<1900)failures.push(`figure_floor:${profiles.length}`);if(selfCatalogOnly)failures.push(`self_catalog_substantive:${selfCatalogOnly}`);if(privateFacts)failures.push(`private_substantive:${privateFacts}`);const accountingPct=profiles.length?Number((((substantive4+explicitInsufficient)/profiles.length)*100).toFixed(6)):0,richPct=profiles.length?Number(((substantive4/profiles.length)*100).toFixed(6)):0;if(accountingPct!==100)failures.push(`profile_accounting:${accountingPct}`);return {ok:!failures.length,profileCount:profiles.length,substantiveFourCount:substantive4,explicitInsufficientCount:explicitInsufficient,substantiveRichCoveragePct:richPct,profileAccountingPct:accountingPct,selfCatalogOnlySubstantiveFacts:selfCatalogOnly,privateFacts,sourceBoundFactCount:sourceBoundFacts,...universeEvidence(files,profiles),measuredNumerator:substantive4,measuredDenominator:profiles.length,failures:failures.slice(0,100)}}
export function runQl7MaterialityOracle(){const language=independentLanguage(),crisis=independentCrisis(),generalHuman=independentGeneral(),conversation=independentCells(),dialects=independentDialect(),composer=independentComposer(),publicFigures=independentFigures(),failures=[];for(const [k,v] of Object.entries({language,crisis,generalHuman,conversation,dialects,composer,publicFigures}))if(!v.ok)failures.push(k);const body={schema:'ql7.support.independent-materiality-oracle',schemaVersion:QL7_SUPPORT_MATERIALITY_ORACLE_VERSION,ok:!failures.length,oracleAuthority:'independent-prelab',oracleImportsProductionExpectedLabels:false,oracleImportsProductionAudit:false,algorithmVersion:'normalized-material-signature.2',language,crisis,generalHuman,conversation,dialects,composer,publicFigures,failures};return Object.freeze({...body,oracleSourceHash:sha(fs.readFileSync(fileURLToPath(import.meta.url))),evidenceHash:sha(JSON.stringify(body))})}
