import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import zlib from 'node:zlib'
function shaFile(file){const h=crypto.createHash('sha256');h.update(fs.readFileSync(file));return h.digest('hex')}
function esc(value=''){return String(value).replace(/[&<>"']/gu,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function atomicJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.tmp`;fs.writeFileSync(tmp,`${JSON.stringify(value,null,2)}\n`,'utf8');fs.renameSync(tmp,file)}
function attr(value){return esc(value)}
function svgGeometry(svg={}){const items=svg.geometry||[];const body=items.map(g=>{const a=g.attrs||{};const attrs=Object.entries(a).filter(([,v])=>v!==undefined&&v!==null).map(([k,v])=>`${k}="${attr(v)}"`).join(' ');if(g.type==='path')return `<path ${attrs}/>`;if(g.type==='circle')return `<circle ${attrs}/>`;if(g.type==='rect')return `<rect ${attrs}/>`;if(g.type==='line')return `<line ${attrs}/>`;if(g.type==='polyline')return `<polyline ${attrs}/>`;if(g.type==='polygon')return `<polygon ${attrs}/>`;if(g.type==='ellipse')return `<ellipse ${attrs}/>`;return ''}).join('');return `<svg viewBox="${attr(svg.viewBox||'0 0 48 48')}" width="64" height="64" role="img" aria-label="${attr(svg.ariaLabel||svg.role||'QL7 Support')}">${body}</svg>`}
function existingMeta(outDir){return fs.existsSync(outDir)?fs.readdirSync(outDir).filter(x=>x.endsWith('.ndjson.gz.meta.json')).map(x=>JSON.parse(fs.readFileSync(path.join(outDir,x),'utf8'))).sort((a,b)=>(a.firstIndex??0)-(b.firstIndex??0)):[]}
export class Ql7SimulationEvidenceWriter{
 constructor({outDir,runId,shardSize=10000,evidenceMode='full',galleryLimit=250,workerId=0,resume=false}={}){this.outDir=outDir;this.runId=runId;this.shardSize=Math.max(1,Number(shardSize)||10000);this.evidenceMode=evidenceMode;this.galleryLimit=galleryLimit;this.workerId=Number(workerId)||0;this.current=null;this.shards=[];this.samples=[];fs.mkdirSync(outDir,{recursive:true});this.previous=resume?existingMeta(outDir):[];this.part=this.previous.reduce((m,x)=>Math.max(m,Number(x.partIndex??-1)+1),0)}
 shouldPersist(row){return this.evidenceMode==='full'||(this.evidenceMode==='failures'&&!row.oracle?.ok)||(this.evidenceMode==='sampled'&&(row.index%100===0||!row.oracle?.ok))}
 open(index){if(this.current&&this.current.count<this.shardSize)return;if(this.current)this.close();const part=this.part++;const base=`evidence-w${String(this.workerId).padStart(3,'0')}-p${String(part).padStart(6,'0')}.ndjson.gz`;const file=path.join(this.outDir,base);if(fs.existsSync(file))throw new Error(`evidence_shard_exists:${file}`);const gzip=zlib.createGzip({level:9});const stream=fs.createWriteStream(file,{flags:'wx'});gzip.pipe(stream);this.current={partIndex:part,workerId:this.workerId,file,gzip,stream,count:0,firstIndex:index,lastIndex:index}}
 write(row){if(this.samples.length<this.galleryLimit&&(this.samples.length<50||!row.oracle?.ok||row.index%(Math.max(1,Math.floor((row.totalCount||1000)/Math.max(1,this.galleryLimit))))===0))this.samples.push(row);if(!this.shouldPersist(row))return;this.open(row.index);this.current.gzip.write(`${JSON.stringify(row)}\n`);this.current.count++;this.current.lastIndex=row.index}
 close(){if(!this.current)return;const c=this.current;c.gzip.end();this.current=null;this.shards.push(c)}
 async finalize(){this.close();for(const c of this.shards){await new Promise((resolve,reject)=>{if(c.stream.closed)return resolve();c.stream.on('close',resolve);c.stream.on('error',reject)});const raw=zlib.gunzipSync(fs.readFileSync(c.file));const text=raw.toString('utf8').trim();const records=text?text.split('\n').length:0;c.meta={file:path.basename(c.file),partIndex:c.partIndex,workerId:c.workerId,sha256:shaFile(c.file),compressedBytes:fs.statSync(c.file).size,uncompressedBytes:raw.length,recordCount:records,firstIndex:c.firstIndex,lastIndex:c.lastIndex,compression:'gzip',compressionValid:records===c.count};delete c.gzip;delete c.stream;atomicJson(`${c.file}.meta.json`,c.meta)}return [...this.previous,...this.shards.map(c=>c.meta)].sort((a,b)=>(a.firstIndex??0)-(b.firstIndex??0))}
 writeGallery(){if(!this.samples.length)return;const cards=this.samples.map(row=>{const a=row.actual||{},s=a.surface||{},badges=(s.badges||[]).map(x=>`<span class="badge">${esc(x.label||x.id)}</span>`).join(''),tables=(s.tables||[]).map(t=>`<section><h4>${esc(t.title||t.schema)}</h4>${(t.rows||[]).map(r=>`<div class="tr"><b>${esc(r.label||r.key)}</b><span>${esc(r.value)}</span></div>`).join('')}</section>`).join(''),actions=(s.actions||s.options||[]).map(x=>`<button>${esc(x.label||x.id)}</button>`).join('');return `<article class="card role-${esc(s.semanticRole||'social')}"><header><div class="icon">${svgGeometry(s.primarySvg||{})}</div><div><code>#${row.index} · ${esc(row.scenario?.locale)}</code><h3>${esc(s.title||'QL7 Support')}</h3><small>${esc(s.primarySvg?.assetId||a.svgAssetId||'')}</small></div></header><p class="q">${esc(row.turn?.originalText||row.scenario?.input)}</p><p>${esc(a.text)}</p><div>${badges}</div>${tables}<div class="actions">${actions}</div><div class="verdict ${row.oracle?.ok?'ok':'bad'}">${row.oracle?.ok?'PASS':esc((row.failureCodes||[]).join(', '))}</div><details><summary>Полный evidence</summary><pre>${esc(JSON.stringify(row,null,2))}</pre></details></article>`}).join('\n');const html=`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>QL7 Support simulation gallery</title><style>body{background:#050711;color:#eef;font:14px system-ui;margin:0;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:18px}.card{background:linear-gradient(145deg,#10172a,#080b15);border:1px solid #355083;border-radius:22px;padding:18px;box-shadow:0 14px 45px #0008}.card header{display:flex;gap:14px;align-items:center;border-bottom:1px solid #ffffff24;padding-bottom:12px}.icon{width:68px;height:68px;display:grid;place-items:center;border:1px solid #ffffff2a;border-radius:18px;background:#101a35}.icon svg{stroke:#8fd7ff;fill:none;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.q{color:#9fb7e8}.badge{display:inline-block;padding:4px 9px;border:1px solid #4e84a9;border-radius:99px;margin:4px}.tr{display:flex;justify-content:space-between;gap:12px;padding:7px;border-bottom:1px solid #ffffff12}.actions button{margin:5px;padding:10px 13px;border-radius:11px;background:#172b50;color:white;border:1px solid #4d80bd}.verdict{margin-top:12px;font-weight:800}.ok{color:#74f0ad}.bad{color:#ff8d9b}pre{white-space:pre-wrap;overflow:auto;max-height:520px}@media(prefers-reduced-motion:no-preference){.icon svg{animation:ql7Intro .55s ease-out 1}}@keyframes ql7Intro{from{opacity:.2;transform:scale(.94)}to{opacity:1;transform:none}}</style><h1>QL7 Support production-shaped simulation</h1><div class="grid">${cards}</div>`;fs.writeFileSync(path.join(this.outDir,'gallery.html'),html,'utf8')}
}
export{atomicJson as writeQl7SimulationJson}
