import {buildQl7SupportScenario} from './scenarioCatalog.js'
import {getQl7SupportTopicLabel} from '../ecosystemCatalog.js'
import {QL7_SUPPORT_RELEASE_DOMAIN_ROOTS} from '../ontology/domainOntology.js'
import {QL7_METAMORPHIC_TRANSFORMS, applyMetamorphicTransform} from './lab/metamorphicGenerator.js'
const LOCALES=Object.freeze(['en','ru','uk','es','tr','ar','zh','he','de','fr','it','pt','pl','nl','sv','no','da','fi','cs','sk','hu','ro','bg','sr','hr','sl','el','ka','az','kk','ja','ko'])
const HOLDOUT_PER_CELL=1000
function cell(index,perCell){const perLocale=QL7_SUPPORT_RELEASE_DOMAIN_ROOTS.length*perCell,localeIndex=Math.floor(index/perLocale),inLocale=index%perLocale,domainIndex=Math.floor(inLocale/perCell),sampleIndex=inLocale%perCell;return{locale:LOCALES[localeIndex],domainId:QL7_SUPPORT_RELEASE_DOMAIN_ROOTS[domainIndex],sampleIndex}}
function question(domainId,locale,sample){const label=getQl7SupportTopicLabel(domainId,locale)||domainId;const frames=[`${label} — what is it and what can I do there?`,`Explain ${label}: purpose, limits and current availability.`,`I need help understanding ${label}.`,`How do I use ${label} safely?`,`What is currently verified about ${label}?`];return frames[sample%frames.length]}
export function buildCellHoldoutScenario(index,{seed='canonical-cell-holdout'}={}){const c=cell(index,HOLDOUT_PER_CELL),base=buildQl7SupportScenario(index,{profile:'knowledge-32',locale:c.locale,seed:`${seed}:${c.domainId}:${c.sampleIndex}`});return Object.freeze({...base,id:`holdout:${c.locale}:${c.domainId}:${String(c.sampleIndex).padStart(4,'0')}`,input:question(c.domainId,c.locale,c.sampleIndex),analysis:{},baseAnalysisTrust:false,expected:{...(base.expected||{}),topic:c.domainId,noAdapter:true},lab:Object.freeze({...base.lab,scientificGate:'F',domainId:c.domainId,microtopicId:`${c.domainId}:overview`,sampleIndex:c.sampleIndex})})}
export function buildMetamorphicScenario(index,{seed='canonical-metamorphic'}={}){const transformIndex=index%16,baseCellIndex=Math.floor(index/16),c=cell(baseCellIndex,100),base=buildQl7SupportScenario(baseCellIndex,{profile:'knowledge-32',locale:c.locale,seed:`${seed}:${c.domainId}:${c.sampleIndex}`}),semanticBase=Object.freeze({...base,id:`metamorphic-base:${c.locale}:${c.domainId}:${c.sampleIndex}`,input:question(c.domainId,c.locale,c.sampleIndex),analysis:{},baseAnalysisTrust:false,expected:{...(base.expected||{}),topic:c.domainId,noAdapter:true}}),transformId=QL7_METAMORPHIC_TRANSFORMS[transformIndex],mutated=applyMetamorphicTransform(semanticBase,transformId);return Object.freeze({...mutated,id:`metamorphic:${c.locale}:${c.domainId}:${String(c.sampleIndex).padStart(3,'0')}:${transformId}`,lab:Object.freeze({...mutated.lab,scientificGate:'H',domainId:c.domainId,microtopicId:`${c.domainId}:overview`,transformId,parentScenarioId:semanticBase.id})})}
export function buildChaosScenario(index,{seed='canonical-chaos'}={}){const modes=['provider-unavailable','delivery-timeout','delivery-uncertain','retry-replay','memory-concurrency','adapter-unavailable','restriction-race','economic-idempotency','worker-retry','source-contradiction'];const failureMode=modes[index%modes.length],provider=failureMode==='provider-unavailable',base=buildQl7SupportScenario(index,{profile:provider?'provider-language-quality':index%2?'production-parity':'adversarial',locale:provider?'de':'en',seed:`${seed}:${failureMode}`});return Object.freeze({...base,id:`chaos:${failureMode}:${String(index).padStart(7,'0')}`,fixtureState:failureMode==='adapter-unavailable'?'unavailable':base.fixtureState,lab:Object.freeze({...base.lab,scientificGate:'I',failureMode}),chaosFailureMode:failureMode})}
export function longitudinalCell(dialogueIndex){return cell(dialogueIndex,100)}
export function buildLongitudinalTurn(dialogueIndex,turnIndex,{seed='canonical-memory'}={}){const c=longitudinalCell(dialogueIndex),label=getQl7SupportTopicLabel(c.domainId,c.locale)||c.domainId;const sequence=[
 {input:`Explain ${label} and remember the exact question I am asking.`,expected:{topic:c.domainId,noAdapter:true}},
 {input:'Now change topic: tell me one useful fact about the ocean.',expected:{}},
 {input:`Return to my ${label} question exactly where we stopped.`,expected:{topic:c.domainId}},
 {input:`Correction: for ${label}, I meant current limitations, not an overview.`,expected:{topic:c.domainId}},
 {input:'Continue from that corrected point without restarting.',expected:{topic:c.domainId}},
];const row=sequence[turnIndex%sequence.length],base=buildQl7SupportScenario(dialogueIndex*100+turnIndex,{profile:'long-dialogue',locale:c.locale,seed:`${seed}:${dialogueIndex}:${turnIndex}`});return Object.freeze({...base,...row,id:`memory:${c.locale}:${c.domainId}:${String(c.sampleIndex).padStart(3,'0')}:${String(turnIndex).padStart(3,'0')}`,locale:c.locale,analysis:{},baseAnalysisTrust:false,lab:Object.freeze({...base.lab,scientificGate:'G',domainId:c.domainId,microtopicId:`${c.domainId}:overview`,dialogueIndex,turnIndex})})}
export {LOCALES as QL7_SUPPORT_SCIENTIFIC_LOCALES}
