import crypto from 'node:crypto'
export const QL7_SEMANTIC_DUPLICATE_ORACLE_VERSION='5.1.0-independent'
function norm(v=''){return String(v||'').normalize('NFKC').toLowerCase().replace(/[\p{P}\p{S}]+/gu,' ').replace(/\s+/gu,' ').trim()}
function sentences(v=''){return String(v||'').split(/(?<=[.!?。！？؟])\s+/u).map(norm).filter(Boolean)}
function clauses(v=''){return String(v||'').split(/[;:,.!?。！？؟،]+/u).map(norm).filter(Boolean)}
function multiset(values=[]){return [...values].sort().join('||')}
function shingles(v='',n=3){const w=norm(v).split(' ').filter(Boolean);const s=new Set();if(w.length<n){if(w.length)s.add(w.join(' '));return s}for(let i=0;i<=w.length-n;i++)s.add(w.slice(i,i+n).join(' '));return s}
function jaccard(a,b){if(!a.size&&!b.size)return 1;let i=0;for(const x of a)if(b.has(x))i++;return i/(a.size+b.size-i||1)}
function skeleton(v=''){return norm(v).replace(/\b\d+(?:[.,]\d+)?\b/gu,'#').replace(/\b[a-f0-9]{8,}\b/gu,'@').split(' ').map(w=>w.length>7?'L':w.length>3?'M':'S').join('-')}
export function fingerprintIndependent(text=''){const normalized=norm(text);return Object.freeze({exactHash:crypto.createHash('sha256').update(String(text||'')).digest('hex'),normalizedHash:crypto.createHash('sha256').update(normalized).digest('hex'),sentenceMultisetHash:crypto.createHash('sha256').update(multiset(sentences(text))).digest('hex'),clauseMultisetHash:crypto.createHash('sha256').update(multiset(clauses(text))).digest('hex'),skeleton:skeleton(text),shingles:shingles(text)})}
export function compareSemanticDuplicateIndependent(a='',b='',threshold=.80){const A=fingerprintIndependent(a),B=fingerprintIndependent(b);const similarity=jaccard(A.shingles,B.shingles);const failures=[];if(A.exactHash===B.exactHash)failures.push('exact_duplicate');if(A.normalizedHash===B.normalizedHash)failures.push('normalized_duplicate');if(A.sentenceMultisetHash===B.sentenceMultisetHash&&norm(a)!==norm(b))failures.push('sentence_multiset_collision');if(A.clauseMultisetHash===B.clauseMultisetHash&&norm(a)!==norm(b))failures.push('clause_multiset_collision');if(A.skeleton===B.skeleton&&similarity>=threshold)failures.push('rhetorical_skeleton_collision');if(similarity>=threshold)failures.push('near_semantic_duplicate');return Object.freeze({ok:!failures.length,similarity,threshold,failures,A:{...A,shingles:undefined},B:{...B,shingles:undefined}})}
