const WINDOW_MS=30*24*60*60*1000
const COLLECTION='composer_warning_events'
let testDb=null
function str(v){return String(v??'').trim()}function iso(v){const n=Number(v);if(!Number.isFinite(n))throw new Error('composer_time_invalid');return new Date(n).toISOString()}
function normalizeDatabase(h){const db=h?.db&&typeof h.db.collection==='function'?h.db:h;if(!db||typeof db.collection!=='function')throw new Error('mongo_db_unavailable');return db}
async function productionDatabase(){if(testDb)return normalizeDatabase(testDb);const {getMongoDb}=require('../mongo/client.cjs');return normalizeDatabase(await getMongoDb())}
function createComposerWarningLedger({database=null,getDatabase=null}={}){if(!database&&typeof getDatabase!=='function')throw new Error('composer_warning_ledger_database_dependency_required');const db=async()=>normalizeDatabase(database||await getDatabase())
 async function listConfirmedWarnings(accountId,now=Date.now()){const since=iso(Number(now)-WINDOW_MS),d=await db();return d.collection(COLLECTION).find({accountId:str(accountId),status:'published_orange_warning',createdAt:{$gte:since}}).sort({createdAt:-1}).limit(64).toArray()}
 async function commitPublishedOrangeWarning({accountId,classId,surface,contentHash,decisionId,now=Date.now()}={}){const d=await db(),id=`warning:${str(decisionId)||`${str(accountId)}:${Number(now)}`}`,createdAt=iso(now),row={_id:id,accountId:str(accountId),classId:str(classId),surface:str(surface),contentHash:str(contentHash),decisionId:str(decisionId),status:'published_orange_warning',createdAt,policyVersion:'message-policy.2'};try{await d.collection(COLLECTION).insertOne(row)}catch(e){if(e?.code!==11000)throw e}return d.collection(COLLECTION).findOne({_id:id})}
 async function recordDroppedAttempt({accountId,classId,surface,contentHash,decisionId,decision,now=Date.now()}={}){const d=await db(),id=`drop:${str(decisionId)||`${str(accountId)}:${Number(now)}`}`,row={_id:id,accountId:str(accountId),classId:str(classId),surface:str(surface),contentHash:str(contentHash),decisionId:str(decisionId),status:decision==='DROP_RED'?'dropped_red_attempt':'dropped_orange_attempt',createdAt:iso(now),policyVersion:'message-policy.2'};try{await d.collection(COLLECTION).insertOne(row)}catch(e){if(e?.code!==11000)throw e}return d.collection(COLLECTION).findOne({_id:id})}
 async function dismissWarning({accountId,decisionId,reviewReceiptId,reasonCode='operator_correction',now=Date.now()}={}){if(!str(accountId)||!str(decisionId)||!str(reviewReceiptId))throw new Error('composer_warning_dismissal_receipt_required');const d=await db(),result=await d.collection(COLLECTION).updateOne({_id:`warning:${str(decisionId)}`,accountId:str(accountId),status:'published_orange_warning'},{$set:{status:'dismissed',dismissedAt:iso(now),dismissReasonCode:str(reasonCode),reviewReceiptId:str(reviewReceiptId)}});return Object.freeze({ok:Number(result?.matchedCount||0)===1,decisionId:str(decisionId),reviewReceiptId:str(reviewReceiptId),excludedFromEscalation:true,excludedFromRating:true})}
 return Object.freeze({WINDOW_MS,listConfirmedWarnings,commitPublishedOrangeWarning,recordDroppedAttempt,dismissWarning,commitConfirmedWarning:commitPublishedOrangeWarning,dismissConfirmedWarning:dismissWarning})
}
const production=createComposerWarningLedger({getDatabase:productionDatabase});function __setTestDb(v){testDb=v||null}
module.exports={...production,createComposerWarningLedger,__setTestDb,WINDOW_MS}
