import crypto from 'node:crypto'
const str=(v)=>String(v??'').trim();const sha=(v)=>crypto.createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex')
export const QL7_SUPPORT_EXPERIMENT_SCENARIO_VERSION='5.1.0'
export function normalizeQl7ExperimentScenario(scenario={}, {experimentId='',familyId='',lineageId='',splitId='',seed=''}={}){
 const userTurns=Array.isArray(scenario.userTurns)&&scenario.userTurns.length?scenario.userTurns:[{turnIndex:0,text:str(scenario.input||scenario.text)}]
 const body={schema:'ql7.support.lab.experiment-scenario',schemaVersion:QL7_SUPPORT_EXPERIMENT_SCENARIO_VERSION,experimentId:str(experimentId||scenario.lab?.experimentId),scenarioId:str(scenario.id),familyId:str(familyId||scenario.lab?.bucket||scenario.profile),lineageId:str(lineageId||scenario.lab?.lineageId||`lineage:${sha({id:scenario.id,parent:scenario.lab?.parentScenarioId||''})}`),splitId:str(splitId||scenario.lab?.splitId),seed:str(seed||scenario.seed),locale:str(scenario.locale),domainId:str(scenario.expected?.topic||scenario.lab?.domainId),microtopicId:str(scenario.lab?.microtopicId),intentId:str(scenario.expected?.intent||scenario.lab?.intentId),speechAct:str(scenario.expected?.messageAct||scenario.lab?.speechAct),memoryPrecondition:scenario.memoryPrecondition||null,factSourcePrecondition:scenario.factSourcePrecondition||null,userTurns:Object.freeze(userTurns.map((r,i)=>Object.freeze({turnIndex:Number(r.turnIndex??i),text:str(r.text),metadata:Object.freeze({...r.metadata})}))),expectedInvariants:Object.freeze([...(scenario.expectedInvariants||scenario.lab?.expectedInvariants||[])]),allowedOutcomes:Object.freeze([...(scenario.allowedOutcomes||scenario.lab?.allowedOutcomes||[])]),forbiddenOutcomes:Object.freeze([...(scenario.forbiddenOutcomes||scenario.lab?.forbiddenOutcomes||[])]),productionReceipts:Object.freeze([]),oracleReceipts:Object.freeze([])}
 const experimentScenarioHash=sha(body);return Object.freeze({...scenario,lab:Object.freeze({...scenario.lab,...body,experimentScenarioHash}),experimentScenario:Object.freeze({...body,experimentScenarioHash})})
}
export function validateQl7ExperimentScenario(scenario={}){const e=scenario.experimentScenario||scenario.lab||{},failures=[];for(const key of ['scenarioId','familyId','splitId','locale'])if(!str(e[key]))failures.push(`missing_${key}`);if(!Array.isArray(e.userTurns)||!e.userTurns.length)failures.push('user_turns_missing');if(!Array.isArray(e.expectedInvariants))failures.push('expected_invariants_missing');return Object.freeze({ok:!failures.length,failures:Object.freeze(failures)})}
