import crypto from 'node:crypto'
import {fingerprintIndependent, compareSemanticDuplicateIndependent} from '../semanticDuplicateOracle.js'
const sha=(v)=>crypto.createHash('sha256').update(String(v)).digest('hex')
function tokens(text=''){return String(text).normalize('NFKC').toLowerCase().match(/[\p{L}\p{N}]+/gu)||[]}
function shingles(text,k=3){const t=tokens(text),out=[];for(let i=0;i<=t.length-k;i++)out.push(t.slice(i,i+k).join(' '));return out.length?out:t}
function minhash(text,perms=32){const ss=shingles(text),sig=[];for(let p=0;p<perms;p++){let best='f'.repeat(64);for(const s of ss){const h=sha(`${p}:${s}`);if(h<best)best=h}sig.push(best.slice(0,16))}return sig}
function bands(sig,bands=8){const width=Math.ceil(sig.length/bands),out=[];for(let b=0;b<bands;b++){const chunk=sig.slice(b*width,(b+1)*width);if(chunk.length)out.push(`${b}:${sha(chunk.join(':')).slice(0,20)}`)}return out}
export function detectSplitLeakage(rows=[],{threshold=.80,maxNearChecks=2_000_000}={}){const failures=[],maps={exact:new Map(),normalized:new Map(),family:new Map(),ancestry:new Map(),mutationSeed:new Map(),humanSource:new Map(),reference:new Map()},lsh=new Map();let checks=0
 for(const row of rows){const split=String(row.splitId||''),id=String(row.scenarioId||''),fp=fingerprintIndependent(row.text||row.input||''),keys={exact:fp.exactHash,normalized:fp.normalizedHash,family:String(row.familyId||row.semanticFamilyId||''),ancestry:String(row.parentId||row.lineageId||row.templateAncestry||''),mutationSeed:String(row.mutationSeed||''),humanSource:String(row.humanSourceId||''),reference:String(row.answerReferenceId||'')};for(const [kind,key] of Object.entries(keys)){if(!key)continue;const prior=maps[kind].get(key);if(prior&&prior.split!==split)failures.push({code:`split_${kind}_leakage`,a:prior.id,b:id,splits:[prior.split,split]});else if(!prior)maps[kind].set(key,{id,split})}
  const sig=minhash(row.text||row.input||'');for(const band of bands(sig)){const bucket=lsh.get(band)||[];for(const prior of bucket){if(checks>=maxNearChecks)break;if(prior.split===split)continue;checks++;const cmp=compareSemanticDuplicateIndependent(prior.text,row.text||row.input||'',threshold);if(cmp.similarity>=threshold)failures.push({code:'split_near_semantic_leakage',a:prior.id,b:id,similarity:cmp.similarity,splits:[prior.split,split]})}bucket.push({id,split,text:row.text||row.input||''});lsh.set(band,bucket.slice(-256))}}
 const truncated=checks>=maxNearChecks;return Object.freeze({ok:!failures.length&&!truncated,checkedNearPairs:checks,maxNearChecks,truncated,failureCount:failures.length,failures:Object.freeze(failures.slice(0,10000))})}
