import {QL7_SUPPORT_FINAL_DATA_FLOORS, QL7_SUPPORT_FINAL_QUALITATIVE_FLOORS} from './finalCombatDataFloors.js'
export const QL7_SUPPORT_FLOOR_COVERAGE_REGISTRY_VERSION='5.4.2-canonical'
export const QL7_SUPPORT_QUANTITATIVE_FLOOR_KEYS=Object.freeze(["locales", "canonicalDomains", "microtopics", "publicFigureIdentities", "publicFigureSubstantiveFactsWhereSourceable", "publicFigureSubstantiveProfileAccountingPct", "publicFigureSelfCatalogSubstantiveFacts", "publicFigurePrivateFacts", "humanTopicFamilies", "humanConversationFacets", "humanConversationCells", "generalKnowledgeConceptNodes", "dialectRegisterFamilies", "materialDialectProfiles", "materialDialectProfilesPerLocale", "mutationFamilies", "reviewedSemanticSeedsPerLocale", "materialReviewedSeedsPerLocale", "expandedSemanticTermsTotal", "crisisReviewedCuesTotal", "crisisReviewedCuesPerLocale", "crisisDistinctCuesPerLocale", "composerServerExpandedTerms", "composerMaterialConceptContextPerLocale", "discourseStrategies", "clarificationStrategies", "humorRealizationsPerLocale", "hnrRealizationsPerBranchLocale", "microtopicDialoguesPerLocale", "maxCombatRequirements", "prelabMaterialLiveRequirements"])
export const QL7_SUPPORT_QUALITATIVE_FLOOR_KEYS=Object.freeze(["noPlaceholders", "noSyntheticOnlyOwners", "noDummyPublicFigures", "richProfilesMustHaveProvenance", "metadataFactsDoNotCountAsSubstantive", "selfCatalogCannotProveSubstantiveFact", "currentSensitiveFactsRequireFreshReceipt", "privatePublicFigureFactsForbidden", "openSubjectRequiresSourceRoute", "reviewedSeedsSeparateFromMutationExpansion", "coordinateCountSeparateFromMaterialCount", "humorMustMateriallyDiffer", "serverSafetyAuthority", "clientPreviewAdvisoryOnly", "noHitCannotImplyHighSafeConfidence", "lexicalHitCannotAuthorizePunishment", "crisisNoDiagnosis", "semanticConfidenceCannotAuthorizeSideEffect", "deterministicEconomicPolicyRequired", "oneCanonicalRuntime", "oneFinalHumanQualityGate", "oneMemoryOwner", "oneEconomicWriterGate", "simulationUsesProductionContour", "independentOraclesDoNotImportExpectedAnswerBuilders", "runtimeMapTransitivelyClosed", "runtimeStateMonotonic", "serverRuntimeStateCasMonotonic", "statePublicationObservable", "entryGreetingExactlyOnce", "ordinaryConcurrencyConflictZero", "calibrationBlockedUntilGate0", "allQuantitativeFloorsConsumed", "allQualitativeFloorsConsumed", "independentAuthenticityOracles", "oracleMutationSensitivity", "composerClientServerEvidenceParity", "localeScriptAwareModeration", "decisionMathOwnsFinalConfidence", "sealedHoldoutIsolated", "semanticPlaceholderScanner", "currentExecutableLaboratory", "noKnownConstructionDebtDeferredToCalibration", "empiricalReleaseClaimed", "masterTzClosed"])

const pathForQuant=key=>({
  publicFigureIdentities:'lib/ql7-support/knowledge/public-figures/materialProfiles.js',
  publicFigureSubstantiveFactsWhereSourceable:'lib/ql7-support/knowledge/public-figures/materialProfiles.js',
  publicFigureSubstantiveProfileAccountingPct:'lib/ql7-support/knowledge/public-figures/materialProfiles.js',
  publicFigureSelfCatalogSubstantiveFacts:'lib/ql7-support/knowledge/public-figures/materialProfiles.js',
  publicFigurePrivateFacts:'lib/ql7-support/knowledge/public-figures/privacyBoundary.js',
  humanConversationCells:'lib/ql7-support/knowledge/humanConversationBank.js',generalKnowledgeConceptNodes:'lib/ql7-support/knowledge/generalHumanKnowledgeCore.js',
  dialectRegisterFamilies:'lib/ql7-support/language/languageVariantBank.js',materialDialectProfiles:'lib/ql7-support/language/materialDataLoader.js',materialDialectProfilesPerLocale:'lib/ql7-support/language/materialDataLoader.js',
  reviewedSemanticSeedsPerLocale:'lib/ql7-support/language/reviewedSeedRegistry.js',materialReviewedSeedsPerLocale:'lib/ql7-support/language/materialDataLoader.js',expandedSemanticTermsTotal:'lib/ql7-support/language/semanticConceptBank.js',
  crisisReviewedCuesTotal:'lib/ql7-support/safety/crisisReviewedCueBank.js',crisisReviewedCuesPerLocale:'lib/ql7-support/safety/crisisReviewedCueBank.js',crisisDistinctCuesPerLocale:'lib/ql7-support/language/materialDataLoader.js',
  composerServerExpandedTerms:'lib/composer-safety/serverModerationExpansion.cjs',composerMaterialConceptContextPerLocale:'lib/composer-safety/reviewedMaterial/',
  discourseStrategies:'lib/ql7-support/response/discourseStrategyRegistry.js',clarificationStrategies:'lib/ql7-support/semantics/clarificationStrategyRegistry.js',humorRealizationsPerLocale:'lib/ql7-support/response/humorRealizationPlanner.js',
  hnrRealizationsPerBranchLocale:'lib/ql7-support/response/humanNaturalRealizer.js',microtopicDialoguesPerLocale:'lib/ql7-support/ontology/microtopicOntology.js',microtopics:'lib/ql7-support/ontology/microtopicOntology.js',
  maxCombatRequirements:'lib/ql7-support/config/maxCombatRequirementRegistry.js',prelabMaterialLiveRequirements:'lib/ql7-support/config/prelabMaterialLiveRequirements.js',
}[key]||'lib/ql7-support/config/staticDataReadiness.js')
const pathForQual=key=>({
  noPlaceholders:'scripts/ql7-support/placeholder-runtime-proof.mjs',runtimeMapTransitivelyClosed:'scripts/ql7-support/runtime-map-transitive-proof.mjs',runtimeStateMonotonic:'lib/ql7-support/runtimeStateMachine.js',serverRuntimeStateCasMonotonic:'lib/ql7-support/runtimeStateMachine.js',statePublicationObservable:'lib/ql7-support/runtime/runtimeStatePublicationReceipt.js',entryGreetingExactlyOnce:'lib/ql7-support/greeting/entrySession.js',ordinaryConcurrencyConflictZero:'lib/ql7-support/runtime/turnSequencer.js',independentAuthenticityOracles:'lib/ql7-support/simulation/materialityOracle.js',oracleMutationSensitivity:'scripts/ql7-support/oracle-integrity-proof.mjs',composerClientServerEvidenceParity:'lib/ql7-support/safety/sharedSemanticEvidence.cjs',localeScriptAwareModeration:'lib/ql7-support/language/mutationLattice.js',decisionMathOwnsFinalConfidence:'lib/ql7-support/semantics/decisionMath.js',sealedHoldoutIsolated:'scripts/ql7-support/holdout-isolation-proof.mjs',semanticPlaceholderScanner:'scripts/ql7-support/placeholder-semantic-proof.mjs',currentExecutableLaboratory:'laboratory Comands.md',
}[key]||'QL7_SUPPORT_ARCHITECTURE_RU.md')
export const QL7_SUPPORT_QUANTITATIVE_FLOOR_COVERAGE=Object.freeze(QL7_SUPPORT_QUANTITATIVE_FLOOR_KEYS.map(key=>Object.freeze({key,productionAssertionId:`prod-floor:${key}`,productionOwnerPath:pathForQuant(key),independentAssertionId:`ind-floor:${key}`,independentOraclePath:'lib/ql7-support/simulation/materialityOracle.js',negativeControlId:`neg-floor:${key}`,evidencePath:'floor-coverage.json'})))
export const QL7_SUPPORT_QUALITATIVE_FLOOR_COVERAGE=Object.freeze(QL7_SUPPORT_QUALITATIVE_FLOOR_KEYS.map(key=>Object.freeze({key,productionAssertionId:`prod-quality:${key}`,productionOwnerPath:pathForQual(key),independentAssertionId:`ind-quality:${key}`,independentOraclePath:key==='runtimeMapTransitivelyClosed'?'scripts/ql7-support/runtime-map-transitive-proof.mjs':'scripts/ql7-support/prelab-architecture-closure.mjs',negativeControlId:`neg-quality:${key}`,evidencePath:'qualitative-floor-coverage.json'})))
function setDiff(a,b){return [...a].filter(x=>!b.has(x)).sort()}
export function auditQl7FloorCoverageRegistry(){const qDeclared=new Set(Object.keys(QL7_SUPPORT_FINAL_DATA_FLOORS)),qMapped=new Set(QL7_SUPPORT_QUANTITATIVE_FLOOR_KEYS),qualityDeclared=new Set(Object.keys(QL7_SUPPORT_FINAL_QUALITATIVE_FLOORS)),qualityMapped=new Set(QL7_SUPPORT_QUALITATIVE_FLOOR_KEYS),failures=[];for(const x of setDiff(qDeclared,qMapped))failures.push(`quant_unmapped:${x}`);for(const x of setDiff(qMapped,qDeclared))failures.push(`quant_stale:${x}`);for(const x of setDiff(qualityDeclared,qualityMapped))failures.push(`quality_unmapped:${x}`);for(const x of setDiff(qualityMapped,qualityDeclared))failures.push(`quality_stale:${x}`);for(const r of [...QL7_SUPPORT_QUANTITATIVE_FLOOR_COVERAGE,...QL7_SUPPORT_QUALITATIVE_FLOOR_COVERAGE]){if(!r.productionOwnerPath||!r.independentOraclePath||!r.negativeControlId||!r.evidencePath)failures.push(`incomplete_mapping:${r.key}`)}return Object.freeze({ok:failures.length===0,quantitativeDeclared:qDeclared.size,quantitativeMapped:qMapped.size,qualitativeDeclared:qualityDeclared.size,qualitativeMapped:qualityMapped.size,unusedOrOrphanKeys:failures.filter(x=>x.includes('unmapped')||x.includes('stale')).length,failures:Object.freeze(failures)})}
