import crypto from 'node:crypto'
import {loadQl7MaterialRows, listQl7MaterialJson, readQl7MaterialJson} from '../language/materialDataLoader.js'
import {auditQl7PublicFigureMaterialProfiles} from '../knowledge/public-figures/materialProfiles.js'
import {auditQl7GeneralHumanKnowledgeCore} from '../knowledge/generalHumanKnowledgeCore.js'
import {auditQl7SupportHumanConversationBank} from '../knowledge/humanConversationBank.js'
import {auditQl7SupportMicrotopicOntology} from '../ontology/microtopicOntology.js'
import {auditQl7SupportDiscourseStrategyCapacity} from '../response/discourseStrategyRegistry.js'
import {auditQl7SupportHumorPlanner} from '../response/humorRealizationPlanner.js'
import {QL7_SUPPORT_FINAL_DATA_FLOORS} from './finalCombatDataFloors.js'
import {QL7_SUPPORT_PRELAB_MATERIAL_LIVE_REQUIREMENTS} from './prelabMaterialLiveRequirements.js'
import {auditQl7FloorCoverageRegistry} from './floorCoverageRegistry.js'
const norm=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().replace(/[\u200B-\u200D\uFEFF]/gu,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim()
const hash=v=>crypto.createHash('sha256').update(String(v)).digest('hex')
function grouped(dir,key,localeKey='locale'){const out={};for(const rel of listQl7MaterialJson(dir)){const doc=readQl7MaterialJson(rel),locale=String(doc?.[localeKey]||'');if(!locale)continue;out[locale]=Array.isArray(doc?.[key])?doc[key]:[]}return out}
function semanticCoordinates(){let total=0;try{for(const rel of listQl7MaterialJson('lib/ql7-support/language/semanticCoordinates')){const d=readQl7MaterialJson(rel);total+=Array.isArray(d.rows)?d.rows.length:0}}catch{}return total}
export function auditQl7ProductionMaterialReadiness(){const f=QL7_SUPPORT_FINAL_DATA_FLOORS,failures=[];const req=(ok,code)=>{if(!ok)failures.push(code)}
 const language=grouped('lib/ql7-support/language/reviewedMaterial','rows'),crisis=grouped('lib/ql7-support/safety/crisisReviewed','rows'),dialects=grouped('lib/ql7-support/language/dialectProfiles','profiles'),composer=grouped('lib/composer-safety/reviewedMaterial','rows')
 const languageRows=Object.fromEntries(Object.entries(language).map(([locale,rows])=>[locale,{rows:rows.length,normalizedDistinct:new Set(rows.map(r=>norm(r.surface)).filter(Boolean)).size,provenanceComplete:rows.every(r=>r.mutationDerived===false&&r.provenance?.sourceRef&&r.surface)}]))
 const crisisRows=Object.fromEntries(Object.entries(crisis).map(([locale,rows])=>[locale,{rows:rows.length,normalizedDistinct:new Set(rows.map(r=>norm(r.surface)).filter(Boolean)).size,provenanceComplete:rows.every(r=>r.mutationDerived===false&&r.provenance?.sourceRef)}]))
 let dialectCount=0,minDialectMaterial=1e9;for(const ps of Object.values(dialects)){dialectCount+=ps.length;for(const p of ps){const n=(p.materialExamples?.length||0)+(p.lexicalPatterns?.length||0)+(p.morphologyNotes?.length||0)+(p.slangAliases?.length||0)+(p.safeNegativeExamples?.length||0);minDialectMaterial=Math.min(minDialectMaterial,n)}}
 let composerMin=1e9;for(const rows of Object.values(composer))composerMin=Math.min(composerMin,new Set(rows.map(r=>norm(r.surface)).filter(Boolean)).size)
 const figures=auditQl7PublicFigureMaterialProfiles(),humanCore=auditQl7GeneralHumanKnowledgeCore(),conversation=auditQl7SupportHumanConversationBank(),microtopics=auditQl7SupportMicrotopicOntology(),floorCoverage=auditQl7FloorCoverageRegistry(),discourse=auditQl7SupportDiscourseStrategyCapacity(),humor=auditQl7SupportHumorPlanner('en')
 const profileAccountingPct=figures.profileCount?Number((((figures.substantiveFourCount+figures.explicitInsufficientCount)/figures.profileCount)*100).toFixed(6)):0
 req(Object.keys(languageRows).length===f.locales,'language_locale_count');req(Object.values(languageRows).every(x=>x.rows>=f.materialReviewedSeedsPerLocale&&x.normalizedDistinct>=f.materialReviewedSeedsPerLocale&&x.provenanceComplete),'language_material_distinct')
 req(Object.keys(crisisRows).length===f.locales,'crisis_locale_count');req(Object.values(crisisRows).every(x=>x.normalizedDistinct>=f.crisisDistinctCuesPerLocale&&x.provenanceComplete),'crisis_material_distinct')
 req(dialectCount>=f.materialDialectProfiles&&Object.values(dialects).every(ps=>ps.length>=f.materialDialectProfilesPerLocale)&&minDialectMaterial>=20,'dialect_material_depth')
 req(composerMin>=f.composerMaterialConceptContextPerLocale,'composer_material_context_floor')
 req(figures.ok&&figures.profileCount>=f.publicFigureIdentities&&profileAccountingPct===f.publicFigureSubstantiveProfileAccountingPct&&figures.selfCatalogOnlySubstantiveFacts===f.publicFigureSelfCatalogSubstantiveFacts&&figures.privateFacts===f.publicFigurePrivateFacts,'public_figure_substantive_accounting')
 req(humanCore.ok&&humanCore.materialNodeCount>=f.generalKnowledgeConceptNodes,'general_human_material');req(conversation.ok&&conversation.materialCellCount>=f.humanConversationCells,'conversation_material');req(microtopics.ok&&microtopics.microtopicCount>=f.microtopics&&microtopics.requiredCapabilityUncovered===0,'microtopic_capability');req(floorCoverage.ok,'floor_coverage_registry');req(QL7_SUPPORT_PRELAB_MATERIAL_LIVE_REQUIREMENTS.length===42,'pl_42');req(discourse.ok&&discourse.count>=f.discourseStrategies,'discourse');req(humor.ok&&humor.capacity>=f.humorRealizationsPerLocale,'humor_resources')
 const body={schema:'ql7.support.production-material-readiness',schemaVersion:'5.4.2-canonical',ok:failures.length===0,language:languageRows,crisis:crisisRows,dialects:{profileCount:dialectCount,minMaterial:minDialectMaterial===1e9?0:minDialectMaterial},composer:{minNormalizedDistinctPerLocale:composerMin===1e9?0:composerMin},publicFigures:{...figures,substantiveRichCoveragePct:figures.profileCount?Number(((figures.substantiveFourCount/figures.profileCount)*100).toFixed(6)):0,profileAccountingPct},humanCore:{materialNodeCount:humanCore.materialNodeCount},conversation:{materialCellCount:conversation.materialCellCount,maxDialogueSignatureReuse:conversation.maxDialogueSignatureReuse},microtopics:{microtopicCount:microtopics.microtopicCount,requiredCapabilityUncovered:microtopics.requiredCapabilityUncovered},semanticCoordinateCount:semanticCoordinates(),floorCoverage,resourceCapacity:{humor:humor.capacity,discourse:discourse.count,hnrBranchTargetInstalled:f.hnrRealizationsPerBranchLocale,microtopicDialogueTargetInstalled:f.microtopicDialoguesPerLocale},failures:Object.freeze(failures)};return Object.freeze({...body,evidenceHash:hash(JSON.stringify(body))})}
