import crypto from 'node:crypto'
const str=(v)=>String(v??'').trim(); const h=(v)=>crypto.createHash('sha256').update(str(v)).digest('hex')
export const QL7_SUPPORT_HTTP_IDEMPOTENCY_VERSION='5.1.0'
const mem=new Map()
const sleep=(ms)=>new Promise((resolve)=>setTimeout(resolve,ms))
export function buildQl7SupportIdempotencyKey({actorId='',routeId='',clientMutationId='',operationId=''}={}){const raw=`${str(actorId)}:${str(routeId)}:${str(clientMutationId||operationId)}`;if(!str(actorId)||!str(routeId)||!str(clientMutationId||operationId)){const e=new Error('support_idempotency_key_required');e.status=400;throw e}return h(raw)}
export async function reserveQl7SupportIdempotency({database=null,keyHash='',payloadHash='',actorIdHash='',ttlMs=24*3600_000,leaseMs=90_000,now=Date.now()}={}){
 const key=str(keyHash),at=Number(now)||Date.now(),expiresAt=new Date(at+ttlMs),leaseUntil=new Date(at+Math.max(30_000,Number(leaseMs)||90_000)),ownerToken=crypto.randomUUID()
 if(!key)throw new Error('support_idempotency_key_required')
 if(database?.collection){const c=database.collection('ql7_support_http_idempotency');await c.createIndex({expiresAt:1},{expireAfterSeconds:0,name:'ttl_support_http_idempotency'}).catch(()=>null);try{await c.insertOne({_id:key,schema:'ql7.support.http-idempotency',schemaVersion:QL7_SUPPORT_HTTP_IDEMPOTENCY_VERSION,payloadHash:str(payloadHash),actorIdHash:str(actorIdHash),state:'reserved',ownerToken,leaseUntil,createdAt:new Date(at),updatedAt:new Date(at),expiresAt});return Object.freeze({ok:true,replay:false,owner:true,ownerToken,keyHash:key,state:'reserved'})}catch(e){if(Number(e?.code)!==11000)throw e;const row=await c.findOne({_id:key});if(row?.payloadHash!==str(payloadHash)){const x=new Error('support_idempotency_payload_conflict');x.status=409;throw x}if(row?.state!=='committed'&&new Date(row?.leaseUntil||0).getTime()<=at){const takeover=await c.findOneAndUpdate({_id:key,payloadHash:str(payloadHash),state:'reserved',leaseUntil:{$lte:new Date(at)}},{$set:{ownerToken,leaseUntil,updatedAt:new Date(at)}},{returnDocument:'after'});const claimed=takeover?.value&&typeof takeover.value==='object'?takeover.value:takeover;if(claimed?.ownerToken===ownerToken)return Object.freeze({ok:true,replay:false,owner:true,ownerToken,keyHash:key,state:'reserved',recovered:true})}return Object.freeze({ok:true,replay:row?.state==='committed',owner:false,keyHash:key,result:row?.result||null,state:row?.state||'reserved'})}}
 const row=mem.get(key);if(row&&row.payloadHash!==str(payloadHash)){const e=new Error('support_idempotency_payload_conflict');e.status=409;throw e}if(row){if(row.state!=='committed'&&Number(row.leaseUntil||0)<=at){mem.set(key,{...row,ownerToken,leaseUntil:leaseUntil.getTime(),updatedAt:at});return Object.freeze({ok:true,replay:false,owner:true,ownerToken,keyHash:key,state:'reserved',recovered:true})}return Object.freeze({ok:true,replay:row.state==='committed',owner:false,keyHash:key,result:row.result||null,state:row.state})}mem.set(key,{payloadHash:str(payloadHash),state:'reserved',ownerToken,leaseUntil:leaseUntil.getTime(),expiresAt:at+ttlMs,updatedAt:at});return Object.freeze({ok:true,replay:false,owner:true,ownerToken,keyHash:key,state:'reserved'})
}
export async function readQl7SupportIdempotency({database=null,keyHash=''}={}){const key=str(keyHash);if(!key)return null;if(database?.collection)return database.collection('ql7_support_http_idempotency').findOne({_id:key});return mem.get(key)||null}
export async function waitForQl7SupportIdempotency({database=null,keyHash='',timeoutMs=30_000,pollMs=300,now=Date.now}={}){const started=Number(now()),deadline=started+Math.max(250,Number(timeoutMs)||30_000);while(Number(now())<=deadline){const row=await readQl7SupportIdempotency({database,keyHash});if(row?.state==='committed'&&row?.result)return Object.freeze({state:'committed',result:row.result,resultHash:str(row.resultHash)});await sleep(Math.max(50,Math.min(1_000,Number(pollMs)||300)))}return Object.freeze({state:'timeout',result:null})}
export async function commitQl7SupportIdempotency({database=null,keyHash='',result=null,ownerToken=''}={}){const key=str(keyHash),owner=str(ownerToken),query=owner?{_id:key,ownerToken:owner,state:'reserved'}:{_id:key};if(database?.collection){const committedAt=new Date();const write=await database.collection('ql7_support_http_idempotency').updateOne(query,{$set:{state:'committed',result,resultHash:h(JSON.stringify(result??null)),committedAt,updatedAt:committedAt},$unset:{leaseUntil:''}},{upsert:false});if(owner&&Number(write?.matchedCount||0)!==1){const e=new Error('support_idempotency_fencing_conflict');e.code='support_idempotency_fencing_conflict';e.status=409;throw e}return}const row=mem.get(key)||{};if(owner&&row.ownerToken!==owner){const e=new Error('support_idempotency_fencing_conflict');e.code='support_idempotency_fencing_conflict';e.status=409;throw e}mem.set(key,{...row,state:'committed',result,resultHash:h(JSON.stringify(result??null)),committedAt:Date.now(),leaseUntil:0})}
