import {buildQl7SupportBadges} from './badgePolicy.js'
import {selectQl7SupportSvg} from './svgRegistry.js'
import {buildQl7SupportTables} from './tableRegistry.js'
import {ql7Locale, ql7StableHash, ql7Str} from '../internal/text.js'
import {getQl7NativeCopy} from '../language/nativeBanks.js'
import {getQl7SupportTopicAction} from '../topicActionRegistry.js'
import {QL7_SUPPORT_SURFACE_COPY_REGISTRY_VERSION} from '../language/supportSurfaceCopyRegistry.js'
import {compactQl7SupportSurfaceRedundancy} from '../response/surfaceRedundancyGuard.js'
import {evaluateQl7SurfaceSemanticDensity} from './surfaceSemanticDensity.js'
import {placeQl7Propositions} from './propositionPlacement.js'
export const QL7_SUPPORT_SURFACE_VERSION='15.2.0'
const THEMES={gratitude:'warm-aurora',greeting:'cosmic-welcome',humor:'playful-neon',emotional_support:'calm-aurora',qcoin:'verified-emerald',vip:'vip-amethyst',ads_package:'ads-gold-cyan',ads_metrics:'analytics-cyan',ai_recommendation:'analytics-cyan',payment:'verified-blue',warning:'boundary-orange',blocked:'safety-red',threat:'security-red',operator:'operator-violet',unavailable:'unavailable-cyan',choice:'choice-blue',identity:'identity-indigo',partnership:'partnership-gold',investment:'investment-gold'}
function statusFor(plan,locale){const c=getQl7NativeCopy(locale).surface;if(plan.safetyBoundary?.category==='insult_uncertain')return{code:'clarify',label:c.details,tone:'info'};if(plan.safetyBoundary?.category==='insult_denied')return null;if(plan.safetyBoundary?.category==='credible_threat')return{code:'blocked',label:c.blocked30,tone:'danger'};if(plan.safetyBoundary?.category==='direct_insult'&&plan.safetyBoundary.cooldownMs)return{code:'blocked',label:c.blocked,tone:'warning'};if(plan.resultKind==='unavailable')return{code:'unavailable',label:c.unavailable,tone:'neutral'};return null}
function choicesAsOptions(plan){return plan?.choices?.options?.map((o)=>({id:o.id,label:o.label,description:o.description||'',semantic:{topic:o.topic,subIntent:o.intent,caseId:o.caseId||''},choiceSetId:plan.choices.id,signedToken:o.signedToken,token:o.signedToken,expiresAt:o.expiresAt,oneTime:o.oneTime}))||[]}
const VIP_ACTIVATE_LABELS={en:'Activate VIP',ru:'Активировать VIP',uk:'Активувати VIP',es:'Activar VIP',tr:'VIP etkinleştir',ar:'تفعيل VIP',zh:'激活 VIP',he:'הפעלת VIP'}
function actionsFor(plan={},locale='en'){const act=ql7Str(plan.messageAct);if(plan.choices||plan.safetyBoundary)return[];const result=plan.receipt?.result&&typeof plan.receipt.result==='object'?plan.receipt.result:{};if(plan.topic==='exchange_ai'&&(result.quotaState==='exhausted'||result.canAnalyze===false)){const vip=getQl7SupportTopicAction('vip',{locale,seed:`${plan.seed}:surface-action:vip`,kind:'primary'});return vip?[{...vip,label:VIP_ACTIVATE_LABELS[locale]||VIP_ACTIVATE_LABELS.en,iconKey:'crown'}]:[]}if(!['informational_question','how_to_question','why_question','when_question','roadmap_question','personal_status_request','ai_recommendation_request'].includes(act)&&plan.resultKind!=='verified'&&plan.resultKind!=='verified_empty')return[];const action=getQl7SupportTopicAction(plan.topic,{locale,seed:`${plan.seed}:surface-action`,kind:'primary'});return action?[action]:[]}
function deliveryTableFor(tables=[],topic='',title='',native={}){
 const first=tables[0];if(!first)return null
 if(topic!=='ads_campaigns')return{schema:ql7Str(first.schema),title:first.title,columns:[{key:'label',label:native.surface?.field||'Field'},{key:'value',label:native.surface?.value||'Value'}],rows:first.rows}
 const sourceKeys=['campaign','status','views','clicks','ctr','spend','regions','updated'];const rowMaps=tables.map((table,index)=>{const values=Object.fromEntries((Array.isArray(table?.rows)?table.rows:[]).map((row)=>[ql7Str(row?.key),row]));const out={key:`campaign-${index+1}`};for(const key of sourceKeys){const source=values[key];if(source&&source.value!==undefined&&source.value!==null&&source.value!=='')out[key]=source.value}if(!out.campaign)out.campaign=ql7Str(table?.title);return out})
 const labelFor=(key)=>{for(const table of tables){const source=(Array.isArray(table?.rows)?table.rows:[]).find((row)=>ql7Str(row?.key)===key);if(ql7Str(source?.label))return ql7Str(source.label)}return key}
 const formatFor=(key)=>{for(const table of tables){const source=(Array.isArray(table?.rows)?table.rows:[]).find((row)=>ql7Str(row?.key)===key);if(ql7Str(source?.format))return ql7Str(source.format)}return'text'}
 const columns=sourceKeys.filter((key)=>rowMaps.some((row)=>row[key]!==undefined&&row[key]!==null&&row[key]!=='')).map((key)=>({key,label:labelFor(key),format:formatFor(key)}))
 return{title:ql7Str(title)||ql7Str(native.surface?.confirmed)||ql7Str(first.title),schema:'ql7.table.ads.campaigns.matrix',layout:'matrix',columns,rows:rowMaps}
}
export function buildQl7SupportSurface({plan={},realized={},text='',locale='en',receipts=[],conversationState={},requestContext={}}={}){
 const lang=ql7Locale(locale);const native=getQl7NativeCopy(lang);const body=ql7Str(realized.text||text);const title=ql7Str(realized.title);const explicitSummary=ql7Str(realized.summary);const summary=explicitSummary||(title.toLowerCase()===body.toLowerCase()?'':body);const svg=selectQl7SupportSvg({role:plan.semanticRole,recentAssetIds:conversationState?.recentSvgAssetIds,seed:`${plan.seed}:${requestContext?.requestId||requestContext?.caseId||''}`,mood:plan.mood,severity:plan.severity});const tables=buildQl7SupportTables({topic:plan.topic,receipt:plan.receipt,locale:lang,factProjection:plan.factProjection});const deliveryTable=deliveryTableFor(tables,plan.topic,title,native);const badges=buildQl7SupportBadges({plan,locale:lang});const status=statusFor(plan,lang);const checkedAt=plan.eventEnvelope?'':plan.receipt&&['verified','verified_empty','inconsistent'].includes(plan.receipt.resultKind)?ql7Str(plan.receipt.checkedAt):'';const options=choicesAsOptions(plan)
 const actions=actionsFor(plan,lang);const rawSurface={schema:'ql7.support.surface',schemaVersion:15,surfaceKind:plan.surfaceKind||'compact',kind:realized.eventPresentation?.snapshot?'moderation_snapshot':plan.choices?'clarification_choices':plan.surfaceKind,purpose:plan.choices?'choice':plan.semanticRole||'notice',topic:plan.topic,semanticRole:plan.semanticRole,mood:plan.mood,severity:plan.severity,locale:lang,title,summary:summary&&summary.toLowerCase()!==title.toLowerCase()?summary:'',status,primarySvg:svg,svgAssetId:svg.assetId,semanticIcon:plan.semanticRole,visualTheme:THEMES[plan.semanticRole]||'knowledge-blue',badges,sections:[],tables,table:deliveryTable,snapshot:realized.eventPresentation?.snapshot||null,actions,options,other:plan.choices?{id:plan.choices.other?.id||'other',label:plan.choices.other?.label||native.surface.other,placeholder:plan.choices.other?.placeholder||native.surface.placeholder,semantic:{topic:'other',subIntent:'other'},choiceSetId:plan.choices.id,signedToken:plan.choices.other?.signedToken,token:plan.choices.other?.signedToken,expiresAt:plan.choices.other?.expiresAt,oneTime:plan.choices.other?.oneTime}:null,checkedAt,factProjection:plan.factProjection||null,translation:{locale:lang,coveragePercent:100,failedStrings:0,copyRegistryVersion:QL7_SUPPORT_SURFACE_COPY_REGISTRY_VERSION,signature:ql7StableHash(`${lang}:${body}:${title}`)},integrityBlock:{surfaceHash:ql7StableHash(JSON.stringify({title,body,svg:svg.assetId,tables,table:deliveryTable,badges,actions,snapshot:realized.eventPresentation?.snapshot||null}))},labels:{checked:native.surface.checked,confirmed:native.surface.confirmed,details:native.surface.details},generatedAt:ql7Str(requestContext?.now)||new Date().toISOString()}
 const compacted=compactQl7SupportSurfaceRedundancy(rawSurface,{bodyText:body});const entities=[plan.topic==='qcoin'?'QCoin':plan.topic==='vip'?'VIP':plan.topic?.startsWith('ads_')?'Ads':''].filter(Boolean);const semanticDensity=evaluateQl7SurfaceSemanticDensity(compacted,entities);return Object.freeze({...compacted,semanticDensity,propositionPlacement:placeQl7Propositions(realized.propositions||[])})
}
export function buildQl7SupportSurfaceSpec(input={}){const plan=input.plan||input.replyPlan?.contentPlan||{};const realized={text:input.text||input.replyPlan?.text||'',title:plan.title||input.replyPlan?.title||'',summary:plan.summary||''};return buildQl7SupportSurface({plan,realized,locale:input.locale,receipts:input.receipts,conversationState:input.conversationState,requestContext:input.requestContext})}
