import { buildQl7SupportBadges } from './badgePolicy.js'
import { selectQl7SupportSvg } from './svgRegistry.js'
import { buildQl7SupportTables } from './tableRegistry.js'
import { ql7Locale, ql7StableHash, ql7Str } from '../internal/text.js'
import { getQl7NativeCopy } from '../language/nativeBanks.js'
import { getQl7SupportTopicActionV9 } from '../topicActionRegistryV9.js'
export const QL7_SUPPORT_SURFACE_VERSION='14.11.0'
const THEMES={gratitude:'warm-aurora',greeting:'cosmic-welcome',humor:'playful-neon',emotional_support:'calm-aurora',qcoin:'verified-emerald',vip:'vip-amethyst',ads_package:'ads-gold-cyan',ads_metrics:'analytics-cyan',ai_recommendation:'analytics-cyan',payment:'verified-blue',warning:'boundary-orange',blocked:'safety-red',threat:'security-red',operator:'operator-violet',unavailable:'unavailable-cyan',choice:'choice-blue',identity:'identity-indigo',partnership:'partnership-gold',investment:'investment-gold'}
function statusFor(plan,locale){const c=getQl7NativeCopy(locale).surface;if(plan.safetyBoundary?.category==='insult_uncertain')return{code:'clarify',label:c.details,tone:'info'};if(plan.safetyBoundary?.category==='insult_denied')return null;if(plan.safetyBoundary?.category==='credible_threat')return{code:'blocked',label:c.blocked30,tone:'danger'};if(plan.safetyBoundary?.category==='direct_insult'&&plan.safetyBoundary.cooldownMs)return{code:'blocked',label:c.blocked,tone:'warning'};if(plan.resultKind==='unavailable')return{code:'unavailable',label:c.unavailable,tone:'neutral'};return null}
function choicesAsOptions(plan){return plan?.choices?.options?.map((o)=>({id:o.id,label:o.label,semantic:{topic:o.topic,subIntent:o.intent},choiceSetId:plan.choices.id,signedToken:o.signedToken,token:o.signedToken,expiresAt:o.expiresAt,oneTime:o.oneTime}))||[]}
const VIP_ACTIVATE_LABELS={en:'Activate VIP',ru:'Активировать VIP',uk:'Активувати VIP',es:'Activar VIP',tr:'VIP etkinleştir',ar:'تفعيل VIP',zh:'激活 VIP',he:'הפעלת VIP'}
function actionsFor(plan={},locale='en'){const act=ql7Str(plan.messageAct);if(plan.choices||plan.safetyBoundary)return[];const result=plan.receipt?.result&&typeof plan.receipt.result==='object'?plan.receipt.result:{};if(plan.topic==='exchange_ai'&&(result.quotaState==='exhausted'||result.canAnalyze===false)){const vip=getQl7SupportTopicActionV9('vip',{locale,seed:`${plan.seed}:surface-action:vip`,kind:'primary'});return vip?[{...vip,label:VIP_ACTIVATE_LABELS[locale]||VIP_ACTIVATE_LABELS.en,iconKey:'crown'}]:[]}if(!['informational_question','how_to_question','why_question','when_question','roadmap_question','personal_status_request','ai_recommendation_request'].includes(act)&&plan.resultKind!=='verified'&&plan.resultKind!=='verified_empty')return[];const action=getQl7SupportTopicActionV9(plan.topic,{locale,seed:`${plan.seed}:surface-action`,kind:'primary'});return action?[action]:[]}
export function buildQl7SupportSurface({plan={},realized={},text='',locale='en',receipts=[],ledger={},requestContext={}}={}){
 const lang=ql7Locale(locale);const native=getQl7NativeCopy(lang);const body=ql7Str(realized.text||text);const title=ql7Str(realized.title);const explicitSummary=ql7Str(realized.summary);const summary=explicitSummary||(title.toLowerCase()===body.toLowerCase()?'':body);const svg=selectQl7SupportSvg({role:plan.semanticRole,recentAssetIds:ledger?.recentSvgAssetIds,seed:`${plan.seed}:${requestContext?.requestId||requestContext?.caseId||''}`,mood:plan.mood,severity:plan.severity});const tables=buildQl7SupportTables({topic:plan.topic,receipt:plan.receipt,locale:lang,factProjection:plan.factProjection});const badges=buildQl7SupportBadges({plan,locale:lang});const status=statusFor(plan,lang);const checkedAt=plan.receipt&&['verified','verified_empty','inconsistent'].includes(plan.receipt.resultKind)?ql7Str(plan.receipt.checkedAt):'';const options=choicesAsOptions(plan)
 const actions=actionsFor(plan,lang);const surface={schema:'ql7.support.surface',schemaVersion:15,surfaceKind:plan.surfaceKind||'compact',kind:plan.choices?'clarification_choices':plan.surfaceKind,purpose:plan.choices?'choice':plan.semanticRole||'notice',topic:plan.topic,semanticRole:plan.semanticRole,mood:plan.mood,severity:plan.severity,locale:lang,title,summary:summary&&summary.toLowerCase()!==title.toLowerCase()?summary:'',status,primarySvg:svg,svgAssetId:svg.assetId,semanticIcon:plan.semanticRole,visualTheme:THEMES[plan.semanticRole]||'knowledge-blue',badges,sections:[],tables,table:tables[0]?{title:tables[0].title,columns:[{key:'label',label:native.surface.field},{key:'value',label:native.surface.value}],rows:tables[0].rows}:null,actions,options,other:plan.choices?{id:plan.choices.other?.id||'other',label:plan.choices.other?.label||native.surface.other,placeholder:plan.choices.other?.placeholder||native.surface.placeholder,semantic:{topic:'other',subIntent:'other'},choiceSetId:plan.choices.id,signedToken:plan.choices.other?.signedToken,token:plan.choices.other?.signedToken,expiresAt:plan.choices.other?.expiresAt,oneTime:plan.choices.other?.oneTime}:null,checkedAt,factProjection:plan.factProjection||null,translation:{locale:lang,coveragePercent:100,failedStrings:0,signature:ql7StableHash(`${lang}:${body}:${title}`)},integrityBlock:{surfaceHash:ql7StableHash(JSON.stringify({title,body,svg:svg.assetId,tables,badges,actions}))},labels:{checked:native.surface.checked,confirmed:native.surface.confirmed,details:native.surface.details},generatedAt:new Date().toISOString()}
 return Object.freeze(surface)
}
export function buildQl7SupportSurfaceSpecV13(input={}){const plan=input.plan||input.replyPlan?.contentPlan||{};const realized={text:input.text||input.replyPlan?.text||'',title:plan.title||input.replyPlan?.title||'',summary:plan.summary||''};return buildQl7SupportSurface({plan,realized,locale:input.locale,receipts:input.receipts,ledger:input.ledger,requestContext:input.requestContext})}
