import {QL7_SUPPORT_ALL_LOCALES} from '../config/behaviorManifest.js'
export const QL7_SUPPORT_CHOICE_LOCALE_LEXICON_VERSION='1.0.0'
const OTHER=Object.freeze({
 en:'Other',ru:'Другое',uk:'Інше',es:'Otro',tr:'Diğer',ar:'أخرى',zh:'其他',he:'אחר',de:'Andere',fr:'Autre',it:'Altro',pt:'Outro',pl:'Inne',nl:'Anders',sv:'Annat',no:'Annet',da:'Andet',fi:'Muu',cs:'Jiné',sk:'Iné',hu:'Más',ro:'Altceva',bg:'Друго',sr:'Drugo',hr:'Drugo',sl:'Drugo',el:'Άλλο',ka:'სხვა',az:'Digər',kk:'Басқа',ja:'その他',ko:'기타'
})
const PLACEHOLDER=Object.freeze({
 en:'Tell me a little more about what you mean.',ru:'Расскажите чуть подробнее, что именно вы имеете в виду.',uk:'Розкажіть трохи докладніше, що саме ви маєте на увазі.',es:'Cuéntame un poco más qué quieres decir.',tr:'Ne demek istediğinizi biraz daha anlatın.',ar:'وضّح لي قليلاً ما الذي تقصده تحديداً.',zh:'请再具体说明一下你的意思。',he:'ספרו קצת יותר למה בדיוק התכוונתם.',de:'Beschreiben Sie bitte etwas genauer, was Sie meinen.',fr:'Précisez un peu ce que vous voulez dire.',it:'Spiega un po’ meglio che cosa intendi.',pt:'Explique um pouco melhor o que você quer dizer.',pl:'Napisz trochę dokładniej, co masz na myśli.',nl:'Vertel iets preciezer wat je bedoelt.',sv:'Berätta lite mer exakt vad du menar.',no:'Fortell litt mer presist hva du mener.',da:'Fortæl lidt mere præcist, hvad du mener.',fi:'Kerro hieman tarkemmin, mitä tarkoitat.',cs:'Upřesněte prosím, co přesně myslíte.',sk:'Upresnite prosím, čo presne myslíte.',hu:'Írd le kicsit pontosabban, mire gondolsz.',ro:'Spune puțin mai clar la ce te referi.',bg:'Уточнете малко по-подробно какво имате предвид.',sr:'Objasnite malo preciznije na šta mislite.',hr:'Objasnite malo preciznije na što mislite.',sl:'Malo natančneje povejte, kaj imate v mislih.',el:'Πείτε λίγο πιο συγκεκριμένα τι εννοείτε.',ka:'ცოტა უფრო ზუსტად აღწერეთ, რას გულისხმობთ.',az:'Nəyi nəzərdə tutduğunuzu bir az daha dəqiq yazın.',kk:'Нені меңзеп тұрғаныңызды сәл нақтырақ жазыңыз.',ja:'何を意味しているのか、もう少し具体的に教えてください。',ko:'무엇을 의미하는지 조금 더 구체적으로 알려 주세요.'
})
function localeOf(value='en'){const v=String(value||'en').trim().toLowerCase().split(/[-_]/u)[0];return QL7_SUPPORT_ALL_LOCALES.includes(v)?v:'en'}
export function localizeQl7ChoiceOther(locale='en'){const l=localeOf(locale);return Object.freeze({locale:l,label:OTHER[l],placeholder:PLACEHOLDER[l],version:QL7_SUPPORT_CHOICE_LOCALE_LEXICON_VERSION})}
export function auditQl7ChoiceLocaleLexicon(){const failures=[];for(const locale of QL7_SUPPORT_ALL_LOCALES){if(!OTHER[locale])failures.push(`missing-other:${locale}`);if(!PLACEHOLDER[locale])failures.push(`missing-placeholder:${locale}`);if(locale!=='en'&&(OTHER[locale]===OTHER.en||PLACEHOLDER[locale]===PLACEHOLDER.en))failures.push(`english-fallback:${locale}`)}return Object.freeze({ok:failures.length===0,localeCount:QL7_SUPPORT_ALL_LOCALES.length,failures:Object.freeze(failures)})}
