import {ql7Str} from '../internal/text.js'
import {getQl7NativeCopy} from '../language/nativeBanks.js'
function lang(locale='en'){return ql7Str(locale).toLowerCase().split(/[-_]/u)[0]||'en'}
function humanDate(value=''){const raw=ql7Str(value);if(!raw)return'';const date=new Date(raw);if(Number.isNaN(date.getTime()))return raw;try{return new Intl.DateTimeFormat(undefined,{year:'numeric',month:'long',day:'numeric'}).format(date)}catch{return date.toISOString().slice(0,10)}}
function cellValue(value,format='text'){return format==='datetime'?humanDate(value):value}
function row(key,label,value,format='text',tone='neutral'){return value===undefined||value===null||value===''?null:{key,label,value:cellValue(value,format),format,tone}}
function rows(...values){return values.filter(Boolean)}
function result(receipt={}){const raw=receipt?.result&&typeof receipt.result==='object'?receipt.result:{};const evidence=raw?.evidence&&typeof raw.evidence==='object'?raw.evidence:{};return Object.freeze({...raw,...evidence})}
const AI_LABELS=Object.freeze({
 en:{symbol:'Symbol',timeframe:'Timeframe',price:'Price',scenario:'Scenario',confidence:'Confidence',entry:'Entry area',stopLoss:'Risk stop',takeProfit:'Targets',quota:'AI quota',source:'Source route',disclaimer:'Warning',htfTrend:'Higher-timeframe trend',risk:'Risk score',spread:'Venue spread',support:'Support levels',resistance:'Resistance levels',checked:'Checked',noAdvice:'Educational analytics only. This is not financial advice.'},
 ru:{symbol:'Монета',timeframe:'Таймфрейм',price:'Цена',scenario:'Сценарий',confidence:'Уверенность',entry:'Зона входа',stopLoss:'Риск-стоп',takeProfit:'Цели',quota:'AI-квота',source:'Маршрут источника',disclaimer:'Предупреждение',htfTrend:'Тренд старших ТФ',risk:'Риск',spread:'Спред площадок',support:'Уровни поддержки',resistance:'Уровни сопротивления',checked:'Проверено',noAdvice:'Только обучающая аналитика. Это не финансовый совет.'},
 uk:{symbol:'Монета',timeframe:'Таймфрейм',price:'Ціна',scenario:'Сценарій',confidence:'Впевненість',entry:'Зона входу',stopLoss:'Ризик-стоп',takeProfit:'Цілі',quota:'AI-квота',source:'Маршрут джерела',disclaimer:'Попередження',htfTrend:'Тренд старших ТФ',risk:'Ризик',spread:'Спред майданчиків',support:'Рівні підтримки',resistance:'Рівні опору',checked:'Перевірено',noAdvice:'Лише навчальна аналітика. Це не фінансова порада.'},
 es:{symbol:'Símbolo',timeframe:'Temporalidad',price:'Precio',scenario:'Escenario',confidence:'Confianza',entry:'Zona de entrada',stopLoss:'Stop de riesgo',takeProfit:'Objetivos',quota:'Cuota AI',source:'Ruta fuente',disclaimer:'Aviso',htfTrend:'Tendencia marco superior',risk:'Riesgo',spread:'Diferencial entre mercados',support:'Soportes',resistance:'Resistencias',checked:'Comprobado',noAdvice:'Solo analítica educativa. No es asesoramiento financiero.'},
 tr:{symbol:'Sembol',timeframe:'Zaman dilimi',price:'Fiyat',scenario:'Senaryo',confidence:'Güven',entry:'Giriş alanı',stopLoss:'Risk stopu',takeProfit:'Hedefler',quota:'AI kotası',source:'Kaynak rotası',disclaimer:'Uyarı',htfTrend:'Üst zaman trendi',risk:'Risk',spread:'Piyasa farkı',support:'Destek seviyeleri',resistance:'Direnç seviyeleri',checked:'Kontrol edildi',noAdvice:'Yalnızca eğitim amaçlı analiz. Finansal tavsiye değildir.'},
 ar:{symbol:'الرمز',timeframe:'الإطار الزمني',price:'السعر',scenario:'السيناريو',confidence:'الثقة',entry:'منطقة الدخول',stopLoss:'إيقاف المخاطر',takeProfit:'الأهداف',quota:'حصة AI',source:'مسار المصدر',disclaimer:'تنبيه',htfTrend:'اتجاه الإطار الأعلى',risk:'درجة المخاطر',spread:'فارق المنصات',support:'مستويات الدعم',resistance:'مستويات المقاومة',checked:'تم التحقق',noAdvice:'تحليل تعليمي فقط. ليست نصيحة مالية.'},
 zh:{symbol:'交易对',timeframe:'周期',price:'价格',scenario:'情景',confidence:'置信度',entry:'入场区域',stopLoss:'风险止损',takeProfit:'目标',quota:'AI 配额',source:'来源路径',disclaimer:'提示',htfTrend:'高周期趋势',risk:'风险评分',spread:'平台价差',support:'支撑位',resistance:'阻力位',checked:'已检查',noAdvice:'仅作教育性分析，不是财务建议。'},
 he:{symbol:'סימול',timeframe:'טווח זמן',price:'מחיר',scenario:'תרחיש',confidence:'ביטחון',entry:'אזור כניסה',stopLoss:'עצירת סיכון',takeProfit:'יעדים',quota:'מכסת AI',source:'נתיב מקור',disclaimer:'אזהרה',htfTrend:'מגמת טווח גבוה',risk:'ציון סיכון',spread:'פער בין זירות',support:'רמות תמיכה',resistance:'רמות התנגדות',checked:'נבדק',noAdvice:'ניתוח לימודי בלבד. זה לא ייעוץ פיננסי.'},
})
function aiLabels(locale='en'){return AI_LABELS[lang(locale)]||AI_LABELS.en}
const AI_SOURCE_COPY=Object.freeze({
 en:'AI Box, Exchange market route and quota/VIP entitlement',
 ru:'AI Box, рыночный контур биржи и доступ по квоте/VIP',
 uk:'AI Box, ринковий контур біржі та доступ за квотою/VIP',
 es:'AI Box, ruta de mercado del exchange y acceso por cuota/VIP',
 tr:'AI Box, borsa piyasa yolu ve kota/VIP erişimi',
 ar:'AI Box ومسار السوق في المنصة وإتاحة الحصة/VIP',
 zh:'AI Box、交易所市场路径与配额/VIP 权限',
 he:'AI Box, נתיב שוק הבורסה וזכאות מכסה/VIP',
})
function aiSource(locale='en'){return AI_SOURCE_COPY[lang(locale)]||AI_SOURCE_COPY.en}
export function buildQl7SupportTables({topic='',receipt=null,locale='en',factProjection=null}={}){
 if(!receipt||!['verified','verified_empty','inconsistent'].includes(receipt.resultKind))return Object.freeze([]);const copy=getQl7NativeCopy(locale);const l=copy.table;const projected=factProjection?.facts&&typeof factProjection.facts==='object'?factProjection.facts:null;const data=projected?{...(projected.sourceData||{}),...projected}:result(receipt)
 if(topic==='qcoin')return Object.freeze([{id:'qcoin-account',schema:'ql7.table.qcoin',title:lang(locale)==='ru'?'QCoin':'QCoin',rows:rows(row('balance',l.balance,data.balance??data.amount,'decimal','success'),row('available',l.available,data.available,'decimal'),row('pending',l.pending,data.pending,'decimal'),row('updated',l.updated,receipt.checkedAt,'datetime'))}])
 if(topic==='vip')return Object.freeze([{id:'vip-status',schema:'ql7.table.vip',title:'VIP',rows:rows(row('status',l.status,data.status??(data.active===true?'active':data.active===false?'inactive':'')),row('tier',l.tier,data.tier??data.plan),row('expiry',l.expiry,data.expiry??data.expiresAt,'datetime'),row('benefits',l.benefits,Array.isArray(data.benefits)?data.benefits.join(', '):data.benefits))}])
 if(topic==='ads_packages')return Object.freeze([{id:'ads-package',schema:'ql7.table.ads.package',title:l.adsPackage,rows:rows(row('package',l.package,data.packageName??data.package??data.tier),row('status',l.status,data.status??data.packageStatus),row('slots',l.slots,data.usedSlots!==undefined&&data.slotLimit!==undefined?`${data.usedSlots}/${data.slotLimit}`:data.slots),row('activeCampaigns',l.activeCampaigns,data.activeCampaignCount??data.activeCampaigns??0,'integer'),row('updated',l.updated,receipt.checkedAt,'datetime'))}])
 if(topic==='ads_campaigns'){const campaigns=Array.isArray(data.campaigns)&&data.campaigns.length?data.campaigns:Array.isArray(data.campaignRows)&&data.campaignRows.length?data.campaignRows:(data.name||data.campaignName?[data]:[]);return Object.freeze(campaigns.slice(0,12).map((c,i)=>({id:`ads-campaign-${i+1}`,schema:'ql7.table.ads.campaign',title:ql7Str(c.name||c.campaignName)||`${l.campaign} ${i+1}`,rows:rows(row('campaign',l.campaign,c.name??c.campaignName),row('status',l.status,c.status),row('views',l.views,c.views??c.impressions,'integer'),row('clicks',l.clicks,c.clicks,'integer'),row('ctr',l.ctr,c.ctr,'percent'),row('spend',l.spend,c.spend,'decimal'),row('regions',l.regions,Array.isArray(c.regions)?c.regions.join(', '):c.regions),row('updated',l.updated,c.updatedAt??receipt.checkedAt,'datetime'))})))}
 if(topic==='payments')return Object.freeze([{id:'payment',schema:'ql7.table.payment',title:l.payment,rows:rows(row('status',l.status,data.status??data.paymentStatus),row('amount',l.amount,data.amount,'decimal'),row('currency',l.currency,data.currency),row('updated',l.updated,data.updatedAt??receipt.checkedAt,'datetime'))}])
 if(topic==='exchange_ai'){const a=aiLabels(locale);const quota=data.quotaState==='exhausted'?`${data.usedSec??data.limitSec??0}/${data.limitSec??0} sec`:data.quotaState||data.entitlement||data.mode||'available';const targets=[data.tp1,data.tp2,data.target1,data.target2].filter(v=>v!==undefined&&v!==null&&v!=='').join(' / ');const support=Array.isArray(data.support)?data.support.slice(0,6).join(' / '):data.support;const resistance=Array.isArray(data.resistance)?data.resistance.slice(0,6).join(' / '):data.resistance;const htfTrend=data.htfTrend!==undefined?Number(data.htfTrend).toFixed(3):undefined;const spread=data.venueSpread!==undefined&&data.venueSpread!==null?`${(Number(data.venueSpread)*100).toFixed(3)}%`:undefined;const risk=data.riskScore!==undefined?`${Number(data.riskScore).toFixed(0)}/100`:undefined;return Object.freeze([{id:'ai-recommendation',schema:'ql7.table.ai.recommendation.canonical',title:'AI Box Analytics',rows:rows(row('symbol',a.symbol,data.symbol),row('timeframe',a.timeframe,data.timeframe??data.tf),row('price',a.price,data.price,'decimal','info'),row('scenario',a.scenario,data.action??data.recommendation??data.signal),row('confidence',a.confidence,data.confidence!==undefined?`${data.confidence}%`:undefined,'percent','success'),row('htfTrend',a.htfTrend,htfTrend),row('risk',a.risk,risk,'text',Number(data.riskScore||0)>=70?'warning':'neutral'),row('spread',a.spread,spread),row('support',a.support,support),row('resistance',a.resistance,resistance),row('entry',a.entry,data.entry??data.entryArea,'decimal'),row('stopLoss',a.stopLoss,data.sl??data.stopLoss,'decimal','warning'),row('takeProfit',a.takeProfit,targets),row('quota',a.quota,quota,'text',data.quotaState==='exhausted'?'warning':'success'),row('source',a.source,aiSource(locale)),row('checked',a.checked,data.checkedAt??receipt.checkedAt,'datetime'),row('disclaimer',a.disclaimer,data.disclaimer||a.noAdvice||a.noAdvice,'text','warning'))}])}
 if(topic==='profile'||topic==='rating')return Object.freeze([{id:'profile-activity',schema:'ql7.table.profile',title:l.profile,rows:rows(row('nickname',l.nickname,data.nickname),row('locale',l.locale,data.locale),row('created',l.created,data.createdAt,'datetime'),row('lastActivity',l.lastActivity,data.lastActivityAt,'datetime'),row('posts',l.posts,data.activity?.posts,'integer'),row('topics',l.topics,data.activity?.topics,'integer'),row('likes',l.likes,data.activity?.likes,'integer'),row('followers',l.followers,data.activity?.followers,'integer'),row('following',l.following,data.activity?.following,'integer'),row('rating',l.rating,data.rating?.value!==undefined?`${data.rating.value}/100`:undefined),row('confidence',l.confidence,data.rating?.confidence!==undefined?`${data.rating.confidence}%`:undefined),row('positiveFactors',l.positiveFactors,Array.isArray(data.rating?.positiveContributors)?data.rating.positiveContributors.map(x=>`${x.key}: +${x.points}`).join('; '):undefined),row('negativeFactors',l.negativeFactors,Array.isArray(data.rating?.negativeContributors)&&data.rating.negativeContributors.length?data.rating.negativeContributors.map(x=>`${x.key}: ${x.points}`).join('; '):undefined),row('missingSignals',l.missingSignals,Array.isArray(data.rating?.missingData)&&data.rating.missingData.length?data.rating.missingData.join(', '):undefined))}])
 if(topic==='forum'||topic==='forum_feed'||topic==='forum_threads')return Object.freeze([{id:'forum-activity',schema:'ql7.table.forum.activity',title:l.forum,rows:rows(row('posts',l.posts,data.posts,'integer'),row('topics',l.topics,data.topics,'integer'),row('likes',l.likes,data.likes,'integer'),row('followers',l.followers,data.followers,'integer'),row('following',l.following,data.following,'integer'))}])
 if(topic==='metamarket')return Object.freeze([{id:'metamarket-status',schema:'ql7.table.metamarket',title:'MetaMarket',rows:rows(row('ownedItems',l.ownedItems,data.ownedItems,'integer'),row('events',l.events,data.events,'integer'),row('updated',l.updated,receipt.checkedAt,'datetime'))}])
 if(topic==='telegram')return Object.freeze([{id:'telegram-link',schema:'ql7.table.telegram',title:'Telegram',rows:rows(row('linked',l.linked,data.linked===true?l.yes:l.no),row('telegramId',l.telegramId,data.links?.[0]?.telegramId))}])
 return Object.freeze([])
}

export function suppressRepeatedEntityTableTitles(tables=[],cardTitle=''){
 const norm=(v)=>String(v||'').normalize('NFKC').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim()
 const title=norm(cardTitle)
 return Object.freeze((tables||[]).map((table)=>Object.freeze({
  ...table,
  title:title&&norm(table?.title)===title?'':table?.title,
  rows:Object.freeze((table?.rows||[]).map((row)=>Object.freeze({
   ...row,
   label:title&&norm(row?.label)===title?'':row?.label,
  }))),
 })))
}
