import { useCallback } from 'react'
import { openInboxGlobalFlow } from '../utils/openInboxGlobal'

export default function useOpenInboxGlobalAction({
  inboxOpen,
  sel,
  threadRoot,
  videoFeedOpen,
  dmWithUserId,
  headAutoOpenRef,
  setHeadPinned,
  setHeadHidden,
  openOnly,
  closeUserInfoPopover,
  closeReportPopover,
  setDmDeletePopover,
  setDmDeleteForAll,
  setInboxTab,
  setDmWithUserId,
  requestAlignInboxStartUnderTabs,
  setInboxOpen,
  pushNavStateStable,
  closeVideoFeed,
  setReplyTo,
  setThreadRoot,
  setSel,
  closeQuests,
}) {
  return useCallback((entryId) => {
    openInboxGlobalFlow(entryId, {
      inboxOpen,
      sel,
      threadRoot,
      videoFeedOpen,
      dmWithUserId,
      headAutoOpenRef,
      setHeadPinned,
      setHeadHidden,
      openOnly,
      closeUserInfoPopover,
      closeReportPopover,
      setDmDeletePopover,
      setDmDeleteForAll,
      setInboxTab,
      setDmWithUserId,
      requestAlignInboxStartUnderTabs,
      setInboxOpen,
      pushNavStateStable,
      closeVideoFeed,
      setReplyTo,
      setThreadRoot,
      setSel,
      closeQuests,
    })
  }, [
    inboxOpen,
    sel,
    threadRoot,
    videoFeedOpen,
    dmWithUserId,
    headAutoOpenRef,
    setHeadPinned,
    setHeadHidden,
    openOnly,
    closeUserInfoPopover,
    closeReportPopover,
    setDmDeletePopover,
    setDmDeleteForAll,
    setInboxTab,
    setDmWithUserId,
    requestAlignInboxStartUnderTabs,
    setInboxOpen,
    pushNavStateStable,
    closeVideoFeed,
    setReplyTo,
    setThreadRoot,
    setSel,
    closeQuests,
  ])
}
