import crypto from 'node:crypto'
import {QL7_SUPPORT_DOMAIN_MODULES, QL7_SUPPORT_DOMAIN_MODULE_BY_ID} from './domains/index.js'
import {QL7_SUPPORT_RELEASE_DOMAIN_ROOTS, auditQl7SupportDomainOntology} from './domainOntology.js'
import {QL7_SUPPORT_MICROTOPICS, QL7_SUPPORT_MICROTOPIC_MANIFEST_HASH, auditQl7SupportMicrotopicOntology} from './microtopicOntology.js'
import {normalizeQl7SupportOntologyNode, QL7_SUPPORT_NODE_SCHEMA_VERSION} from './nodeSchemas.js'
import {createQl7SupportOntologyEdge, QL7_SUPPORT_EDGE_SCHEMA_VERSION} from './edgeSchemas.js'
import {QL7_SUPPORT_INTENT_ONTOLOGY_VERSION} from './intentOntology.js'
import {QL7_SUPPORT_SPEECH_ACT_ONTOLOGY_VERSION} from './speechActOntology.js'
import {QL7_SUPPORT_ENTITY_ONTOLOGY_VERSION} from './entityOntology.js'
import {QL7_SUPPORT_ACTION_ONTOLOGY_VERSION} from './actionOntology.js'
import {QL7_SUPPORT_EMOTION_ONTOLOGY_VERSION} from './emotionOntology.js'
import {QL7_SUPPORT_SAFETY_ONTOLOGY_VERSION} from './safetyOntology.js'
import {QL7_SUPPORT_SOURCE_CLAIM_ONTOLOGY_VERSION} from './sourceClaimOntology.js'
import {QL7_SUPPORT_MEMORY_ONTOLOGY_VERSION, auditQl7SupportMemoryOntology} from './memoryOntology.js'
import {validateQl7SupportOntology} from './ontologyValidator.js'
const stable=(v)=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v;const h=(v)=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex')
const nodes=[];const edges=[]
for(const mod of QL7_SUPPORT_DOMAIN_MODULES)nodes.push(...mod.nodes)
const sourceNodes=new Map(),statusNodes=new Map()
for(const row of QL7_SUPPORT_MICROTOPICS){const domain=QL7_SUPPORT_DOMAIN_MODULE_BY_ID[row.domainId];const canonicalLabel=`${row.domainId} ${row.intentId}`;const m=normalizeQl7SupportOntologyNode({nodeId:`microtopic:${row.microtopicId}`,nodeType:'MicrotopicNode',canonicalLabel,aliasesByLocale:{},parentIds:[`domain:${row.domainId}`],status:row.availability||domain?.nodes?.[0]?.status||'unknown',validFrom:'2026-08-15T00:00:00.000Z',validTo:'',sourceReceiptIds:[...(row.sourceRefs||[])],requiredEvidenceTypes:['source_receipt'],forbiddenClaims:['unverified_secondary_domain_insertion'],privacyClass:domain?.nodes?.[0]?.privacyClass||'public',ownerId:'ql7-support.ontology'});nodes.push(m);edges.push(createQl7SupportOntologyEdge({edgeId:`contains:${row.domainId}:${h(row.microtopicId).slice(0,16)}`,edgeType:'contains',fromNodeId:`domain:${row.domainId}`,toNodeId:m.nodeId}));for(const ref of row.sourceRefs||[]){const id=`source:${h(ref).slice(0,24)}`;if(!sourceNodes.has(id)){const s=normalizeQl7SupportOntologyNode({nodeId:id,nodeType:'SourceNode',canonicalLabel:String(ref),aliasesByLocale:{},parentIds:[],status:'available',validFrom:'2026-08-15T00:00:00.000Z',validTo:'',sourceReceiptIds:[String(ref)],requiredEvidenceTypes:[],forbiddenClaims:[],privacyClass:'internal',ownerId:'ql7-support.ontology'});sourceNodes.set(id,s);nodes.push(s)}edges.push(createQl7SupportOntologyEdge({edgeId:`supported:${h(`${m.nodeId}:${id}`).slice(0,24)}`,edgeType:'supported_by',fromNodeId:m.nodeId,toNodeId:id}))}const status=String(m.status||'unknown');const sid=`status:${status}`;if(!statusNodes.has(sid)){const s=normalizeQl7SupportOntologyNode({nodeId:sid,nodeType:'StatusNode',canonicalLabel:status,aliasesByLocale:{},parentIds:[],status,validFrom:'2026-08-15T00:00:00.000Z',validTo:'',sourceReceiptIds:[],requiredEvidenceTypes:[],forbiddenClaims:[],privacyClass:'public',ownerId:'ql7-support.ontology'});statusNodes.set(sid,s);nodes.push(s)}edges.push(createQl7SupportOntologyEdge({edgeId:`status:${h(`${m.nodeId}:${sid}`).slice(0,24)}`,edgeType:'has_status',fromNodeId:m.nodeId,toNodeId:sid}))}
export const QL7_SUPPORT_ONTOLOGY_NODES=Object.freeze(nodes);export const QL7_SUPPORT_ONTOLOGY_EDGES=Object.freeze(edges)
const contracts=Object.freeze({node:QL7_SUPPORT_NODE_SCHEMA_VERSION,edge:QL7_SUPPORT_EDGE_SCHEMA_VERSION,intent:QL7_SUPPORT_INTENT_ONTOLOGY_VERSION,speechAct:QL7_SUPPORT_SPEECH_ACT_ONTOLOGY_VERSION,entity:QL7_SUPPORT_ENTITY_ONTOLOGY_VERSION,action:QL7_SUPPORT_ACTION_ONTOLOGY_VERSION,emotion:QL7_SUPPORT_EMOTION_ONTOLOGY_VERSION,safety:QL7_SUPPORT_SAFETY_ONTOLOGY_VERSION,sourceClaim:QL7_SUPPORT_SOURCE_CLAIM_ONTOLOGY_VERSION,memory:QL7_SUPPORT_MEMORY_ONTOLOGY_VERSION})
const body={schema:'ql7.support.ontology-manifest',schemaVersion:'5.1.0',owner:'ql7-support.ontology',domainRoots:QL7_SUPPORT_RELEASE_DOMAIN_ROOTS,domainModuleIds:QL7_SUPPORT_DOMAIN_MODULES.map((r)=>r.domainId),microtopicCount:QL7_SUPPORT_MICROTOPICS.length,microtopicManifestHash:QL7_SUPPORT_MICROTOPIC_MANIFEST_HASH,nodeCount:nodes.length,edgeCount:edges.length,contracts,relationPolicy:'typed-versioned-source-gated-no-final-prose'}
export const QL7_SUPPORT_ONTOLOGY_MANIFEST=Object.freeze({...body,manifestHash:h(body),graphHash:h({nodes,edges})})
export function auditQl7SupportOntologyManifest(){const d=auditQl7SupportDomainOntology(),m=auditQl7SupportMicrotopicOntology(),mem=auditQl7SupportMemoryOntology(),v=validateQl7SupportOntology({nodes,edges});const failures=[...(d.failures||[]),...(m.failures||[]),...(mem.failures||[]),...(v.failures||[])];if(QL7_SUPPORT_ONTOLOGY_MANIFEST.domainModuleIds.length!==46)failures.push('domain_module_count');if(new Set(QL7_SUPPORT_ONTOLOGY_MANIFEST.domainModuleIds).size!==46)failures.push('domain_module_duplicate');return Object.freeze({ok:!failures.length,manifest:QL7_SUPPORT_ONTOLOGY_MANIFEST,validation:v,failures:Object.freeze(failures)})}
