import crypto from 'node:crypto'
export const QL7_COGNITIVE_PLAN_GRAPH_VERSION='1.0.0'
const TYPES=new Set(['EXPLAIN','RETRIEVE','READ','COMPARE','CLARIFY','SAFE_ACTION','HANDOFF','GENERATE'])
const STATES=new Set(['PENDING','SATISFIED','BLOCKED','SKIPPED'])
const h=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')
function cycle(nodes){const map=new Map(nodes.map(n=>[n.nodeId,n.dependsOn]));const visiting=new Set(),done=new Set();function go(id){if(done.has(id))return false;if(visiting.has(id))return true;visiting.add(id);for(const d of map.get(id)||[])if(map.has(d)&&go(d))return true;visiting.delete(id);done.add(id);return false}return nodes.some(n=>go(n.nodeId))}
export function createQl7PlanGraph({nodes=[],goalIds=[],constraintIds=[]}={}){
 const clean=(Array.isArray(nodes)?nodes:[]).map((n,i)=>Object.freeze({nodeId:String(n.nodeId||`p${i}`),type:TYPES.has(String(n.type))?String(n.type):'EXPLAIN',dependsOn:Object.freeze([...(n.dependsOn||[])].map(String)),requiredClaims:Object.freeze([...(n.requiredClaims||[])].map(String)),requiredReceipts:Object.freeze([...(n.requiredReceipts||[])].map(String)),forbiddenClaims:Object.freeze([...(n.forbiddenClaims||[])].map(String)),privacyClass:String(n.privacyClass||'public'),completionState:STATES.has(String(n.completionState))?String(n.completionState):'PENDING'}))
 const ids=new Set(clean.map(n=>n.nodeId));const invalidDeps=clean.flatMap(n=>n.dependsOn.filter(d=>!ids.has(d)).map(d=>`${n.nodeId}->${d}`));if(invalidDeps.length)throw Object.assign(new Error('plan_graph_unknown_dependency'),{invalidDeps});if(cycle(clean))throw new Error('plan_graph_cycle')
 const body={schema:'ql7.support.cognitive-plan-graph',schemaVersion:QL7_COGNITIVE_PLAN_GRAPH_VERSION,nodes:Object.freeze(clean),goalIds:Object.freeze([...goalIds].map(String)),constraintIds:Object.freeze([...constraintIds].map(String))};return Object.freeze({...body,planHash:h(body)})
}
export function verifyQl7PlanConstraints(plan={}, {availableClaims=[],availableReceipts=[],forbiddenClaims=[]}={}){const claims=new Set(availableClaims),receipts=new Set(availableReceipts),forbidden=new Set(forbiddenClaims);const failures=[];for(const n of plan.nodes||[]){for(const c of n.requiredClaims||[])if(!claims.has(c))failures.push(`missing_claim:${n.nodeId}:${c}`);for(const r of n.requiredReceipts||[])if(!receipts.has(r))failures.push(`missing_receipt:${n.nodeId}:${r}`);for(const c of n.forbiddenClaims||[])if(claims.has(c)||forbidden.has(c))failures.push(`forbidden_claim:${n.nodeId}:${c}`)}return Object.freeze({ok:!failures.length,failures:Object.freeze(failures)})}
