'use strict'
const crypto=require('node:crypto')
const CASE_COLLECTION='ql7_support_cases'
const CASE_KINDS=Object.freeze(['support','composer_security','economic_security','crisis','moderation','identity_parity','data_contradiction'])
const str=v=>String(v??'').trim(),sha=v=>crypto.createHash('sha256').update(str(v)).digest('hex')
function normalizeDatabase(db){const d=db?.db&&typeof db.db.collection==='function'?db.db:db;if(!d||typeof d.collection!=='function')throw new Error('case_database_required');return d}
function getCaseCollection(database){return normalizeDatabase(database).collection(CASE_COLLECTION)}
function createCaseId({caseKind='support',actorId='',operationId='',contentHash=''}={}){const kind=CASE_KINDS.includes(str(caseKind))?str(caseKind):'support',publicKind=kind.replaceAll('_','-');return `${publicKind}:${sha(`${kind}:${actorId}:${operationId}:${contentHash}`).slice(0,40)}`}
async function createOrGetCase({database,caseKind='support',actorId='',actorIdHash='',operationId='',surface='',classId='',contentHash='',evidence=[],privacyClass='support_minimized',status='ready_for_review',now=Date.now(),extra={}}={}){const actor=str(actorId),actorHash=str(actorIdHash)||sha(actor);if(!actorHash||!str(operationId))throw new Error('case_identity_required');const caseId=createCaseId({caseKind,actorId:actorHash,operationId,contentHash});const row=Object.freeze({_id:caseId,caseId,caseKind:CASE_KINDS.includes(str(caseKind))?str(caseKind):'support',actorId:actor||undefined,actorIdHash:actorHash,surface:str(surface),classId:str(classId),operationId:str(operationId),contentHash:str(contentHash),evidenceCodes:Object.freeze((Array.isArray(evidence)?evidence:[]).map(str).filter(Boolean).slice(0,64)),status:str(status)||'ready_for_review',privacyClass:str(privacyClass)||'support_minimized',createdAt:new Date(Number(now)).toISOString(),...extra});const c=getCaseCollection(database);await c.updateOne({_id:caseId},{$setOnInsert:row},{upsert:true});return Object.freeze((await c.findOne({_id:caseId}))||row)}
function auditCaseAuthority(){return Object.freeze({ok:CASE_COLLECTION==='ql7_support_cases'&&new Set(CASE_KINDS).size===CASE_KINDS.length,collection:CASE_COLLECTION,caseKinds:CASE_KINDS})}
module.exports=Object.freeze({CASE_COLLECTION,CASE_KINDS,getCaseCollection,createCaseId,createOrGetCase,auditCaseAuthority})
