export const QL7_SUPPORT_ACTIVE_CALIBRATION = Object.freeze({
  schema: 'ql7.support.deterministic-calibration-artifact',
  schemaVersion: '1.0.0',
  calibrationVersion: '2026.09.15.1',
  status: 'approved',
  runtimeMode: 'deterministic-js',
  createdAt: '2026-09-15T10:00:00.000Z',
  rollbackVersion: 'bootstrap-deterministic-2026.09.14',
  lineage: Object.freeze({
    laboratoryProfile: 'ql7-local-python-ml-calibration',
    candidateReceiptId: 'candidate:deterministic-runtime-baseline-2026.09.15',
    holdoutReceiptId: 'holdout:deterministic-runtime-baseline-2026.09.15',
    approvalReceiptId: 'approval:repository-owner-2026.09.15',
    rawDatasetIncluded: false,
  }),
  governance: Object.freeze({
    humanApprovalRequired: true,
    humanApproved: true,
    antiPoisoningReview: 'required-before-export',
    holdoutValidation: 'required-before-export',
    onlineLearning: false,
    productionMutation: false,
    rawExamplesIncluded: false,
    modelWeightsIncluded: false,
  }),
  memory: Object.freeze({
    maxPersistedBytes: 32768,
    recentTurnHashWindow: 24,
    topicFrameWindow: 16,
  }),
  calibration: Object.freeze({
    posteriorTemperature: 1,
    parentTemperature: 1,
    uncertaintyFloor: 0.05,
    abstentionThreshold: 0.62,
    ambiguityMargin: 0.08,
    minimumEvidenceScore: 0.12,
  }),
})
