import { describe, expect, it } from 'vitest'
import { executeQl7SupportTurnRuntime } from '../../../lib/ql7-support/runtime/executeTurn.js'
import { createQl7SupportAdapterReceipt } from '../../../lib/ql7-support/data/adapterReceipt.js'
const run=(text,messageAct='informational_question',topic='support_system',extra={})=>executeQl7SupportTurnRuntime({mode:'test',text,selectedLocale:'ru',analysis:{topic,messageAct},route:{topic,messageAct},tone:{taxonomyCategory:'neutral'},...extra})
describe('QL7 Support canonical compatibility over canonical canonical runtime',()=>{
  it('keeps gratitude minimal and premium',()=>{const r=run('спасибо','gratitude');expect(r.replyPlan.text.length).toBeLessThan(40);expect(r.replyPlan.cardSpec.surfaceKind).toBe('compact');expect(r.replyPlan.cardSpec.semanticIcon).toBe('gratitude');expect(r.critic.ok).toBe(true)})
  it('answers information instead of incident intake',()=>{const r=run('Что умеет QL7 Support?','informational_question');expect(r.replyPlan.text).not.toMatch(/что вы ожидали/i);expect(r.replyPlan.text.length).toBeLessThanOrEqual(400);expect(r.replyPlan.cardSpec.surfaceKind).toBe('structured');expect(r.replyPlan.cardSpec.semanticRole).toBe('identity')})
  it('clarifies vague balance with one scoped question and requires verified receipt for explicit checked result',()=>{const vague=run('Какой у меня баланс?','personal_status_request','qcoin');expect(vague.replyPlan.text).not.toMatch(/Проверка завершена|Проверено|Баланс:\s*\d/i);expect(vague.replyPlan.cardSpec.surfaceKind).toBe('choices');expect(vague.replyPlan.cardSpec.options.length).toBeGreaterThanOrEqual(2);expect(vague.replyPlan.cardSpec.options.length).toBeLessThanOrEqual(4);expect(vague.replyPlan.cardSpec.other).toBeTruthy();expect(vague.replyPlan.contentPlan.waitingFor).toBe('signed_choice');expect(vague.replyPlan.cardSpec.checkedAt).toBe('');const r=run('Покажи баланс QCoin','personal_status_request','qcoin');expect(r.replyPlan.text).not.toMatch(/Проверка завершена|Проверено/i);expect(r.replyPlan.cardSpec.semanticIcon).toBe('unavailable');expect(r.replyPlan.cardSpec.checkedAt).toBe('');const ok=run('Покажи баланс QCoin','personal_status_request','qcoin',{adapterReceipts:[createQl7SupportAdapterReceipt({executed:true,verified:true,source:'qcoin.read',scope:'self',result:{balance:'1'},checkedAt:'2026-01-01T00:00:00.000Z',writeCount:0})]});expect(ok.factProjection).toMatchObject({ verified:true, topic:'qcoin', facts:expect.objectContaining({ balance:'1' }) });expect(ok.noveltyFallbackReceipt).toBeNull();expect(ok.regenerationReceipt).toBeNull();expect(ok.qualityGate.surfaceRedundancy).toMatchObject({ ok:true, failures:[] });expect(ok.replyPlan.text).not.toMatch(/Баланс:\s*1\s*QCoin/i);expect(ok.replyPlan.cardSpec.tables[0].rows.find((row)=>row.key==='balance')).toMatchObject({ value:'1' });expect(ok.replyPlan.cardSpec.status).toBeNull();expect(ok.replyPlan.cardSpec.badges).toEqual(expect.arrayContaining([expect.objectContaining({ id:'verified',tone:'success' })]));expect(ok.replyPlan.cardSpec.tables).toEqual(expect.arrayContaining([expect.objectContaining({ schema:'ql7.table.qcoin' })]));expect(ok.replyPlan.cardSpec.semanticIcon).toBe('qcoin');expect(ok.replyPlan.cardSpec.checkedAt).toBe('2026-01-01T00:00:00.000Z')})
  it('does not leak internal machinery',()=>{const r=run('Расскажи про поддержку');expect(r.replyPlan.text).not.toMatch(/route|oracle|adapter|pipeline/i)})
  it('uses safety surface only for actual threat',()=>{const normal=run('Проверь баланс','personal_status_request','qcoin');expect(normal.replyPlan.cardSpec.semanticIcon).not.toBe('warning');const threat=executeQl7SupportTurnRuntime({mode:'test',text:'Я атакую систему',selectedLocale:'ru',analysis:{topic:'security',messageAct:'incident_report'},route:{topic:'security',messageAct:'incident_report'},tone:{threat:true,safetyEscalation:true,taxonomyCategory:'threat'}});expect(threat.replyPlan.cardSpec.surfaceKind).toBe('safety');expect(threat.replyPlan.cardSpec.semanticIcon).toBe('threat')})
})
