import { ql7Arr, ql7StableHash, ql7Str } from '../internal/text.js'
export const QL7_SUPPORT_LEDGER_VERSION='14.2.0'
const cap=(rows,max)=>ql7Arr(rows).slice(-max)
export function createQl7SupportConversationLedger(input={}){
 const source=input&&typeof input==='object'?input:{}
 return Object.freeze({
  version:QL7_SUPPORT_LEDGER_VERSION,
  activeGoal:ql7Str(source.activeGoal),activeTopic:ql7Str(source.activeTopic||source.topic),topicBranches:Object.freeze(cap(source.topicBranches,24)),entities:Object.freeze({...source.entities}),
  openQuestions:Object.freeze(cap(source.openQuestions,24)),resolvedQuestions:Object.freeze(cap(source.resolvedQuestions,48)),confirmedFacts:Object.freeze(cap(source.confirmedFacts,64)),
  corrections:Object.freeze(cap(source.corrections||source.userCorrections,32)),rejectedHypotheses:Object.freeze(cap(source.rejectedHypotheses,32)),pendingAction:ql7Str(source.pendingAction),waitingFor:ql7Str(source.waitingFor),lastMaterialTurnId:ql7Str(source.lastMaterialTurnId),closureState:ql7Str(source.closureState||'open'),
  responseFingerprints:Object.freeze(cap(source.responseFingerprints||source.replyHistory?.map(r=>r?.hash||r?.fingerprint||r?.semanticFingerprint||r?.textHash),512)),sentenceFingerprints:Object.freeze(cap(source.sentenceFingerprints,2048)),propositionFingerprints:Object.freeze(cap(source.propositionFingerprints,2048)),recentSvgAssetIds:Object.freeze(cap(source.recentSvgAssetIds,20)),
  safety:Object.freeze({directInsultCount:Number(source.safety?.directInsultCount||source.safetyStrikeCount||0),confirmedDirectInsultCount:Number(source.safety?.confirmedDirectInsultCount??source.safety?.directInsultCount??source.safetyStrikeCount??0),pendingBoundaryClarification:source.safety?.pendingBoundaryClarification&&typeof source.safety.pendingBoundaryClarification==='object'?Object.freeze({...source.safety.pendingBoundaryClarification}):Object.freeze({active:false}),lastAssessment:source.safety?.lastAssessment&&typeof source.safety.lastAssessment==='object'?Object.freeze({...source.safety.lastAssessment}):null,lastCategory:ql7Str(source.safety?.lastCategory),blockedUntil:ql7Str(source.safety?.blockedUntil),history:Object.freeze(cap(source.safety?.history,32))}),
  social:Object.freeze({smallTalkTurns:Number(source.social?.smallTalkTurns||0),supportiveTurns:Number(source.social?.supportiveTurns||0),humorMode:source.social?.humorMode===true}),
  business:Object.freeze({intakeTurns:Number(source.business?.intakeTurns||0),operatorRequestTurns:Number(source.business?.operatorRequestTurns||0),contactPrompted:source.business?.contactPrompted===true,contactProvided:source.business?.contactProvided===true,contactRefused:source.business?.contactRefused===true,lastStage:ql7Str(source.business?.lastStage)}),
  turns:Number(source.turns||source.turnCount||0),updatedAt:ql7Str(source.updatedAt),
 })
}
function sentenceHashes(text=''){return ql7Str(text).split(/(?<=[.!?。！？])\s+/u).map(s=>ql7StableHash(s.toLowerCase())).filter(Boolean)}
export function mergeQl7SupportLedgerTurn(ledgerInput={},turn={}){
 const ledger=createQl7SupportConversationLedger(ledgerInput);const topic=ql7Str(turn.topic||ledger.activeTopic);const act=ql7Str(turn.messageAct);const assistantText=ql7Str(turn.assistantText);const safety=turn.safety||{}
 const isMaterial=!['greeting','gratitude','farewell','small_talk','casual_chat','humor_request','humor_followup','joke_request','emotional_support','wellbeing_question','topic_recall','topic_resume','ambiguous_request','spam_or_noise'].includes(act)
 const isRelationship=['business_proposal','partnership_request','human_operator_request'].includes(act)||['partnership','investment','contact'].includes(topic)||turn.operatorHandoff===true
 const responseHash=assistantText?ql7StableHash(assistantText.toLowerCase()):''
 const propositionHashes=ql7Arr(turn.propositions).map(v=>ql7StableHash(ql7Str(v).toLowerCase())).filter(Boolean)
 const history=cap([...(ledger.safety.history||[]),...(safety.category&&safety.category!=='none'?[{category:safety.category,level:safety.escalationLevel,at:turn.now||new Date().toISOString()}]:[])],32)
 const nextActiveTopic=isMaterial?(topic||ledger.activeTopic):ledger.activeTopic
 return Object.freeze({...ledger,
  activeGoal:ql7Str(turn.activeGoal||ledger.activeGoal),activeTopic:nextActiveTopic,
  topicBranches:Object.freeze(isMaterial&&topic&&topic!==ledger.activeTopic?cap([...ledger.topicBranches,{topic,at:turn.now||''}],24):ledger.topicBranches),
  entities:Object.freeze({...ledger.entities,...(turn.entities||{})}),
  corrections:Object.freeze(turn.correction?cap([...ledger.corrections,turn.correction],32):ledger.corrections),
  rejectedHypotheses:Object.freeze(turn.rejectedHypothesis?cap([...ledger.rejectedHypotheses,turn.rejectedHypothesis],32):ledger.rejectedHypotheses),
  waitingFor:ql7Str(turn.waitingFor),pendingAction:ql7Str(turn.pendingAction),closureState:turn.resolved?'closed':(turn.closureState||ledger.closureState),lastMaterialTurnId:isMaterial?ql7Str(turn.userTurnId||turn.turnId||ledger.lastMaterialTurnId):ledger.lastMaterialTurnId,
  responseFingerprints:Object.freeze(responseHash?cap([...ledger.responseFingerprints,responseHash],512):ledger.responseFingerprints),sentenceFingerprints:Object.freeze(cap([...ledger.sentenceFingerprints,...sentenceHashes(assistantText)],2048)),propositionFingerprints:Object.freeze(cap([...ledger.propositionFingerprints,...propositionHashes],2048)),recentSvgAssetIds:Object.freeze(turn.svgAssetId?cap([...ledger.recentSvgAssetIds,turn.svgAssetId],20):ledger.recentSvgAssetIds),
  safety:Object.freeze({directInsultCount:safety.category==='direct_insult'?Math.max(ledger.safety.directInsultCount,Number(safety.escalationLevel||0)):ledger.safety.directInsultCount,confirmedDirectInsultCount:safety.category==='direct_insult'?Math.max(ledger.safety.confirmedDirectInsultCount||0,Number(safety.escalationLevel||0)):(ledger.safety.confirmedDirectInsultCount||0),pendingBoundaryClarification:turn.insultState?.createPending?turn.insultState.pendingBoundaryClarification:turn.insultState?.clearPending?Object.freeze({active:false}):ledger.safety.pendingBoundaryClarification,lastAssessment:safety.insultAssessment||ledger.safety.lastAssessment,lastCategory:ql7Str(safety.category||ledger.safety.lastCategory),blockedUntil:ql7Str(safety.blockedUntil||ledger.safety.blockedUntil),history:Object.freeze(history)}),
  social:Object.freeze({smallTalkTurns:ledger.social.smallTalkTurns+(act==='small_talk'||act==='casual_chat'?1:0),supportiveTurns:ledger.social.supportiveTurns+(turn.emotionalSupport?1:0),humorMode:turn.humorMode===true||(ledger.social.humorMode&&act==='humor_followup')}),
  business:Object.freeze({intakeTurns:ledger.business.intakeTurns+(isRelationship?1:0),operatorRequestTurns:ledger.business.operatorRequestTurns+(act==='human_operator_request'?1:0),contactPrompted:ledger.business.contactPrompted||turn.contactPrompted===true,contactProvided:ledger.business.contactProvided||turn.contactProvided===true,contactRefused:ledger.business.contactRefused||turn.contactRefused===true,lastStage:ql7Str(turn.relationshipStage||ledger.business.lastStage)}),
  turns:ledger.turns+1,updatedAt:turn.now||new Date().toISOString(),
 })
}

export const QL7_SUPPORT_CONVERSATION_LEDGER_VERSION_V13='13.0.0'
const V13_SOCIAL_ACTS=new Set(['greeting','gratitude','farewell','casual_chat','small_talk','humor_request','joke_request','ambiguous_request','spam_or_noise'])
const V13_CORRECTION=/(?:^|\b)(?:нет[,\s]|не\s+это|я\s+про\s+другое|имею\s+в\s+виду|ні[,\s]|не\s+те|я\s+про\s+інше|no[,\s]|not\s+that|i\s+mean|wrong|correction|hayır|değil|不是|不对|לא[,\s]|לא\s+זה)(?:\b|$)/iu
const V13_RESOLVED=/(?:^|\b)(?:спасибо[,!.\s]*вс[её]|решено|получилось|готово|дякую[,!.\s]*все|resolved|fixed|it works|gracias[,!.\s]*ya|tamam[,!.\s]*çözüldü)(?:\b|$)/iu
export function createQl7SupportConversationLedgerV13(seed={}){
 return Object.freeze({version:QL7_SUPPORT_CONVERSATION_LEDGER_VERSION_V13,conversationId:ql7Str(seed.conversationId)||'ql7-support-v13-conversation',activeTopic:ql7Str(seed.activeTopic||seed.currentTopic||seed.topic),previousTopic:ql7Str(seed.previousTopic),branches:Object.freeze(ql7Arr(seed.branches).slice(-12)),entities:Object.freeze({...seed.entities}),confirmedFacts:Object.freeze(ql7Arr(seed.confirmedFacts).slice(-40)),rejectedHypotheses:Object.freeze(ql7Arr(seed.rejectedHypotheses).slice(-30)),openQuestions:Object.freeze(ql7Arr(seed.openQuestions).slice(-20)),resolvedQuestions:Object.freeze(ql7Arr(seed.resolvedQuestions).slice(-30)),pendingAction:ql7Str(seed.pendingAction),waitingFor:ql7Str(seed.waitingFor),openMaterialQuestion:seed.openMaterialQuestion===true,lastUserCorrection:ql7Str(seed.lastUserCorrection),lastAssistantClaim:ql7Str(seed.lastAssistantClaim),turns:Object.freeze(ql7Arr(seed.turns).slice(-40))})
}
export function mergeQl7SupportLedgerTurnV13(ledger={},turn={}){
 const current=createQl7SupportConversationLedgerV13(ledger);const userText=ql7Str(turn.userText||turn.input||turn.text);const assistantText=ql7Str(turn.assistantText||turn.responseText);const topic=ql7Str(turn.topic||turn.route?.topic||current.activeTopic);const messageAct=ql7Str(turn.messageAct||turn.route?.messageAct);const correction=Boolean(turn.correction)||['correction','denial'].includes(messageAct)||V13_CORRECTION.test(userText);const material=Boolean(topic&&!V13_SOCIAL_ACTS.has(messageAct));const resolved=Boolean(turn.resolved)||V13_RESOLVED.test(userText)||messageAct==='farewell';const questionId=ql7Str(turn.questionId||`${topic}:${messageAct}`);const previousTopic=topic&&topic!==current.activeTopic?current.activeTopic:current.previousTopic;const branches=topic&&topic!==current.activeTopic&&current.activeTopic?[...current.branches,{topic:current.activeTopic,closedBy:correction?'correction':'switch',atTurn:current.turns.length}]:current.branches;const openQuestions=resolved?current.openQuestions.filter((q)=>ql7Str(q?.id||q)!==questionId):(material&&questionId?[...current.openQuestions.filter((q)=>ql7Str(q?.id||q)!==questionId),{id:questionId,topic,messageAct}]:current.openQuestions);const resolvedQuestions=resolved&&questionId?[...current.resolvedQuestions,{id:questionId,topic}]:current.resolvedQuestions
 return createQl7SupportConversationLedgerV13({...current,activeTopic:topic||current.activeTopic,previousTopic,branches,entities:{...current.entities,...(turn.entities||{})},confirmedFacts:turn.confirmedFacts||current.confirmedFacts,rejectedHypotheses:correction&&current.activeTopic?[...current.rejectedHypotheses,{topic:current.activeTopic,text:userText}]:current.rejectedHypotheses,openQuestions,resolvedQuestions,pendingAction:resolved?'':ql7Str(turn.pendingAction||current.pendingAction),waitingFor:resolved?'':ql7Str(turn.waitingFor||current.waitingFor),openMaterialQuestion:resolved?false:(material||current.openMaterialQuestion),lastUserCorrection:correction?userText:current.lastUserCorrection,lastAssistantClaim:assistantText||current.lastAssistantClaim,turns:[...current.turns,Object.freeze({userText,assistantText,topic,messageAct,material,correction,resolved})]})
}
export function ledgerToQl7SupportPreviousContextV13(ledger={}){
 const row=createQl7SupportConversationLedgerV13(ledger)
 return Object.freeze({topic:row.activeTopic,previousTopic:row.previousTopic||row.activeTopic,caseStatus:row.openMaterialQuestion?'waiting_user':'idle',openMaterialQuestion:row.openMaterialQuestion,unresolvedSlots:row.waitingFor?[row.waitingFor]:[],replyHistory:row.turns.filter((t)=>t.assistantText).slice(-8).map((t)=>({text:t.assistantText,responseCode:t.messageAct})),relevantMessages:row.turns.slice(-8).map((t)=>({text:t.userText,topic:t.topic,messageAct:t.messageAct})),entities:row.entities,rejectedHypotheses:row.rejectedHypotheses})
}
