import {buildQl7SupportLocaleBanks, createQl7SupportLocaleProfile} from './profileFactory.js'
export default createQl7SupportLocaleProfile({
  locale: 'fr', languageTag: 'fr-FR', script: 'Latin', direction: 'ltr', tokenization: { strategy: 'unicode-word', segmenterLocale: 'fr', compounds: 'space-or-hyphen', apostropheInsideWord: true },
  sentenceSegmentation: { strategy: 'unicode-sentence', terminators: ['.', '!', '?', '…'], abbreviations: ['p. ex.', 'M.', 'Mme', 'env.'] }, negationAndDenial: { negationMarkers: ['ne…pas', 'non', 'jamais', 'aucun', 'plus'], denialMarkers: ['pas contre vous', 'je ne parlais pas de vous', 'c’est une citation', 'on m’a dit'], scope: 'bipartite-or-colloquial' },
  quotationAndReportedSpeech: { quotePairs: [['«', '»'], ['“', '”'], ['"', '"']], reportedMarkers: ['a dit', 'a écrit', 'm’a traité de', 'je cite'], nestedQuotes: true }, address: { defaultFormality: 'formal', formalPronouns: ['vous'], informalPronouns: ['tu', 'te'], imperativeStyle: 'polite-formal' },
  morphology: { agreement: 'gender-number-person', pluralRule: 'intl-cardinal-fr', articleSystem: 'definite-indefinite-partitive', grammaticalGender: 'masculine-feminine' }, typography: { questionSpacing: 'narrow-before', colonSpacing: 'narrow-before-after', decimalSeparator: ',', thousandsSeparator: ' ', productCasePreserved: true },
  codeSwitch: { allowedProducts: ['QCoin', 'VIP Plus', 'CryptoRadar', 'MetaMarket', 'AI Box', 'BattleCoin'], unexpectedScriptPolicy: 'evidence-required' }, inputHypotheses: { transliteration: ['ascii-diacritics'], keyboardLayouts: ['azerty', 'qwerty'], typoDistance: 1, joinedWordRecovery: true }, protectedSpans: { kinds: ['url', 'email', 'phone', 'product', 'wallet-id', 'telegram-id', 'receipt-id'], preserveOffsets: true },
  emotionPragmatics: { acknowledgementThreshold: 0.8, neutralQuestionIsDistress: false, intensifierMarkers: ['très', 'vraiment', 'terriblement', 'complètement'] }, safetyCollisionControls: { negativeContexts: ['quotation', 'reported-speech', 'education', 'news', 'victim-report', 'counter-speech', 'explicit-denial'], negationWindowTokens: 10 }, formatting: { intlLocale: 'fr-FR', dateStyle: 'long', timeStyle: 'short', numberSystem: 'latn', currency: 'EUR', rtlIsolation: false }, review: { owner: 'ql7-language-quality', status: 'pending-human-review', evidenceIds: [] },
  banks: buildQl7SupportLocaleBanks({ aliases: ['aide', 'assistance', 'vérifier', 'afficher', 'expliquer'], morphology: ['singulier', 'pluriel', 'genre', 'temps', 'conditionnel'], negation: ['ne pas', 'jamais', 'ne plus'], quotation: ['a dit', 'a écrit', 'citation'], politeness: ['s’il vous plaît', 'pourriez-vous', 'précisez'], relations: ['parce que', 'cependant', 'si', 'donc', 'par exemple'], clarification: ['quel résultat', 'quelle section', 'quel changement', 'attendu et observé'], explanation: ['objectif', 'raison', 'limite', 'exemple'], instruction: ['ouvrir', 'choisir', 'vérifier', 'comparer', 'confirmer'], incident: ['changement observé', 'heure approximative', 'état attendu', 'dernière action'], emotion: ['nommer la pression', 'reconnaître la perte', 'éviter le diagnostic'], gratitude: ['merci', 'je vous remercie', 'cela a aidé'], recovery: ['question incomplète', 'symbole isolé', 'fragment endommagé'], contact: ['contact proposé', 'consentement confirmé', 'message privé seulement'], titles: ['état', 'détails', 'prochaine étape'], badges: ['vérifié', 'attention', 'restreint'], cta: ['ouvrir la section', 'voir les détails', 'continuer'] }),
})
