// lib/geo/countries.js

// lib/geo/countries.js
// ISO-3166-1 alpha-2 country list (English fallback names)
export const countries = [
  { code: 'AD', name_en: 'Andorra' },
  { code: 'AE', name_en: 'United Arab Emirates' },
  { code: 'AF', name_en: 'Afghanistan' },
  { code: 'AG', name_en: 'Antigua & Barbuda' },
  { code: 'AI', name_en: 'Anguilla' },
  { code: 'AL', name_en: 'Albania' },
  { code: 'AM', name_en: 'Armenia' },
  { code: 'AO', name_en: 'Angola' },
  { code: 'AQ', name_en: 'Antarctica' },
  { code: 'AR', name_en: 'Argentina' },
  { code: 'AS', name_en: 'Samoa (American)' },
  { code: 'AT', name_en: 'Austria' },
  { code: 'AU', name_en: 'Australia' },
  { code: 'AW', name_en: 'Aruba' },
  { code: 'AX', name_en: 'Åland Islands' },
  { code: 'AZ', name_en: 'Azerbaijan' },
  { code: 'BA', name_en: 'Bosnia & Herzegovina' },
  { code: 'BB', name_en: 'Barbados' },
  { code: 'BD', name_en: 'Bangladesh' },
  { code: 'BE', name_en: 'Belgium' },
  { code: 'BF', name_en: 'Burkina Faso' },
  { code: 'BG', name_en: 'Bulgaria' },
  { code: 'BH', name_en: 'Bahrain' },
  { code: 'BI', name_en: 'Burundi' },
  { code: 'BJ', name_en: 'Benin' },
  { code: 'BL', name_en: 'St Barthelemy' },
  { code: 'BM', name_en: 'Bermuda' },
  { code: 'BN', name_en: 'Brunei' },
  { code: 'BO', name_en: 'Bolivia' },
  { code: 'BQ', name_en: 'Caribbean NL' },
  { code: 'BR', name_en: 'Brazil' },
  { code: 'BS', name_en: 'Bahamas' },
  { code: 'BT', name_en: 'Bhutan' },
  { code: 'BV', name_en: 'Bouvet Island' },
  { code: 'BW', name_en: 'Botswana' },
  { code: 'BY', name_en: 'Belarus' },
  { code: 'BZ', name_en: 'Belize' },
  { code: 'CA', name_en: 'Canada' },
  { code: 'CC', name_en: 'Cocos (Keeling) Islands' },
  { code: 'CD', name_en: 'Congo (Dem. Rep.)' },
  { code: 'CF', name_en: 'Central African Rep.' },
  { code: 'CG', name_en: 'Congo (Rep.)' },
  { code: 'CH', name_en: 'Switzerland' },
  { code: 'CI', name_en: 'Côte d\'Ivoire' },
  { code: 'CK', name_en: 'Cook Islands' },
  { code: 'CL', name_en: 'Chile' },
  { code: 'CM', name_en: 'Cameroon' },
  { code: 'CN', name_en: 'China' },
  { code: 'CO', name_en: 'Colombia' },
  { code: 'CR', name_en: 'Costa Rica' },
  { code: 'CU', name_en: 'Cuba' },
  { code: 'CV', name_en: 'Cape Verde' },
  { code: 'CW', name_en: 'Curaçao' },
  { code: 'CX', name_en: 'Christmas Island' },
  { code: 'CY', name_en: 'Cyprus' },
  { code: 'CZ', name_en: 'Czech Republic' },
  { code: 'DE', name_en: 'Germany' },
  { code: 'DJ', name_en: 'Djibouti' },
  { code: 'DK', name_en: 'Denmark' },
  { code: 'DM', name_en: 'Dominica' },
  { code: 'DO', name_en: 'Dominican Republic' },
  { code: 'DZ', name_en: 'Algeria' },
  { code: 'EC', name_en: 'Ecuador' },
  { code: 'EE', name_en: 'Estonia' },
  { code: 'EG', name_en: 'Egypt' },
  { code: 'EH', name_en: 'Western Sahara' },
  { code: 'ER', name_en: 'Eritrea' },
  { code: 'ES', name_en: 'Spain' },
  { code: 'ET', name_en: 'Ethiopia' },
  { code: 'FI', name_en: 'Finland' },
  { code: 'FJ', name_en: 'Fiji' },
  { code: 'FK', name_en: 'Falkland Islands' },
  { code: 'FM', name_en: 'Micronesia' },
  { code: 'FO', name_en: 'Faroe Islands' },
  { code: 'FR', name_en: 'France' },
  { code: 'GA', name_en: 'Gabon' },
  { code: 'GB', name_en: 'Britain (UK)' },
  { code: 'GD', name_en: 'Grenada' },
  { code: 'GE', name_en: 'Georgia' },
  { code: 'GF', name_en: 'French Guiana' },
  { code: 'GG', name_en: 'Guernsey' },
  { code: 'GH', name_en: 'Ghana' },
  { code: 'GI', name_en: 'Gibraltar' },
  { code: 'GL', name_en: 'Greenland' },
  { code: 'GM', name_en: 'Gambia' },
  { code: 'GN', name_en: 'Guinea' },
  { code: 'GP', name_en: 'Guadeloupe' },
  { code: 'GQ', name_en: 'Equatorial Guinea' },
  { code: 'GR', name_en: 'Greece' },
  { code: 'GS', name_en: 'South Georgia & the South Sandwich Islands' },
  { code: 'GT', name_en: 'Guatemala' },
  { code: 'GU', name_en: 'Guam' },
  { code: 'GW', name_en: 'Guinea-Bissau' },
  { code: 'GY', name_en: 'Guyana' },
  { code: 'HK', name_en: 'Hong Kong' },
  { code: 'HM', name_en: 'Heard Island & McDonald Islands' },
  { code: 'HN', name_en: 'Honduras' },
  { code: 'HR', name_en: 'Croatia' },
  { code: 'HT', name_en: 'Haiti' },
  { code: 'HU', name_en: 'Hungary' },
  { code: 'ID', name_en: 'Indonesia' },
  { code: 'IE', name_en: 'Ireland' },
  { code: 'IL', name_en: 'Israel' },
  { code: 'IM', name_en: 'Isle of Man' },
  { code: 'IN', name_en: 'India' },
  { code: 'IO', name_en: 'British Indian Ocean Territory' },
  { code: 'IQ', name_en: 'Iraq' },
  { code: 'IR', name_en: 'Iran' },
  { code: 'IS', name_en: 'Iceland' },
  { code: 'IT', name_en: 'Italy' },
  { code: 'JE', name_en: 'Jersey' },
  { code: 'JM', name_en: 'Jamaica' },
  { code: 'JO', name_en: 'Jordan' },
  { code: 'JP', name_en: 'Japan' },
  { code: 'KE', name_en: 'Kenya' },
  { code: 'KG', name_en: 'Kyrgyzstan' },
  { code: 'KH', name_en: 'Cambodia' },
  { code: 'KI', name_en: 'Kiribati' },
  { code: 'KM', name_en: 'Comoros' },
  { code: 'KN', name_en: 'St Kitts & Nevis' },
  { code: 'KP', name_en: 'Korea (North)' },
  { code: 'KR', name_en: 'Korea (South)' },
  { code: 'KW', name_en: 'Kuwait' },
  { code: 'KY', name_en: 'Cayman Islands' },
  { code: 'KZ', name_en: 'Kazakhstan' },
  { code: 'LA', name_en: 'Laos' },
  { code: 'LB', name_en: 'Lebanon' },
  { code: 'LC', name_en: 'St Lucia' },
  { code: 'LI', name_en: 'Liechtenstein' },
  { code: 'LK', name_en: 'Sri Lanka' },
  { code: 'LR', name_en: 'Liberia' },
  { code: 'LS', name_en: 'Lesotho' },
  { code: 'LT', name_en: 'Lithuania' },
  { code: 'LU', name_en: 'Luxembourg' },
  { code: 'LV', name_en: 'Latvia' },
  { code: 'LY', name_en: 'Libya' },
  { code: 'MA', name_en: 'Morocco' },
  { code: 'MC', name_en: 'Monaco' },
  { code: 'MD', name_en: 'Moldova' },
  { code: 'ME', name_en: 'Montenegro' },
  { code: 'MF', name_en: 'St Martin (French)' },
  { code: 'MG', name_en: 'Madagascar' },
  { code: 'MH', name_en: 'Marshall Islands' },
  { code: 'MK', name_en: 'North Macedonia' },
  { code: 'ML', name_en: 'Mali' },
  { code: 'MM', name_en: 'Myanmar (Burma)' },
  { code: 'MN', name_en: 'Mongolia' },
  { code: 'MO', name_en: 'Macau' },
  { code: 'MP', name_en: 'Northern Mariana Islands' },
  { code: 'MQ', name_en: 'Martinique' },
  { code: 'MR', name_en: 'Mauritania' },
  { code: 'MS', name_en: 'Montserrat' },
  { code: 'MT', name_en: 'Malta' },
  { code: 'MU', name_en: 'Mauritius' },
  { code: 'MV', name_en: 'Maldives' },
  { code: 'MW', name_en: 'Malawi' },
  { code: 'MX', name_en: 'Mexico' },
  { code: 'MY', name_en: 'Malaysia' },
  { code: 'MZ', name_en: 'Mozambique' },
  { code: 'NA', name_en: 'Namibia' },
  { code: 'NC', name_en: 'New Caledonia' },
  { code: 'NE', name_en: 'Niger' },
  { code: 'NF', name_en: 'Norfolk Island' },
  { code: 'NG', name_en: 'Nigeria' },
  { code: 'NI', name_en: 'Nicaragua' },
  { code: 'NL', name_en: 'Netherlands' },
  { code: 'NO', name_en: 'Norway' },
  { code: 'NP', name_en: 'Nepal' },
  { code: 'NR', name_en: 'Nauru' },
  { code: 'NU', name_en: 'Niue' },
  { code: 'NZ', name_en: 'New Zealand' },
  { code: 'OM', name_en: 'Oman' },
  { code: 'PA', name_en: 'Panama' },
  { code: 'PE', name_en: 'Peru' },
  { code: 'PF', name_en: 'French Polynesia' },
  { code: 'PG', name_en: 'Papua New Guinea' },
  { code: 'PH', name_en: 'Philippines' },
  { code: 'PK', name_en: 'Pakistan' },
  { code: 'PL', name_en: 'Poland' },
  { code: 'PM', name_en: 'St Pierre & Miquelon' },
  { code: 'PN', name_en: 'Pitcairn' },
  { code: 'PR', name_en: 'Puerto Rico' },
  { code: 'PS', name_en: 'Palestine' },
  { code: 'PT', name_en: 'Portugal' },
  { code: 'PW', name_en: 'Palau' },
  { code: 'PY', name_en: 'Paraguay' },
  { code: 'QA', name_en: 'Qatar' },
  { code: 'RE', name_en: 'Réunion' },
  { code: 'RO', name_en: 'Romania' },
  { code: 'RS', name_en: 'Serbia' },
  { code: 'RU', name_en: 'Russia' },
  { code: 'RW', name_en: 'Rwanda' },
  { code: 'SA', name_en: 'Saudi Arabia' },
  { code: 'SB', name_en: 'Solomon Islands' },
  { code: 'SC', name_en: 'Seychelles' },
  { code: 'SD', name_en: 'Sudan' },
  { code: 'SE', name_en: 'Sweden' },
  { code: 'SG', name_en: 'Singapore' },
  { code: 'SH', name_en: 'St Helena' },
  { code: 'SI', name_en: 'Slovenia' },
  { code: 'SJ', name_en: 'Svalbard & Jan Mayen' },
  { code: 'SK', name_en: 'Slovakia' },
  { code: 'SL', name_en: 'Sierra Leone' },
  { code: 'SM', name_en: 'San Marino' },
  { code: 'SN', name_en: 'Senegal' },
  { code: 'SO', name_en: 'Somalia' },
  { code: 'SR', name_en: 'Suriname' },
  { code: 'SS', name_en: 'South Sudan' },
  { code: 'ST', name_en: 'Sao Tome & Principe' },
  { code: 'SV', name_en: 'El Salvador' },
  { code: 'SX', name_en: 'St Maarten (Dutch)' },
  { code: 'SY', name_en: 'Syria' },
  { code: 'SZ', name_en: 'Eswatini (Swaziland)' },
  { code: 'TC', name_en: 'Turks & Caicos Is' },
  { code: 'TD', name_en: 'Chad' },
  { code: 'TF', name_en: 'French S. Terr.' },
  { code: 'TG', name_en: 'Togo' },
  { code: 'TH', name_en: 'Thailand' },
  { code: 'TJ', name_en: 'Tajikistan' },
  { code: 'TK', name_en: 'Tokelau' },
  { code: 'TL', name_en: 'East Timor' },
  { code: 'TM', name_en: 'Turkmenistan' },
  { code: 'TN', name_en: 'Tunisia' },
  { code: 'TO', name_en: 'Tonga' },
  { code: 'TR', name_en: 'Turkey' },
  { code: 'TT', name_en: 'Trinidad & Tobago' },
  { code: 'TV', name_en: 'Tuvalu' },
  { code: 'TW', name_en: 'Taiwan' },
  { code: 'TZ', name_en: 'Tanzania' },
  { code: 'UA', name_en: 'Ukraine' },
  { code: 'UG', name_en: 'Uganda' },
  { code: 'UM', name_en: 'US minor outlying islands' },
  { code: 'US', name_en: 'United States' },
  { code: 'UY', name_en: 'Uruguay' },
  { code: 'UZ', name_en: 'Uzbekistan' },
  { code: 'VA', name_en: 'Vatican City' },
  { code: 'VC', name_en: 'St Vincent' },
  { code: 'VE', name_en: 'Venezuela' },
  { code: 'VG', name_en: 'Virgin Islands (UK)' },
  { code: 'VI', name_en: 'Virgin Islands (US)' },
  { code: 'VN', name_en: 'Vietnam' },
  { code: 'VU', name_en: 'Vanuatu' },
  { code: 'WF', name_en: 'Wallis & Futuna' },
  { code: 'WS', name_en: 'Samoa (western)' },
  { code: 'YE', name_en: 'Yemen' },
  { code: 'YT', name_en: 'Mayotte' },
  { code: 'ZA', name_en: 'South Africa' },
  { code: 'ZM', name_en: 'Zambia' },
  { code: 'ZW', name_en: 'Zimbabwe' },
]
