// lib/geo/regions.js

// lib/geo/regions.js
// Selected ISO-3166-2 region lists (extendable)
export const regions = {
  US: [
    { code: 'AL', name_en: 'Alabama' },
    { code: 'AK', name_en: 'Alaska' },
    { code: 'AZ', name_en: 'Arizona' },
    { code: 'AR', name_en: 'Arkansas' },
    { code: 'CA', name_en: 'California' },
    { code: 'CO', name_en: 'Colorado' },
    { code: 'CT', name_en: 'Connecticut' },
    { code: 'DE', name_en: 'Delaware' },
    { code: 'FL', name_en: 'Florida' },
    { code: 'GA', name_en: 'Georgia' },
    { code: 'HI', name_en: 'Hawaii' },
    { code: 'ID', name_en: 'Idaho' },
    { code: 'IL', name_en: 'Illinois' },
    { code: 'IN', name_en: 'Indiana' },
    { code: 'IA', name_en: 'Iowa' },
    { code: 'KS', name_en: 'Kansas' },
    { code: 'KY', name_en: 'Kentucky' },
    { code: 'LA', name_en: 'Louisiana' },
    { code: 'ME', name_en: 'Maine' },
    { code: 'MD', name_en: 'Maryland' },
    { code: 'MA', name_en: 'Massachusetts' },
    { code: 'MI', name_en: 'Michigan' },
    { code: 'MN', name_en: 'Minnesota' },
    { code: 'MS', name_en: 'Mississippi' },
    { code: 'MO', name_en: 'Missouri' },
    { code: 'MT', name_en: 'Montana' },
    { code: 'NE', name_en: 'Nebraska' },
    { code: 'NV', name_en: 'Nevada' },
    { code: 'NH', name_en: 'New Hampshire' },
    { code: 'NJ', name_en: 'New Jersey' },
    { code: 'NM', name_en: 'New Mexico' },
    { code: 'NY', name_en: 'New York' },
    { code: 'NC', name_en: 'North Carolina' },
    { code: 'ND', name_en: 'North Dakota' },
    { code: 'OH', name_en: 'Ohio' },
    { code: 'OK', name_en: 'Oklahoma' },
    { code: 'OR', name_en: 'Oregon' },
    { code: 'PA', name_en: 'Pennsylvania' },
    { code: 'RI', name_en: 'Rhode Island' },
    { code: 'SC', name_en: 'South Carolina' },
    { code: 'SD', name_en: 'South Dakota' },
    { code: 'TN', name_en: 'Tennessee' },
    { code: 'TX', name_en: 'Texas' },
    { code: 'UT', name_en: 'Utah' },
    { code: 'VT', name_en: 'Vermont' },
    { code: 'VA', name_en: 'Virginia' },
    { code: 'WA', name_en: 'Washington' },
    { code: 'WV', name_en: 'West Virginia' },
    { code: 'WI', name_en: 'Wisconsin' },
    { code: 'WY', name_en: 'Wyoming' },
    { code: 'DC', name_en: 'District of Columbia' },
  ],
  CA: [
    { code: 'AB', name_en: 'Alberta' },
    { code: 'BC', name_en: 'British Columbia' },
    { code: 'MB', name_en: 'Manitoba' },
    { code: 'NB', name_en: 'New Brunswick' },
    { code: 'NL', name_en: 'Newfoundland and Labrador' },
    { code: 'NS', name_en: 'Nova Scotia' },
    { code: 'NT', name_en: 'Northwest Territories' },
    { code: 'NU', name_en: 'Nunavut' },
    { code: 'ON', name_en: 'Ontario' },
    { code: 'PE', name_en: 'Prince Edward Island' },
    { code: 'QC', name_en: 'Quebec' },
    { code: 'SK', name_en: 'Saskatchewan' },
    { code: 'YT', name_en: 'Yukon' },
  ],
  AU: [
    { code: 'ACT', name_en: 'Australian Capital Territory' },
    { code: 'NSW', name_en: 'New South Wales' },
    { code: 'NT', name_en: 'Northern Territory' },
    { code: 'QLD', name_en: 'Queensland' },
    { code: 'SA', name_en: 'South Australia' },
    { code: 'TAS', name_en: 'Tasmania' },
    { code: 'VIC', name_en: 'Victoria' },
    { code: 'WA', name_en: 'Western Australia' },
  ],
  BR: [
    { code: 'AC', name_en: 'Acre' },
    { code: 'AL', name_en: 'Alagoas' },
    { code: 'AP', name_en: 'Amapa' },
    { code: 'AM', name_en: 'Amazonas' },
    { code: 'BA', name_en: 'Bahia' },
    { code: 'CE', name_en: 'Ceara' },
    { code: 'DF', name_en: 'Distrito Federal' },
    { code: 'ES', name_en: 'Espirito Santo' },
    { code: 'GO', name_en: 'Goias' },
    { code: 'MA', name_en: 'Maranhao' },
    { code: 'MT', name_en: 'Mato Grosso' },
    { code: 'MS', name_en: 'Mato Grosso do Sul' },
    { code: 'MG', name_en: 'Minas Gerais' },
    { code: 'PA', name_en: 'Para' },
    { code: 'PB', name_en: 'Paraiba' },
    { code: 'PR', name_en: 'Parana' },
    { code: 'PE', name_en: 'Pernambuco' },
    { code: 'PI', name_en: 'Piaui' },
    { code: 'RJ', name_en: 'Rio de Janeiro' },
    { code: 'RN', name_en: 'Rio Grande do Norte' },
    { code: 'RS', name_en: 'Rio Grande do Sul' },
    { code: 'RO', name_en: 'Rondonia' },
    { code: 'RR', name_en: 'Roraima' },
    { code: 'SC', name_en: 'Santa Catarina' },
    { code: 'SP', name_en: 'Sao Paulo' },
    { code: 'SE', name_en: 'Sergipe' },
    { code: 'TO', name_en: 'Tocantins' },
  ],
  IN: [
    { code: 'AP', name_en: 'Andhra Pradesh' },
    { code: 'AR', name_en: 'Arunachal Pradesh' },
    { code: 'AS', name_en: 'Assam' },
    { code: 'BR', name_en: 'Bihar' },
    { code: 'CT', name_en: 'Chhattisgarh' },
    { code: 'GA', name_en: 'Goa' },
    { code: 'GJ', name_en: 'Gujarat' },
    { code: 'HR', name_en: 'Haryana' },
    { code: 'HP', name_en: 'Himachal Pradesh' },
    { code: 'JH', name_en: 'Jharkhand' },
    { code: 'KA', name_en: 'Karnataka' },
    { code: 'KL', name_en: 'Kerala' },
    { code: 'MP', name_en: 'Madhya Pradesh' },
    { code: 'MH', name_en: 'Maharashtra' },
    { code: 'MN', name_en: 'Manipur' },
    { code: 'ML', name_en: 'Meghalaya' },
    { code: 'MZ', name_en: 'Mizoram' },
    { code: 'NL', name_en: 'Nagaland' },
    { code: 'OR', name_en: 'Odisha' },
    { code: 'PB', name_en: 'Punjab' },
    { code: 'RJ', name_en: 'Rajasthan' },
    { code: 'SK', name_en: 'Sikkim' },
    { code: 'TN', name_en: 'Tamil Nadu' },
    { code: 'TG', name_en: 'Telangana' },
    { code: 'TR', name_en: 'Tripura' },
    { code: 'UP', name_en: 'Uttar Pradesh' },
    { code: 'UT', name_en: 'Uttarakhand' },
    { code: 'WB', name_en: 'West Bengal' },
    { code: 'AN', name_en: 'Andaman and Nicobar Islands' },
    { code: 'CH', name_en: 'Chandigarh' },
    { code: 'DN', name_en: 'Dadra and Nagar Haveli and Daman and Diu' },
    { code: 'DL', name_en: 'Delhi' },
    { code: 'JK', name_en: 'Jammu and Kashmir' },
    { code: 'LA', name_en: 'Ladakh' },
    { code: 'LD', name_en: 'Lakshadweep' },
    { code: 'PY', name_en: 'Puducherry' },
  ],
  RU: [
    { code: 'AD', name_en: 'Adygea' },
    { code: 'AL', name_en: 'Altai Republic' },
    { code: 'ALT', name_en: 'Altai Krai' },
    { code: 'AMU', name_en: 'Amur Oblast' },
    { code: 'ARK', name_en: 'Arkhangelsk Oblast' },
    { code: 'AST', name_en: 'Astrakhan Oblast' },
    { code: 'BA', name_en: 'Bashkortostan' },
    { code: 'BEL', name_en: 'Belgorod Oblast' },
    { code: 'BRY', name_en: 'Bryansk Oblast' },
    { code: 'BU', name_en: 'Buryatia' },
    { code: 'CE', name_en: 'Chechnya' },
    { code: 'CHE', name_en: 'Chelyabinsk Oblast' },
    { code: 'CHU', name_en: 'Chukotka Autonomous Okrug' },
    { code: 'CU', name_en: 'Chuvashia' },
    { code: 'DA', name_en: 'Dagestan' },
    { code: 'IN', name_en: 'Ingushetia' },
    { code: 'IRK', name_en: 'Irkutsk Oblast' },
    { code: 'IVA', name_en: 'Ivanovo Oblast' },
    { code: 'KB', name_en: 'Kabardino-Balkaria' },
    { code: 'KGD', name_en: 'Kaliningrad Oblast' },
    { code: 'KL', name_en: 'Kalmykia' },
    { code: 'KLU', name_en: 'Kaluga Oblast' },
    { code: 'KAM', name_en: 'Kamchatka Krai' },
    { code: 'KC', name_en: 'Karachay-Cherkessia' },
    { code: 'KR', name_en: 'Karelia' },
    { code: 'KEM', name_en: 'Kemerovo Oblast' },
    { code: 'KHA', name_en: 'Khabarovsk Krai' },
    { code: 'KHM', name_en: 'Khanty-Mansi Autonomous Okrug' },
    { code: 'KIR', name_en: 'Kirov Oblast' },
    { code: 'KO', name_en: 'Komi Republic' },
    { code: 'KOS', name_en: 'Kostroma Oblast' },
    { code: 'KDA', name_en: 'Krasnodar Krai' },
    { code: 'KYA', name_en: 'Krasnoyarsk Krai' },
    { code: 'KGN', name_en: 'Kurgan Oblast' },
    { code: 'KRS', name_en: 'Kursk Oblast' },
    { code: 'LEN', name_en: 'Leningrad Oblast' },
    { code: 'LIP', name_en: 'Lipetsk Oblast' },
    { code: 'MAG', name_en: 'Magadan Oblast' },
    { code: 'ME', name_en: 'Mari El' },
    { code: 'MO', name_en: 'Mordovia' },
    { code: 'MOS', name_en: 'Moscow Oblast' },
    { code: 'MOW', name_en: 'Moscow' },
    { code: 'MUR', name_en: 'Murmansk Oblast' },
    { code: 'NEN', name_en: 'Nenets Autonomous Okrug' },
    { code: 'NIZ', name_en: 'Nizhny Novgorod Oblast' },
    { code: 'NGR', name_en: 'Novgorod Oblast' },
    { code: 'NVS', name_en: 'Novosibirsk Oblast' },
    { code: 'OMS', name_en: 'Omsk Oblast' },
    { code: 'ORE', name_en: 'Orenburg Oblast' },
    { code: 'ORL', name_en: 'Oryol Oblast' },
    { code: 'PER', name_en: 'Perm Krai' },
    { code: 'PNZ', name_en: 'Penza Oblast' },
    { code: 'PRI', name_en: 'Primorsky Krai' },
    { code: 'PSK', name_en: 'Pskov Oblast' },
    { code: 'ROS', name_en: 'Rostov Oblast' },
    { code: 'RYA', name_en: 'Ryazan Oblast' },
    { code: 'SA', name_en: 'Sakha (Yakutia)' },
    { code: 'SAK', name_en: 'Sakhalin Oblast' },
    { code: 'SAM', name_en: 'Samara Oblast' },
    { code: 'SAR', name_en: 'Saratov Oblast' },
    { code: 'SE', name_en: 'North Ossetia-Alania' },
    { code: 'SMO', name_en: 'Smolensk Oblast' },
    { code: 'SPE', name_en: 'Saint Petersburg' },
    { code: 'STA', name_en: 'Stavropol Krai' },
    { code: 'SVE', name_en: 'Sverdlovsk Oblast' },
    { code: 'TAM', name_en: 'Tambov Oblast' },
    { code: 'TA', name_en: 'Tatarstan' },
    { code: 'TOM', name_en: 'Tomsk Oblast' },
    { code: 'TUL', name_en: 'Tula Oblast' },
    { code: 'TVE', name_en: 'Tver Oblast' },
    { code: 'TY', name_en: 'Tuva' },
    { code: 'TYU', name_en: 'Tyumen Oblast' },
    { code: 'UD', name_en: 'Udmurtia' },
    { code: 'ULY', name_en: 'Ulyanovsk Oblast' },
    { code: 'VLA', name_en: 'Vladimir Oblast' },
    { code: 'VGG', name_en: 'Volgograd Oblast' },
    { code: 'VLG', name_en: 'Vologda Oblast' },
    { code: 'VOR', name_en: 'Voronezh Oblast' },
    { code: 'YAN', name_en: 'Yamalo-Nenets Autonomous Okrug' },
    { code: 'YAR', name_en: 'Yaroslavl Oblast' },
    { code: 'YEV', name_en: 'Jewish Autonomous Oblast' },
    { code: 'ZAB', name_en: 'Zabaykalsky Krai' },
  ],
  UA: [
    { code: 'VN', name_en: 'Vinnytsia Oblast' },
    { code: 'VL', name_en: 'Volyn Oblast' },
    { code: 'DP', name_en: 'Dnipropetrovsk Oblast' },
    { code: 'DT', name_en: 'Donetsk Oblast' },
    { code: 'ZT', name_en: 'Zhytomyr Oblast' },
    { code: 'ZK', name_en: 'Zakarpattia Oblast' },
    { code: 'ZP', name_en: 'Zaporizhzhia Oblast' },
    { code: 'IF', name_en: 'Ivano-Frankivsk Oblast' },
    { code: 'KV', name_en: 'Kyiv Oblast' },
    { code: 'KR', name_en: 'Kirovohrad Oblast' },
    { code: 'LH', name_en: 'Luhansk Oblast' },
    { code: 'LV', name_en: 'Lviv Oblast' },
    { code: 'MY', name_en: 'Mykolaiv Oblast' },
    { code: 'OD', name_en: 'Odesa Oblast' },
    { code: 'PL', name_en: 'Poltava Oblast' },
    { code: 'RV', name_en: 'Rivne Oblast' },
    { code: 'SM', name_en: 'Sumy Oblast' },
    { code: 'TP', name_en: 'Ternopil Oblast' },
    { code: 'KK', name_en: 'Kharkiv Oblast' },
    { code: 'KS', name_en: 'Kherson Oblast' },
    { code: 'KM', name_en: 'Khmelnytskyi Oblast' },
    { code: 'CK', name_en: 'Cherkasy Oblast' },
    { code: 'CH', name_en: 'Chernihiv Oblast' },
    { code: 'CV', name_en: 'Chernivtsi Oblast' },
    { code: 'CR', name_en: 'Autonomous Republic of Crimea' },
    { code: 'KC', name_en: 'Kyiv City' },
    { code: 'SC', name_en: 'Sevastopol' },
  ],
  DE: [
    { code: 'BW', name_en: 'Baden-Wuerttemberg' },
    { code: 'BY', name_en: 'Bavaria' },
    { code: 'BE', name_en: 'Berlin' },
    { code: 'BB', name_en: 'Brandenburg' },
    { code: 'HB', name_en: 'Bremen' },
    { code: 'HH', name_en: 'Hamburg' },
    { code: 'HE', name_en: 'Hesse' },
    { code: 'MV', name_en: 'Mecklenburg-Vorpommern' },
    { code: 'NI', name_en: 'Lower Saxony' },
    { code: 'NW', name_en: 'North Rhine-Westphalia' },
    { code: 'RP', name_en: 'Rhineland-Palatinate' },
    { code: 'SL', name_en: 'Saarland' },
    { code: 'SN', name_en: 'Saxony' },
    { code: 'ST', name_en: 'Saxony-Anhalt' },
    { code: 'SH', name_en: 'Schleswig-Holstein' },
    { code: 'TH', name_en: 'Thuringia' },
  ],
  FR: [
    { code: 'ARA', name_en: 'Auvergne-Rhone-Alpes' },
    { code: 'BFC', name_en: 'Bourgogne-Franche-Comte' },
    { code: 'BRE', name_en: 'Brittany' },
    { code: 'CVL', name_en: 'Centre-Val de Loire' },
    { code: 'COR', name_en: 'Corsica' },
    { code: 'GES', name_en: 'Grand Est' },
    { code: 'HDF', name_en: 'Hauts-de-France' },
    { code: 'IDF', name_en: 'Ile-de-France' },
    { code: 'NOR', name_en: 'Normandy' },
    { code: 'NAQ', name_en: 'Nouvelle-Aquitaine' },
    { code: 'OCC', name_en: 'Occitanie' },
    { code: 'PDL', name_en: 'Pays de la Loire' },
    { code: 'PAC', name_en: "Provence-Alpes-Cote d'Azur" },
    { code: 'GP', name_en: 'Guadeloupe' },
    { code: 'MQ', name_en: 'Martinique' },
    { code: 'GF', name_en: 'French Guiana' },
    { code: 'RE', name_en: 'Reunion' },
    { code: 'YT', name_en: 'Mayotte' },
  ],
  GB: [
    { code: 'ENG', name_en: 'England' },
    { code: 'NIR', name_en: 'Northern Ireland' },
    { code: 'SCT', name_en: 'Scotland' },
    { code: 'WLS', name_en: 'Wales' },
  ],
  SG: [
    { code: 'C', name_en: 'Central Region' },
    { code: 'E', name_en: 'East Region' },
    { code: 'N', name_en: 'North Region' },
    { code: 'NE', name_en: 'North-East Region' },
    { code: 'W', name_en: 'West Region' },
  ],
}
