'use client'

import React from 'react'
import InboxTabsHeader from './InboxTabsHeader'
import InboxRepliesPane from './InboxRepliesPane'
import DmMessagesPane from './DmMessagesPane'
import PublishedPostsPane from '../../feed/components/PublishedPostsPane'

export default function InboxPane({
  t,
  inboxTab,
  setInboxTab,
  setDmWithUserId,
  mounted,
  unreadCount,
  dmUnreadCount,
  myPublishedPosts,
  formatCount,
  visibleRepliesToMe,
  adEvery,
  interleaveAds,
  debugAdsSlots,
  dataPosts,
  resolveNickForDisplay,
  openReportPopover,
  openSharePopover,
  openThreadForPost,
  reactMut,
  isAdmin,
  delPost,
  delPostOwn,
  banUser,
  unbanUser,
  bannedSet,
  viewerId,
  markViewPost,
  starredAuthors,
  toggleAuthorStar,
  handleUserInfoToggle,
  pickAdUrlForSlot,
  compensateScrollOnResize,
  repliesHasMore,
  setVisibleRepliesCount,
  repliesPageSize,
  sortedRepliesToMe,
  dmWithUserId,
  dmBlockedMap,
  dmBlockedByReceiverMap,
  meId,
  dmThreadRef,
  dmThreadHasMore,
  dmThreadLoading,
  dmThreadCursor,
  loadDmThread,
  dmThreadItems,
  dmDeletedMsgMap,
  dmThreadSeenTs,
  dmTranslateMap,
  setDmTranslateMap,
  resolveProfileAccountId,
  resolveIconForDisplay,
  openDmDeletePopover,
  toggleDmBlock,
  locale,
  dmDialogs,
  dmDeletedMap,
  dmSeenMap,
  pushNavState,
  stripMediaUrlsFromText,
  dmDialogsHasMore,
  dmDialogsLoading,
  dmDialogsCursor,
  loadDmDialogs,
  dmDialogsLoaded,
  visiblePublishedPosts,
  publishedHasMore,
  setVisiblePublishedCount,
  publishedPageSize,
  LoadMoreSentinel,
  PostCard,
  ForumAdSlot,
}) {
  return (
    <>
      <InboxTabsHeader
        t={t}
        inboxTab={inboxTab}
        setInboxTab={setInboxTab}
        setDmWithUserId={setDmWithUserId}
        mounted={mounted}
        unreadCount={unreadCount}
        dmUnreadCount={dmUnreadCount}
        myPublishedCount={myPublishedPosts?.length || 0}
        formatCount={formatCount}
      />
      <div
        className="grid gap-2 inboxBody"
        style={{ marginTop: 'var(--inbox-content-top-offset, 8px)' }}
        suppressHydrationWarning
      >
        {inboxTab === 'replies' && (
          <InboxRepliesPane
            visibleRepliesToMe={visibleRepliesToMe}
            adEvery={adEvery}
            interleaveAds={interleaveAds}
            debugAdsSlots={debugAdsSlots}
            dataPosts={dataPosts}
            resolveNickForDisplay={resolveNickForDisplay}
            openReportPopover={openReportPopover}
            openSharePopover={openSharePopover}
            openThreadForPost={openThreadForPost}
            reactMut={reactMut}
            isAdmin={isAdmin}
            delPost={delPost}
            delPostOwn={delPostOwn}
            banUser={banUser}
            unbanUser={unbanUser}
            bannedSet={bannedSet}
            viewerId={viewerId}
            markViewPost={markViewPost}
            t={t}
            starredAuthors={starredAuthors}
            toggleAuthorStar={toggleAuthorStar}
            handleUserInfoToggle={handleUserInfoToggle}
            pickAdUrlForSlot={pickAdUrlForSlot}
            compensateScrollOnResize={compensateScrollOnResize}
            repliesHasMore={repliesHasMore}
            setVisibleRepliesCount={setVisibleRepliesCount}
            repliesPageSize={repliesPageSize}
            sortedRepliesLength={sortedRepliesToMe.length}
            PostCard={PostCard}
            ForumAdSlot={ForumAdSlot}
            LoadMoreSentinel={LoadMoreSentinel}
          />
        )}

        {inboxTab === 'messages' && (
          <DmMessagesPane
            dmWithUserId={dmWithUserId}
            dmBlockedMap={dmBlockedMap}
            dmBlockedByReceiverMap={dmBlockedByReceiverMap}
            meId={meId}
            t={t}
            starredAuthors={starredAuthors}
            toggleAuthorStar={toggleAuthorStar}
            handleUserInfoToggle={handleUserInfoToggle}
            dmThreadRef={dmThreadRef}
            dmThreadHasMore={dmThreadHasMore}
            dmThreadLoading={dmThreadLoading}
            dmThreadCursor={dmThreadCursor}
            loadDmThread={loadDmThread}
            dmThreadItems={dmThreadItems}
            dmDeletedMsgMap={dmDeletedMsgMap}
            dmThreadSeenTs={dmThreadSeenTs}
            dmTranslateMap={dmTranslateMap}
            setDmTranslateMap={setDmTranslateMap}
            resolveProfileAccountId={resolveProfileAccountId}
            resolveNickForDisplay={resolveNickForDisplay}
            resolveIconForDisplay={resolveIconForDisplay}
            openDmDeletePopover={openDmDeletePopover}
            toggleDmBlock={toggleDmBlock}
            locale={locale}
            dmDialogs={dmDialogs}
            dmDeletedMap={dmDeletedMap}
            dmSeenMap={dmSeenMap}
            pushNavState={pushNavState}
            setInboxTab={setInboxTab}
            setDmWithUserId={setDmWithUserId}
            stripMediaUrlsFromText={stripMediaUrlsFromText}
            dmDialogsHasMore={dmDialogsHasMore}
            dmDialogsLoading={dmDialogsLoading}
            dmDialogsCursor={dmDialogsCursor}
            loadDmDialogs={loadDmDialogs}
            dmDialogsLoaded={dmDialogsLoaded}
            LoadMoreSentinel={LoadMoreSentinel}
          />
        )}

        {inboxTab === 'published' && (
          <PublishedPostsPane
            visiblePublishedPosts={visiblePublishedPosts}
            dataPosts={dataPosts}
            resolveNickForDisplay={resolveNickForDisplay}
            openReportPopover={openReportPopover}
            openSharePopover={openSharePopover}
            openThreadForPost={openThreadForPost}
            reactMut={reactMut}
            isAdmin={isAdmin}
            delPost={delPost}
            delPostOwn={delPostOwn}
            banUser={banUser}
            unbanUser={unbanUser}
            bannedSet={bannedSet}
            viewerId={viewerId}
            markViewPost={markViewPost}
            t={t}
            starredAuthors={starredAuthors}
            toggleAuthorStar={toggleAuthorStar}
            handleUserInfoToggle={handleUserInfoToggle}
            publishedHasMore={publishedHasMore}
            setVisiblePublishedCount={setVisiblePublishedCount}
            publishedPageSize={publishedPageSize}
            myPublishedPostsLength={myPublishedPosts.length}
            PostCard={PostCard}
            LoadMoreSentinel={LoadMoreSentinel}
          />
        )}
      </div>
    </>
  )
}

