'use client'
import React from 'react'
function s(v){return String(v??'').trim()}
function formatSeconds(value=0){const total=Math.max(0,Math.ceil(Number(value||0)));if(total<60)return`${total}s`;const m=Math.floor(total/60);const sec=String(total%60).padStart(2,'0');return`${m}:${sec}`}
export default function Ql7SupportComposerRuntimePanel({textLen=0,textLimit=600,policy=null,blocked=false,seconds=0,sendDisabled=false,onSendClick,t=(k)=>k,cls=(...v)=>v.filter(Boolean).join(' ')}={}){
 const title=s(policy?.reasonLabel||policy?.title||(blocked?policy?.message:(t?.('ql7_support_text_only')||'Text only')));const detail=s(policy?.detail||policy?.message);const remainingMs=Math.max(0,Number(policy?.remainingMs??(Number(seconds||0)*1000)));const totalMs=Math.max(remainingMs,Number(policy?.totalCooldownMs||policy?.cooldownMs||remainingMs));const progress=blocked&&totalMs>0?Math.max(0,Math.min(100,100-(remainingMs*100/totalMs))):100;const stage=s(policy?.runtimeStage||policy?.state);const trulyReady=!blocked&&policy?.allowed!==false&&['input_ready','ready_for_input','waiting_user','waiting_choice','idle','completed',''].includes(stage)
 return <div className={cls('ql7SupportComposerRuntimePanel',blocked&&'isLocked')} data-ql7-support-composer-runtime="canonical" data-ql7-support-input-policy={blocked?'locked':trulyReady?'ready':'processing'} data-ql7-support-runtime-stage={stage||undefined} data-ql7-support-server-now={s(policy?.serverNow)||undefined} data-ql7-support-countdown={blocked?'finite':'none'} role="status" aria-live="polite">
  <div className="ql7SupportRuntimeCounter"><span>{textLen}</span><span>/</span><span className={textLen>textLimit?'over':''}>{textLimit}</span></div>
  <div className="ql7SupportRuntimeCore"><span className="ql7SupportRuntimeGlyph" aria-hidden="true"><svg viewBox="0 0 44 44" width="32" height="32" preserveAspectRatio="xMidYMid meet" focusable="false"><circle cx="22" cy="22" r="15" fill="none"/><path d="M22 7a15 15 0 0 1 15 15" fill="none"/></svg></span><div className="ql7SupportRuntimeCopy"><b>{title}</b>{detail&&detail!==title?<small>{detail}</small>:null}<span className="ql7SupportRuntimeProgress"><i style={{width:`${progress}%`}}/></span></div>{blocked?<strong className="ql7SupportRuntimeCountdown">{formatSeconds(Math.ceil(remainingMs/1000))}</strong>:trulyReady?<span className="ql7SupportRuntimeReady" aria-hidden="true"><svg viewBox="0 0 18 18" width="18" height="18" focusable="false"><path d="M4 9.2l3 3.1 7-7.3" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg></span>:<span className="ql7SupportRuntimePending" aria-hidden="true">...</span>}</div>
  <button type="button" className={cls('iconBtn planeBtn',sendDisabled&&'disabled')} aria-label={t?.('dm_send')||'Send'} disabled={sendDisabled} onClick={onSendClick}><svg viewBox="0 0 24 24" width="22" height="22" preserveAspectRatio="xMidYMid meet" className="plane" aria-hidden><path d="M3 11.5l17-8.5-7.2 18.5-2.3-6.2-6.5-3.8z"/></svg></button>
 </div>
}
