import { ql7StableHash, ql7Str } from '../internal/text.js'
import { collectQl7SafetySignals } from '../language/semanticBanks.js'
import { assessQl7SupportInsult } from './insultAssessment.js'
import { resolveQl7SupportInsultState } from './insultStateMachine.js'
const QUOTE=/^(?:>|“|"|«)|(?:он|она|они|they|he|she)\s+(?:сказал|сказала|said)|(?:цитат\p{L}*|quote|lyrics|песня|film|movie)/iu
const DIRECT_INSULT=/(?:ты|вы|ти|ви|you|u|eres|usted|ustedes|sen|siz|أنت|انتم|你|您|אתה|אתם).{0,24}(?:идиот|ідіот|дебил|дебіл|туп(?:ой|ые|ий|і)|мудак|moron|idiot|stupid|fuck\s*you|imbécil|idiota|estúpido|aptal|salak|غبي|أحمق|白痴|蠢|מטומטם|אידיוט)|^(?:идиоты|ідіоти|дебилы|дебіли|мудаки|уроды|morons?|idiots?|idiotas?|aptallar|حمقى|白痴|מטומטמים)[!?.\s]*$/iu
const PRODUCT_FRUSTRATION=/(?:сервис|сайт|приложение|система|функция|app|service|site|system).{0,24}(?:бесит|достал|дерьмо|ужас|sucks|broken|terrible|shit)/iu
const THREAT=/(?:я|мы|i|we|yo|nosotros|voy\s+a|ben|biz|سوف|سأ|انا|我|我要|我们|אני|אנחנו).{0,36}(?:убью|вб'ю|знищу|уничтожу|взорву|підірву|атакую|атакуватиму|взломаю|зламаю|هاجم|سأهاجم|kill|destroy|bomb|attack|hack|matar|destruir|atacar|hackear|öldür|yok\s+et|saldır|hackle|قتل|أدمر|أهاجم|سأهاجم|أخترق|杀|摧毁|攻击|入侵|אהרוג|אשמיד|אתקוף|אפרוץ)|(?:теракт|бомба|massacre|terror(?:ist)?\s+attack|ataque\s+terrorista|terör\s+saldırısı|هجوم\s+إرهابي|恐怖袭击|פיגוע|взорв(?:у|ем)|підірв)/iu
const SELF_HARM=/(?:хочу\s+(?:умереть|не\s+жить)|не\s+хочу\s+жить|жить\s+не\s+хочу|нет\s+сил\s+жить|покончу\s+с\s+собой|убью\s+себя|сдела(?:ю|ть).{0,24}с\s+собой|что[-\s]?то\s+с\s+собой|наврежу\s+себе|навредить\s+себе|причинить\s+себе\s+вред|само(?:вред|убий)|су[еиы]цид|накладу\s+на\s+себя\s+руки|выйти\s+в\s+окно|мені\s+(?:не\s+хочеться\s+жити|погано.{0,24}зробити\s+щось\s+із\s+собою)|не\s+хочу\s+жити|заподіяти\s+собі\s+шкоду|i\s+(?:want\s+to\s+die|do\s+not\s+want\s+to\s+live|don't\s+want\s+to\s+live|cant\s+go\s+on|can't\s+go\s+on)|kill\s+myself|hurt\s+myself|harm\s+myself|self[-\s]?harm|end\s+(?:it\s+all|my\s+life)|take\s+my\s+life|quiero\s+morir|no\s+quiero\s+vivir|hacerme\s+daño|suicid|kendime\s+zarar|ölmek\s+istiyorum|yaşamak\s+istemiyorum|انتحار|أريد\s+أن\s+أموت|أؤذي\s+نفسي|自杀|不想活|伤害自己|想死|להתאבד|לא\s+רוצה\s+לחיות|לפגוע\s+בעצמי)/iu
const SUPPORT_TARGET=/(?:^|[^\p{L}\p{N}_])(?:ты|вы|тебя|вам|support|саппорт|оператор|bot|бот|you|your|u|du|dich|dir|euch|tu|usted|sen|siz|أنت|انتم|你|您|אתה|אתם)(?=$|[^\p{L}\p{N}_])/iu
export function evaluateQl7SupportSafety({text='',priorLedger={},now=Date.now,locale=''}={}){
 const source=ql7Str(text);const bank=collectQl7SafetySignals(source,locale);const quoted=QUOTE.test(source);const rawInsultAssessment=assessQl7SupportInsult({text:source,locale,priorLedger});const obfuscatedThreatHits=rawInsultAssessment?.matches?.threats||[];const threat=!quoted&&(THREAT.test(source)||bank.threats.length>0||obfuscatedThreatHits.length>0);const selfHarm=!quoted&&SELF_HARM.test(source);const frustration=PRODUCT_FRUSTRATION.test(source);const insultAssessment=quoted?Object.freeze({...rawInsultAssessment,score:Math.min(.2,Number(rawInsultAssessment.score||0)),decision:'none',target:'third_party',counterEvidence:Object.freeze(Array.from(new Set([...(rawInsultAssessment.counterEvidence||[]),'quoted_or_reported'])))}):rawInsultAssessment;const insultState=resolveQl7SupportInsultState({assessment:insultAssessment,priorLedger,now:typeof now==='function'?new Date(now()).toISOString():new Date(Number(now||Date.now())).toISOString()});const prior=Number(priorLedger?.safety?.confirmedDirectInsultCount??priorLedger?.safety?.directInsultCount??priorLedger?.safetyStrikeCount??0)
 let category='none',severity='normal',escalationLevel=0,cooldownMs=0,operatorRequired=false
 if(selfHarm){category='crisis';severity='critical';escalationLevel=5;operatorRequired=true}
 else if(threat){category='credible_threat';severity='critical';escalationLevel=5;cooldownMs=30*60*1000;operatorRequired=true}
 else if(insultAssessment.decision==='uncertain'){category='insult_uncertain';severity='normal';escalationLevel=prior}
 else if(insultAssessment.decision==='denied'){category='insult_denied';severity='normal';escalationLevel=prior}
 else if(['confirmed','continued'].includes(insultAssessment.decision)){category='direct_insult';escalationLevel=prior+1;severity=escalationLevel===1?'warning':'elevated';cooldownMs=escalationLevel===1?0:escalationLevel===2?60*1000:escalationLevel===3?5*60*1000:15*60*1000;operatorRequired=escalationLevel>=4}
 else if(frustration){category='product_frustration';severity='normal'}
 const current=typeof now==='function'?Number(now()):Number(now||Date.now());const blockedUntil=cooldownMs?new Date(current+cooldownMs).toISOString():''
 return Object.freeze({category,severity,escalationLevel,cooldownMs,blockedUntil,operatorRequired,quoted,frustration,insult:category==='direct_insult',threat,selfHarm,insultAssessment,insultState,profanityHits:Object.freeze([...bank.profanity,...bank.euphemisms].slice(0,16)),threatHits:Object.freeze([...bank.threats,...obfuscatedThreatHits].slice(0,16)),matchedSpanHash:category==='none'?'':ql7StableHash(source.toLowerCase()),allowMaterialHelp:!threat&&!selfHarm})
}
