import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const ROOT = process.cwd()
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), 'utf8')

const source = read('lib/forum/forum-user-recommendation-pool.cjs')
const route = read('app/api/forum/recommendations/users/route.js')
const hook = read('app/forum/features/feed/hooks/useUserRecommendationsRail.js')
const videoFeedState = read('app/forum/features/media/hooks/useVideoFeedState.js')
const runtime = read('app/forum/shared/config/runtime.js')
const deletion = read('lib/mongo/account-deletion-primary.cjs')
const rebuild = read('scripts/forum-recommendations/rebuild-top500.mjs')
const verify = read('scripts/forum-recommendations/verify-top500-mongo.mjs')

 describe('forum user recommendation Top-500 Mongo production contract', () => {
  it('pins the V11 clean-baseline feature and one canonical Mongo pool', () => {
    expect(source).toContain('QL7_FORUM_USER_RECOMMENDATIONS_TOP500_MONGO_FINAL_BASELINE_V12')
    expect(source).toContain("const COLLECTION = 'forum_user_recommendation_pool'")
    expect(source).toContain("const POOL_ID = 'weekly-top:v1'")
    expect(source).toContain("const FORMULA_VERSION = 'balanced-history-profile-v1'")
    expect(source).toContain('const TOP_LIMIT = 500')
    expect(source).toContain('const SCHEMA_VERSION = 9')
  })

  it('uses authoritative follower relation sets and never gates eligibility on the legacy count projection', () => {
    expect(source).toContain("const FOLLOWER_AUTHORITY_VERSION = 'forum-subscription-sets-relation-v2'")
    expect(source).toContain("db.collection('forum_subscription_sets')")
    expect(source).toContain('async function readFollowerRelationUniverse')
    expect(source).toContain('async function readExactFollowerCounts')
    expect(source).toContain('forum_subscription_counts')
    expect(source).toContain('is deliberately not consulted')
    expect(source).not.toContain("db.collection('forum_subscription_counts')")
    expect(verify).toContain("const forumPrimary = require('../../lib/mongo/forum-primary.cjs')")
    expect(verify).toContain('forumPrimary.getFollowersCount')
    expect(verify).not.toContain('profilePrimary.getFollowersCount')
    expect(verify).not.toContain("db.collection('forum_subscription_counts')")
  })

  it('requires follower>=1, current nickname/avatar, no permanent ban and no active media safety lock', () => {
    expect(source).toContain("const ELIGIBILITY_POLICY_VERSION = 'followers-relation-profile-moderation-gate-v2'")
    expect(source).toContain('const MIN_FOLLOWERS = 1')
    expect(source).toContain('if (Math.max(0, num(metric?.followers)) < MIN_FOLLOWERS) continue')
    expect(source).toContain('const missingNickname = !profile?.nickname')
    expect(source).toContain('const missingAvatar = !profile?.avatar')
    expect(source).toContain("const MODERATION_POLICY_VERSION = 'active-media-lock-exclusion-v1'")
    expect(source).toContain("const MEDIA_LOCK_KEY_PREFIX = 'forum:lock:media:'")
    expect(source).toContain('selectModerationEligibleRanked')
    expect(source).toContain("readMediaLockStates(deliveryCanonicalIds, aliasesByCanonical, 'delivery-media-lock', Date.now(), db)")
    expect(source).toContain("databaseHandle.collection('forum_media_locks')")
    expect(source).toContain('One indexed batch query replaces the old')
    expect(source).toContain('MEDIA_LOCK_LEGACY_COMPAT_MARKER_KEY')
    expect(source).toContain('legacyMediaLockChecked')
    expect(source).toContain("source: 'legacy_recommendation_redis_migration'")
    expect(source).toContain('const keys = group.map((canonical) => `${MEDIA_LOCK_KEY_PREFIX}${canonicalMediaLockRedisId(canonical)}`)')
    expect(source).not.toContain('function mediaLockIdentityVariants')
    expect(source).not.toContain('if (!(parts.score > 0)) continue')
  })

  it('ranks with lifetime history, followers, engagement, profile completeness, tenure, recent activity and VIP', () => {
    expect(source).toContain('20 * logNorm(publicationsLifetime, 1000)')
    expect(source).toContain('20 * logNorm(viewsLifetime, 1_000_000)')
    expect(source).toContain('25 * logNorm(followers, 50_000)')
    expect(source).toContain('6 * logNorm(likesLifetime, 50_000)')
    expect(source).toContain('4 * logNorm(repliesLifetime, 10_000)')
    expect(source).toContain('profileSignals.aboutFilled ? 4 : 0')
    expect(source).toContain('profileSignals.genderFilled ? 3 : 0')
    expect(source).toContain('profileSignals.birthYearFilled ? 3 : 0')
    expect(source).toContain('5 * logNorm(tenureDays, 730)')
    expect(source).toContain('2 * logNorm(publications7d, 30)')
    expect(source).toContain('3 * logNorm(views7d, 100_000)')
    expect(source).toContain('metrics.vipAtBuild ? 5 : 0')
  })

  it('uses lifetime activity as ranking data while keeping seven-day activity only as a freshness signal', () => {
    expect(source).toContain('async function aggregateActivityCollection')
    expect(source).toContain("'visibility.deleted': false")
    expect(source).not.toContain("'sort.new': { $gte: windowFromMs }")
    expect(source).toContain('countLifetime')
    expect(source).toContain('count7d')
    expect(source).toContain("db.collection('forum_user_stats')")
  })

  it('preserves the V7 normalized-seed identity and current profile runtime contracts', () => {
    expect(source).toContain("const IDENTITY_RESOLVER_VERSION = 'top500-forum-normalized-seed-v7'")
    expect(source).toContain("const IDENTITY_AUTHORITY_POLICY = 'forum-normalized-seed-profile-read-v5'")
    expect(source).toContain('function forumIdentityLookupSeed')
    expect(source).toContain("mode: 'profile-read'")
    expect(source).toContain('representationVariantsCollapsed')
    expect(source).toContain('identity_seed_semantic_authority_conflict')
    expect(source).toContain("const AUTHORITATIVE_PROFILE_SOURCE = 'profilePrimary.getUserProfile'")
    expect(source).toContain("presentationHydration: 'live-per-response'")
    expect(source).toContain('profile_duplication:')
  })

  it('fixes the rail at 15 and atomically invalidates guest/user state across auth transitions', () => {
    expect(runtime).toContain('const DEFAULT_USER_RECOMMENDATIONS_BATCH_SIZE = 15')
    expect(runtime).toContain('const recommendationsBatchSize = DEFAULT_USER_RECOMMENDATIONS_BATCH_SIZE')
    expect(runtime).not.toContain('process.env.NEXT_PUBLIC_FORUM_USER_RECOMMENDATIONS_BATCH_SIZE')
    expect(route).toContain('const batchSize = DEFAULT_BATCH_SIZE')
    expect(route).not.toContain("readBoundedNumber(searchParams, 'batchSize'")
    expect(hook).toContain('const requestAbortRef = useRef(null)')
    expect(hook).toContain('requestAbortRef.current?.abort()')
    expect(hook).toContain('...INITIAL_STATE')
    expect(hook).toContain('activeViewerKeyRef.current !== requestViewerKey')
    expect(hook).toContain('controller.signal.aborted')
    expect(hook).toContain('state.activeFeedContextKey === recommendationFeedContextKey')
    expect(hook).toContain('followersCount < 1')
    expect(hook).toContain('responseViewerCanonicalId')
    expect(hook).toContain('desiredMissingCount - unusedBufferedBatchCount')
    expect(hook).toContain("desiredRailSlotKeys.join(',') || 'bootstrap'")
    expect(hook).toContain('bootstrapPreloadNeeded')
    expect(hook).toMatch(/const requestBatchCount = state\.batchOrder\.length === 0\s*\? 1\s*:\s*Math\.max/)
    expect(videoFeedState).not.toContain('buildVideoFeedContextSignature')
    expect(route).toContain('viewerCanonicalId: viewerId')
  })

  it('keeps deterministic no-repeat cycles and excludes the current canonical viewer', () => {
    expect(source).toContain('cycleExhausted: offset >= ranked.length')
    expect(source).toContain('Build one rail at a time')
    expect(source).toContain('cycleTransitions += 1')
    expect(source).toContain('canonicalViewerId')
    expect(source).toContain('globallyExcluded')
    expect(source).not.toContain('while (selected.length < wanted && safety <')
  })

  it('keeps GET cheap and POST rebuild lease-based while live delivery rechecks follower/profile/ban/media lock', () => {
    expect(route).toContain('recommendationPool.getPage')
    expect(route).toContain('recommendationPool.rebuildPool')
    expect(route).not.toContain('readForumSnapshot')
    expect(source).toContain('leaseToken')
    expect(source).toContain('async function ensurePoolShell')
    expect(source).toContain('await ensurePoolShell(db, nowMs)')
    expect(source).toContain('recommendation_pool_lease_lost_before_commit')
    expect(source).toContain('readBannedIds(db)')
    expect(source).toContain('readExactFollowerCounts(db, deliveryCanonicalIds, aliasesByCanonical)')
    expect(source).toContain("readAuthoritativeProfiles(deliveryCanonicalIds, 'delivery-profile')")
  })

  it('keeps privacy deletion physical and lease-revoking', () => {
    expect(deletion).toContain("db.collection('forum_user_recommendation_pool').updateOne")
    expect(deletion).toContain('$pull: { users: { canonicalAccountId: { $in: ids } } }')
    expect(deletion).toContain('leaseToken: null')
    expect(deletion).toContain('leaseUntil: null')
  })

  it('exposes follower/moderation build evidence and independent read-only relation/media-lock proof', () => {
    expect(rebuild).toContain('followerAuthorityVersion')
    expect(rebuild).toContain('mediaLockExcludedCount')
    expect(rebuild).toContain('moderationPolicyVersion')
    expect(rebuild).toContain('mongoWrites: 0')
    expect(verify).toContain('independentEligibilityAudit')
    expect(verify).toContain('independentMediaLockAudit')
    expect(verify).toContain('liveEligibleMissingFromPool')
    expect(verify).toContain('liveStoredActiveMediaLocks')
    expect(verify).toContain("readOnly: { mongoWrites: 0, collectionWrites: 0 }")
  })

  it('pins the 168-hour freshness window, 72-hour maximum cadence and earlier media-unlock wakeup', () => {
    expect(source).toContain('const WINDOW_MS = 7 * 24 * 60 * 60 * 1000')
    expect(source).toContain('const REBUILD_MS = 72 * 60 * 60 * 1000')
    expect(source).toContain('const RETRY_MS = 15 * 60 * 1000')
    expect(source).toContain('Math.min(nextCadenceMs, earliestUntilMs + 1000)')
    expect(source).toContain('media_unlock_rebuild_schedule')
  })
})
