import { describe, expect, it } from 'vitest'
import {
  basenameWithoutExtension,
  listProjectFiles,
  readRepoFile,
} from '../../support/projectSurface.js'

const forumHookFiles = listProjectFiles(
  'app/forum',
  (relPath) => /\/hooks\/use[A-Z][^/]*\.jsx?$/.test(relPath),
)

function findExportedHookNames(source) {
  const rx =
    /\bexport\s+(?:default\s+)?function\s+(use[A-Z][A-Za-z0-9_]*)\b|\bexport\s+(?:const|let|var)\s+(use[A-Z][A-Za-z0-9_]*)\b|\bexport\s*\{([^}]*)\}/g

  const names = new Set()
  let match

  while ((match = rx.exec(source)) !== null) {
    if (match[1]) names.add(match[1])
    if (match[2]) names.add(match[2])
    if (match[3]) {
      match[3]
        .split(',')
        .map((chunk) => chunk.trim())
        .forEach((chunk) => {
          const named = chunk.match(/\b(use[A-Z][A-Za-z0-9_]*)\b/)
          if (named?.[1]) names.add(named[1])
        })
    }
  }

  return Array.from(names)
}

describe('Forum hook contracts', () => {
  it('discovers the hook surface of the forum runtime', () => {
    expect(forumHookFiles.length).toBeGreaterThan(40)
  })

  it.each(forumHookFiles)('%s exports at least one hook symbol', (hookFile) => {
    const source = readRepoFile(hookFile)
    const hookName = basenameWithoutExtension(hookFile)
    const exportedHookNames = findExportedHookNames(source)

    expect(exportedHookNames.length).toBeGreaterThan(0)
    expect(hookName.startsWith('use')).toBe(true)
  })

  it('keeps forum diagnostics hook guarded by the master env flag', () => {
    const source = readRepoFile('app/forum/features/diagnostics/hooks/useForumDiagnostics.js')

    expect(source).toContain('NEXT_PUBLIC_FORUM_EARLY_DIAG_ENABLED')
    expect(source).toContain('if (!isDiagMasterEnabled()) return false')
  })

  it('keeps PostCardBridge and TopicItem memoized at the list entrypoints', () => {
    const postCardSource = readRepoFile('app/forum/features/feed/components/PostCardBridge.jsx')
    const topicItemSource = readRepoFile('app/forum/features/feed/components/TopicItem.jsx')

    expect(postCardSource).toContain('React.memo')
    expect(postCardSource).toContain('arePostCardBridgePropsEqual')
    expect(topicItemSource).toContain('React.memo')
    expect(topicItemSource).toContain('areTopicItemPropsEqual')
  })

  it('keeps feed panes passing memo-friendly author flags instead of bulky viewer context', () => {
    const videoFeedPane = readRepoFile('app/forum/features/media/components/VideoFeedPane.jsx')
    const threadRepliesPane = readRepoFile('app/forum/features/feed/components/ThreadRepliesPane.jsx')
    const inboxRepliesPane = readRepoFile('app/forum/features/dm/components/InboxRepliesPane.jsx')
    const userPostsPane = readRepoFile('app/forum/features/feed/components/UserPostsPane.jsx')
    const publishedPostsPane = readRepoFile('app/forum/features/feed/components/PublishedPostsPane.jsx')
    const topicsPane = readRepoFile('app/forum/features/feed/components/TopicsPane.jsx')

    ;[
      videoFeedPane,
      threadRepliesPane,
      inboxRepliesPane,
      userPostsPane,
      publishedPostsPane,
    ].forEach((source) => {
      expect(source).toContain('isSelfAuthor={isSelfAuthor}')
      expect(source).toContain('isStarredAuthor={isStarredAuthor}')
      expect(source).not.toContain('viewerId={viewerId}')
      expect(source).not.toContain('starredAuthors={starredAuthors}')
    })

    expect(topicsPane).toContain('isSelfAuthor={isSelfAuthor}')
    expect(topicsPane).toContain('isStarredAuthor={isStarredAuthor}')
    expect(topicsPane).not.toContain('viewerId={viewerId}')
    expect(topicsPane).not.toContain('starredAuthors={starredAuthors}')
  })

  it('keeps heavy card components consuming memo-friendly booleans instead of global viewer sets', () => {
    const forumPostCardSource = readRepoFile('app/forum/features/feed/components/ForumPostCard.jsx')
    const topicItemSource = readRepoFile('app/forum/features/feed/components/TopicItem.jsx')

    expect(forumPostCardSource).toContain('isSelfAuthor = false')
    expect(forumPostCardSource).toContain('isStarredAuthor = false')
    expect(forumPostCardSource).toContain('const isSelf = !!isSelfAuthor')
    expect(forumPostCardSource).toContain('const isStarred = !!isStarredAuthor')
    expect(forumPostCardSource).not.toContain('starredAuthors')

    expect(topicItemSource).toContain('isSelfAuthor = false')
    expect(topicItemSource).toContain('isStarredAuthor = false')
    expect(topicItemSource).toContain('const isSelf = !!isSelfAuthor')
    expect(topicItemSource).toContain('const isStarred = !!isStarredAuthor')
    expect(topicItemSource).not.toContain('starredAuthors')
  })

  it('keeps focus and visibility events from silently rebuilding the visible forum feed', () => {
    const syncLoopSource = readRepoFile('app/forum/features/feed/hooks/useForumSyncLoop.js')
    const visibleSyncMatch = syncLoopSource.match(/const requestVisibleSync = \(\) => \{([\s\S]*?)\n    \}/)

    expect(syncLoopSource).toContain("document.addEventListener('visibilitychange', requestVisibleSync)")
    expect(syncLoopSource).toContain("window.addEventListener('focus', requestVisibleSync)")
    expect(visibleSyncMatch).toBeTruthy()
    expect(visibleSyncMatch[1]).toContain('NO_FOCUS_VISIBLE_REORDER')
    expect(visibleSyncMatch[1]).not.toContain('syncNowRef')
    expect(visibleSyncMatch[1]).not.toContain('runTick')
    expect(visibleSyncMatch[1]).not.toContain('feedPage')
    expect(visibleSyncMatch[1]).not.toContain('bumpFeedRequestGeneration')
  })

  it('keeps Home topic sorting and counters on the server-complete reader contract', () => {
    const topicsRouteSource = readRepoFile('app/api/forum/topics/page/route.js')
    const sortControlsSource = readRepoFile('app/forum/features/ui/components/ForumSearchSortControls.jsx')
    const topicDiscoverySource = readRepoFile('app/forum/features/feed/hooks/useTopicDiscoveryModel.js')

    expect(topicsRouteSource).toContain('forum-server-complete-reader.cjs')
    expect(topicsRouteSource).toContain('readForumTopicsPage')
    expect(sortControlsSource).toContain('setTopicSort(nextSort)')
    expect(topicDiscoverySource).toContain("normalizedTopicSort === 'random' && shouldStabilizeByScroll")
  })

  it('keeps Geo/World rebuilds narrow and clears stale geo rank in World mode', () => {
    const forumRootSource = readRepoFile('app/forum/ForumRoot.jsx')
    const postMergeSource = readRepoFile('app/forum/features/feed/utils/postMerge.js')
    const videoBuilderSource = readRepoFile('app/forum/features/media/utils/videoFeedBuilder.js')
    const forumApiSource = readRepoFile('app/forum/services/forumApi.js')
    const forumFeedRuntimeSource = readRepoFile('app/forum/features/feed/hooks/useForumFeedRuntime.js')
    const threadRepliesPaneSource = readRepoFile('app/forum/features/feed/components/ThreadRepliesPane.jsx')
    const threadPostsModelSource = readRepoFile('app/forum/features/feed/hooks/useThreadPostsModel.js')
    const threadOpenNavigationSource = readRepoFile('app/forum/features/feed/hooks/useThreadOpenNavigation.js')
    const completeReaderSource = readRepoFile('lib/forum/forum-server-complete-reader.cjs')
    const sortControlsSource = readRepoFile('app/forum/features/ui/components/ForumSearchSortControls.jsx')

    expect(forumRootSource).toContain('startup_geo_retry_6s_rebuild')
    expect(forumRootSource).toContain('startup_geo_retry_8s_rebuild')
    expect(forumRootSource).toContain('startup_geo_retry_10s_rebuild')
    expect(forumRootSource).toContain('startupRebuildCount')
    expect(forumRootSource).toContain('geo_mode_world_rebuild')
    expect(forumRootSource).toContain('geo_mode_geo_rebuild')
    expect(forumRootSource).not.toContain('forum:home-action-refresh-click')
    expect(forumRootSource).not.toContain('forceFeedScrollTop')
    expect(postMergeSource).toContain('delete out.__ql7GeoFeedRank')
    expect(videoBuilderSource).toContain("mode === 'geo' ? item?.__ql7GeoFeedRank : undefined")
    expect(videoBuilderSource).toContain('finiteServerRankForActiveMode')
    expect(videoBuilderSource).toContain('const hasServerRankedItems = only.some')
    expect(forumRootSource).toContain('pageAgeMs > 10_500')
    expect(readRepoFile('app/forum/features/feed/hooks/useTopicDiscoveryModel.js')).toContain('topicRankForActiveMode')
    expect(readRepoFile('app/forum/features/feed/hooks/useTopicDiscoveryModel.js')).toContain('runtimeGeoFeedMode,')
    expect(sortControlsSource).toContain('forceRandomFeedRebuildForMode')
    expect(sortControlsSource).toContain("writeForumFeedSortPreference('random')")
    expect(readRepoFile('app/forum/features/media/hooks/useForumVideoFeedRuntime.js')).toContain('normalizeVideoFeedSort')
    expect(readRepoFile('app/forum/features/media/hooks/useForumVideoFeedRuntime.js')).toContain('setVideoFeedEntryToken')
    expect(readRepoFile('app/forum/features/media/hooks/useForumVideoFeedRuntime.js')).toContain('setServerVideoPosts([])')
    expect(readRepoFile('app/forum/features/media/hooks/useForumVideoFeedRuntime.js')).toContain('videoFeedHardResetRef.current?.()')
    expect(readRepoFile('app/forum/features/media/hooks/useForumVideoFeedRuntime.js')).toContain('scheduleVideoFeedFirstCardSnap')
    expect(readRepoFile('app/forum/features/media/hooks/useVideoFeedWindowing.js')).toContain('scrollToTopOnHardReset: false')
    expect(readRepoFile('app/forum/features/media/hooks/useVideoFeedState.js')).toContain('const sourceData = videoFeedOpen')
    expect(readRepoFile('app/forum/features/media/hooks/useVideoFeedState.js')).toContain('data: sourceData')
    expect(readRepoFile('app/forum/features/media/utils/videoFeedScroll.js')).toContain('firstVideoFeedPostCard')
    expect(readRepoFile('app/forum/features/media/utils/videoFeedScroll.js')).toContain('markProgrammaticVideoSnap')
    expect(readRepoFile('app/forum/features/media/utils/videoFeedScroll.js')).toContain('data-ql7-video-feed-grid="1"')
    expect(forumApiSource).toContain('normalizeForumThreadSort')
    expect(forumApiSource).toContain('feedMode:')
    expect(forumFeedRuntimeSource).toContain("feedMode: 'world'")
    expect(forumFeedRuntimeSource).toContain('setPostSort,')
    expect(forumRootSource).toContain('lastTopicOpenDefaultSortIdRef')
    expect(forumRootSource).toContain("setPostSort('new')")
    expect(threadPostsModelSource).toContain('hasServerRankedChildren')
    expect(threadPostsModelSource).toContain('shouldUseServerRankedChildren')
    expect(threadOpenNavigationSource).toContain("setPostSort?.('new')")
    expect(threadOpenNavigationSource).toContain("hydrateThreadTarget(seed, seq, 0, 'new')")
    expect(completeReaderSource).toContain('makeThreadNextCursor')
    expect(completeReaderSource).toContain("__ql7ServerFeedSurface: 'thread'")
    expect(sortControlsSource).toContain('sortGeoRailBtn--disabled')
    expect(threadRepliesPaneSource).toContain('data-thread-replies-pane="1"')
    expect(threadRepliesPaneSource).toContain('data-thread-replies-start="1"')
    expect(threadRepliesPaneSource).toContain('data-thread-list-first-card={slotIndex === 0 ?')
    expect(forumRootSource).toContain('[data-thread-list-first-card="1"][data-feed-card="1"]')
    expect(forumRootSource).toContain('[data-thread-replies-start="1"]')
  })

  it('keeps topic creation geo-marked privately like posts', () => {
    const mutateRouteSource = readRepoFile('app/api/forum/mutate/route.js')
    const maintenanceSource = readRepoFile('lib/forum/forum-index-maintenance.cjs')
    const sanitizerSource = readRepoFile('lib/forum/public-sanitize.cjs')

    expect(mutateRouteSource).toContain('const requestGeo = resolveRequestGeo(request)')
    expect(mutateRouteSource).toContain('_geoOrigin: forumGeoOrigin')
    expect(mutateRouteSource).toContain('maintainForumIndexesForTopicCreated({ topic, canonicalAuthorId: userId, geoOrigin: forumGeoOrigin })')
    expect(maintenanceSource).toContain('const geo = geoOrigin || t._geoOrigin || null')
    expect(maintenanceSource).toContain('const scopeKeys = scopeKeysFromGeoOrigin(geo)')
    expect(maintenanceSource).toContain('const geoPrivate = { scopeKeys, origin: geo }')
    expect(maintenanceSource).toContain('_geoOrigin: geo, geoPrivate')
    expect(sanitizerSource).toContain("'geoPrivate'")
    expect(sanitizerSource).toContain("'_geoOrigin'")
  })

  it('keeps forum header VIP state on one passed vipActive truth', () => {
    const vipStateSource = readRepoFile('app/forum/features/profile/hooks/useVipSubscriptionState.js')
    const vipPaySource = readRepoFile('app/forum/features/profile/hooks/useVipPayAction.js')
    const vipFlagSource = readRepoFile('app/forum/features/profile/hooks/useVipFlag.js')
    const profileSyncSource = readRepoFile('app/forum/features/profile/hooks/useForumProfileSync.js')
    const headerSource = readRepoFile('app/forum/ForumHeaderPanel.jsx')
    const vipPopoverSource = readRepoFile('app/forum/features/profile/components/VipPopover.jsx')
    const qcoinInlineSource = readRepoFile('app/forum/features/qcoin/components/QCoinInline.jsx')
    const vipControlSource = readRepoFile('app/forum/features/profile/components/ForumVipControl.jsx')

    expect(vipStateSource).toContain('/api/subscription/status')
    expect(vipPaySource).toContain('/api/subscription/status')
    expect(vipFlagSource).toContain('/api/forum/vip/batch')
    expect(profileSyncSource).toContain("safeLocalStorageGet('account')")
    expect(profileSyncSource).toContain("safeLocalStorageGet('wallet')")
    expect(profileSyncSource).toContain("safeLocalStorageGet('asherId')")
    expect(profileSyncSource).toContain("safeLocalStorageGet('ql7_uid')")

    expect(headerSource).toContain('vipActive,')
    expect(headerSource).toContain('vipActive={vipActive}')
    expect(headerSource).toContain('<QCoinInline t={t} userKey={idShown} vipActive={vipActive} />')
    expect(headerSource).toContain('<ForumVipControl')
    expect(headerSource).not.toContain('/api/subscription/status')
    expect(headerSource).not.toContain('/api/forum/vip/batch')
    expect(headerSource).not.toContain('headerVipActive')
    expect(headerSource).not.toContain('readHeaderVipFlag')
    expect(headerSource).not.toContain('HEADER_VIP_PROBE')
    expect(headerSource).not.toContain('forum:vip-status-ready')
    expect(headerSource).not.toContain('fetch(')

    expect(vipPopoverSource).toContain('vipActive ? (')
    expect(vipPopoverSource).not.toContain('fetch(')
    expect(qcoinInlineSource).toContain("cls('qcoinX2', vipActive ? 'vip' : 'needVip'")
    expect(qcoinInlineSource).not.toContain('fetch(')
    expect(vipControlSource).toContain("vipActive ? 'vip is-vip-active' : 'vipGray is-vip-invite'")
    expect(vipControlSource).toContain('vipActive={vipActive}')
    expect(vipControlSource).not.toContain('fetch(')
    expect(vipStateSource).toContain("localStorage.getItem(VIP_KEY) === '1'")
    expect(vipStateSource).toContain("localStorage.getItem(VIP_QUOTA_KEY) === '1'")
    expect(vipStateSource).toContain('const resolvedAccountId = accountId || asherId ||')
    expect(vipStateSource).toContain('writeLocalVipFlag(isVip)')
    expect(vipStateSource).not.toContain('/api/forum/vip/batch')
  })

  it('keeps the forum invite button behind the shared auth continuation gate', () => {
    const actionRowSource = readRepoFile('app/forum/features/ui/components/ForumActionRow.jsx')

    expect(actionRowSource).toContain('runAuthorizedClientAction')
    expect(actionRowSource).toContain("actionKey: 'forum-invite-open'")
    expect(actionRowSource).toContain("source: 'forum-invite-button'")
    expect(actionRowSource).toContain("window.dispatchEvent(new CustomEvent('invite:open'")
    expect(actionRowSource).toContain('accountId,')
    expect(actionRowSource).toContain("source: 'forum-invite-button'")
  })

  it('keeps forum nickname badges capped and fitted instead of ellipsized', () => {
    const forumRootSource = readRepoFile('app/forum/ForumRoot.jsx')
    const forumStylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')
    const profileStylesSource = readRepoFile('app/forum/styles/modules/profileStyles.js')
    const qcoinStylesSource = readRepoFile('app/forum/styles/modules/qcoinStyles.js')
    const dmStylesSource = readRepoFile('app/forum/styles/modules/dmStyles.js')

    expect(forumRootSource).toContain('function useForumNickBadgeFit()')
    expect(forumRootSource).toContain('const maxBadgeWidthPx = 130')
    expect(forumRootSource).toContain("textEl.style.textOverflow = 'clip'")
    expect(forumRootSource).toContain('textEl.style.fontSize = `${nextFontPx.toFixed(2)}px`')

    for (const source of [forumStylesSource, profileStylesSource, qcoinStylesSource]) {
      expect(source).toContain('max-width:130px')
      expect(source).toContain('text-overflow:clip')
    }

    expect(dmStylesSource).toContain('.dmRow .nick-badge .nick-text{ max-width:100%; }')
  })

  it('keeps initial forum branch loading filled with skeleton cards instead of blank panes', () => {
    const stylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')
    const topicsPane = readRepoFile('app/forum/features/feed/components/TopicsPane.jsx')
    const threadPane = readRepoFile('app/forum/features/feed/components/ThreadRepliesPane.jsx')
    const videoPane = readRepoFile('app/forum/features/media/components/VideoFeedPane.jsx')
    const publishedPane = readRepoFile('app/forum/features/feed/components/PublishedPostsPane.jsx')
    const inboxPane = readRepoFile('app/forum/features/dm/components/InboxRepliesPane.jsx')
    const dmThreadPane = readRepoFile('app/forum/features/dm/components/DmMessagesPane.jsx')

    expect(stylesSource).toContain('.forumSkeletonPane')
    expect(stylesSource).toContain('.forumSkeletonCard')
    expect(stylesSource).toContain('@keyframes forumSkeletonSweep')

    for (const source of [topicsPane, threadPane, videoPane, publishedPane, inboxPane, dmThreadPane]) {
      expect(source).toContain('function ForumPaneSkeleton')
      expect(source).toContain('forumSkeletonPane')
      expect(source).toContain('forumSkeletonCard')
    }

    expect(topicsPane).toContain('showInitialTopicsSkeleton')
    expect(threadPane).toContain('showInitialThreadSkeleton')
    expect(videoPane).toContain('showInitialVideoSkeleton')
    expect(publishedPane).toContain('showInitialPublishedSkeleton')
    expect(inboxPane).toContain('showInitialRepliesSkeleton')
    expect(dmThreadPane).toContain('showInitialDmThreadSkeleton')
    expect(dmThreadPane).toContain('dmThreadItemCount === 0 && (!!dmThreadLoading || !!dmThreadHasMore)')
  })

  it('keeps DM thread presence status cheap, localized, and scoped to the open dialog header', () => {
    const dmHeader = readRepoFile('app/forum/features/dm/components/DmThreadHeader.jsx')
    const dmThreadPane = readRepoFile('app/forum/features/dm/components/DmMessagesPane.jsx')
    const userPopoverRoute = readRepoFile('app/api/profile/user-popover/route.js')
    const userInfoPopover = readRepoFile('app/forum/features/profile/components/UserInfoPopover.jsx')
    const qcoinHook = readRepoFile('app/forum/features/qcoin/hooks/useQCoinLive.js')
    const qcoinHeartbeatRoute = readRepoFile('app/api/qcoin/heartbeat/route.js')
    const qcoinPrimary = readRepoFile('lib/mongo/qcoin-primary.cjs')
    const walletSessionClient = readRepoFile('lib/walletSessionClient.js')
    const stylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')
    const dictFiles = [
      'components/i18n-dicts/en.js',
      'components/i18n-dicts/ru.js',
      'components/i18n-dicts/uk.js',
      'components/i18n-dicts/es.js',
      'components/i18n-dicts/tr.js',
      'components/i18n-dicts/ar.js',
      'components/i18n-dicts/zh.js',
    ].map(readRepoFile)

    expect(userPopoverRoute).toContain("require('../../../../lib/mongo/qcoin-primary.cjs')")
    expect(userPopoverRoute).toContain("searchParams.get('presence') === '1'")
    expect(userPopoverRoute).toContain('lastActiveAt: Number(qcoinState?.lastActiveAt || 0)')
    expect(userPopoverRoute).toContain('presenceOfflineAt: Number(qcoinState?.presenceOfflineAt || 0)')
    expect(userPopoverRoute).toContain('presenceOnly: true')
    expect(userInfoPopover).toContain('USER_INFO_ONLINE_WINDOW_MS = 75 * 1000')
    expect(userInfoPopover).toContain("qs.set('presence', '1')")
    expect(userInfoPopover).toContain('presenceOfflineAt < lastActiveAt')
    expect(userInfoPopover).toContain('setPresenceOnline(false)')
    expect(userInfoPopover).toContain('userInfoPopover--onlinePulse')
    expect(userInfoPopover).not.toContain('setInterval')
    expect(dmHeader).toContain('/api/profile/user-popover?')
    expect(dmHeader).toContain("qs.set('uid', threadUid)")
    expect(dmHeader).toContain('DM_PRESENCE_REFRESH_MS')
    expect(dmHeader).toContain("qs.set('presence', '1')")
    expect(dmHeader).toContain("window.addEventListener('focus', syncIfVisible)")
    expect(dmHeader).toContain("document.addEventListener('visibilitychange', syncIfVisible)")
    expect(dmHeader).toContain('DM_ONLINE_WINDOW_MS')
    expect(dmHeader).toContain('DM_RECENT_WINDOW_MS')
    expect(dmHeader).toContain('dmThreadPresenceBadge')
    expect(dmHeader).toContain('presenceBadgeRef')
    expect(dmHeader).toContain('presenceTextRef')
    expect(dmHeader).toContain('--dm-presence-text-scale')
    expect(dmHeader).toContain('presenceOfflineAt >= ts')
    expect(dmHeader).toContain('ResizeObserver')
    expect(dmHeader).toContain('className="dmThreadPresenceText"')
    expect(dmHeader).toContain('dm_presence_online')
    expect(dmHeader).toContain('dm_presence_recently')
    expect(dmHeader).toContain('dm_presence_long_ago')
    expect(dmThreadPane).toContain('className="dmThreadHeaderRail"')
    expect(stylesSource).toContain('.dmThreadHeaderRail')
    expect(stylesSource).toContain('.dmThreadAvatarImg{ width:100%; height:100%; border-radius:14px; overflow:hidden; background:transparent; }')
    expect(stylesSource).toContain('max-width:104px')
    expect(stylesSource).toContain('.dmThreadPresenceText')
    expect(stylesSource).toContain('font-size:calc(1em * var(--dm-presence-text-scale, 1))')
    expect(dmHeader).not.toContain('dmThreadPresenceDot')
    expect(stylesSource).toContain('border:1px solid rgba(255,81,109,.76)')
    expect(stylesSource).toContain('box-shadow:0 0 16px rgba(255,81,109,.22), inset 0 0 12px rgba(255,81,109,.08)')
    expect(stylesSource).toContain('.dmThreadPresenceBadge.online{')
    expect(stylesSource).not.toContain('.dmThreadPresenceDot')
    expect(stylesSource).toContain('@keyframes dmPresencePulse')
    expect(stylesSource).toContain('.userInfoPopover--onlinePulse')
    expect(stylesSource).toContain('@keyframes userInfoPresencePulse')
    expect(qcoinHook).toContain('bootPresenceRef')
    expect(qcoinHook).toContain('presencePush: true')
    expect(qcoinHook).toContain('PRESENCE_ACTIVE_KEEPALIVE_MS')
    expect(qcoinHook).toContain('PRESENCE_IDLE_KEEPALIVE_MS')
    expect(qcoinHook).toContain("fetch('/api/qcoin/heartbeat'")
    expect(qcoinHeartbeatRoute).toContain("body?.offline === true || body?.presence === 'offline'")
    expect(qcoinHeartbeatRoute).toContain('shortAlivePart')
    expect(qcoinHeartbeatRoute).toContain('`qa:${userPart}:${clientPart}`')
    expect(qcoinHeartbeatRoute).toContain('qcoinPrimary.markPresenceOffline')
    expect(qcoinPrimary).toContain('presenceOfflineAt')
    expect(qcoinPrimary).toContain('async function markPresenceOffline')
    expect(walletSessionClient).toContain('markQcoinPresenceOffline')
    expect(walletSessionClient).toContain('offline: true')
    for (const source of dictFiles) {
      expect(source).toContain('"dm_presence_online"')
      expect(source).toContain('"dm_presence_recently"')
      expect(source).toContain('"dm_presence_long_ago"')
    }
  })

  it('keeps open DM dialogs newest-first without bottom autoscroll grabs', () => {
    const dmThreadPane = readRepoFile('app/forum/features/dm/components/DmMessagesPane.jsx')
    const dmLoadMore = readRepoFile('app/forum/features/dm/components/DmThreadLoadMore.jsx')
    const dmRuntime = readRepoFile('app/forum/features/dm/hooks/useForumDmRuntime.js')
    const dmAutoScroll = readRepoFile('app/forum/features/dm/hooks/useDmThreadAutoScroll.js')
    const dmSeenObservers = readRepoFile('app/forum/features/dm/hooks/useDmSeenObservers.js')
    const presetsSource = readRepoFile('app/forum/shared/utils/forumWindowingPresets.js')
    const dmReadDomain = readRepoFile('lib/mongo/dm-read-domain-codec.cjs')
    const dmDbSource = readRepoFile('app/api/dm/_db.js')
    const dmRowSource = readRepoFile('app/forum/features/dm/components/DmThreadMessageRow.jsx')
    const dmLoadersSource = readRepoFile('app/forum/features/dm/utils/dmLoaders.js')
    const dmOpenEventsSource = readRepoFile('app/forum/features/dm/hooks/useDmOpenEvents.js')
    const dmDeleteRouteSource = readRepoFile('app/api/dm/delete/route.js')
    const dmDeleteControllerSource = readRepoFile('app/forum/features/dm/hooks/useDmDeleteController.js')
    const dmDeletePopoverSource = readRepoFile('app/forum/features/ui/components/DmDeletePopover.jsx')
    const videoCaptureSource = readRepoFile('app/forum/features/media/hooks/useVideoCaptureController.js')
    const stylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')
    const dmSeenRouteSource = readRepoFile('app/api/dm/seen/route.js')
    const dmSendRouteSource = readRepoFile('app/api/dm/send/route.js')
    const dmPrimarySource = readRepoFile('lib/mongo/dm-primary.cjs')
    const webPushSource = readRepoFile('lib/webPush.js')
    const notificationSyncSource = readRepoFile('components/AndroidNotificationBadgeSync.jsx')
    const notificationWorkerSource = readRepoFile('public/ql7-notification-sw.js')

    expect(dmThreadPane).toContain('function DmThreadWindowSpacer')
    expect(dmThreadPane).toContain('data-dm-thread-window-skeleton')
    expect(dmThreadPane).toContain('forumSkeletonPane--compact')
    expect(dmThreadPane).toContain('dmThreadRenderItems')
    expect(dmThreadPane).toContain('dmThreadItems.slice().reverse()')
    expect(dmThreadPane).toContain('data-dm-thread-order="newest-first"')
    expect(dmThreadPane.indexOf('<DmThreadLoadMore')).toBeGreaterThan(dmThreadPane.indexOf('dmThreadWin.bottom'))
    expect(dmLoadMore).toContain('data-dm-thread-loadmore-anchor="1"')
    expect(dmLoadMore).toContain('rootMargin="1800px 0px"')
    expect(dmLoadMore).toContain('checkNearHistoryEnd')
    expect(dmLoadMore).toContain('rect.top - vh <= 1800')
    expect(dmReadDomain).toContain('.sort({ score: -1, messageSeq: -1, messageId: -1 })')
    expect(dmReadDomain).toContain('itSeq >= cursorSeq')
    expect(dmReadDomain).toContain('Math.max((effectiveLimit + 1) * 3, 20)')
    expect(dmReadDomain).toContain('hasMore: Boolean(hasMore && nextCursor)')
    expect(dmDbSource).toContain('entry.frontCameraMirror = true')
    expect(dmDbSource).toContain('entry.mirrorVideo = true')
    expect(dmRowSource).toContain('frontCameraMirror={mirrorVideo}')
    expect(videoCaptureSource).toContain('frontCameraMirror: recordedFromFrontCamera')
    expect(videoCaptureSource).toContain('mirrorVideo: recordedFromFrontCamera')
    expect(videoCaptureSource).not.toContain('createUnmirroredFrontStreamFn')
    expect(videoCaptureSource).not.toContain('createWebCoreFrontMirrorRecorderStream')
    expect(dmRuntime).toContain('newestFirst: true')
    expect(dmRuntime).toContain('const DM_THREAD_SEEN_SCAN_EVENT')
    expect(dmRuntime).toContain('function dispatchDmThreadSeenScan')
    expect(dmRuntime).toContain('dispatchDmThreadSeenScan(uid, reason)')
    expect(dmRuntime).toContain('runOpenDmThreadRealtimeImpulse')
    expect(dmRuntime).toContain('runOpenDmThreadRealtimeImpulse(\'notification-count\')')
    expect(dmRuntime).toContain('runOpenDmThreadRealtimeImpulse(\'service-worker-push\')')
    expect(dmRuntime).toContain('dmUnreadCount: rawDmUnreadCount')
    expect(dmRuntime).toContain('const dmListMode = !!inboxOpen && inboxTab === \'messages\' && !dmWithUserId')
    expect(dmRuntime).toContain('if (dmListMode && next < prev) return prev')
    expect(dmRuntime).toContain('localUnreadProjection: true')
    expect(dmRuntime).toContain('if (detail?.clientOnly === true || detail?.localUnreadProjection === true) return false')
    expect(dmLoadersSource).toContain('const incomingIsOlder = !!(prevTs && nextTs && nextTs < prevTs)')
    expect(dmLoadersSource).toContain('if (prevSending || incomingIsOlder)')
    expect(dmLoadersSource).toContain('unreadCount: Math.max(Number(d?.unreadCount || 0), Number(inc?.unreadCount || 0))')
    expect(dmOpenEventsSource).toContain('reopenDeletedDmDialog?.(uid, rawUid)')
    expect(dmRuntime).toContain('const dmDeletedComposeOpenRef = useRef(new Set())')
    expect(dmRuntime).toContain('const reopenDeletedDmDialog = useCallback')
    expect(dmRuntime).toContain('allowDeletedDialogCompose: true')
    expect(dmLoadersSource).toContain('const allowDeletedDialogCompose = opts?.allowDeletedDialogCompose === true')
    expect(dmLoadersSource).toContain('if (!allowDeletedDialogCompose) {')
    expect(dmLoadersSource).toContain('setDmThreadHasMore?.(false)')
    expect(dmRuntime).not.toContain('DM_OPEN_THREAD_POLL_MS')
    expect(dmRuntime).not.toContain('window.setInterval(() => syncOpenThread')
    expect(dmSeenObservers).toContain('const DM_THREAD_SEEN_SCAN_EVENT')
    expect(dmSeenObservers).toContain('function dmSeenScanMatchesTarget')
    expect(dmSeenObservers).toContain('const refreshObservedNodes')
    expect(dmSeenObservers).toContain('new MutationObserver')
    expect(dmSeenObservers).toContain('window.addEventListener(DM_THREAD_SEEN_SCAN_EVENT')
    expect(dmSeenObservers).toContain('window.removeEventListener(DM_THREAD_SEEN_SCAN_EVENT')
    expect(dmSendRouteSource).toContain('itemId: id')
    expect(dmPrimarySource).toContain('async function listIncomingMessageIdsForSeenWindow')
    expect(dmPrimarySource).toContain('ts: { $gt: after, $lte: until }')
    expect(dmPrimarySource).toContain('listIncomingMessageIdsForSeenWindow,')
    expect(dmSeenRouteSource).toContain('markPushItemsRead')
    expect(dmSeenRouteSource).toContain('publishStoredNotificationImpulse(me')
    expect(dmSeenRouteSource).toContain('listIncomingMessageIdsForSeenWindow(meIds, withIds, currentMax, nextSeenTs)')
    expect(dmSeenRouteSource).toContain('[NOTIFICATION_SOURCES.MESSENGER_MESSAGES]: newlySeenMessageIds')
    expect(dmSeenRouteSource).toContain('reason: \'dm_messages_seen\'')
    expect(dmSeenRouteSource).toContain('publishNotificationImpulse(withId')
    expect(dmSeenRouteSource).toContain('reason: \'dm_seen_receipt\'')
    expect(webPushSource).toContain('export async function publishNotificationImpulse')
    expect(webPushSource).toContain('export async function publishStoredNotificationImpulse')
    expect(webPushSource).toContain('forceSync: forceSync === true')
    expect(webPushSource).toContain('realtimeOnly: true')
    expect(dmDeleteRouteSource).toContain('publishDmDeleteImpulse')
    expect(dmDeleteRouteSource).toContain('publishStoredNotificationImpulse')
    expect(dmDeleteRouteSource).toContain('dmDeletedMessageId: value.messageId')
    expect(dmDeleteRouteSource).toContain('dmDeletedPeerId: value.peerId')
    expect(dmDeleteRouteSource).toContain('dmDeletedDialog: value.dialog === true')
    expect(dmDeleteRouteSource).toContain('dm_message_delete_for_all')
    expect(dmDeleteRouteSource).toContain('dm_dialog_delete_for_all')
    expect(dmDeleteRouteSource).toContain("{ userId: from, peerId: to, messageId: msgId }")
    expect(dmDeleteRouteSource).toContain("{ userId: me, peerId: withId, dialog: true }")
    expect(dmDeleteControllerSource).toContain("if (kind === 'dialog')")
    expect(dmDeleteControllerSource).toContain('dmDeletePendingRef')
    expect(dmDeleteControllerSource).toContain('setDmDeletePending(true)')
    expect(dmDeleteControllerSource).toContain("if (forAll) {\n          await deleteDmDialogServer(uid)")
    expect(dmDeleteControllerSource).toContain('} else {\n          deleteDmDialogLocal(uid)\n        }')
    expect(dmDeleteControllerSource).not.toContain("if (kind === 'dialog') forAll = true")
    expect(dmDeleteControllerSource).not.toContain('deleteForAll: forAll')
    expect(dmDeletePopoverSource).toContain('aria-busy={!!pending}')
    expect(dmDeletePopoverSource).toContain('dmConfirmSpinner')
    expect(stylesSource).toContain('.dmConfirmBtn.primary.isPending')
    expect(stylesSource).toContain('@keyframes dmConfirmSpin')
    expect(dmRuntime).toContain('function mergeRealtimeThreadItems(existing, incomingDesc, deletedMap = {}, options = {})')
    expect(dmRuntime).toContain('options?.authoritative === true')
    expect(dmRuntime).toContain('const applyDmRealtimeDeleteImpulse = useCallback')
    expect(dmRuntime).toContain('dmDeletedMessageId')
    expect(dmRuntime).toContain('dmDeletedDialog')
    expect(dmRuntime).toContain("applyDmRealtimeDeleteImpulse(detail)")
    expect(dmRuntime).toContain("mergeRealtimeThreadItems(prev, incoming, dmDeletedMsgMap, { authoritative: true })")
    expect(dmLoadersSource).toContain('export function filterServerDeletedDialogs')
    expect(dmLoadersSource).toContain('export function persistDeletedDialogs')
    expect(notificationSyncSource).toContain('payload?.forceSync === true')
    expect(notificationSyncSource).toContain('dmDeletedMessageId: String(payload?.dmDeletedMessageId || \'\')')
    expect(notificationSyncSource).toContain('if (forceSync && !explicitRead && nextCount <= previousCount)')
    expect(notificationSyncSource).toContain('serverCounts?.[source] ?? payload?.count')
    expect(notificationSyncSource).toContain('DM read receipts are owned by /api/dm/seen')
    expect(notificationSyncSource.indexOf("if (source === 'messenger_messages')")).toBeLessThan(
      notificationSyncSource.indexOf('if ((nextCount <= 0 && previousCount > 0) || explicitRead)'),
    )
    expect(notificationWorkerSource).toContain('forceSync: payload?.forceSync === true')
    expect(notificationWorkerSource).toContain('const realtimeOnly = payload?.realtimeOnly === true')
    expect(notificationWorkerSource).toContain('realtimeOnly ? Promise.resolve() : updateSourceNotification')
    expect(dmAutoScroll).toContain('newestFirst = false')
    expect(dmAutoScroll).toContain('if (newestFirst) {')
    expect(presetsSource).toContain("case 'dm_message':\n      return constrained ? 24 : 30")
    expect(presetsSource).toContain("dm_message: {\n      mobile: 1600,\n      tablet: 1780,\n      desktop: 1960,")
    expect(stylesSource).toContain('.dmThreadWindowSpacer')
    expect(stylesSource).toContain('.dmThreadWindowSkeleton')
    expect(stylesSource).toContain('.dmThread .forumSkeletonPane--compact')
    expect(stylesSource).toContain('.dmRowAvatar{')
    expect(stylesSource).toContain('background:transparent;')
    expect(stylesSource).toContain('.dmRowAvatarImg{\n  width:100%; height:100%; border-radius:12px; overflow:hidden; background:transparent;')
    expect(stylesSource).toContain('.dmMediaBox[data-kind="video"]')
    expect(stylesSource).toContain('--mb-video-min-h:350px')
    expect(stylesSource).toContain('.dmMediaBox[data-kind="video"] > video')
    expect(stylesSource).toContain('min-height:350px')
  })

  it('keeps front-camera video mirroring metadata wired through fullscreen preview and safe upload fallback', () => {
    const forumRootSource = readRepoFile('app/forum/ForumRoot.jsx')
    const overlayStackSource = readRepoFile('app/forum/features/ui/components/ForumOverlayStack.jsx')
    const layoutPropsSource = readRepoFile('app/forum/features/ui/utils/buildForumLayoutProps.js')
    const videoOverlaySource = readRepoFile('app/forum/features/media/components/VideoOverlay.jsx')
    const composerPreviewSource = readRepoFile('app/forum/features/media/components/ComposerAttachmentPreview.jsx')
    const videoMediaSource = readRepoFile('app/forum/features/media/components/VideoMedia.jsx')
    const dmRowSource = readRepoFile('app/forum/features/dm/components/DmThreadMessageRow.jsx')
    const forumStylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')
    const videoCaptureSource = readRepoFile('app/forum/features/media/hooks/useVideoCaptureController.js')
    const uploadServiceSource = readRepoFile('app/forum/features/media/services/uploadR2MediaFile.js')
    const uploadVideoRouteSource = readRepoFile('app/api/forum/uploadVideo/route.js')
    const uploadImageRouteSource = readRepoFile('app/api/forum/upload/route.js')
    const blobUploadUrlRouteSource = readRepoFile('app/api/forum/blobUploadUrl/route.js')
    const mediaConstantsSource = readRepoFile('app/forum/shared/constants/media.js')
    const composerAttachmentsSource = readRepoFile('app/forum/features/media/hooks/useForumComposerAttachments.js')
    const progressBarSource = readRepoFile('app/forum/features/ui/components/ComposerMediaProgressBar.jsx')

    expect(forumRootSource).toContain('pendingVideoInfoRef')
    expect(forumRootSource).toContain('pendingVideoBlobMetaRef')
    expect(forumRootSource).toContain('const phaseBusy = (')
    expect(forumRootSource).toContain("phase === 'uploading'")
    expect(forumRootSource).toContain("phase !== 'ready' && phase !== 'idle'")
    expect(forumRootSource).not.toContain('mediaBarOn ||\n    phase ===')
    expect(layoutPropsSource).toContain('pendingVideoInfoRef')
    expect(layoutPropsSource).toContain('pendingVideoBlobMetaRef')
    expect(overlayStackSource).toContain('overlayPreviewMirror')
    expect(overlayStackSource).toContain('pendingVideoBlobMetaRef?.current?.get')
    expect(overlayStackSource).toContain('previewMirror={overlayPreviewMirror}')
    expect(videoOverlaySource).toContain('previewMirror = false')
    expect(videoOverlaySource).toContain('<NativeSafeVideoPlayer')
    expect(videoOverlaySource).toContain('frontCameraMirror={previewMirror}')
    expect(videoOverlaySource).toContain('mirrorVideo={previewMirror}')
    expect(videoOverlaySource).not.toContain('<video\n                  ref={previewVidRef}')
    expect(videoOverlaySource).not.toContain('controls\n                  playsInline')
    expect(videoOverlaySource).not.toContain('.voPreviewVideo[data-front-camera-mirror="1"]::-webkit-media-controls-panel')
    expect(composerPreviewSource).toContain('<NativeSafeVideoPlayer')
    expect(composerPreviewSource).toContain('frontCameraMirror={pendingVideoMirror}')
    expect(composerPreviewSource).not.toContain('enableVideoControlsOnTap')
    expect(composerPreviewSource).toContain('previewTouchWebKit')
    expect(composerPreviewSource).toContain('previewControlTop')
    expect(dmRowSource).toContain('<NativeSafeVideoPlayer')
    expect(dmRowSource).toContain('data-dm-media="1"')
    expect(videoMediaSource).toContain('export const NativeSafeVideoPlayer')
    expect(videoMediaSource).toContain('data-native-safe-video-player="1"')
    expect(videoMediaSource).toContain('controls={false}')
    expect(videoMediaSource).toContain('controlsVisible')
    expect(videoMediaSource).toContain('queueControlsHide')
    expect(videoMediaSource).toContain('playPause({ withSound: true })')
    expect(videoMediaSource).toContain("className={`ql7NativeSafeControls ${controlsVisible ? 'isVisible' : ''}`}")
    expect(videoMediaSource).toContain('.ql7NativeSafeControls.isVisible')
    expect(videoMediaSource).toContain('background:transparent;')
    expect(videoMediaSource).toContain('.ql7NativeSafeVideo::-webkit-media-controls-panel')
    expect(videoMediaSource).toContain("transform: videoStyle?.transform ? `${videoStyle.transform} scaleX(-1)` : 'scaleX(-1)'")
    expect(forumStylesSource).toContain('QL7_FRONT_CAMERA_NATIVE_CONTROLS_FIX_V1')
    expect(forumStylesSource).toContain('@supports (-webkit-touch-callout:none)')
    expect(forumStylesSource).not.toContain('.videoCard video[data-front-camera-mirror="1"]::-webkit-media-controls-panel')
    expect(forumStylesSource).not.toContain('@media (hover:hover) and (pointer:fine){\n      .videoCard video[data-front-camera-mirror="1"]::-webkit-media-controls-panel')
    expect(videoCaptureSource).toContain('restoreVideoComposerScroll')
    expect(videoCaptureSource).toContain('setTimeout(retry, 180)')
    expect(videoCaptureSource).toContain("if (videoState !== 'live')")
    expect(videoCaptureSource).toContain('try { restoreVideoComposerScroll?.() } catch {}')

    expect(uploadServiceSource).toContain('canUseForumVideoFallback')
    expect(uploadServiceSource).toContain("String(kind || '').trim().toLowerCase() === 'forum_video'")
    expect(uploadServiceSource).toContain("fetch('/api/forum/uploadVideo'")
    expect(uploadServiceSource).toContain('putFileWithProgress')
    expect(uploadServiceSource).toContain('ql7_forum_video_direct_upload_failed_server_fallback')
    expect(uploadVideoRouteSource).toContain('video\\/quicktime')
    expect(mediaConstantsSource).toContain('FORUM_IMAGE_MAX_BYTES = 50 * 1024 * 1024')
    expect(mediaConstantsSource).toContain('FORUM_VIDEO_MAX_BYTES = 100 * 1024 * 1024')
    expect(uploadImageRouteSource).toContain('MAX_TOTAL_SIZE_BYTES = FORUM_IMAGE_MAX_BYTES')
    expect(uploadImageRouteSource).toContain("errors: ['too_large_total']")
    expect(uploadVideoRouteSource).toContain('MAX_SIZE_BYTES = FORUM_VIDEO_MAX_BYTES')
    expect(blobUploadUrlRouteSource).toContain('MAX_SIZE = FORUM_VIDEO_MAX_BYTES')
    expect(composerAttachmentsSource).toContain("toast?.err?.(t?.('forum_image_too_big'))")
    expect(composerAttachmentsSource).toContain('URL.createObjectURL(vf)')
    expect(composerAttachmentsSource).toContain("source: 'paperclip_preview'")
    expect(composerAttachmentsSource).not.toContain('uploadR2MediaFile')
    expect(progressBarSource).toContain('MediaPipelineProgress')
    expect(progressBarSource).toContain("pipelineKind === 'video'")
    expect(progressBarSource).toContain('stageOrder={stageOrder}')
  })

  it('keeps the composer emoji and sticker switcher as a sticky glass capsule above the scrolling grid', () => {
    const panel = readRepoFile('app/forum/features/ui/components/ComposerEmojiPanel.jsx')
    const stylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')

    expect(panel).toContain('className="emojiPanelContent p-1"')
    expect(panel).toContain('className="emojiTabs"')
    expect(panel).toContain('const REGIONAL_INDICATOR_RE')
    expect(panel).toContain('const KEYCAP_RE')
    expect(panel).toContain('const BROKEN_COMPOSER_GLYPH_RE')
    expect(panel).toContain('const RENDERABLE_EMOJI_RE')
    expect(panel).toContain("new Set(['flags'])")
    expect(panel).toContain('key={emojiTab}')
    expect(panel).toContain('data-emoji-mode={emojiTab}')
    expect(panel).toContain('el.scrollTop = 0')
    expect(panel).toContain('el.scrollLeft = 0')
    expect(stylesSource).toContain('.emojiPanelContent')
    expect(stylesSource).toContain('.emojiPanelMode, .emojiCategoryBlock, .emojiGrid{ contain:layout paint; }')
    expect(stylesSource).toContain('.emojiTabs{')
    expect(stylesSource).toContain('position:sticky')
    expect(stylesSource).toContain('.emojiTabs::before')
    expect(stylesSource).toContain('backdrop-filter:blur(14px) saturate(1.18)')
  })

  it('keeps Published posts connected to the same tombstone deletion contour as threads', () => {
    const forumRootSource = readRepoFile('app/forum/ForumRoot.jsx')
    const dmRuntimeSource = readRepoFile('app/forum/features/dm/hooks/useForumDmRuntime.js')
    const publishedModelSource = readRepoFile('app/forum/features/feed/hooks/usePublishedPostsModel.js')
    const ownerActionsSource = readRepoFile('app/forum/features/feed/hooks/useForumMutationActions.js')
    const reportControllerSource = readRepoFile('app/forum/features/moderation/hooks/useReportController.js')

    expect(forumRootSource).toContain('tombstones,')
    expect(forumRootSource).toContain('useForumDmRuntime({')
    expect(forumRootSource).toContain('tombstones,')
    expect(dmRuntimeSource).toContain('tombstones = null')
    expect(dmRuntimeSource).toContain('usePublishedPostsModel({')
    expect(dmRuntimeSource).toContain('tombstones,')
    expect(publishedModelSource).toContain('tombstones = null')
    expect(publishedModelSource).toContain('tombstonePostsRef')
    expect(publishedModelSource).toContain('!isPostTombstoned(post)')
    expect(publishedModelSource).toContain('!isPostTombstonedNow(post)')
    expect(ownerActionsSource).toContain('persistTombstones((prev) => {')
    expect(ownerActionsSource).toContain('emitPostDeletedFn?.(postId, post?.topicId)')
    expect(reportControllerSource).toContain('deletedPostIds')
    expect(reportControllerSource).toContain('persistTombstones((prev) => ({')
  })

  it('routes owner edit mode through thread-open preparation and mounted composer focus retries', () => {
    const ownerActionsSource = readRepoFile('app/forum/features/feed/hooks/usePostOwnerActions.js')
    const editModeSource = readRepoFile('app/forum/features/ui/hooks/useForumEditMode.js')
    const forumRootSource = readRepoFile('app/forum/ForumRoot.jsx')
    const composeDockSource = readRepoFile('app/forum/features/ui/components/ComposeDock.jsx')

    expect(ownerActionsSource).toContain('topicId: post?.topicId')
    expect(ownerActionsSource).toContain('post,')
    expect(editModeSource).toContain('prepareEditMode')
    expect(editModeSource).toContain('scheduleComposerFocus')
    expect(editModeSource).toContain("document.getElementById('forum-composer')")
    expect(forumRootSource).toContain('const prepareEditMode = React.useCallback((detail) => {')
    expect(forumRootSource).toContain('openThreadForPost(targetPost, {')
    expect(forumRootSource).toContain('scheduleEditModeBranchAlign(targetPostId)')
    expect(forumRootSource).toContain('revealForumWindowedDomId(`post_${targetPostId}`')
    expect(forumRootSource).toContain('if (profileBranchMode) clearProfileBranch()')
    expect(composeDockSource).toContain('id="forum-composer"')
  })

  it('keeps composer image selection preview-first and ships a focused carousel in composer and fullscreen overlay', () => {
    const attachmentsSource = readRepoFile('app/forum/features/media/hooks/useForumComposerAttachments.js')
    const composerRuntimeSource = readRepoFile('app/forum/features/ui/hooks/useForumComposerRuntime.js')
    const composerPreviewSource = readRepoFile('app/forum/features/media/components/ComposerAttachmentPreview.jsx')
    const videoOverlaySource = readRepoFile('app/forum/features/media/components/VideoOverlay.jsx')
    const overlayStackSource = readRepoFile('app/forum/features/ui/components/ForumOverlayStack.jsx')
    const uploadRouteSource = readRepoFile('app/api/forum/upload/route.js')
    const stylesSource = readRepoFile('app/forum/styles/ForumStyles.jsx')

    const mediaResolverSource = readRepoFile('app/forum/features/media/services/resolveComposerMediaPayload.js')
    const mediaPipelineSource = readRepoFile('app/forum/features/media/hooks/useMediaPipelineController.js')
    const dmSendSource = readRepoFile('app/forum/features/dm/services/sendDmComposerMessage.js')
    const vitestConfigSource = readRepoFile('vitest.config.mjs')

    expect(attachmentsSource).toContain('URL.createObjectURL(file)')
    expect(attachmentsSource).toContain('pendingImageDraftsRef?.current?.set?.(draftId')
    expect(attachmentsSource).not.toContain("beginMediaPipeline?.('Moderating')")
    expect(attachmentsSource).not.toContain("fetch('/api/forum/upload'")
    expect(mediaResolverSource).toContain("beginMediaPipeline?.(localImageUrls.length ? 'Moderating' : 'Processing')")
    expect(mediaResolverSource).toContain('moderation = await moderateImageFiles(files, { signal })')
    expect(mediaResolverSource.indexOf('moderation = await moderateImageFiles(files, { signal })')).toBeLessThan(
      mediaResolverSource.indexOf("fetch('/api/forum/upload'"),
    )
    expect(mediaResolverSource).toContain("form.append('draftIds', draftId)")
    expect(mediaResolverSource).toContain('imageUrlsToSend = pendingImageUrls.map')
    expect(mediaPipelineSource).toContain('localImagePreviewOnly')
    expect(dmSendSource).toContain("finalImageUrls.some((url) => /^blob:/i.test(String(url || '')))")
    expect(uploadRouteSource).toContain("form.getAll('draftIds')")
    expect(uploadRouteSource).toContain('items.push({ draftId, index, url, error: null })')
    expect(composerRuntimeSource).toContain('revokeLocalImageUrl')
    expect(composerRuntimeSource).toContain('pendingImageDraftsRef')
    expect(composerRuntimeSource).toContain('removePendingImageAt')
    expect(composerRuntimeSource).toContain('openPendingImageFullscreen')
    expect(composerPreviewSource).toContain('className="composerImageCarousel"')
    expect(composerPreviewSource).toContain('onTouchStart={handleImageTouchStart}')
    expect(composerPreviewSource).toContain('hasManyImages &&')
    expect(composerPreviewSource).toContain('onRemoveImage?.(activeImageIndex)')
    expect(composerPreviewSource).toContain('onOpenImageFullscreen?.(activeImageIndex)')
    expect(videoOverlaySource).toContain("mediaKind === 'image' && imageItems.length > 0")
    expect(videoOverlaySource).toContain('hasManyImages &&')
    expect(videoOverlaySource).toContain('onRemoveImage?.(activeImageIndex)')
    expect(videoOverlaySource).toContain("e.key === 'ArrowLeft'")
    expect(overlayStackSource).toContain('imageUrls={pendingImgs}')
    expect(overlayStackSource).toContain('onImageIndexChange={setOverlayImageIndex}')
    expect(stylesSource).toContain('.forumComposer .composerImageCarousel{')
    expect(stylesSource).toContain('height:min(var(--mb-video-h, 620px), 620px)')
    expect(stylesSource).toContain('.composerImageControl--trash')
    expect(stylesSource).toContain('background:#000 !important')
    expect(stylesSource).toContain('z-index:10')
    expect(stylesSource).toContain('@keyframes composerImageArrowPulse')
    const mediaLifecycleRuntimeSource = readRepoFile('app/forum/features/media/utils/mediaLifecycleRuntime.js')
    expect(vitestConfigSource).toContain("import react from '@vitejs/plugin-react'")
    expect(vitestConfigSource).toContain('plugins: [react()]')
    expect(vitestConfigSource).not.toContain('oxc: {')
    expect(mediaLifecycleRuntimeSource).toContain('React.createElement(VideoMediaLeaf')
    expect(mediaLifecycleRuntimeSource).toContain('React.createElement(NativeSafeVideoPlayerLeaf')
    expect(mediaLifecycleRuntimeSource).toContain('React.createElement(QCastPlayerLeaf')
    expect(mediaLifecycleRuntimeSource).not.toContain('<VideoMediaLeaf')
    expect(mediaLifecycleRuntimeSource).not.toContain('<NativeSafeVideoPlayerLeaf')
    expect(mediaLifecycleRuntimeSource).not.toContain('<QCastPlayerLeaf')
    expect((vitestConfigSource.match(/extends:\s*true/g) || []).length).toBe(1)
  })

  it('does not render the global composer pencil while the forum session is unauthenticated', () => {
    const forumRootSource = readRepoFile('app/forum/ForumRoot.jsx')
    const layoutPropsSource = readRepoFile('app/forum/features/ui/utils/buildForumLayoutProps.js')
    const composeDockSource = readRepoFile('app/forum/features/ui/components/ComposeDock.jsx')

    expect(forumRootSource).toContain('composerFabVisible: Boolean(auth?.asherId || auth?.accountId)')
    expect(layoutPropsSource).toContain('composerFabVisible: composerFabVisible === true')
    expect(composeDockSource).toContain('{composerFabVisible ? (')
    expect(composeDockSource).toContain('<ComposerFabButton')
    expect(composeDockSource).toContain(') : null}')
  })

})
