import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, test } from 'vitest'

const root = process.cwd()
const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8')

describe('QL7 native video poster V1 contracts', () => {
  test('defines one device-agnostic lightweight poster policy without a second full transcode', () => {
    const poster = read('lib/nativeVideoPoster.js')
    expect(poster).toContain("QL7_NATIVE_VIDEO_POSTER_MARKER = 'QL7_NATIVE_VIDEO_POSTER_V1_FINAL'")
    expect(poster).toContain("QL7_FRONT_CAMERA_POSTER_MIRROR_MARKER = 'QL7_FRONT_CAMERA_POSTER_MIRROR_R24_FIX2_FINAL'")
    expect(poster).toContain('QL7_NATIVE_VIDEO_POSTER_TARGET_SECONDS = 2')
    expect(poster).toContain('QL7_NATIVE_VIDEO_POSTER_MAX_EDGE = 960')
    expect(poster).toContain('QL7_NATIVE_VIDEO_POSTER_HARD_BYTES = 768 * 1024')
    expect(poster).toContain("document.createElement('video')")
    expect(poster).toContain("document.createElement('canvas')")
    expect(poster).toContain('video.currentTime = timeSec')
    expect(poster).toContain('actualMime !== mime')
    expect(poster).toContain("['image/webp', 'image/jpeg'].includes(mime)")
    expect(poster).toContain('resolveNativeVideoPosterCacheKey')
    expect(poster).toContain('mirror=${mirrorX ? 1 : 0}')
    expect(poster).not.toContain('Conversion(')
    expect(poster).not.toContain('navigator.userAgent')
    expect(poster).not.toContain('maxTouchPoints')
    expect(poster).not.toContain('isAppleMobile')
    expect(poster).not.toContain('isMobileRuntime')
  })

  test('all native video uploads create and upload a bounded R2 poster before the video presign', () => {
    const gateway = read('app/forum/features/media/services/uploadR2MediaFile.js')
    const signer = read('app/api/forum/blobUploadUrl/route.js')
    const keys = read('lib/storage/mediaKeys.js')
    expect(gateway).toContain('posterFactory = createNativeVideoPoster')
    expect(gateway).toContain("kind: posterKindForVideoKind(kind)")
    expect(gateway.indexOf('await prepareForumVideoForUpload({')).toBeLessThan(gateway.indexOf("fetch('/api/forum/blobUploadUrl'"))
    expect(gateway.indexOf("if (preparation?.isVideo && resolvedContentType !== 'video/mp4')")).toBeLessThan(gateway.indexOf("fetch('/api/forum/blobUploadUrl'"))
    expect(gateway).toContain('posterUrl: String(posterUpload?.publicUrl || \'\')')
    expect(gateway.indexOf('posterUpload = await signAndPutMedia')).toBeLessThan(gateway.indexOf("const signResponse = await fetch('/api/forum/blobUploadUrl'", gateway.indexOf('posterUpload = await signAndPutMedia')))
    expect(signer).toContain("const POSTER_ALLOWED = ['image/webp', 'image/jpeg']")
    expect(signer).toContain('const VIDEO_POSTER_MAX_BYTES = 768 * 1024')
    expect(signer).toContain('MAX_SIZE = FORUM_VIDEO_MAX_BYTES')
    expect(signer).toContain('(100MB)')
    expect(keys).toContain("return 'forum/video-posters'")
    expect(keys).toContain("return 'ads/video-posters'")
  })

  test('forum post and DM persistence transport posterUrl without turning it into primary post media', () => {
    const resolver = read('app/forum/features/media/services/resolveComposerMediaPayload.js')
    const create = read('app/forum/features/feed/hooks/useForumCreatePostAction.js')
    const mutate = read('app/api/forum/mutate/route.js')
    const mongo = read('lib/mongo/forum-primary.cjs')
    const index = read('lib/forum/forum-index-maintenance.cjs')
    const dmSend = read('app/forum/features/dm/services/sendDmComposerMessage.js')
    const dmDb = read('app/api/dm/_db.js')
    expect(resolver).toContain('videoPosterUrlToSend = String(result?.posterUrl || \'\')')
    expect(create).toContain('videoPosterUrlToSend ? { posterUrl: videoPosterUrlToSend } : {}')
    expect(mutate).toContain('isR2PublicUrl(posterCandidate)')
    const topicStart = mongo.indexOf('async function createTopic(')
    const postStart = mongo.indexOf('async function createPost(')
    const getTopicStart = mongo.indexOf('async function getTopic(')
    expect(topicStart).toBeGreaterThanOrEqual(0)
    expect(postStart).toBeGreaterThan(topicStart)
    expect(getTopicStart).toBeGreaterThan(postStart)
    const topicBlock = mongo.slice(topicStart, postStart)
    const postBlock = mongo.slice(postStart, getTopicStart)
    expect(topicBlock).not.toContain('posterUrl')
    expect(postBlock).toContain("posterUrl = ''")
    expect(postBlock).toContain('...(str(posterUrl) ? { posterUrl: str(posterUrl) } : {})')
    expect(index).toContain('posterUrl: str(post.posterUrl)')
    expect(index).not.toContain("['videoUrl', 'imageUrl', 'audioUrl', 'posterUrl', 'url']")
    expect(dmSend).toContain('...(posterUrl ? { posterUrl } : {})')
    expect(dmDb).toContain('isR2PublicUrl(posterUrl)')
  })

  test('forum, search, DM, Ads and global AdCard consumers use the persisted native poster', () => {
    const stack = read('app/forum/features/feed/components/PostMediaStack.jsx')
    const leaf = read('app/forum/features/media/components/VideoMedia.jsx')
    const search = read('app/forum/features/media/utils/mediaLinks.js')
    const dmRenderer = read('app/forum/features/dm/components/DmMediaRenderer.jsx')
    const dmDialog = read('app/forum/features/dm/components/DmDialogRow.jsx')
    const adsHome = read('app/ads/home.js')
    const adsCore = read('lib/adsCore.js')
    const forumAds = read('app/forum/ForumAds.js')
    const globalAds = read('app/ads.js')
    expect(stack).toContain('poster={i === 0 && posterUrl ? posterUrl : undefined}')
    expect(leaf).toContain('poster={shouldMirrorVideo ? undefined : renderPoster}')
    expect(search).toContain('export function buildSearchVideoMedia(url, posterUrl = \'\')')
    expect(dmRenderer).toContain('poster: str(item?.posterUrl || item?.poster) || undefined')
    expect(dmDialog).toContain("previewMedia.kind === 'video' && previewMedia.posterUrl")
    expect(adsHome).toContain('videoPosterPreviewUrl')
    expect(adsHome).toContain('poster={selectedCampaign.posterUrl || undefined}')
    expect(adsCore).toContain('posterUrl: cr.posterUrl || campaign.posterUrl || \'\'')
    expect(forumAds).toContain('POSTER_BY_MEDIA')
    expect(forumAds).toContain('poster={media.poster || undefined}')
    expect(globalAds).toContain('AdCard')
  })

  test('camera/trim/composer share the gateway and R22 one-shot streaming remains intact', () => {
    const resolver = read('app/forum/features/media/services/resolveComposerMediaPayload.js')
    const capture = read('app/forum/features/media/hooks/useVideoCaptureController.js')
    const trim = read('app/forum/features/media/hooks/useVideoTrimController.js')
    const preview = read('app/forum/features/media/components/ComposerAttachmentPreview.jsx')
    const overlay = read('app/forum/features/media/components/VideoOverlay.jsx')
    const leaf = read('app/forum/features/media/components/VideoMedia.jsx')
    const worker = read('lib/forumClientVideoOptimizerWorker.js')
    expect(capture).toContain('MediaRecorder')
    expect(capture).toContain('frontCameraMirror')
    expect(trim).toContain('durationSec')
    expect(resolver).toContain("kind: 'forum_video'")
    expect(resolver).toContain('mirrorX: !!videoMetaToSend?.frontCameraMirror')
    expect(resolver).toContain("readCachedNativeVideoPoster(pendingVideoCurrent, { mirrorX: !!videoMetaToSend?.frontCameraMirror })")
    expect(preview).toContain('mirrorX: pendingVideoMirror')
    expect(overlay).toContain('mirrorX: previewMirror')
    expect(leaf).toContain('data-front-camera-poster-layer="1"')
    expect(leaf).toContain('data-front-camera-feed-poster-layer="1"')
    expect(leaf).toContain('Front-camera poster pixels are already mirrored at extraction time.')
    expect(leaf).toContain('release the independent poster only once real')
    expect(leaf).toContain('onPlaying={(event) => {')
    expect(leaf).toContain("transform: videoStyle?.transform ? `${videoStyle.transform} scaleX(-1)` : 'scaleX(-1)'")
    expect(leaf).toContain("transform: style?.transform ? `${style.transform} scaleX(-1)` : 'scaleX(-1)'")
    expect(leaf).toContain('poster={shouldMirrorVideo ? undefined : (poster || undefined)}')
    expect(leaf).toContain('poster={shouldMirrorVideo ? undefined : renderPoster}')
    expect(preview).toContain('createNativeVideoPoster')
    expect(overlay).toContain('createNativeVideoPoster')
    expect(overlay).toContain('poster={previewPoster || undefined}')
    expect(worker).toContain('QL7_MOBILE_VIDEO_WORKER_R22_ONE_SHOT_FINAL')
    expect(worker.split('await conversion.execute()').length - 1).toBe(1)
    expect(worker).not.toContain('conversion.execute({ until })')
  })

  test('post-video lifecycle keeps the poster passive and forbids competing runtime poster mutation', () => {
    const runtime = read('app/forum/features/media/utils/mediaLifecycleRuntime.js')
    const leaf = read('app/forum/features/media/components/VideoMedia.jsx')
    const audit = read('tools/audit-post-video-lifecycle.js')
    expect(runtime).not.toMatch(/data-poster|__posterOriginal|__posterMediaKey|__posterRevealed/)
    expect(leaf).not.toContain('data-poster')
    expect(audit).toContain('leafPassiveNativePoster')
    expect(audit).toContain('postMediaPassivePoster')
  })
  test('forum feed playback is poster-first and removes aggressive first-frame priming without changing active autoplay ownership', () => {
    const coordinator = read('app/forum/features/media/hooks/useForumMediaCoordinator.js')
    const leaf = read('app/forum/features/media/components/VideoMedia.jsx')
    expect(coordinator).toContain('QL7_FORUM_NATIVE_VIDEO_POSTER_FIRST_LIGHT_PREWARM_R24_FIX2_FINAL')
    expect(coordinator).toContain("preloadMode: 'metadata'")
    expect(coordinator).toContain('native_prewarm_metadata_kick')
    expect(coordinator).toContain('const POST_NATIVE_SRC_CAP = 2')
    expect(coordinator).not.toContain('const primeNativeFirstFrame =')
    expect(coordinator).not.toContain('native_prime_offscreen_warmup_play')
    expect(coordinator).not.toContain('requestVideoFrameCallback')
    expect(coordinator).not.toContain('__nativePrime')

    const lifecycle = read('app/forum/features/media/utils/mediaLifecycleRuntime.js')
    expect(lifecycle).toContain('QL7_FORUM_NATIVE_VIDEO_POSTER_FIRST_LIGHT_PREWARM_R24_FIX2_RUNTIME')
    expect(lifecycle).toContain("el.preload = isPostFeedVideo ? 'metadata' : (keepWarmFetchOnSoftUnload ? 'auto' : 'metadata')")
    expect(lifecycle).not.toContain('__nativePrime')

    const videoLeaf = read('app/forum/features/media/components/VideoMedia.jsx')
    expect(videoLeaf).toContain("postPlaybackIntent ? 'auto' : (wantsWarm ? 'metadata' : 'none')")
    expect(videoLeaf).toMatch(/isNewMediaNode && isPostVideo[\s\S]{0,520}el\.preload = 'none'/)

    expect(coordinator).toMatch(/candidate_activate_native_pending_play[\s\S]{0,700}playMedia\(active\)/)
    expect(leaf).toContain("const renderPreload = coordinatorOwnsPostLifecycle ? 'none' : (isPostVideo ? 'metadata' : preload)")
    expect(leaf).toContain('poster={shouldMirrorVideo ? undefined : renderPoster}')
  })

})
